- packages/framework/src/Component/Router/DomainRouter.php
static routers (faster) have higher priorties than dynamic friendly url (slower)
|Description, reason for the PR| little performance boost -> pages without friendly url save one query to database
|Fixes issues| #1071 
> [framework] higher priority for static routes, lower for dynamic routes

- packages/framework/src/Form/MoneyTypeExtension.php
- upgrade/UPGRADE-v9.0.0-dev.md
|Description, reason for the PR| Setting currency in `MoneyFormType` now renders the currency the same way as `symbolAfterInput` is (wrapped in span) – default `appendix_block`from `theme.html.twig` is used. So it's easier to style everything after input same way.
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| Possible 
> [framework] unified rendering of currency and symbolAfterInput in forms

- build.xml
- packages/backend-api/phpunit.xml
- packages/http-smoke-testing/phpunit.xml
- packages/migrations/phpunit.xml
- packages/product-feed-google/phpunit.xml
- packages/product-feed-google/tests/Unit/GoogleFeedItemTest.php
- packages/product-feed-heureka-delivery/phpunit.xml
- packages/product-feed-heureka/phpunit.xml
- packages/product-feed-heureka/tests/Unit/HeurekaFeedItemTest.php
- packages/product-feed-zbozi/phpunit.xml
- packages/product-feed-zbozi/tests/Unit/ZboziFeedItemTest.php
- packages/read-model/phpunit.xml
- utils/releaser/phpunit.xml
|Description, reason for the PR| Unit tests will not fail on warning. The tests are marked as warning only and then skipped. This PR fixes it.<br> In #1543 was method renamed but this change was not affected in some unit tests. This PR fixes wrong tests too.
> [shopsys] unit tests don't pass on warning + fix feed packages tests

- packages/framework/easy-coding-standard.yml
- packages/framework/src/Form/Admin/AdvancedSearch/AdvancedSearchFilterTranslation.php
- packages/framework/src/Form/Admin/AdvancedSearch/AdvancedSearchOperatorTranslation.php
- packages/framework/src/Form/Transformers/CategoriesIdsToCategoriesTransformer.php
- packages/framework/src/Form/Transformers/CategoriesTypeTransformer.php
- packages/framework/src/Form/Transformers/FilesIdsToFilesTransformer.php
- packages/framework/src/Form/Transformers/ImagesIdsToImagesTransformer.php
- packages/framework/src/Form/Transformers/InverseMultipleChoiceTransformer.php
- packages/framework/src/Form/Transformers/NumericToMoneyTransformer.php
- packages/framework/src/Form/Transformers/ProductIdToProductTransformer.php
- packages/framework/src/Form/Transformers/ProductParameterValueToProductParameterValuesLocalizedTransformer.php
- packages/framework/src/Form/Transformers/ProductsIdsToProductsTransformer.php
|Description, reason for the PR| simpler extensibility, Eg. creating new operator for Advanced search was pain (array with translations was private)<br> We forbid using private properties in framework classes due to extensibility. This PR changes its visibility to protected.
> [framework] use protected properties in Transformers and AdvancedSearch

- packages/coding-standards/easy-coding-standard.yml
|Description, reason for the PR| Symplify by default enforces PHP_EOL line endings, which is interpreted variously on various platforms. Therefore, on Windows, running ecs changes line endings to CRLF. See https://github.com/Symplify/EasyCodingStandard/blob/master/config/config.yaml#L12
> [coding-standards] force unix line endings

- packages/framework/src/Migrations/Version20191121145700.php
|Description, reason for the PR| In #1522 migration for contact page was introduced, but when migration is run on the already running project (with some data in database), migration fails on the duplicate primary key because contact page text was always inserted with domainId = 1. This PR fixes it.
_migration is not part of any released version, so it can be changed_
> [framework] fixed contact form text db migration

- packages/framework/src/Model/Pricing/BasePriceCalculation.php
|Description, reason for the PR| Function `calculateBasePriceRoundedByCurrency` for price calculation with rounding by currency has deprecated annotation, which is wrong. This annotation belongs to `applyCoefficients`. This PR fixes wrongly placed anntoation. 
> [framework] fix wrongly placed annotation in BasePriceCalculation

- packages/framework/build.xml
- packages/framework/src/Command/CreateDomainsDataCommand.php
|Description, reason for the PR| Current implementation is unacceptable for projects with more products. Recalculations are now run only for newly created domains. Any products marked for recalculation are calculated with cron only and not during the deploy.
|Fixes issues| #1387 
> [framework] Run all recalculators during deploy only if domain is created

- packages/framework/assets/js/admin/components/ProductVisibility.js
|Description, reason for the PR| It caused multiple ajax loading after show popup with visibilities (after click to icon)
> [framework] fix multiple binding js-product-visibility

- upgrade/UPGRADE-v9.0.0-dev.md
|Description, reason for the PR| We have merged #1407 without upgrade notes. This PR adds them.
> [doc] added missing upgrade notes for cron overview

- packages/framework/src/Migrations/Version20200127085928.php
|Description, reason for the PR| migration does not work on existing database
It causes
```
Migration 20200127085928 failed during Execution. Error An exception occurred while executing '
ALTER TABLE
delivery_addresses
ADD
CONSTRAINT FK_2BAF39849395C3F3 FOREIGN KEY (customer_id) REFERENCES customers (id) NOT DEFERRABLE INITIALLY IMMEDIATE':
SQLSTATE[23503]: Foreign key violation: 7 ERROR:  insert or update on table "delivery_addresses" violates foreign key constraint "fk_2baf39849395c3f3"
DETAIL: …
```
> fix wrong migration on database with data

- docker/conf/docker-compose-mac.yml.dist
- docker/conf/docker-compose-win.yml.dist
- docker/conf/docker-compose.yml.dist
- project-base/docker/conf/docker-compose-mac.yml.dist
- project-base/docker/conf/docker-compose-win.yml.dist
- project-base/docker/conf/docker-compose.yml.dist
- project-base/kubernetes/deployments/adminer.yml
- upgrade/UPGRADE-v9.0.0-dev.md
|Description, reason for the PR| After upgrading to PostgreSQL 12 the [bug](https://sourceforge.net/p/adminer/bugs-and-features/719/) in Adminer occured. The fix is released in image adminer:4.7.6. This PR upgrades the image version.
> [shopsys] updated adminer

- packages/framework/src/Component/Doctrine/QueryBuilderExtender.php
- packages/framework/tests/Unit/Component/Doctrine/QueryBuilderExtenderTest.php
- packages/framework/tests/Unit/Component/Doctrine/__fixtures/Product.php
- packages/framework/tests/Unit/Component/Doctrine/__fixtures/ProductData.php
- project-base/tests/ShopBundle/Functional/Component/Doctrine/QueryBuilderExtenderTest.php
|Description, reason for the PR| there are problems with QueryBuilderExtender's method AddOrExtendJoin 
|Fixes issues| closes #997  
> [shopsys] fix issues with QueryBuilderExtender's method AddOrExtendJoin

- packages/framework/src/Model/Feed/DailyFeedCronModule.php
- packages/framework/tests/Unit/Model/Feed/DailyFeedCronModuleTest.php
|Description, reason for the PR| when feed cron module finish one feed exact before sleep, it causes fatal error. This PR prevents such case.
|Fixes issues| #1253 
> [framework] fix call sleep() on null on sleep cron module between two feeds

- packages/framework/src/Model/Product/Availability/ProductAvailabilityCalculation.php
- packages/framework/src/Model/Product/Product.php
- project-base/tests/App/Functional/Model/Product/ProductVariantCreationTest.php
- upgrade/UPGRADE-v9.0.0-dev.md
|Description, reason for the PR| It is better to keep current availability, then changing it to default, until calculation is run.
> [shopsys] do not change product availability to default when availability cannot be calculated immediately

- composer.json
- packages/framework/build.xml
- packages/framework/composer.json
- project-base/composer.json
- upgrade/UPGRADE-v9.0.0-dev.md
|Description, reason for the PR| New version of JMS/translation-bundle broke dumping translations.
> [shopsys] jms/translation-bundle fixed to version 1.4.4

- project-base/phpstan.neon
|Description, reason for the PR| With upgrading to symfony4 we made a mistake in phpstan file in project-base. This PR fixed it.
> [project-base] fixed phpstan.neon

- packages/framework/src/Form/Admin/Administrator/AdministratorFormType.php
- packages/framework/src/Form/Admin/Customer/User/CustomerUserFormType.php
- packages/framework/src/Resources/translations/validators.cs.po
- packages/framework/src/Resources/translations/validators.en.po
- project-base/src/Form/Front/Customer/Password/NewPasswordFormType.php
- project-base/src/Form/Front/Customer/User/CustomerUserFormType.php
- project-base/src/Form/Front/Registration/RegistrationFormType.php
- project-base/translations/validators.cs.po
- project-base/translations/validators.en.po
- upgrade/UPGRADE-v9.0.0-dev.md
|Description, reason for the PR| "Password must be longer than {{ limit }} characters" was not good for min length constraint. This PR fixes that.
|Fixes issues| closes #1518 
PS: Again. I want dump translation so I want to use `php phing dump-translations` as I am used to but this command not exists 😐. Only exists info `php phing dump-translations` [is deprecated](https://github.com/shopsys/shopsys/blame/master/upgrade/UPGRADE-v7.3.0.md#L130). Maybe I am just dumb but I don't see exactly message `php phing …
> [shopsys] bad constraint message for minimum password length

- packages/product-feed-heureka/src/Model/HeurekaCategory/HeurekaCategoryDownloader.php
- upgrade/UPGRADE-v9.0.0-dev.md
|Description, reason for the PR| Originally created by @pk16011990. The method name was wrong, so it has been changed.
> [product-feed-heureka] rename method "convertToShopEntities" to "convertToHeurekaCategoriesData"

- docs/cookbook/modifying-a-template-in-administration.md
|Description, reason for the PR| We have cookbook how to change original template from the administration, but it does not contain any information about overriding templates. This PR adds new note to inform people that it is possible to override template
> [shopsys] added note about overriding templates

- packages/framework/assets/package.json
- project-base/package.json
|Description, reason for the PR| We did not update npm dependencies to latest version in #1725 
> [shopsys] updated @shopsys/framework npm dependencies

- packages/framework/assets/js/admin/components/FileUpload.js
|Description, reason for the PR| When upload failed on some error, flash message "Uploading..." was not removed and might confuse users. This was fixed.
> [framework] hide "Uploading..." flash message on error

- packages/framework/src/Form/AbstractFileUploadType.php
- packages/framework/src/Form/FileUploadType.php
- packages/framework/src/Resources/translations/validators.cs.po
- packages/framework/src/Resources/translations/validators.en.po
- otherwise, when the file name is empty, the application fails on type error:
- UploadedFile::setNameAndSlug() must be of the type string, null given
|Description, reason for the PR| the "not blank" constraints are essential
> [framework] file upload: add NotBlank contraints for "currentFilenamesIndexedById" and "uploadedFilenames" fields

- packages/backend-api/install/config/packages/security.yml.patch
- packages/backend-api/install/install.sh
- packages/backend-api/install/uninstall.sh
|Description, reason for the PR| command `phing backend-api-install backend-api-uninstall` created new file `project-base/config/packages/security.yml.orig` because patch contains small discrepancy. It can caused commiting this useles file.
> [backend-api] prevent forgotten file after install and uninstall backend api in monorepo + fix patch

- packages/framework/src/Component/Image/Processing/ImageProcessor.php
- packages/framework/src/Form/Admin/Slider/SliderItemFormType.php
- packages/framework/src/Form/Constraints/FileAllowedExtension.php
- packages/framework/src/Form/Constraints/FileAllowedExtensionValidator.php
- packages/framework/src/Form/ImageUploadType.php
- packages/framework/src/Resources/translations/validators.cs.po
- packages/framework/src/Resources/translations/validators.en.po
|Description, reason for the PR| Uploading image with wrong extension leaded to error 500. This validation prevents such situations.
> [framework] added validation of images extensions so only jpg, jpeg, gif and png are allowed

- packages/framework/assets/js/admin/components/OrderItems.js
|Description, reason for the PR| Parameters in JS `Translator.trans` function need to have names without percent symbol.
> [framework] fixed parameter name in remove item from order confirm window

- packages/framework/src/Controller/Admin/CategoryController.php
- packages/framework/src/Resources/translations/messages.cs.po
- packages/framework/src/Resources/translations/messages.en.po
|Description, reason for the PR| When category was modified, the original text was missing space in text. This PR fixes that.
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| Possible (changed translation id) 
> [framework] fixed typo in category edit flash message

- packages/framework/src/Resources/config/services.yml
|Description, reason for the PR| Since Symfony 4, the main_filesystem service was removed when the container was compiled. This can be verified with `./bin/console debug:container main_filesystem`. ElFinder obtain the filesystem service from the container (see `\FM\ElfinderBundle\Configuration\ElFinderConfigurationReader::getFlysystemFilesystem`). This PR makes main_filesystem service public, so it's possible to use $container->get in method mentioned above. 
> [framework] main_filesystem is now public service for elFinder to work properly

- upgrade/UPGRADE-v9.0.0-dev.md
|Description, reason for the PR| We forgot for upgrade notes in #1725 ...
> [shopsys] added missing upgrades for webpack and css

- packages/framework/src/Form/Constraints/DeliveryAddressOfCurrentCustomerValidator.php
- project-base/tests/App/Functional/Model/Product/Availability/ProductAvailabilityCalculationTest.php
- upgrade/UPGRADE-v9.0.0-dev.md
|Description, reason for the PR| After update of FriendsOfPHP/PHP-CS-Fixer to version 2.16.2, some more unused imports were found thanks to https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4736. This PR removes these unused imports.
> [shopsys] removed unused imports

- packages/framework/assets/js/admin/components/ProductsPickerWindow.js
|Description, reason for the PR| Removing of just added product in product picker window was not working. This PR fixes it.
> [framework] fixed removing product in product picker window

- packages/framework/src/Form/Admin/Customer/DeliveryAddressFormType.php
|Description, reason for the PR| There was typo in variable name, this is fixed now.
|Fixes issues| closes #1773 
> [framework] fixed typo in variable name

- packages/framework/src/Form/Admin/Article/ArticleFormType.php
- see https://www.php.net/manual/en/migration70.new-features.php#migration70.new-features.null-coalesce-op
- the former way always returns true, which is 1 without using strict types, however, it is just wrong
|Description, reason for the PR| the operator was used in a bad way. As a result of the bad usage, you can see that all the URLs in article details in admin point to the article with ID 1 now...I found that bug because of smoke tests and using strict types on my project - a function was expecting int but got boolean :facepalm: However, it cost me 1 hour of my life :smile:  …
> [framework] ArticleFormType: fix wrong usage of null coalescing operator

- packages/framework/src/Form/Transformers/FilesIdsToFilesTransformer.php
|Description, reason for the PR| Wrong code has been sent to TransformationFailedException as it only accepts integer.
> [framework] fixed code sent to TransformationFailedException

- packages/framework/src/Model/Mail/MessageFactoryInterface.php
- the name of the parameter is less specific (and less confusing) now
|Description, reason for the PR| the specific parameter name did not make sense as the interface itself is very general
> [framework] MessageFactoryInterface:createMessage(): rename $personalData parameter

- packages/framework/composer.json
- should have been done in https://github.com/shopsys/shopsys/pull/1602
|Description, reason for the PR| it does not make sense to work with Elasticsearch 7 and require version 6 in composer.json. I believe this was just a mistake in https://github.com/shopsys/shopsys/pull/1602 because only monorepo's composer.json has been updated there
> [framework] fix version of elasticsearch in composer.json

- packages/framework/src/Resources/views/Front/Form/deliveryAddressChoiceFields.html.twig
|Description, reason for the PR| `DeliveryAddress::$country` is nullable so it might happen that getter on null is called in the template
> [framework] deliveryAddressChoiceFields.html.twig: fix risk of getter call on null

- composer.json
- packages/coding-standards/src/CsFixer/OrmJoinColumnRequireNullableFixer.php
- packages/framework/composer.json
- packages/framework/src/Model/Order/Status/Grid/OrderStatusInlineEdit.php
- project-base/composer.json
- project-base/src/Shopsys/ShopBundle/Controller/Front/ErrorController.php
- upgrade/UPGRADE-v7.3.4-dev.md
|Description, reason for the PR| New minor version (1.6) of `fp/jsformvalidator-bundle` should be used with Symfony 4 only. This PR pin version of `fp/jsformvalidator-bundle` to 1.5 minor. 
> [shopsys] fp/jsformvalidator-bundle is pinned to minor 1.5

- composer.json
- packages/coding-standards/composer.json
|Description, reason for the PR| With [slevomat/coding-standard v6.3.0](https://github.com/slevomat/coding-standard/releases/tag/6.3.0) release classes from SlevomatCodingStandard namespace are no longer autoloaded (see https://github.com/slevomat/coding-standard/pull/969). This PR locks the version to previous minor until fixed in slevomat/coding-standard.
> [coding-standards] pinned version of slevomat/coding-standard to ~6.2.0

- composer.json
- docs/installation/application-requirements.md
- docs/introduction/faq-and-common-issues.md
- docs/introduction/shopsys-framework-on-docker.md
- docs/introduction/start-building-your-application.md
- packages/backend-api/.travis.yml
- packages/coding-standards/.travis.yml
- packages/form-types-bundle/.travis.yml
- packages/framework/.travis.yml
- packages/framework/composer.json
- packages/frontend-api/.travis.yml
- packages/google-cloud-bundle/.travis.yml
- packages/http-smoke-testing/.travis.yml
- packages/migrations/.travis.yml
- packages/plugin-interface/.travis.yml
- packages/product-feed-google/.travis.yml
- packages/product-feed-google/composer.json
- packages/product-feed-heureka-delivery/.travis.yml
- packages/product-feed-heureka-delivery/composer.json
- packages/product-feed-heureka/.travis.yml
- packages/product-feed-heureka/composer.json
- packages/product-feed-zbozi/.travis.yml
- packages/product-feed-zbozi/composer.json
- packages/read-model/.travis.yml
- project-base/composer.json
- project-base/docker/php-fpm/Dockerfile
- upgrade/UPGRADE-v9.0.0-dev.md
|Description, reason for the PR| Beyond nine mountains and nine forests there was introduced new version of PHP language in version 7.4. After a while, the whole world began to whisper about the news this version brings. it wasn't long before the power of this version began to emerge. And soon this power will also appear in the Shopsys framework.
- https://github.com/shopsys/doctrine-orm package was updated to [v2.6.6](https://github.com/shopsys/doctrine-orm/releases)
- PR with fix was merged into …
> [shopsys] Upgrade PHP to 7.4

- packages/framework/src/Component/Doctrine/MoneyType.php
- project-base/config/packages/doctrine.yaml
- upgrade/UPGRADE-v9.0.0-dev.md
|Description, reason for the PR| In #1704 was deprecation about _implicitly marked type as commented_* resolved with setting the commented attribute to false. That resulted in strange behavior when generating new migrations with Money type. This PR re-enables SQL comment hints with `MoneyType::requiresSQLCommentHint()` method. (The type itself should be aware of the need of SQL comment hint)
\* `User Deprecated: The type "money" was implicitly marked as commented due to the configuration. This is …
> [shopsys] doctrine money type now requires sql comment hint

- packages/framework/assets/js/admin/components/GridDragAndDrop.js
- packages/framework/assets/js/admin/components/GridMultipleDragAndDrop.js
- packages/framework/src/Controller/Admin/SliderController.php
|Description, reason for the PR| Slider items were wrongly ordered in admin. Also there was increasing number of ajax calls, this has been solved by initializing sortable grids only for particular content.
> [framework] fix ordering of slider items in administration

- packages/framework/src/Model/AdminNavigation/SideMenuBuilder.php
- packages/framework/src/Resources/translations/messages.cs.po
- packages/framework/src/Resources/translations/messages.en.po
- packages/framework/src/Resources/views/Admin/Content/Currency/list.html.twig
- packages/framework/src/Resources/views/Admin/Content/Vat/list.html.twig
|Description, reason for the PR| In #1487 roundings was moved to currencies and global rounding was removed. This PR renames menu entries and headers on related pages. 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| Yes (removed translations) 
`VAT and roundings` renamed to `VAT` as it no longer contains rounding settings.
`Currencies` renamed to `Currencies and rounding` as rounding was moved to currency setting.
> [framework] renamed rounding related menu entries

- packages/framework/src/Component/Domain/Config/DomainsConfigLoader.php
|Description, reason for the PR| To extend parameters in `domains.yml` and `domains_url.yml`, you need to copy and paste the whole method `loadDomainConfigsFromYaml` with changed config definition classes. This PR adds method for obtaining those classes without need of duplicating the whole original method.
> [framework] used methods for providing config definition classes

- packages/framework/src/Component/Error/ErrorPagesFacade.php
|Description, reason for the PR| We do not want this form on error page sites
> [framework] subscription form removed from error pages

- composer.json
- packages/framework/composer.json
- packages/framework/phpstan.neon
- packages/framework/src/Model/Customer/User/CurrentCustomerUser.php
- project-base/composer.json
|Description, reason for the PR| In the framework we are working with FrontendApi class only in case, that bundle is installed. PHPStan ignores class_exists condition and throws an error about not the existing class. This has been resolved in this PR.
> [framework] fixed phpstan error due to not existent class from different package

- project-base/app/autoload.php
- upgrade/UPGRADE-v9.0.0-dev.md
|Description, reason for the PR| We are using shorter `d()` function for dumping some content, but most people out of Shopsys do not know about this function and they are trying to use Symfony built-in function `dump()` which is not working properly because of same function from Nette/Tracy package that is load instead of Symfony's function. A lot of people will be able to debug now :)
|Fixes issues| closes #1535 
> [project-base] fix dump function

- packages/framework/src/Resources/config/services.yml
|Description, reason for the PR| After upgrade to Symfony 4  `NotLogFakeHttpExceptionsErrorListener` was not configured properly and is not taken into account as ErrorListener. Resulting in missing ErrorID in log entries. This PR fixes that.
In the 3.4 version, the listener was configured with Twig, which was deprecated in 4.x version.
`NotLogFakeHttpExceptionsErrorListener` now replaces Symfony's default service `exception_listener`
> [framework] reconfigured NotLogFakeHttpExceptionsErrorListener service

- packages/framework/src/Resources/config/services.yml
- explicit definition of "EventDispatcherInterface $eventDispatcher" argument causes production application build to fail because TraceableEventDispatcher requires Stopwatch in its constructor and the dependency is not installed in production
|Description, reason for the PR| I am not able to install application in production env (`composer install --no-dev` fails on `Cannot autowire service "Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher": argument "$stopwatch" of method Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher::__construct()" has type "Symfony\Component\Stopwatch\Stopwatch" but this class was not found.`
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promis …
> [framework] fix Authenticator definition

- upgrade/UPGRADE-v9.0.0-dev.md
|Description, reason for the PR| We replaced #project-base-diff with commit links to prepare upgrade notes for the release of the new version
> [shopsys] replaced #project-base-diff as link to GH

- project-base/babel.config.js
- project-base/package.json
- project-base/webpack.config.js
- upgrade/UPGRADE-v9.0.0-dev.md
|Description, reason for the PR| Our js`s were broken in edge, we added missing babel plugin and fix this problem.
> [project-base] added plugin-proposal-object-rest-spread as babel plugin

- packages/framework/assets/js/admin/components/CategoryTreeSorting.js
- packages/framework/assets/js/admin/components/GridDragAndDrop.js
- packages/framework/assets/js/admin/components/GridInlineEdit.js
- packages/framework/assets/js/admin/components/GridMultipleDragAndDrop.js
- packages/framework/assets/js/admin/components/SortableValues.js
- packages/framework/assets/js/admin/components/fileUploadPreview.js
- packages/framework/assets/js/admin/components/productsPicker.js
- packages/framework/assets/package.json
- project-base/assets/js/admin/admin.js
- project-base/assets/js/frontend.js
- project-base/babel.config.js
- upgrade/UPGRADE-v9.0.0-dev.md
|Description, reason for the PR| We set support for Safari8+ in babel config and import jquery-ui-touch-punch for correct work jquery-ui on touch devices.
> [project-base] import jquery-ui-touch-punch and add safari support into babel

- composer.json
- packages/framework/composer.json
- project-base/composer.json
- upgrade/UPGRADE-v9.0.0-dev.md
|Description, reason for the PR| We want remove dev-master dependency for js fomr validator bundle
> [shopsys] updated fp/jsFormValidator bundle

- packages/framework/src/Component/EntityExtension/EntityManagerDecorator.php
- packages/product-feed-heureka/tests/Unit/HeurekaFeedItemTest.php
- packages/product-feed-zbozi/tests/Unit/ZboziFeedItemTest.php
|Description, reason for the PR| Fixes errors in annotation found by new version of PHPStan 
`packages/framework/src/Component/EntityExtension/EntityManagerDecorator.php` 
fails on 
```
Method Shopsys\FrameworkBundle\Component\EntityExtension\EntityManagerDecorator::getRepository()
should return Doctrine\Common\Persistence\ObjectRepository<T> 
but returns Doctrine\Common\Persistence\ObjectRepository<object>.
```
Maybe it's a bug in phpstan-doctrine (without phpstan-doctrine, the error is not …
> [shopsys] fixed typo in annotations

- phpstan.neon
|Description, reason for the PR| Add PHPStan limit for concurrent jobs so CI server is not overloaded.
> [shopsys] PHPStan limit maximum number of processes

- packages/framework/composer.json
|Description, reason for the PR| From #1817 there is a typo in composer.json file resulting in non-installable package. This PR fixes it.
> [framework] fixed typo in framework composer.json file

- composer.json
- project-base/composer.json
- project-base/docker/php-fpm/Dockerfile
- upgrade/UPGRADE-v9.0.0-dev.md
|Description, reason for the PR| Cache is now cleared before any other commands in composer scripts and does not rely on working application. Built Docker image does not contain cache generated on build. 
|Fixes issues| #1002 
_Note: why it's necessary to clear the cache first? 
For example, after #1606 it's necessary to clear cache after composer update. But if any symfony command is run before clearing cache, application try to use old cache with incompatible method definition and fails on `Declaration of …
> [project-base] improved clearing cache behavior

- packages/framework/assets/package.json
- project-base/package.json
|Description, reason for the PR| @shopsys/framework npm package is released in version dev.8. This PR changes the version and dependency.
> [shopsys] bump framework npm package version

- packages/framework/src/Migrations/Version20200511110953.php
- packages/framework/src/Model/Customer/User/CustomerUserRefreshTokenChain.php
|Description, reason for the PR| If some customer had refresh token chain, this customer can not be removed. This PR fixes it.
> [framework] added onDelete action on customer user refresh token chain entity

- packages/framework/assets/js/admin/components/CategoryTreeSorting.js
- project-base/package.json
- project-base/webpack.config.js
- upgrade/upgrade-instruction-for-webpack.md
|Description, reason for the PR| Sorting categories in administration requires `nestedSorting` plugin to work properly. With this PR this plugin is added and configured.
> [shopsys] fixed categories sorting in admin

- packages/framework/src/Form/Admin/Advert/AdvertFormType.php
- packages/framework/src/Form/Admin/Customer/User/CustomerUserFormType.php
- packages/framework/src/Form/Admin/CustomerCommunication/CustomerUserCommunicationFormType.php
- packages/framework/src/Form/Admin/PromoCode/PromoCodeFormType.php
- project-base/assets/js/loadTranslations.js
- project-base/src/Form/Admin/ArticleFormTypeExtension.php
- upgrade/UPGRADE-v9.0.0-dev.md
|Description, reason for the PR| Several texts in administration were not translated. This PR fixes it.
> [shopsys] fixed untranslated texts

- packages/framework/src/DependencyInjection/Compiler/RegisterExtendedEntitiesCompilerPass.php
- see https://prnt.sc/scsxyl
|Description, reason for the PR| if there is a translatable entity in project-base (i.e. it extends AbstractTranslatableEntity), the compiler pass fails on the exception as it is not possible to load metadata for the non-entity. This PR adds a check if parent is a real entity class.
> [framework] RegisterExtendedEntitiesCompilerPass: catch MappingException

- docs/frontend/npm-and-webpack.md
- packages/framework/src/Resources/views/Admin/Layout/base.html.twig
- project-base/package.json
- project-base/templates/Front/Layout/base.html.twig
- project-base/webpack.config.js
- upgrade/UPGRADE-v9.0.0-dev.md
|Description, reason for the PR| We put back liverload plugin after upgrade to webpack encore
|Fixes issues| closes #1694
> [shopsys] added livereload plugin for webpack

- packages/framework/build.xml
|Description, reason for the PR| Without passthru, all error messages (ie deprecation notices) are added into outputProperty, this should not happen as it's then impossible to parse values for multidomain check
> [framework] domain-info-load phing target now does not include errors in output properties

- packages/framework/src/Component/FlashMessage/ErrorExtractor.php
- upgrade/UPGRADE-v9.0.0-dev.md
- according to the usage of the method, the second parameter should be an array
- the bug was introduced in https://github.com/shopsys/shopsys/pull/1704
(3761f8e930931aa7a661fe3c0202ac77fa7cbe71)
|Description, reason for the PR| there is a conflict in method interface and it's usage. I had two options - change the method's interface to fit the usages, or fix the usages. I chose the first one as it seemed easier to use it this way. If you want to fix the problem another way, I am ok with it :slightly_smiling_face: Maybe `FlashMessageTrait` could provide a getter for `\Symfony\Component\HttpFoundation\Session\Flash\FlashBag` instance :thinking: 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-prom …
> [framework] fix ErrorExtractor::getAllErrorsAsArray()

- packages/framework/build.xml
|Description, reason for the PR| Solution in #1844 is not good as in translation-dump target it does not load the properties at all (visible confusion). This PR only redirects error output
> [framework] Phing: domain info load target now does not include errors in output properties

- utils/releaser/config/services.yaml
|Description, reason for the PR| We didn't update services in releaser after upgrade to symfony4. This PR fix it.
> [shopsys] fixed services in releaser

- composer.json
- packages/framework/composer.json
- project-base/composer.json
|Description, reason for the PR| newest version generate error strtolower() expects parameter 1 to be string, object given in FormExtractor class
> [shopsys] pinned jms/translator bundle to version 1.4.4

- composer.json
- packages/framework/composer.json
- project-base/composer.json
- symfony.lock
- upgrade/UPGRADE-v9.1.0-dev.md
|Description, reason for the PR| New version of PHPStan 0.12.29 started to cause `Reflection error: Psr\EventDispatcher\StoppableEventInterface not found. ` in classes extending `\Symfony\Contracts\EventDispatcher\Event`. This has been fixed by adding such classes to project in dev environment.
> [shopsys] added psr/event-dispatcher in order to prevent phpstan to repport missing class errors

- packages/framework/src/Model/Administrator/AdministratorFacade.php
|Description, reason for the PR| Method is used in `shopsys:administrator:change-password` command, but it was not working until now.
> [framework] fixed AdministratorFacade::changePassword() method

- packages/framework/src/Model/Product/Availability/ProductAvailabilityCalculation.php
|Description, reason for the PR| We canceled the default availability setting when availability can't be calculated immediately in # 1659, but new products that use stock can't be created because they need to set some availability because it's a non-null property.
> [framework] fixed calculate availability for new product

- project-base/templates/Front/Content/Login/windowForm.html.twig
- upgrade/UPGRADE-v9.0.1-dev.md
- a given form should be provided to init_js_validation function as the first parameter, otherwise, it triggers the validation init for all forms on the page - and if they are not rendered yet, it actually breaks the JS validation for them
|Description, reason for the PR| On our project, the window form is rendered directly in the site header and the original way of the js validation init has actually broken the JS validation of the other forms on the page. Kudos to @pk16011990 that helped me to find the underlying problem :pray:  …
> [project-base] windowForm: fix initialization of JS validation

- packages/framework/src/ShopsysFrameworkBundle.php
|Description, reason for the PR| There was problem, that container cache was not invalidated when changes were made in Model classes, like new entity class extending framework entity. This extended entity was not registered until cache was cleared, which could lead in several problems e.g. unable to generate database migrations.
> [framework] new entity extensions are now registered immediately

- docs/cookbook/adding-a-new-administration-page.md
- docs/cookbook/create-advanced-grid.md
- docs/cookbook/create-basic-grid.md
|Description, reason for the PR| `Sensio\Bundle\FrameworkExtraBundle\Configuration\Route` is marked as deprecated and should be replaced by `Symfony\Component\Routing\Annotation\Route` according to its own description.
> [docs] updated deprecated uses in a cookbook

- packages/framework/assets/js/admin/components/initSelect2.js
- packages/framework/assets/styles/admin/libs/select2/select2-custom.less
|Description, reason for the PR| When is some selectbox placed at the bottom of the content in the administration, it will hide under bar at the bottom of page. Select2 is supposed to recognize such behavior and display select options to the top, but it is not working well and PR created to force position of options (https://github.com/select2/select2/pull/4618) has not been accepted by author for four years. This PR introduces fix, that will force such behavior.
> [framework] select2 is no longer hidden under bottom bar in administration

- packages/framework/src/Form/Admin/Customer/User/CustomerUserFormType.php
|Description, reason for the PR| fix undefined property userData in admin form CustomerUserFormType
> [framework] fixed undefined property userData

- composer.json
- packages/backend-api/install/config/bundles.php.patch
- packages/coding-standards/composer.json
- packages/coding-standards/easy-coding-standard.yml
- project-base/config/bundles.php
- symfony.lock
- utils/releaser/src/ReleaseWorker/AbstractCheckUncommittedChangesReleaseWorker.php
- utils/releaser/src/ReleaseWorker/AfterRelease/CheckPackagesOnPackagistReleaseWorker.php
- utils/releaser/src/ReleaseWorker/Message.php
- utils/releaser/src/ReleaseWorker/Release/CheckChangelogForTodaysDateReleaseWorker.php
- utils/releaser/src/ReleaseWorker/ReleaseCandidate/CheckNewDoctrineReleaseReleaseWorker.php
- utils/releaser/src/ReleaseWorker/ReleaseCandidate/ResolveDocsTodoReleaseWorker.php
- utils/releaser/src/ReleaseWorker/ReleaseCandidate/SetFrameworkBundleVersionReleaseWorker.php
- utils/releaser/src/ReleaseWorker/ReleaseCandidate/SetMutualDependenciesToVersionReleaseWorker.php
- utils/releaser/src/ReleaseWorker/ReleaseCandidate/TestYourBranchLocallyReleaseWorker.php
- utils/releaser/src/ReleaseWorker/ReleaseCandidate/UpdateUpgradeReleaseWorker.php
- utils/releaser/src/ReleaseWorker/ReleaseCandidate/ValidateConflictsInComposerJsonReleaseWorker.php
- utils/releaser/src/ReleaseWorker/ReleaseCandidate/ValidateRequireFormatInComposerJsonReleaseWorker.php
|Description, reason for the PR| Upgrading [coding-standards] dependecy to "symplify/easy-coding-standard": "^7.3.18", needed for Symfony 5 
|Fixes issues| closes #1859 
> [coding-standards] Upgrade dependency on symplify/easy-coding-standard

- packages/framework/src/Form/Admin/BestsellingProduct/BestsellingProductFormType.php
- packages/framework/src/Model/Product/BestsellingProduct/BestsellingProductFacade.php
|Description, reason for the PR| When changing limit for bestselling products in admin, developer needed to overwrite both BestsellingProductFormType and BestsellingProductFacade. This has now been resolved using one constant for both classes.
|Fixes issues| closes #1889 
> [framework] BestsellingProductFormType now uses constant for rendering product list

- packages/backend-api/install/build.xml.patch
- packages/framework/assets/js/admin/utils/Window.js
- project-base/assets/js/frontend/utils/Window.js
- project-base/build.xml
- project-base/webpack.config.js
- upgrade/UPGRADE-v9.0.1-dev.md
|Description, reason for the PR| We are loading translations befor content load callback in `Window.js` classes - at this moment the translations wasn't load, because translations are loaded in content load callback with the highest priority. Next, we are having bad framework javascript's path in `project-base/build.xml` and we are having unnecessary path to translations in `webpack.config.js`
|Fixes issues| closes #1875  
> [shopsys] fixed JavaScript translations generation

- project-base/config/packages/snc_redis.yaml
- upgrade/UPGRADE-v9.0.1-dev.md
|Description, reason for the PR| Session were never deleted from Redis and this caused some high disk space usage. This is fixed by this PR.
Delete a session after 24 hours of user inactivity, because the session stays on the server forever and takes up memory space.
> [project-base] Automatically delete sessions after 7 days of user inactivity

- project-base/docker/php-fpm/docker-php-entrypoint
|Description, reason for the PR| `tail` used in log-pipe return last 10 lines + all following (option -f), it causes that first command has logged only last 10 lines after start new container. Eg. It is problem for crons in kubernetes (each cron starts new container and whole output is discarted except last 10 lines)
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| I don't know 
> [project-base] container log now catches all lines from first command output

- packages/framework/src/Component/Error/LogoutExceptionSubscriber.php
- packages/framework/src/Resources/translations/messages.cs.po
- packages/framework/src/Resources/translations/messages.en.po
- upgrade/UPGRADE-v9.0.1-dev.md
|Description, reason for the PR| Application did end with 500 error page when user was trying to logout, when had not valid CSRF token. This has been fixed.
|Fixes issues| closes #769 closes #1559 
> [framework] fixed error 500 during logout when the user is already logged out

- packages/framework/src/Controller/Admin/CurrencyController.php
- packages/framework/src/Model/AdminNavigation/SideMenuBuilder.php
- project-base/config/packages/security.yaml
- project-base/tests/App/Smoke/Http/RouteConfigCustomization.php
- upgrade/UPGRADE-v9.0.1-dev.md
|Description, reason for the PR| When changing a basic frontend currency on a domain in administration, the product prices are not recalculated or changed in any way. They remain the same, but in a different currency. This may happen without any warning or prompt. Because of this, I suggest restricting the access to currency setting to superadmin only.
|[BC breaks](https://github.com/shopsys/shopsys/blob/master/docs/contributing/backward-compatibility-promise.md)| No <br> ~~(for this reason, I've used `@Security` annotation instead of a record in `security.yml`, which is used for restricting access to other pages)~~<br>Record in security.yml is necessaary as it is project-base thing same as upgrading smoke tests. The app will …
> [framework] restrict access to currency settings to superadmin

- packages/http-smoke-testing/composer.json
|Description, reason for the PR| I want to use http smoke tests for my project on symfony 5
> [http-smoke-testing] added Symfony 5 support to shopsys/http-smoke-testing package

- project-base/tests/FrontendApiBundle/Functional/Customer/User/ChangePasswordTest.php
|Description, reason for the PR| ChaangePasswordTest was running without provided access token
> [frontend-api] fixed ChangePasswordTest for FE API

- project-base/tests/App/Acceptance/acceptance/CartCest.php
- upgrade/UPGRADE-v9.0.1-dev.md
|Description, reason for the PR| In CartCest were used wrong translations and that cause problems with different language on first domain. This is now fixed.
> [project-base] CartCest now uses correct translations

- packages/framework/build.xml
|Description, reason for the PR| Production protection phing target now not return 0 as the return code when user chooses to not proceed.
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| maybe (when relying on the return code 0 on fail) 
The default value is `n` (do not proceed) and when some "dangerous" target is run on the CI server (ie. Jenkins), the console output says "FAIL", but job result is a success (as the job/phing target exited with 0). This is very confusing and can lead to false assumptions that my tests pass while they weren't actually …
> [framework] production protection phing target now returns 1 on error

- packages/framework/assets/js/common/components/datePicker.js
|Description, reason for the PR| If there are more datepicker on the page, the settings are copied among themselves. For example, I have two datepicker for the first set max date to today and the second not. At this point, the second datepicker has max date set and should not have. This PR is copy of #1541 as we were not able to manage it and change previous branch as needed.
> [framework] datepicker.js assigns options per instance

- packages/framework/src/Model/Product/ProductDataFactory.php
- upgrade/UPGRADE-v9.0.1-dev.md
|Description, reason for the PR| When new `ProductData` are created, `usingStock` [attribute is set to `false` by default](https://github.com/shopsys/shopsys/blob/master/packages/framework/src/Model/Product/ProductData.php#L181). Therefore, `$availability` attribute must be set, otherwise invalid product can be created. Related to https://github.com/shopsys/shopsys/pull/1115
> [framework] default product data now have availability set

- packages/framework/src/Model/Pricing/Currency/Currency.php
|Description, reason for the PR| In order to add new rouding type I need to override functions `getRoundingTypes` and `setRoundingType` . This PR resolves problem, so overriding function `getRoundingTypes` is enough to make it work. 
> [framework] updated Currency::setRoundingType() for easier extension in project-base

- packages/framework/src/Model/Product/Elasticsearch/ProductExportRepository.php
|Description, reason for the PR| `$product->getCategoriesIndexedByDomainId` may not contain categories for provided domain ID
> [framework] ProductExportRepository: prevent Undefined offset notice

- packages/read-model/src/Product/Action/ProductActionViewFactory.php
- packages/read-model/tests/Unit/Product/Action/ProductActionViewFacadeTest.php
- packages/read-model/tests/Unit/Product/Action/ProductActionViewFactoryTest.php
|Description, reason for the PR| If I am not mistaken, `productActionView.sellingDenied` is used on one place only - https://github.com/shopsys/shopsys/blob/master/project-base/templates/Front/Inline/Cart/productAction.html.twig#L7. It does not make sense to use the value of product's `sellingDenied` attribute directly, we should use the calculated attribute. The reason is following: When a product is sold out and has "out of stock action" set to "exclude from sale" (i.e. `sellingDenied` might be `false`, but `calculatedSellingDenied` is `true` in such a case), "Product no longer on sale" should be displayed in product list as well.
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No, …
> [read-model] ProductActionView creation: use calculatedSellingDenied

- packages/framework/src/Model/Category/CategoryRepository.php
Hello,
I had a problem in project with non-found category for some products at generating feeds. Console wrote only `ERROR     [cron]` so it was a great debugging 😄 If at little possible, fill the messages for exceptions to avoid dumping vendor packages 😊 
Thanks.
PS: thanks @pk16011990 with this 🙏 
```bash
/var/www/html$ php bin/console shopsys:cron --module="overriddenDailyFeedCronModule" --instance-name=default
12:48:09 INFO      [cron] Start of …
```
> [framework] Added missing exception message about category was not found for product and domain

- packages/framework/build.xml
|Description, reason for the PR| On our project, there are "last visited products" displayed on the error pages and the data for them are fetched from elasticsearch. Also, recreating ES index and exporting data is right after `db-demo` in the other phing targets (eg. `build-demo-ci`, `build-demo-dev`, ...)
|New feature| kind of 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No, however, it could be mentioned in upgrade notes (the target might be overridden in project) 
> [framework] build-demo phing target: create elasticsearch index and export data before generating error pages

- packages/framework/src/Resources/views/Admin/Form/localizedFullWidth.html.twig
|Description, reason for the PR| CKEditor rendered as full width had flag flowing over first button, this was fixed.
> [framework] CKEditor is now rendered right in full width

- packages/framework/src/Model/Product/Search/FilterQuery.php
In the product filter on the frontend it was wrong to calculate the plus value of the parameters with multiple values for unselected parameter values, the reason being the reverse condition for the choice of elastic. For a more detailed description and explanation I am available on the slack.
> [framework] fix condition for plus numbers of parameters in the product filter

- packages/framework/assets/js/admin/utils/Window.js
- project-base/assets/js/frontend/utils/Window.js
- upgrade/UPGRADE-v9.0.1-dev.md
|Description, reason for the PR| when using `$.extend`, the first parameter is populated with the result of the function (see https://api.jquery.com/jQuery.extend/). That means, when new Window is created with some options that override the defaults, another Window that is created after the first one has default options affected by the settings of the first Window
1. Go to homepage
1. Click on "Add to cart" (for any product in "Special offers")
1. Close the window
1. Fill in a mail into the …
> [shopsys] fix Window.js - default options are not overridden by jQuery.extend function anymore

- packages/framework/src/Twig/LocalizationExtension.php
|Description, reason for the PR| When project use configuration framework.assets.base_urls eg. for using of CDN, locale flags in administraions don't work. Tested filepath looks like `/var/www/html/src/../webhttp://cdn.example.test:8000/public/admin/images/flags/cs.png`
> [framework] Locale flags now use asset packages to retrieve its URL

- packages/framework/src/Component/Filesystem/Flysystem/VolumeDriver.php
|Description, reason for the PR| While renaming file via elfinder there was warning about undefined index in VolumeDriver. This PR fixes it.
> [framework] fixed renamig files in elfinder

- packages/framework/src/Component/Filesystem/Flysystem/VolumeDriver.php
|Description, reason for the PR| This PR fixes generating thumbnails when there are more than 1 image uploaded.
> [framework] fixed saving thumbnails in elfinder

- packages/framework/assets/js/admin/components/Product.js
|Description, reason for the PR| When page has changed the side menu is aappended to current one. Thir PR empty already rendered side menu and append it into empty element.
|Fixes issues| fixes #1907  
> [framework] prevent duplicating of admin side menu

- packages/framework/assets/js/common/validation/customizeBundle.js
|Description, reason for the PR| With webpack introduction there has been a lot of rewritten Javascript code and problem with delayedValidators has been introduced - delayedValidators has been run only for one form element, not all. This has been fixed by this PR.
|Fixes issues| closes #1895 
> [framework] fixed validation of form after browser autofill

- composer.json
|Description, reason for the PR| The current state is invalid - `symplify/changelog-linker 7.2` requires class from `simplify/package-builder 7.3`. This result in uncaught error.
> [shopsys] fixed version of symplify/changelog-linker

- packages/backend-api/install/config/bundles.php.patch
- project-base/config/bundles.php
|Description, reason for the PR| In #1862 we extended `budles.php` with 3 more bundles. This change was not needed and even unwanted because it causes error in project-base. 
> [shopsys] fixed budles definition

- packages/framework/phpstan.neon
- phpstan.neon
|Description, reason for the PR| This change has been introduced in phpstan 0.12.33 https://github.com/phpstan/phpstan-src/commit/8479d405a452d915c79792c0d1c54c55dd3a9790
> [shopsys] added escaping for parenthesis in phpstan.neon

- project-base/src/DataFixtures/Demo/ImageDataFixture.php
- upgrade/UPGRADE-v9.0.2-dev.md
|Description, reason for the PR| Because I am lazy and It caused errors 
> [project-base] generate images_id_seq in data fixtures automatically

- packages/framework/src/Form/Admin/Article/ArticleFormType.php
- packages/framework/src/Model/Article/ArticleFacade.php
|Description, reason for the PR| If I want to add a new placement for articles, I have to extend the entire form because of one field. I've created a method that returns this field, and to add one (or more) placement, just overload this method
> [framework] better extensibility of article form type

- project-base/phing
- upgrade/UPGRADE-v9.0.2-dev.md
|Description, reason for the PR| It is better to use __DIR__
> [project-base] use __DIR__ instead of dirname(__FILE__)

- packages/framework/src/Model/Administrator/Security/AdministratorFrontSecurityFacade.php
|Description, reason for the PR| When method `AdministratorFrontSecurityFacade::isAdministratorLogged()` is called on front-end (eg. in GTM layer), it causes redirect to `front_login` route. And if this calling is in login page, It causes `Too many redirections`. All exceptions catched can be thrown in `AdministratorUserProvider::refreshUser`.
> [framework] updated AdministratorFrontSecurityFacade::isAdministratorLogged() to work well if used on frontend

- packages/framework/src/Component/Doctrine/NotNullableColumnsFinder.php
- packages/framework/tests/Unit/Component/Doctrine/NotNullableColumnsFinderTest.php
|Description, reason for the PR| Fixed issue
|Fixes issues| closes #1759 
> [framework] added array_key_exists condition into to NotNullableColumnsFinder method

- packages/framework/src/Model/Product/Product.php
- the method now adds the new elements only when they are not present in the current data
- this solution prevents the application from possible duplicate key errors
- original problem: when flush without parameter is called on entity manager, elements
that are removed from collection are scheduled for DELETE, however,
INSERT queries are executed before DELETE, so the application fails here
- the behavior is connected with `orphanremoval=true` and `cascade={"persist"}` settings of `Product::$productCategoryDomains`
|Description, reason for the PR| the application might fail on duplicate key error when flush without parameter is called during the product editing
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward- …
> [framework] Product::setProductCategoryDomains() fix

- project-base/tests/FrontendApiBundle/Functional/Category/CategoriesTest.php
- project-base/tests/FrontendApiBundle/Functional/Customer/User/ChangePasswordTest.php
- project-base/tests/FrontendApiBundle/Functional/Customer/User/CurrentCustomerUserTest.php
- project-base/tests/FrontendApiBundle/Functional/Login/LoginTest.php
- project-base/tests/FrontendApiBundle/Functional/Logout/LogoutTest.php
- project-base/tests/FrontendApiBundle/Functional/Order/CompanyFieldsAreValidatedTest.php
- project-base/tests/FrontendApiBundle/Functional/Order/DeliveryFieldsAreValidatedTest.php
- project-base/tests/FrontendApiBundle/Functional/Order/DynamicFieldsInOrderTest.php
- project-base/tests/FrontendApiBundle/Functional/Order/RequiredFieldsTest.php
- project-base/tests/FrontendApiBundle/Functional/Product/ProductsTest.php
- project-base/tests/FrontendApiBundle/Test/GraphQlTestCase.php
- upgrade/UPGRADE-v9.1.0-dev.md
|Description, reason for the PR| FE API tests end by throwing error (undefined index) instead of failure.
TODO:
> [project-base] more reliable FE API tests

- utils/releaser/src/ReleaseWorker/Release/CreateAndPushGitTagReleaseWorker.php
- utils/releaser/src/ReleaseWorker/Release/MergeReleaseCandidateBranchReleaseWorker.php
|Description, reason for the PR| In `release` stage of `monorepo-builder release` is recommneding wrong tools to run. These names are fixed to proper one in this PR
> [releaser] fixed names of required heimdall tools for releasing new version

- utils/releaser/src/ReleaseWorker/Release/CreateAndPushGitTagsExceptProjectBaseReleaseWorker.php
|Description, reason for the PR| In releaser we have outdated list of repositories which are unmaintained or forked. This PR updates the list.
> [releaser] updated releaser list of excluded packages

- utils/releaser/src/ReleaseWorker/ReleaseCandidate/ReleaseNewNodeModulePackageVersion.php
|Description, reason for the PR| The command for releasing of new npm package is wrong. This PR fixes it.
> [releaser] releaser fixed npm command

- UPGRADE.md
- upgrade/UPGRADE-v9.0.1.md
|Description, reason for the PR| This PR fixes links in upgrade notes from v9.0.1 release
> [docs] fixed links in upgrade notes

- utils/releaser/src/ReleaseWorker/Release/CreateAndPushGitTagsExceptProjectBaseReleaseWorker.php
|Description, reason for the PR| When running `release` stage you need to fill in username and password for each repository (unless it is not already saved in git config). This PR adds a note how to prevent this state.
> [releaser] added note about posibility of credentials caching while releasing

- utils/releaser/src/ReleaseWorker/AbstractCheckPackagesTravisBuildsReleaseWorker.php
- utils/releaser/src/ReleaseWorker/AfterRelease/CheckPackagesTravisBuildsReleaseWorker.php
- utils/releaser/src/ReleaseWorker/ReleaseCandidate/CheckPackagesTravisBuildsReleaseWorker.php
|Description, reason for the PR| In `after-release` stage of releaser there is check for passing builds on travis. The check should validated the released version instead initial branch. This PR fixes that.
> [releaser] fixed checking builds in after-release stage

- packages/framework/assets/js/common/validation/customizeFpValidator.js
|Description, reason for the PR| When compound item has property with reserved name (eg. `id`), it causes broken FpJsElement.
> [framework] JS validation: fix creating of prototype of compound item in collection

- packages/framework/src/Resources/config/services_test.yaml
- project-base/config/services_test.yaml
- project-base/tests/App/Functional/EntityExtension/EntityExtensionTest.php
- project-base/tests/App/Performance/Feed/AllFeedsTest.php
- project-base/tests/App/Performance/Page/AllPagesTest.php
- project-base/tests/App/Smoke/Http/HttpSmokeTest.php
- project-base/tests/App/Smoke/Http/RouteConfigCustomization.php
- project-base/tests/App/Test/Codeception/Helper/SymfonyHelper.php
- project-base/tests/App/Test/FunctionalTestCase.php
- upgrade/UPGRADE-v9.0.2-dev.md
|Description, reason for the PR| With Symfony 4.1 came new test container that includes all defined services in `services.yaml`. There are some restrictions like services not used in any other service are removed from this container. That is reason why some services must be kept. This PR has been inspired by #1661.
|Fixes issues| closes #907 
> [shopsys] update tests to use tests container to decrease amount of services defined in `services_test.yaml`

- packages/framework/assets/js/admin/components/ProductsPickerWindow.js
|Description, reason for the PR| In this scenario if you choose product as product accessory for example, this product is added to form more than once.
|Fixes issues| closes #1962 
> [framework] fixed multiple binding of product picker events

- packages/framework/src/Component/Elasticsearch/AbstractExportChangedCronModule.php
- packages/framework/src/Model/Product/Elasticsearch/ProductExportChangedCronModule.php
|Description, reason for the PR| If I export data to the ES, the data is never set as exported...
|Fixes issues|
> [framework] IndexExportedEvent is called after elasticsearch export cron module finished

- packages/framework/src/Model/Product/Availability/ProductAvailabilityCalculation.php
|Description, reason for the PR| Seems like a little typo but it has kind of huge impact - it breaks the functionality of annotations fixer - it is not able to get the property type properly and it results in adding `@property  $productSellingDeniedRecalculator` (ie. the type is missing completely) property annotation into my extended class. Of course, phpstan has a problem with such an annotation so we end up in a cycle of failing annotations-fix <-> phpstan . In combination with https://github.com/shopsys/shopsys/issues/1958, it is really unpleasant 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)|No  …
> [framework] ProductAvailabilityCalculation: fix property annotation

- packages/coding-standards/easy-coding-standard.yml
- upgrade/UPGRADE-v9.1.0-dev.md
|Description, reason for the PR| This PR bring compliance of our coding-standards package with [PSR-12](https://www.php-fig.org/psr/psr-12/). It uses the [PSR-12 set](https://github.com/Symplify/EasyCodingStandard/blob/master/config/set/psr12.yaml) in `Symplify/EasyCodingStandard` package for the automated checking.<br>Some parts of the standard are not checked by ECS yet (for example [multiline conditionals](https://www.php-fig.org/psr/psr-12/#51-if-elseif-else)) - this will probably be fixed in new versions of ECS in the future (we can even create a PR with new such fixers and help the PHP community).<br>There were no changes required in the code for compliance with the new standards.
|[BC …
> [coding-standards] easy-coding-standard.yml: declare compliance with PSR-12

- utils/releaser/src/ReleaseWorker/Release/MergeReleaseCandidateBranchReleaseWorker.php
|Description, reason for the PR| When merging release candidate on github may cause troubles in further progress. This PR adds warning to prvent it.
> [releaser] releaser added warning when merging RC branch

- packages/framework/assets/js/admin/components/FileUpload.js
- packages/framework/easy-coding-standard.yml
- packages/framework/src/Component/FileUpload/DeleteOldUploadedFilesCronModule.php
- packages/framework/src/Component/FileUpload/FileUpload.php
- packages/framework/src/Component/Image/Processing/ImageProcessor.php
- packages/framework/src/DependencyInjection/Compiler/AddConstraintValidatorsPass.php
- packages/framework/src/Form/Constraints/FileAbstractFilesystemValidator.php
- packages/framework/src/Form/Constraints/ImageAbstractFilesystemValidator.php
- packages/framework/src/Model/Mail/MailTemplateAttachmentFilepathProvider.php
- packages/framework/src/Resources/config/directories.yaml
- packages/framework/src/Resources/config/paths.yaml
- packages/framework/src/Resources/config/services.yaml
- packages/framework/src/Resources/config/services/cron.yaml
- packages/framework/src/ShopsysFrameworkBundle.php
- packages/framework/tests/Unit/Component/Image/ImageFactoryTest.php
- project-base/config/paths.yaml
- project-base/config/services/cron.yaml
- upgrade/UPGRADE-v9.0.2-dev.md
|Description, reason for the PR| With more replicas of PHP-FPM is possible to run on another replica before uploaded file is saved to abstract filesystem. This has been now solved.
|Fixes issues| closes #1917 
> [shopsys] temporary fileupload is now uploaded to abstract filesystem

- packages/framework/src/Component/Collector/ShopsysFrameworkDataCollector.php
- packages/framework/src/Component/Doctrine/MoneyType.php
- packages/framework/src/Component/Money/Exception/InvalidNumericArgumentException.php
- packages/framework/src/Component/Money/Exception/UnsupportedTypeException.php
- packages/framework/src/Component/Money/Money.php
- packages/framework/src/Form/Transformers/CopyTotalPricesOfOrderItemTransformer.php
- packages/framework/src/Form/Transformers/NumericToMoneyTransformer.php
- packages/framework/src/Migrations/Version20181114102106.php
- packages/framework/src/Migrations/Version20181114120915.php
- packages/framework/src/Migrations/Version20181114134959.php
|Description, reason for the PR| Shopsys Framework uses class extendability like main way, how to override it. However few classes break is with their `final` definition. And it is inconsistent (3 DB migrations are final and others not). I didn't solve classes in tests, coding standards package and utils. Maybe it can be watched by automatic sniff like protected property, because protected property in final class is funny and sad in one time... 
> [framework] remove final from relevant classes

- packages/framework/src/Model/Product/ProductOnCurrentDomainElasticFacade.php
- packages/framework/src/Model/Product/ProductOnCurrentDomainFacade.php
- packages/framework/src/Model/Product/ProductOnCurrentDomainFacadeInterface.php
- packages/framework/src/Model/Product/Search/ProductElasticsearchRepository.php
- packages/frontend-api/src/Model/Resolver/Products/ProductsResolver.php
- project-base/tests/FrontendApiBundle/Functional/Product/ProductsTest.php
|Description, reason for the PR| Keyword last was working wrong way. This was caused by wrong implementation of Paginator. This has been solved in this PR.
> [shopsys] fixed filtering of products in frontend API

- packages/framework/src/Model/Order/OrderFacade.php
- packages/framework/src/Model/Order/OrderRepository.php
- packages/frontend-api/apiary.apib
- packages/frontend-api/src/Model/Resolver/Order/OrderResolver.php
- packages/frontend-api/src/Model/Resolver/Order/OrdersResolver.php
- packages/frontend-api/src/Resources/config/graphql-types/Pagination/OrderDecoratorConnection.types.yaml
- packages/frontend-api/src/Resources/config/graphql-types/QueryDecorator.types.yaml
- project-base/config/graphql/types/Pagination/OrderConnection.types.yaml
- project-base/tests/FrontendApiBundle/Functional/Order/GetOrderAsAuthenticatedCustomerUserTest.php
- project-base/tests/FrontendApiBundle/Functional/Order/GetOrderAsUnauthenticatedCustomerUserTest.php
- project-base/tests/FrontendApiBundle/Functional/Order/GetOrdersAsAuthenticatedCustomerUserTest.php
- project-base/tests/FrontendApiBundle/Functional/Order/GetOrdersAsUnauthenticatedCustomerUserTest.php
- project-base/tests/FrontendApiBundle/Test/GraphQlWithLoginTestCase.php
|Description, reason for the PR| This PR adds posibility to retreive order list or single order for given customer user or combination of uuid and urls hash.
> [frontend-api] Added resolvers for orders

- project-base/phpstan.neon
- upgrade/UPGRADE-v9.1.0-dev.md
|Description, reason for the PR| Wrong path has been used in implementation of phpstan-symfony, this is now fixed.
> [project-base] fixed path to tests in phpstan.neon

- .gitignore
|Description, reason for the PR| Every time I work with the projetct file `.phpcs-cache` is created. I do not want to exclude or delete it before every commit so I added it to `.gitignore` to prevent commiting it accidentally.
> [shopsys] ignored phpcs-cache file for git repository

- packages/framework/src/Component/Image/Config/ImageConfig.php
- packages/framework/src/Component/Image/Config/ImageConfigLoader.php
- packages/framework/tests/Unit/Component/Image/Config/ImageConfigLoaderTest.php
- packages/framework/tests/Unit/Component/Image/Config/ImageConfigTest.php
- packages/framework/tests/Unit/Component/Image/DirectoryStructureCreatorTest.php
- packages/framework/tests/Unit/Component/Image/ImageLocatorTest.php
- project-base/config/services_test.yaml
- project-base/tests/App/Functional/Component/Image/Config/ImageConfigTest.php
- upgrade/UPGRADE-v9.0.1.md
|Description, reason for the PR| See #1693... This issue is unfixable on project, because class `ImageClass` contains extra semicolon in annotation (first commit). The extra semicolon fails in phing target annotation fix. Please accept this PR ASAP.
|Fixes issues| #1693 
> [shopsys] ImageConfig accepts extended entities

- packages/coding-standards/easy-coding-standard.yml
- packages/coding-standards/src/Sniffs/ForbiddenDoctrineDefaultValueSniff.php
- packages/coding-standards/tests/Unit/Sniffs/ForbiddenDoctrineDefaultValueSniff/ForbiddenDoctrineDefaultValueSniffTest.php
- packages/coding-standards/tests/Unit/Sniffs/ForbiddenDoctrineDefaultValueSniff/config.yaml
- packages/coding-standards/tests/Unit/Sniffs/ForbiddenDoctrineDefaultValueSniff/correct/invalid_docblock_annotation.php
- packages/coding-standards/tests/Unit/Sniffs/ForbiddenDoctrineDefaultValueSniff/correct/missing_default_value_annotation.php
- packages/coding-standards/tests/Unit/Sniffs/ForbiddenDoctrineDefaultValueSniff/wrong/default_value_annotation.php
- packages/coding-standards/tests/Unit/Sniffs/ForbiddenDoctrineDefaultValueSniff/wrong/different_order_annotation.php
- packages/coding-standards/tests/Unit/Sniffs/ForbiddenDoctrineDefaultValueSniff/wrong/multiline_annotation.php
- packages/coding-standards/tests/Unit/Sniffs/ForbiddenDoctrineDefaultValueSniff/wrong/spaces_around_annotation.php
- packages/coding-standards/tests/Unit/Sniffs/ForbiddenDoctrineDefaultValueSniff/wrong/split_annotation.php
- packages/framework/src/Component/Cron/CronModule.php
- packages/framework/src/Migrations/Version20200803105229.php
- packages/framework/src/Model/Newsletter/NewsletterSubscriber.php
- packages/framework/src/Model/Product/Product.php
- upgrade/UPGRADE-v9.1.0-dev.md
|Description, reason for the PR| This PR prevents using a DB default value in doctrine properties (with a sniff) and also removes usages through the codebase.
|Fixes issues| closes #1242 
> [shopsys] added sniff fobidden default values in Doctrine

- packages/framework/easy-coding-standard.yml
- packages/framework/src/Command/ChangeAdminPasswordCommand.php
- packages/framework/src/Component/Filesystem/Flysystem/VolumeDriver.php
- packages/framework/src/Form/Constraints/UniqueEmailValidator.php
- packages/framework/src/Model/AdvancedSearchOrder/Filter/OrderCityFilter.php
- packages/framework/src/Model/AdvancedSearchOrder/Filter/OrderEmailFilter.php
- packages/framework/src/Model/AdvancedSearchOrder/Filter/OrderLastNameFilter.php
- packages/framework/src/Model/AdvancedSearchOrder/Filter/OrderNameFilter.php
- packages/framework/src/Model/AdvancedSearchOrder/Filter/OrderNumberFilter.php
- packages/framework/src/Model/AdvancedSearchOrder/Filter/OrderPhoneNumberFilter.php
- packages/framework/src/Model/AdvancedSearchOrder/Filter/OrderPriceFilterWithVatFilter.php
- packages/framework/src/Model/AdvancedSearchOrder/Filter/OrderStreetFilter.php
- packages/framework/src/Model/Pricing/InputPriceRecalculator.php
- packages/framework/src/Twig/NumberFormatterExtension.php
- project-base/easy-coding-standard.yml
- upgrade/UPGRADE-v9.1.0-dev.md
|Description, reason for the PR| Disallows using loose == and != comparison operators. Use === and !== instead, they are much more secure, predictable and consistent.
Fixer needs manual check, because some code could rely on less strict comparisons -> BC break in my opinion.
> [shopsys] coding standards for using strict comparison operators

- project-base/assets/js/frontend/components/spinbox.js
|Description, reason for the PR| Spinbox was not using minimal value, when incrementing number and maximal value when decreasing number. The calculation is now same for both actions and spinbox should now work correctly.
|Fixes issues| closes #1516 
> [framework] spinbox plus now works correctly with min value

- packages/framework/src/Model/Product/ProductRepository.php
|Description, reason for the PR| doctrine fails to hydrate non-unique rows when used iterator. error when running cron Shopsys\FrameworkBundle\Model\Pricing\Vat\VatDeletionCronModule
|Fixes issues| #1968 
> [framework] select distinct product for vat replace

- packages/framework/src/Form/Admin/Category/CategoryFormType.php
- packages/framework/src/Model/AdvancedSearch/Filter/ProductCategoryFilter.php
- packages/framework/src/Model/Category/CategoryFacade.php
- packages/framework/src/Model/Category/CategoryRepository.php
- upgrade/UPGRADE-v9.0.2-dev.md
|Description, reason for the PR| Domain locale has been used for loading categories in admin instead of admin locale, this has been fixed now.
|Fixes issues| closes #1729 
> [framework] categories in admin are now loaded using admin locale

- packages/framework/src/Resources/views/Admin/Content/Administrator/list.html.twig
- packages/framework/src/Resources/views/Admin/Content/Advert/list.html.twig
- packages/framework/src/Resources/views/Admin/Content/Article/list.html.twig
- packages/framework/src/Resources/views/Admin/Content/Category/list.html.twig
- packages/framework/src/Resources/views/Admin/Content/Country/list.html.twig
- packages/framework/src/Resources/views/Admin/Content/Customer/list.html.twig
- packages/framework/src/Resources/views/Admin/Content/Product/list.html.twig
- packages/framework/src/Resources/views/Admin/Content/PromoCode/list.html.twig
- packages/framework/src/Resources/views/Admin/Content/Script/list.html.twig
- packages/framework/src/Resources/views/Admin/Content/Slider/list.html.twig
- packages/framework/src/Resources/views/Admin/Layout/layoutWithPanel.html.twig
|Description, reason for the PR| Beside page title in administration there are empty blocks, which make title smaller. Now we are generating right block only if contains buttons.
|Fixes issues| closes #1887  
> [framework] design - admin title button wrap bar only if contains buttons

- packages/framework/src/Model/Customer/Customer.php
- packages/framework/src/Model/Customer/CustomerFacade.php
- packages/framework/src/Model/Customer/CustomerRepository.php
- packages/framework/src/Model/Customer/User/CustomerUserFacade.php
- upgrade/UPGRADE-v9.0.2-dev.md
|Description, reason for the PR| When customer user is deleted, all his addresses and customer are also deleted.
|Fixes issues| closes #663 
> [framework] remove customer and his addresses with customer user

- docs/introduction/console-commands-for-application-management-phing-targets.md
- packages/backend-api/install/config/parameters_common.yaml.patch
- project-base/config/packages/snc_redis.yaml
- project-base/config/parameters_common.yaml
- project-base/config/parameters_version.yaml.dist
- upgrade/UPGRADE-v9.0.2-dev.md
|Description, reason for the PR| Application was using same redis tables for each environment and this could result in unexpected problems. This has been solved by adding environment into build-version and using it for all redis tables.
|Fixes issues| closes #860 
> [shopsys] redis build-version now includes application environment

- packages/framework/src/Resources/views/Admin/Inline/Breadcrumb/breadcrumb.html.twig
|Description, reason for the PR| We have breadcrumb navigation in the administration, but if there is a link to the route, this navigation will not display the link. This PR adds a link to the navigation.
> [framework] added link into breadcrumb item in admin if uri is not null

- packages/framework/assets/js/common/validation/customizeBundle.js
|Description, reason for the PR| There has been accidentally removed logic around delayed validators in previous versions. This logic has now been returned back and makes for example connected password input validations work again. 
> [framewok] fixed delayed javascript validators

- docs/introduction/cron.md
- docs/introduction/working-with-date-time-values.md
- packages/backend-api/install/config/parameters_common.yaml.patch
- packages/framework/src/Command/CronCommand.php
- packages/framework/src/Resources/config/parameters_common.yaml
- project-base/config/parameters_common.yaml
- upgrade/UPGRADE-v9.0.2-dev.md
|Description, reason for the PR| With introduction of setting all dates and times in UTC timezone, problems with running crons in desired times has occurred.
|Fixes issues| closes #1924 
> [shopsys] timezone for running crons

- project-base/src/Controller/Front/CartController.php
- project-base/templates/Front/Inline/Cart/afterAddWindow.html.twig
|Description, reason for the PR| The accessories is load with every addProductAjaxAction request now. I added condition into controller for get accessories if module is enabled only. Condition in view is to late in my opinion. 
> [project-base] added condition for get accessories if module is enabled only

- packages/framework/src/Component/Redis/RedisVersionsFacade.php
|Description, reason for the PR| There was released a [new version of phpstan](https://github.com/phpstan/phpstan/releases/tag/0.12.40) which leaad to errors. The referenced property is not recognized right so it needs to be aannotated.
> [framework] annotated referenced variable

- packages/framework/src/Controller/Admin/ProductController.php
|Description, reason for the PR| Product sellingTo has been set to 00:00 hours, so products have been hidden one day earlier than expected. This has been solved now.
|Fixes issues| closes #1924 
> [framework] sellingTo is now set with the end of day time

- project-base/app/getEnvironment.php
|Description, reason for the PR| Test environment was wrongly detected as production and it caused production-protection phing target to warn user, that he is in production environment when it was not true.
> [framework] test environment is no longer wrongly detected as prod

- packages/framework/src/Migrations/Version20200828131906.php
- packages/framework/src/Model/Cart/Cart.php
- packages/framework/src/Model/Cart/Item/CartItem.php
|Description, reason for the PR| There was an error when deleting customer user with cart items. This PR fixes that.
|Fixes issues| closes #2008 
> [framework] cart items are now correctly deleted when cart is deleted

- docs/introduction/console-commands-for-application-management-phing-targets.md
- packages/framework/build.xml
|Description, reason for the PR| programmer can easily switch to desired environment. There is a protection to run command in production environment.
|[BC breaks] No 
|Fixes issues| closes #1744  
> [framework] new phing target for changing environment

- .gitignore
- project-base/.gitignore
- project-base/docker/php-fpm/Dockerfile
- upgrade/UPGRADE-v9.1.0-dev.md
|Description, reason for the PR| Previous location was /home/www-data, which is not persisted and after running docker-compose down and docker-compose up was npm link information lost and npm was not able to recreate it again
> [shopsys] moved npm-global directory to project so it is included in volume

- packages/backend-api/easy-coding-standard.yml
- packages/coding-standards/easy-coding-standard.yml
- packages/form-types-bundle/easy-coding-standard.yml
- packages/framework/easy-coding-standard.yml
- packages/frontend-api/easy-coding-standard.yml
- packages/google-cloud-bundle/easy-coding-standard.yml
- packages/http-smoke-testing/easy-coding-standard.yml
- packages/migrations/easy-coding-standard.yml
- packages/plugin-interface/easy-coding-standard.yml
- packages/product-feed-google/easy-coding-standard.yml
- packages/product-feed-heureka-delivery/easy-coding-standard.yml
- packages/product-feed-heureka/easy-coding-standard.yml
- packages/product-feed-zbozi/easy-coding-standard.yml
- packages/read-model/easy-coding-standard.yml
- project-base/easy-coding-standard.yml
- upgrade/UPGRADE-v9.0.3-dev.md
|Description, reason for the PR| According to cahnge in symplify package there is no longer possible to use `%vendor_dir%`. The usages should be replaced via path. See https://github.com/symplify/symplify/pull/1752
|Fixes issues| fixes #2012  
> [shopsys] fixed import path in ecs configurations

- .codeac.yml
|Description, reason for the PR| We wanna try codeac, but we want to prevent it to run on all branches before it is set correctly. This PR should ensure that.
> [shopsys] disable codeac.io by default so it is not run on branches until it is set properly

- docker/conf/docker-compose-mac.yml.dist
- docker/conf/docker-compose-win.yml.dist
- docker/conf/docker-compose.yml.dist
- docker/conf/docker-sync-win.yml.dist
- docker/conf/docker-sync.yml.dist
|Description, reason for the PR| Docker-sync is needed mainly for PHP files, so project runs smoothly. Other files can be synced via internal docker volumes, as its speed does not impact project performance much. This optimizations are made in hope to decrease number of files maintained by docker-sync. .git folder added to enable optimized phing targets on Win and Mac in the future. Only monorepo files are included in order to test impact of these changes.
> [shopsys] optimized monorepo docker files

- upgrade/UPGRADE-v9.1.0-dev.md
|Description, reason for the PR| in #1827 are missing upgrade notes. This PR adding them
> [shopsys] added missing upgrade notes for 1827

- upgrade/UPGRADE-v9.0.1.md
- upgrade/UPGRADE-v9.0.2.md
- added a link to project-base diff
- the instruction moved from UPGRADE-v9.0.1.md to UPGRADE-v9.0.2.md as
the modification was actaully released in 9.0.2
|Description, reason for the PR| it was really confusing for us that the newly added `ImageConfigTest` was failing and it took some time until we realized that the modification is not present in `9.0.1` version :smile: 
> [shopsys] fix upgrade notes for https://github.com/shopsys/shopsys/pull/1777

- packages/framework/src/Form/Admin/Slider/SliderItemFormType.php
|Description, reason for the PR| Removed constraint NotBlank for ID, because slider ID cannot be change.
> [framework] removed SliderFormType excessive ID constraint

- packages/framework/src/Component/Elasticsearch/IndexDefinition.php
- packages/framework/src/Model/Category/CategoryFacade.php
- packages/framework/src/Model/Category/CategoryRepository.php
|Description, reason for the PR| We have added @deprecated annotation to deprecated methods, but triggering deprecated notice was missing. This has been now added to alert users they should update their code before next major.
> [framework] deprecated notice is triggered when deprecated method is called

- project-base/templates/Front/Content/Product/filterFormMacro.html.twig
- upgrade/UPGRADE-v9.1.0-dev.md
|Description, reason for the PR| When the count in the filter was 0, the "+" sign was still displayed and the corresponding checkbox was not disabled (you can test it with demo data in "tv, audio" category by checking "Sencor" brand + "250 kWh/year" for "Annual energy consumption" parameter - see https://prnt.sc/ubmrdd) - that was a bug for flags and parameter values. For brands, this is already ok :slightly_smiling_face: 
> [project-base] filterFormMacro.html.twig: display "+" only if counts > 0

- packages/framework/src/Model/Product/ProductOnCurrentDomainElasticFacade.php
- packages/framework/src/Model/Product/Search/FilterQueryFactory.php
- upgrade/UPGRADE-v9.0.3-dev.md
|Description, reason for the PR| ProductOnCurrentDomainElasticFacade had more responsibilities than it should. One of them was creating FilterQuery object and filling it with necessary data. This part has now been moved to factory.
> [framework] move creation of FilterQuery from facade to factory

- docs/introduction/how-to-set-up-domains-and-locales.md
- packages/framework/src/Model/Administration/AdministrationFacade.php
- packages/framework/src/Resources/config/services_test.yaml
- packages/framework/tests/Test/TestTranslatableListener.php
- project-base/config/packages/test/prezent_doctrine_translatable.yaml
- project-base/tests/App/Functional/Model/Cart/CartFacadeTest.php
- upgrade/UPGRADE-v9.1.0-dev.md
|Description, reason for the PR| Tests are running from CLI without having locale set. It results in using default locale configured in `parameters.locale` variable.<br>This PR make tests to be running with first domain locale.
> [framework] changed default locale in test to domain locale

- project-base/src/DataFixtures/Demo/ProductDataFixture.php
- project-base/tests/FrontendApiBundle/Functional/Article/GetArticleTest.php
- project-base/tests/FrontendApiBundle/Functional/Article/GetArticlesTest.php
- project-base/tests/FrontendApiBundle/Functional/Category/CategoriesTest.php
- project-base/tests/FrontendApiBundle/Functional/Customer/User/CurrentCustomerUserTest.php
- project-base/tests/FrontendApiBundle/Functional/Order/AbstractOrderTestCase.php
- project-base/tests/FrontendApiBundle/Functional/Order/CompanyFieldsAreValidatedTest.php
- project-base/tests/FrontendApiBundle/Functional/Order/DeliveryFieldsAreValidatedTest.php
- project-base/tests/FrontendApiBundle/Functional/Order/FullOrderTest.php
- project-base/tests/FrontendApiBundle/Functional/Order/GetOrdersAsAuthenticatedCustomerUserTest.php
- project-base/tests/FrontendApiBundle/Functional/Order/MinimalOrderTest.php
- project-base/tests/FrontendApiBundle/Functional/Order/MultipleProductsInOrderTest.php
- project-base/tests/FrontendApiBundle/Functional/Product/ProductTest.php
- project-base/tests/FrontendApiBundle/Functional/Product/ProductVariantTest.php
- project-base/tests/FrontendApiBundle/Functional/Product/ProductsTest.php
- upgrade/UPGRADE-v9.1.0-dev.md
|Description, reason for the PR| Current state of functional tests in [frontend api](https://github.com/shopsys/frontend-api) is not suitable for changing locales on domain. When doing so the FEAPI tests will start failing. This PR will make the tests more stable
> [frontend-api] Made functional tests independent on domain locales

- packages/backend-api/composer.json
- packages/form-types-bundle/composer.json
- packages/frontend-api/composer.json
- packages/google-cloud-bundle/composer.json
- packages/migrations/composer.json
- packages/product-feed-google/composer.json
- packages/product-feed-heureka-delivery/composer.json
- packages/product-feed-heureka/composer.json
- packages/product-feed-zbozi/composer.json
- packages/read-model/composer.json
|Description, reason for the PR| Required fixed version of `symfony/http-kernel` due to https://github.com/advisories/GHSA-754h-5r27-7x3r
> [shopsys] required symfony/http-kernel in 4.4.13 or higher due to security issue

- packages/framework/src/Component/Image/ImageFacade.php
- packages/framework/src/Model/Product/ProductFacade.php
- packages/framework/src/Model/Product/ProductOnCurrentDomainElasticFacade.php
- packages/framework/src/Model/Product/ProductOnCurrentDomainFacade.php
- packages/framework/src/Model/Product/ProductOnCurrentDomainFacadeInterface.php
- packages/framework/src/Model/Product/ProductRepository.php
- packages/frontend-api/src/Component/Constraints/ProductCanBeOrderedValidator.php
- packages/frontend-api/src/Component/Image/ImageFacade.php
- packages/frontend-api/src/Model/Product/ProductFacade.php
- packages/frontend-api/src/Model/Product/ProductRepository.php
- packages/frontend-api/src/Model/Resolver/Image/ImagesResolver.php
- packages/frontend-api/src/Resources/config/services.yaml
- upgrade/UPGRADE-v9.0.3-dev.md
|Description, reason for the PR| We added in previous versions some methods in framework, that were used only by FE API. Some of those methods even lead to BC break. All these were moved to FE API to remove not necessary methods from framework.
> [shopsys] Moved methods used only by FE API from framework facades to FE API facades

- packages/frontend-api/src/Model/Resolver/Products/ProductsResolver.php
|Description, reason for the PR| In refactoring of ProductOnCurrentDomainFacade we forgot to update frontend API resolvers. This has been fixed here.
> [frontend-api] frontend API now correctly uses methods from frontend API facades instead of framework ones

- packages/framework/src/Model/Article/ArticleFacade.php
- packages/framework/src/Model/Article/ArticleRepository.php
- packages/framework/src/Model/Order/OrderFacade.php
- packages/framework/src/Model/Order/OrderRepository.php
- packages/frontend-api/src/Model/Article/ArticleFacade.php
- packages/frontend-api/src/Model/Article/ArticleRepository.php
- packages/frontend-api/src/Model/Order/OrderFacade.php
- packages/frontend-api/src/Model/Order/OrderRepository.php
- packages/frontend-api/src/Model/Resolver/Article/ArticleResolver.php
- packages/frontend-api/src/Model/Resolver/Article/ArticlesResolver.php
- packages/frontend-api/src/Model/Resolver/Order/OrderResolver.php
- packages/frontend-api/src/Model/Resolver/Order/OrdersResolver.php
|Description, reason for the PR| When working on FE API we have added some methods to framework classes that should not be there. This PR fixes that.
> [shopsys] remove FE API only dependencies from framework

- .ci/build_kubernetes.sh
- project-base/tests/FrontendApiBundle/Functional/Image/ProductImagesTest.php
- project-base/tests/FrontendApiBundle/Functional/Payment/PaymentsTest.php
- project-base/tests/FrontendApiBundle/Functional/Transport/TransportsTest.php
- upgrade/UPGRADE-v9.0.3-dev.md
|Description, reason for the PR| Currently tests were not run by default and sometimes there would be helpful. This PR also fixes problems with image urls on our current CI.
> [shopsys] frontend API tests are always run on CI in monorepo

- packages/frontend-api/src/Model/Product/ProductFacade.php
- packages/frontend-api/src/Model/Resolver/Products/ProductsResolver.php
|Description, reason for the PR| Count of products fo categories has been counted in wrong way. This has been now fixed.
> [frontend-api] pagination now works with right number of products

- docs/introduction/autocompletion-for-phing-targets.md
- docs/introduction/console-commands-for-application-management-phing-targets.md
- docs/introduction/index.md
- docs/introduction/navigation.yml
- project-base/docker/php-fpm/Dockerfile
- project-base/docker/php-fpm/phing-completion
- upgrade/UPGRADE-v9.1.0-dev.md
|Description, reason for the PR| In the container is now possible to autocomplete names of the Phing targets. Behavior is documented with hints how to set up autocompletion on the host machine too. Thanks to @pk16011990 for the solution on the host machine.
|Fixes issues| closes #776 
> [shopsys] autocompletion for Phing targets

- packages/framework/src/Component/Domain/Multidomain/Twig/FilesystemLoader.php
- packages/framework/src/DependencyInjection/Compiler/RegisterMultiDesignFilesystemLoaderCompilerPass.php
- packages/framework/src/Resources/config/services.yaml
- packages/framework/src/ShopsysFrameworkBundle.php
- project-base/templates/Front/Tests/twigLoader.custom.html.twig
- project-base/templates/Front/Tests/twigLoader.html.twig
- project-base/tests/App/Functional/Twig/FilesystemLoaderTest.php
- upgrade/UPGRADE-v9.0.3-dev.md
|Description, reason for the PR| With upgrade on Symfony 4 there has been changes in FilesystemLoaders and it caused our FilesystemLoader to not be used anymore. This PR fixes that and adds test to check, if it is working correctly in the future.
|Fixes issues| closes #2042  
> [framework] fixed loading of multi design templates

- packages/framework/src/Component/Paginator/QueryPaginator.php
- project-base/easy-coding-standard.yml
- upgrade/UPGRADE-v9.1.0-dev.md
|Description, reason for the PR| In #2035 was required checker/fixer for short list syntaxt. Unfortunatelly there is a bug in `jmstranslation-bundle` which does not work well with it (https://github.com/schmittjoh/JMSTranslationBundle/issues/506) and `phing translations-dump` started failing because of that.<br>This PR adds ignore for this rule. 
> [shopsys] do not require short list syntax

- project-base/src/DataFixtures/Demo/OrderDataFixture.php
- project-base/tests/FrontendApiBundle/Functional/Article/GetArticleTest.php
- upgrade/UPGRADE-v9.1.0-dev.md
|Description, reason for the PR| Wher we are not running exactly 2 domain the faker will generate different created date to order so some tests will fail (when they are dependent on sorted orders). This PR removes faker for datetime.
> [shopsys] fixed wrong generated demodata for different number of domains than 2

- upgrade/UPGRADE-v9.0.3.md
|Description, reason for the PR| upgrade notes were updated with actual deprecated method names
> [shopsys] fixed deprecated method name from #2041

- .ci/build_kubernetes.sh
- composer.json
- docs/cookbook/dumping-and-importing-the-database.md
- docs/installation/application-configuration.md
- docs/installation/installation-using-docker-on-production-server.md
- docs/introduction/running-acceptance-tests.md
- packages/framework/src/Twig/MailerSettingExtension.php
- project-base/.env
- project-base/.env.test
- project-base/build/codeception.yml
- project-base/composer.json
- project-base/config/bootstrap.php
- project-base/config/parameters.yaml.dist
- project-base/config/parameters_test.yaml.dist
- project-base/kubernetes/deployments/webserver-php-fpm.yml
- project-base/src/Kernel.php
- project-base/symfony.lock
- project-base/tests/App/Acceptance/acceptance.suite.yml
- symfony.lock
- upgrade/UPGRADE-v9.1.0-dev.md
- upgrade/upgrading-monorepo.md
|Description, reason for the PR| We want to be able change parameters via ENV variables to easier change setting of application in any environment. This PR allows developers to override all parameters in `parameters.yaml` by ENV variables. This PR also unifies usage of parameters in different environment (dev, test, prod).
The original PR (#1615) was braking backward compatibility.
> [shopsys] made parameters overridable by ENV variables

- docker/conf/docker-compose-mac.yml.dist
- docker/conf/docker-compose-win.yml.dist
- docker/conf/docker-compose.yml.dist
|Description, reason for the PR| widely used tool `yq` does not properly handle those and throw them away. Apart is no reason to have it when it's used only in one place.
> [shopsys] removed merging common args monorepo docker-compose

- project-base/docker/php-fpm/Dockerfile
- upgrade/UPGRADE-v9.1.0-dev.md
|Description, reason for the PR| it's no longer necessary since composer v2
> [project-base] removed hirak/prestissimo from build

- packages/framework/src/Model/Heureka/HeurekaSetting.php
|Description, reason for the PR| In #2035 empty function was removed, but checking for settings values was not properly changed. Based on this value, some fields (ga tracking code or extra checkbox field in order) are rendered. Those values are considered empty when null. This PR fixes usage. 
> [framework] fixed checking of empty settings values

- packages/framework/src/Model/AdminNavigation/SideMenuBuilder.php
|Description, reason for the PR| After #1338 was merged, renamed menu entry for currencies (and rounding) was reverted by mistake. Rename was in #1791. This PR changes it back.
> [framework] fixed currencies menu text

- project-base/src/Controller/Front/ErrorController.php
- upgrade/UPGRADE-v9.1.0-dev.md
|Description, reason for the PR| This PR fixes standards which were not applied correctly because of bug in FriendsOfPHP/PHP-CS-Fixer
> [project-base] fixed standards on new release of FriendsOfPHP/PHP-CS-Fixer

- project-base/tests/App/Functional/Controller/ProductRenameRedirectPreviousUrlTest.php
|Description, reason for the PR| This PR fixes that test when OVERWRITE_DOMAIN_URL is set to secured (https) domain. More description follows
When env variable OVERWRITE_DOMAIN_URL is set to value with HTTPS scheme and the test environment is active, this test starts to fail on 
```
Failed asserting that 500 matches expected 301.
```
This is due to an invalid requested domain, so the returned response is 
```
You are trying to access an unknown domain 'https://127.0.0.1:8000'. TEST environment is …
```
> [project-base] fix ProductRenameRedirectPreviousUrlTest when overwrite_domain_url is https

- packages/framework/src/Component/Cron/CronFacade.php
|Description, reason for the PR| When a cron module fails on error, in logs, we just see that it failed but it is difficult to find out why (I usually need to run the module again manually and see the output). Thanks to this modification, there should be all the necessary information included in the log entry.
> [framework] throwable is now available in logger context when a cron fails on error

- packages/framework/assets/js/admin/components/MeasuringScript.js
- packages/framework/src/Controller/Admin/ScriptController.php
- packages/framework/src/Form/Admin/Script/ScriptFormType.php
- packages/framework/src/Form/Transformers/ScriptPlacementToBooleanTransformer.php
- packages/framework/src/Model/Script/Script.php
- packages/framework/src/Model/Script/ScriptFacade.php
- packages/framework/src/Resources/translations/messages.cs.po
- packages/framework/src/Resources/translations/messages.en.po
- packages/framework/src/Resources/views/Admin/Content/Script/detail.html.twig
- packages/framework/src/Resources/views/Admin/Content/Script/listGrid.html.twig
- packages/framework/src/Twig/ScriptsExtension.php
- project-base/src/Controller/Front/ScriptController.php
- project-base/templates/Front/Content/Order/sent.html.twig
- project-base/templates/Front/Layout/base.html.twig
- upgrade/UPGRADE-v9.1.0-dev.md
|Description, reason for the PR| Scripts (various javascript) created in administration can be now placed after content to avoid negative impact on page performance. Rendering scripts was also changer from rendering controller to calling function to improve page performance.
> [shopsys] allow placing scripts in administration after content

- docker/conf/docker-compose-mac.yml.dist
- docker/conf/docker-compose-win.yml.dist
- docker/conf/docker-compose.yml.dist
- docs/introduction/running-acceptance-tests.md
- packages/framework/src/Resources/config/services.yaml
- packages/framework/src/Resources/config/services/twig.yaml
- packages/framework/src/Twig/JsFormValidatorTwigExtension.php
- project-base/docker/conf/docker-compose-mac.yml.dist
- project-base/docker/conf/docker-compose-win.yml.dist
- project-base/docker/conf/docker-compose.yml.dist
- project-base/kubernetes/deployments/selenium-server.yml
- project-base/templates/Front/Layout/base.html.twig
- project-base/tests/App/Acceptance/acceptance/CustomerRegistrationCest.php
- upgrade/UPGRADE-v9.1.0-dev.md
|Description, reason for the PR| Javascripts are blocking page to be loaded fast. This PR moves scripts at the bottom of page to speed up page loading
Lighthouse (on localhost) speed comparison:
Before
After
> [project-base] Load javascripts after content is loaded

- packages/framework/src/Model/Cart/CartFacade.php
|Description, reason for the PR| Cart is deleted after creating of an order. On cart delete, checks for cart modifications are run. At this point some checks can fail, because ordered products are sellout already. Customer then see warning flash message on sent page. More info can be found in reported issue #2082
|Fixes issues| closes #2082  
> [framework] do not run checks for cart modifications on cart delete

- packages/frontend-api/apiary.apib
- packages/frontend-api/src/Model/Customer/User/CustomerUserDataFactory.php
- packages/frontend-api/src/Model/Mutation/Customer/User/CustomerUserMutation.php
- packages/frontend-api/src/Resources/config/graphql-types/Mutation.types.yaml
- packages/frontend-api/src/Resources/config/graphql-types/RegistrationDataInputDecorator.types.yaml
- project-base/config/graphql/types/RegistrationDataInput.types.yaml
- project-base/tests/FrontendApiBundle/Functional/Customer/User/RegisterTest.php
- upgrade/UPGRADE-v9.1.0-dev.md
|Description, reason for the PR| added support for customer user registration to Frontend API
|[BC breaks]| No 
> [framework] added support for customer user registration to Frontend API

- project-base/config/packages/snc_redis.yaml
- upgrade/UPGRADE-v9.1.0-dev.md
|Description, reason for the PR| On our project, after upgrading to `9.0.2`, old redis cache is not removed after calling `shopsys:redis:clean-cache-old`. Removing the build version from the prefix fixes the problem, but TBH, I am not sure whether this is ok and whether this modification does not break anything else
> fix cleaning of old redis cache

- packages/framework/src/Model/Order/OrderFacade.php
|Description, reason for the PR| For a long time, I thought that for improving performance, you should always flush just the relevenat entities, not the whole identity map. However, during optimizations on my project, I found out, that the previous is probably not 100 % true. When you have the new entities in the identity map only (e.g. when creating a new order), then flush without parameters is much faster. This single change really helped me on the project - it **decreased the flush time from 2.75s to 955ms**! It would be great if you had time for exploring this behavior further and maybe change other pieces of code that call flush with an array of new entities :thinking: 
|[BC …
> [framework] optimization: flush the whole identity map when an order is created

- project-base/config/packages/test/monolog.yaml
- upgrade/UPGRADE-v9.1.0-dev.md
|Description, reason for the PR| Logging in tests was disabled which lead to harder debugging of problems with tests. Now we have enabled logging of level WARNING or higher, so only important informations are logged.
> [project-base] enabled logging in tests

- easy-coding-standard.yml
- packages/frontend-api/src/Component/Arguments/PaginatorArgumentsBuilder.php
|Description, reason for the PR| These two sniffs were wrongly set in monorepo. This PR fixes that.
> [framework] ConstantVisibilityRequiredSniff and ForceLateStaticBindingForProtectedConstantsSniff are ignored for sources folders only in project-base

- packages/framework/easy-coding-standard.yml
- packages/framework/src/Form/Constraints/CountryValidator.php
- packages/framework/src/Form/Constraints/EmailValidator.php
- packages/framework/src/Form/Constraints/FileAbstractFilesystemValidator.php
- packages/framework/src/Form/Constraints/ImageAbstractFilesystemValidator.php
- packages/framework/src/Form/Constraints/NotSelectedDomainToShowValidator.php
- packages/framework/src/Form/Constraints/UniqueCollectionValidator.php
- packages/framework/src/Form/Constraints/UniqueEmailValidator.php
- packages/framework/src/Form/Constraints/UniqueSlugsOnDomainsValidator.php
|Description, reason for the PR| Validators can be extended since #1955 and private properties or methods don't do it easier.
> Do not use private in constraints

- .gitignore
|Description, reason for the PR| In monorepo we don't want to commit file `frontend_api.yaml`, which enables FE API. This file needs to be commited only for projects build on top of the SSFW 
> [monorepo] add frontend_api.yaml to .gitignore for monorepo

- project-base/docker/php-fpm/docker-php-entrypoint
- upgrade/UPGRADE-v9.1.0-dev.md
|Description, reason for the PR| By default, `tail` command output is buffered by 8KB when it runs in the background. Because of this, some logs can be missed or there can be delayed to see logs. More information can be found here:https://superuser.com/questions/742238/piping-tail-f-into-awk/1123674#1123674 and https://unix.stackexchange.com/questions/46723/flush-tail-f-buffer
> [project-base] tail logs unbuffered

- project-base/src/Form/Front/Product/ProductFilterFormType.php
- upgrade/UPGRADE-v9.1.0-dev.md
|Description, reason for the PR| JS validation consuming a lot of compute power and increase HTML output even if there is no validation needed.
> [project-base] disable javascript validation for product filter form

- packages/framework/src/Component/Doctrine/Cache/FallbackCacheFactory.php
- packages/framework/src/Resources/config/services.yaml
- project-base/config/packages/snc_redis.yaml
- upgrade/UPGRADE-v9.1.0-dev.md
|Description, reason for the PR| Every HTTP request do a lot of requests to Redis cache. This dramatically increases Redis CPU usage and may kill Redis. With OPcache configured for production, performance should be similar
> [shopsys] move doctrine metadata and annotations cache to file instead of redis

- packages/read-model/src/Product/Detail/ProductDetailViewElasticsearchFactory.php
|Description, reason for the PR| After implementing product detail from Elasticsearch there are unnecessary calls to Elasticsearch if accessories or variants are not set to product. This PR fixes it.
> [framework] do not call unnecessary elasticsearch queries

- packages/frontend-api/src/Controller/FrontendApiController.php
- packages/frontend-api/src/Model/Customer/User/CustomerUserDataFactory.php
- packages/frontend-api/src/Model/GraphqlConfigurator.php
- packages/frontend-api/src/Model/Mutation/Newsletter/NewsletterMutation.php
- packages/frontend-api/src/Model/ScalarType/PasswordType.php
- packages/frontend-api/src/Model/ScalarType/StringType.php
- packages/frontend-api/src/Resources/config/graphql-types/ChangePasswordInputDecorator.types.yaml
- packages/frontend-api/src/Resources/config/graphql-types/ChangePersonalDataInputDecorator.types.yaml
- packages/frontend-api/src/Resources/config/graphql-types/LoginInputDecorator.types.yaml
- packages/frontend-api/src/Resources/config/graphql-types/NewsletterSubscriptionDataInputDecorator.types.yaml
- packages/frontend-api/src/Resources/config/graphql-types/OrderInput/OrderInputDecorator.types.yaml
- packages/frontend-api/src/Resources/config/graphql-types/RegistrationDataInputDecorator.types.yaml
- packages/frontend-api/src/Resources/config/graphql-types/ScalarType/PasswordDecorator.types.yaml
- packages/frontend-api/src/Resources/config/services.yaml
- project-base/config/graphql/types/ScalarType/Password.types.yaml
- upgrade/UPGRADE-v9.1.0-dev.md
|Description, reason for the PR| All string input is trimmed. To prevent trimming passwords there was introduced a new type `Password` which do not manipulate with the values.
|Fixes issues| fixes #2111  
> [frontend-api] string inputs are always trimmed

- project-base/docker/php-fpm/docker-install-composer
- upgrade/UPGRADE-v7.3.6-dev.md
|Description, reason for the PR| Version 7.3.x supports Composer 1 only and this version is now locked during installation.
> [project-base] lock composer to version 1.x for 7.3 branch

- project-base/docker/php-fpm/docker-install-composer
- upgrade/UPGRADE-v9.0.4-dev.md
|Description, reason for the PR| Version 9.0.x supports Composer 1 only and this version is now locked during installation.
> [project-base] lock composer to version 1.x for 9.0 branch

- packages/framework/src/Model/Category/CategoryFacade.php
- packages/framework/src/Model/Category/CategoryRepository.php
|Description, reason for the PR| Wrong annotation of return type in `CategoryFacade` and `CategoryRepository` `getFullPathsIndexedByIdsForDomain`
|Fixes issues| fixes #2061
> [framework] Wrong annotation of return type in getFullPathsIndexedByIdsForDomain

- packages/frontend-api/src/Model/Resolver/Article/ArticleResolver.php
- packages/frontend-api/src/Model/Resolver/Brand/BrandResolver.php
- packages/frontend-api/src/Model/Resolver/Category/CategoryResolver.php
- packages/frontend-api/src/Model/Resolver/Order/OrderResolver.php
- packages/frontend-api/src/Model/Resolver/Payment/PaymentResolver.php
- packages/frontend-api/src/Model/Resolver/Products/ProductByUuidResolver.php
- packages/frontend-api/src/Model/Resolver/Products/ProductResolver.php
- packages/frontend-api/src/Model/Resolver/Transport/TransportResolver.php
|Description, reason for the PR| UUID is validated by the type and it's not necessary to validate them separately in the resolvers anymore
> [frontend-api] removed unnecessary UUID validations from resolvers

- packages/framework/src/Component/Router/DomainRouterFactory.php
- packages/framework/src/Component/Router/LocalizedRouterFactory.php
- packages/framework/src/Resources/config/paths.yaml
- packages/framework/src/Resources/config/services.yaml
- packages/framework/tests/Unit/Component/Router/DomainRouterFactoryTest.php
- packages/framework/tests/Unit/Component/Router/LocalizedRouterFactoryTest.php
- upgrade/UPGRADE-v9.1.0-dev.md
|Description, reason for the PR| Static and localized routes are now cached into file.
|Fixes issues| closes #2106  
> [framework] Enabled caching for DomainRouter and LocalizedRouter

- docs/frontend-api/pagination.md
- project-base/config/graphql/types/Pagination/ArticleConnection.types.yaml
- project-base/config/graphql/types/Pagination/OrderConnection.types.yaml
- project-base/config/graphql/types/Pagination/ProductConnection.types.yaml
- upgrade/UPGRADE-v9.1.0-dev.md
|Description, reason for the PR| Added total count for every pagination in frontend API. Sadly this must be done in project-base because of bug in overblog graphql bundle - https://github.com/overblog/GraphQLBundle/issues/341
> [project-base] added total count to frontend API connections

- packages/framework/src/Component/Image/ImageFacade.php
|Description, reason for the PR| Temporary files must be created on abstract filesystem. Related to #1955.
|Fixes issues| fixes #2134  
> [framework] fixed copying images when creating variants

- packages/framework/src/Model/Feed/FeedExportFactory.php
|Description, reason for the PR| This PR fixes retyping `$lastSeekId` from `string\|null` to `int\|null`. At this moment generating feeds don't add begin to feeds (eg. [this](https://github.com/shopsys/shopsys/blob/master/packages/product-feed-heureka-delivery/src/Resources/views/feed.xml.twig#L1-L4)) because [FeedExport class render begin only if $lastSeekId is null](https://github.com/shopsys/shopsys/blob/master/packages/framework/src/Model/Feed/FeedExport.php#L141-L143) and `$lastSeekId` is always retyped to int so null never comes and begin is never rendered. This is issue in 9.1 version so I recommend you add this there. Thanks …
> [framework] FeedExportFactory: fixed casting of $lastSeekId to nullable int

- yaml-standards.yaml
|Description, reason for the PR| Files, not committed in repository, does not make sense to check for standards
> [shopsys] excluded not commited files from yaml standards checks

- project-base/.gitignore
- upgrade/UPGRADE-v9.1.0-dev.md
|Description, reason for the PR| ACCEPTANCE file is not versioned by Git
> [project-base] add ACCEPTANCE file to .gitignore

- project-base/src/Form/Front/Newsletter/SubscriptionFormType.php
- upgrade/UPGRADE-v9.1.0-dev.md
|Description, reason for the PR| add email length validation in SubscriptionFormType
> [project-base] added email length validation in SubscriptionFormType

- docs/model/introduction-to-model-architecture.md
- packages/framework/src/Component/DataFixture/AbstractNativeFixture.php
- packages/framework/src/Component/Domain/DomainDbFunctionsFacade.php
- packages/framework/src/Component/Domain/DomainUrlReplacer.php
- packages/framework/src/Component/Domain/Multidomain/MultidomainEntityDataCreator.php
- packages/framework/src/Component/Setting/SettingValueRepository.php
- packages/framework/src/Component/Translation/TranslatableEntityDataCreator.php
- packages/framework/src/Model/Cart/CartRepository.php
- packages/framework/src/Model/Localization/DbIndexesRepository.php
- packages/framework/src/Model/Product/Pricing/ProductCalculatedPriceRepository.php
- packages/framework/src/Model/Product/ProductVisibilityRepository.php
- project-base/src/DataFixtures/Demo/ImageDataFixture.php
- upgrade/UPGRADE-v9.1.0-dev.md
|Description, reason for the PR| Native queries for DELETE, UPDATE or INSERT statements now don't use [ORM Native SQL API](https://www.doctrine-project.org/projects/doctrine-orm/en/2.7/reference/native-sql.html). `EntityManager::getConnection()` to access the native database connection and the `executeStatement()` method for these queries is used instead to ensure working application with database replication configured (see [PrimaryReadReplicaConnection class](https://github.com/doctrine/dbal/blob/2.12.x/lib/Doctrine/DBAL/Connections/PrimaryReadReplicaConnection.php#L19))
|Fixes issues| closes #2121   …
> [shopsys] use DBAL native queries for DML instead of ORM Native SQL

- packages/framework/src/Component/Router/NormalizeUrlTrailingSlashSubscriber.php
- packages/framework/src/Component/String/TransformString.php
- packages/framework/tests/Unit/Component/String/TransformStringTest.php
…TrailingSlashFromString
|Description, reason for the PR| refactoring of NormalizeUrlTrailingSlashSubscriber
> [framework] refactoring of NormalizeUrlTrailingSlashSubscriber

- packages/framework/src/Model/Category/CategoryFacade.php
- packages/frontend-api/src/Model/Resolver/Category/CategoryResolver.php
|Description, reason for the PR| FE API returns category by uuid, which is visible on domain
> [shopsys] FE API returns visible category by uuid

- packages/framework/src/Component/Router/FriendlyUrl/FriendlyUrlCacheKeyProvider.php
- packages/framework/src/Component/Router/FriendlyUrl/FriendlyUrlFacade.php
- packages/framework/src/Component/Router/FriendlyUrl/FriendlyUrlGenerator.php
- packages/framework/src/Component/Router/FriendlyUrl/FriendlyUrlRouterFactory.php
- project-base/config/packages/framework.yaml
- project-base/config/packages/snc_redis.yaml
- upgrade/UPGRADE-v9.1.0-dev.md
|Description, reason for the PR| Each friendly URL created in twig recieved slug from database. This PR adds slugs to be cached in redis to reduce queries.
> [shopsys] cache friendly url slugs for generator into redis

- packages/frontend-api/src/Model/Token/TokenFacade.php
|Description, reason for the PR| Using integer as a time value in lcobucci/jwt is deprecated* since version 3.4. This PR change `issued at` and `expires at` claims to use DateTimeImmutable object instead
\* throws `Using integers for registered date claims is deprecated, please use DateTimeImmutable objects instead`
see 
- https://github.com/lcobucci/jwt/blob/3.4.0/src/Builder.php#L140
- https://github.com/lcobucci/jwt/blob/3.4.0/src/Builder.php#L150
> [frontend-api] removed deprecated use of time as integer in IAT and EXP claims

- packages/framework/src/Model/Customer/User/CustomerUserPasswordFacade.php
|Description, reason for the PR| In #1891 there was introduced a BC break because of the required dependency. This PR fixes it.
> [framework] CustomerUserPasswordFacade has dependency passed with setter injection

- easy-coding-standard.yml
- project-base/easy-coding-standard.yml
- upgrade/UPGRADE-v9.1.0-dev.md
|Description, reason for the PR| In #2035 was introduced rule for maximum line length in conditions and function calls. This rule is controversial between programmers so it is removed for now. 
> ecs: removed rule for maximum line length in conditions and function calls

- packages/framework/src/Model/Product/ProductDataFactory.php
|Description, reason for the PR| There was error that main url radio button was not checked by default. This caused connected JS to stop function and that was reason why there was remove button next to the main URL instead of info icon with text, that main URL cannot be removed.
|Fixes issues| closes #2034  
> [framework] admin: fixed displaying remove button for urls

- packages/framework/src/Model/Category/CategoryFacade.php
|Description, reason for the PR| When category was removed, no recalculations of products has been scheduled. This PR adds such functionality.
|Fixes issues| closes #1763 
> [framework] product visibility is now recalculated, when their category is removed

- packages/framework/src/Form/Admin/Administrator/AdministratorFormType.php
- packages/framework/src/Form/Admin/Category/CategoryFormType.php
- packages/framework/src/Form/DisplayOnlyType.php
|Description, reason for the PR| DisplayOnlyType is only for displaying the value. Any validation is not necessary and editing this field should not affect anything.
|Fixes issues| fixes #1867 , fixes #1943 
> [framework] removed validation of DisplayOnlyType

- packages/framework/src/Command/CronCommand.php
- project-base/tests/App/Functional/EntityExtension/EntityExtensionTest.php
- upgrade/UPGRADE-v9.1.1-dev.md
|Description, reason for the PR| PHPStan has released new patch version which reported us some incompatibilities in our interfaces. This PR fixes that.
> [shopsys] fixed interfaces reported by phpstan

- packages/framework/src/Model/Product/Search/FilterQuery.php
|Description, reason for the PR| Default ordering in FilterQuery is now a little bit more clear.
|Fixes issues| fixes #2165 
> [framework] added info about default ordering in elasticsearch

- packages/framework/src/Component/Domain/Domain.php
- packages/framework/src/Component/HttpFoundation/DenyScriptNameInRequestPathListener.php
- packages/framework/src/Component/Router/NormalizeUrlTrailingSlashSubscriber.php
|Description, reason for the PR| URL with `index.php` can throw an unhandled exception or redirect to an invalid location. This PR always returns 404, when index.php is present in the URL (examples follows)
|Fixes issues| fixes #2071  
<details><summary>tested URLs (click to show)</summary>
- http://127.0.0.1:8000/index.php
- http://127.0.0.1:8000/index.php/
- http://127.0.0.1:8000/whatever/index.php
- http://127.0.0.1:8000/whatever/index.php/
- http://127.0.0.1:8000/index.php/whatever
- …
> [framework] script name (index.php) in URL now always returns 404

- composer.json
- packages/coding-standards/composer.json
See
- https://github.com/symplify/symplify/issues/2872
- https://github.com/symfony/dependency-injection/commit/d749132342b401fb36621bfdee91363dffb87189
|Description, reason for the PR| New release of symfony/dependency-injection breaks symplify/easy-coding-standard which in versions <9 and they will never be fixed.
> [coding-standards] hotfix: exclude version of symfony/dependency-injection which breaks ECS

- composer.json
- packages/coding-standards/composer.json
|Description, reason for the PR| In #2210 we defined conflict on symfony/dependency-injection unfortunatelly there is also conflict in version 5 which is used in our package shopsys/coding-standards
> hotfix: prevent coding-standards of failing with symfony/dependency-injection in v5

- composer.json
- docs/cookbook/jenkins-configuration.md
- packages/framework/build.xml
- project-base/composer.json
- project-base/config/packages/security_checker.yaml
- project-base/symfony.lock
- symfony.lock
- upgrade/UPGRADE-v9.1.1-dev.md
|Description, reason for the PR| API on security.symfony.com nearing the end of service, so this PR introduces the replacement
> [shopsys] replaced sensiolabs/security-checker with enlightn/security-checker

- packages/framework/build.xml
- packages/framework/src/Command/ElFinderInstallerCommand.php
- packages/framework/src/Command/ElFinderPostInstallCommand.php
- upgrade/UPGRADE-v9.1.1-dev.md
|Description, reason for the PR| New version of helios-ag/fm-elfinder-bundle has come and this PR makes SSFW compatible with that new version.
> [framework] updated elfinder installer to be compatible with helios-ag/fm-elfinder-bundle v10.1

- packages/framework/src/Component/String/TransformString.php
- packages/framework/src/Migrations/Version20210127085903.php
- packages/framework/src/Model/Category/CategoryTranslation.php
- packages/framework/src/Model/Payment/PaymentTranslation.php
- packages/framework/src/Model/Product/Brand/BrandTranslation.php
- packages/framework/src/Model/Product/Parameter/ParameterTranslation.php
- packages/framework/src/Model/Product/ProductTranslation.php
- packages/framework/src/Model/Transport/TransportTranslation.php
- packages/framework/tests/Unit/Component/String/TransformStringTest.php
|Description, reason for the PR| We use nullable datatype in our database schema but actually we are saving empty string on many places. This PR unifies saving those empty strings (each of them is converted to null) to prevent confusions.
|Fixes issues| closes #1735  
> [framework] empty strings are stored as null if possible

- packages/framework/assets/styles/admin/components/box/upload.less
|Description, reason for the PR| Inside in `&__place` there is `&:after` that have position: absolute. That is white line trough file input. It is not noticeable but it overflows the box. See picture.
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)|No 
> [framework] fixed box-upload white line overlapping box

- packages/framework/src/Form/Admin/Customer/User/CustomerUserFormType.php
|Description, reason for the PR| Now administrator can't edit customer email because condition is not good. This should help.
> [framework] admin: customer user form: customer user with not existing email can be saved

- packages/frontend-api/src/Resources/config/graphql-types/PaymentDecorator.types.yaml
|Description, reason for the PR| Payment price must be required because `Shopsys\FrontendApiBundle\Model\Resolver\Price::resolveByPayment` always returns object of `\Shopsys\FrameworkBundle\Model\Pricing\Price`
> [frontend-api] Payment price is required

- packages/frontend-api/src/Resources/config/graphql-types/MainVariantDecorator.types.yaml
- packages/frontend-api/src/Resources/config/graphql-types/RegularProductDecorator.types.yaml
- packages/frontend-api/src/Resources/config/graphql-types/VariantDecorator.types.yaml
- upgrade/UPGRADE-v9.1.1-dev.md
|Description, reason for the PR| product decorators are correctly configured to inherit all fields from product type.
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No (But I'm not sure) 
> [frontend-api] product decorators inherit all fields from product type

- docs/frontend-api/introduction-to-frontend-api.md
|Description, reason for the PR| `ProductResolverMap::map()` has been changed, since introducing `ProductEntityFieldMapper` and `ProductArrayFieldMapper` in  SSFW 9.1. There is also custom section called `ProductResolverMap`.I think it would be better to use `CategoryResolverMap` as an example of `ResolverMap` for better understanding how resolver mappers work (Anyone can look at current implementation of `CategoryResolverMap`).
> [docs] use `CategoryResolverMap` as an example of `ResolverMap` in FE API introduction

- packages/framework/src/Component/EntityExtension/EntityManagerDecorator.php
- packages/framework/src/Model/Product/ProductVisibilityRepository.php
- project-base/tests/App/Functional/Model/Order/OrderFacadeTest.php
- upgrade/UPGRADE-v9.1.1-dev.md
|Description, reason for the PR| entities are, by default, not refreshed in identity map after update with native query. This PR add a manual refresh of loaded entities, so it's safe to work with those entites after recalculations (=native queries).
|Fixes issues| closes #2108 
> [shopsys] entites are refreshed after product visibility recalculations

- project-base/tests/App/Smoke/NewProductTest.php
- upgrade/UPGRADE-v9.1.1-dev.md
|Description, reason for the PR| This PR fixes failing smoke test for a new product in case the first domain is set as HTTPS.
|Fixes issues| closes #2139 
> [project-base] smoke test for new product now work with HTTPS domain

- packages/frontend-api/src/Resources/config/graphql-types/OrderInput/OrderInputDecorator.types.yaml
- project-base/tests/FrontendApiBundle/Functional/Order/MinimalOrderTest.php
- upgrade/UPGRADE-v9.1.1-dev.md
|Description, reason for the PR| It was possible to send order without products vie Frontend API. This PR adds validation rule for that.
|Fixes issues| fixes #2204  
> [frontend-api] fixed creating order with no products

- packages/frontend-api/src/Resources/config/graphql-types/AdvertCodeDecorator.types.yaml
- packages/frontend-api/src/Resources/config/graphql-types/AdvertImageDecorator.types.yaml
- packages/frontend-api/src/Resources/config/graphql-types/ProductPriceDecorator.types.yaml
- upgrade/UPGRADE-v9.1.1-dev.md
|Description, reason for the PR| This PR makes overriding of FEAPI types easier.
|Fixes issues| closes #2208  
> [frontend-api] decorators inherits from base type instead of decorator

- packages/framework/src/Component/Csv/CsvReader.php
- upgrade/UPGRADE-v9.2.0-dev.md
|Description, reason for the PR| Class CsvReader should not be used and is deprecated in this PR.
|Fixes issues| closes #2171  
> [framework] CsvReader class is now deprecated

- packages/framework/assets/js/common/validation/customizeBundle.js
|Description, reason for the PR| `isExpandedChoiceEmpty` function accepts only arrays as an argument. In `isExpandedChoiceFormType` was a bad condition, so the scalar value could be passed into this function, resulting in javascript error. 
|Fixes issues| fixes #2054 
Can be tested on `admin/advert/new/` path
> [framework] fixed javascript validation for radiobuttons

- packages/framework/src/Component/Filesystem/Flysystem/VolumeDriver.php
|Description, reason for the PR| There was problem that elFinder attempts to remove thumbnails for files that have no thumbnail created. This has been fixed in this PR.
|Fixes issues| closes #2162  
> [framework] elFinder: thumbnail is only removed when some thumbnail exists

- packages/backend-api/.github/workflows/run-checks-tests.yaml
- packages/coding-standards/.github/workflows/run-checks-tests.yaml
- packages/form-types-bundle/.github/workflows/run-checks-tests.yaml
- packages/framework/.github/workflows/run-checks-tests.yaml
- packages/frontend-api/.github/workflows/run-checks-tests.yaml
- packages/google-cloud-bundle/.github/workflows/run-checks-tests.yaml
- packages/http-smoke-testing/.github/workflows/run-checks-tests.yaml
- packages/migrations/.github/workflows/run-checks-tests.yaml
- packages/plugin-interface/.github/workflows/run-checks-tests.yaml
- packages/product-feed-google/.github/workflows/run-checks-tests.yaml
- packages/product-feed-heureka-delivery/.github/workflows/run-checks-tests.yaml
- packages/product-feed-heureka/.github/workflows/run-checks-tests.yaml
- packages/product-feed-zbozi/.github/workflows/run-checks-tests.yaml
- packages/read-model/.github/workflows/run-checks-tests.yaml
- project-base/.github/workflows/docker-build.yaml
|Description, reason for the PR| Travis is too slow last few months so we are migrating all Travis builds to Github Actions, that is at least 100x faster.
> [monorepo] added github actions configs for all packages

- packages/framework/src/Component/Error/ExceptionListener.php
|Description, reason for the PR| Default behavior of Symfony is, when NotFoundHttpException is thrown during Twig template rendering during subrequest, application will fail on Twig\Error\RuntimeError (500). This PR transform such exceptions to a proper 404.
|Fixes issues| closes #2182  
> [framework] transform twig exception to proper 404

- packages/framework/src/Model/Cart/Watcher/CartWatcher.php
|Description, reason for the PR| When there is no price for product and pricing group and recalculations was not executed, it was possible to buy product with zero price for a short period of time. This PR adds check which do not allow customers to buy these products. The whole bug is rare edge case, when there are incomplete data or  different bug introduced during implementation.
|Fixes issues| closes #2205  
> [framework] prevent buying product with zero price

- docs/installation/application-configuration.md
- packages/framework/src/Component/Elasticsearch/ElasticsearchClientFactory.php
- packages/framework/src/Resources/config/services.yaml
- upgrade/UPGRADE-v9.1.1-dev.md
|Description, reason for the PR| This PR allows setting up multiple Elasticsearch hosts to be able to connect to a cluster of nodes.
> [framework] allow multiple elasticsearch hosts

- project-base/templates/Front/Content/Default/index.html.twig
- upgrade/UPGRADE-v9.1.1-dev.md
|Description, reason for the PR| Linked logo on homepage is consistent with the rest of the web, removed unnecessary code, and just image inside H1 has no semantic information so H1 wrapper is removed from logo allowing the H1 to be included  in the content
|Fixes issues| ... closes #2243
> [project-base] logo on homepage is link and is not wrapped in H1 

- upgrade/UPGRADE-v9.1.0.md
|Description, reason for the PR| We are missing links for project-base diff. This PR adds them to make upgrading easier. 
> [monorepo] improve upgrade notes for upgrading ECS in v9.1.0

- packages/framework/build.xml
|Description, reason for the PR| in #2107 annotation cache was moved from Redis to file. This PR adjust phing targets related to db-migrations, so the cache is always properly cleared before generating db migrations
> [framework] clean annotation cache before generating db migrations

- packages/framework/assets/js/common/validation/ShopsysConstraintUniqueProductParameters.js
- packages/framework/assets/js/common/validation/customizeFpValidator.js
- packages/framework/src/Form/Admin/Product/ProductFormType.php
- packages/framework/src/Form/Constraints/UniqueProductParametersValidator.php
- packages/framework/src/Form/Transformers/ProductParameterValueToProductParameterValuesLocalizedTransformer.php
- packages/framework/src/Resources/views/Admin/Form/productParameterValue.html.twig
|Description, reason for the PR| Parameters in the collection were not saved, when parameter was added, deleted, and added again without page reload. This was fixed. Also, server-side validation is now more user-friendly – outputs which parameters are duplicated.  
|Fixes issues| closes #1562  
Example of improved validation:
> [framework] fixed product parameters saving

- packages/framework/src/Model/Product/Elasticsearch/MarkProductForExportSubscriber.php
|Description, reason for the PR| Parameter names are exported to elastic, so when a parameter is updated, changes have to be propagated to Elasticsearch.
|Fixes issues| closes #2160 
> [framework] changing parameter name now affects product detail

- packages/framework/src/Component/Elasticsearch/IndexFacade.php
|Description, reason for the PR| see linked issue
|Fixes issues| closes #2247  
> [framework] disallow partial export when elasticsearch structure is not created

- packages/framework/src/Controller/ElFinder/ElfinderController.php
- packages/framework/src/Resources/config/services.yaml
|Description, reason for the PR| ElFinder lock mechanism is bound to the local filesystem. When the application is running on several replicas, it's possible one replica creates a lock, but different tries to read it. This PR catch thrown exception and returns empty response instead.
This PR is related to #2172
> [framework] ElFinder abort exception is now muted

- packages/framework/src/Component/ClassExtension/MethodAnnotationsFactory.php
|Description, reason for the PR| MethodAnnotationsFactory::getMethodAnnotationLine() method was almost impossible to read, so it has been refactored to be more developer friendly.
> [framework] improved readibility of MethodAnnotationsFactory::getMethodAnnotationLine() method

- project-base/docker/conf/docker-compose-mac.yml.dist
- project-base/docker/conf/docker-sync.yml.dist
- upgrade/UPGRADE-v9.1.1-dev.md
|Description, reason for the PR| In #2025 we have introduced few improvements for working with Docker and Docker-sync on MacOS. After several months of using it we came to conclusion that problems with Docker-sync now do not occur so often as with previous setup. Sadly, they are not eliminated completely.
> [project-base] improved docker-sync reliability on MacOS

- .ci/build_kubernetes.sh
- .github/workflows/docker-build.yaml
- project-base/kubernetes/deployments/webserver-php-fpm.yml
|Description, reason for the PR| Backend and frontend API installation was added to Github Actions. Installation of backend and frontend apis was moved in initialize step of building application in Kubernetes. FW-571 in internal JIRA has been created to resolve building application with both enabled and disabled backend API.
> [monorepo] fixed CI builds

- packages/coding-standards/composer.json
|Description, reason for the PR| In #2183 was added posibility to install `coding-standard` with symfony 5.0. Unforutenatelly there is missing support for higher versions.
> [coding-standards] allowed installing coding-standards with symfony 5 and higher

- composer.json
- packages/migrations/composer.json
|Description, reason for the PR| versions bellow 1.8.1 was not working because of namespace mess in it (bug is introduced by #706)
> [shopsys] bumped version of doctrine/migrations

- open-source-license-acknowledgements-and-third-party-copyrights.md
|Description, reason for the PR| hirak/prestissimo is not used since #2089
> [shopsys] removed prestissimo from open source license acknowledgements

- .github/workflows/docker-build.yaml
|Description, reason for the PR| Fix of failed build https://github.com/shopsys/shopsys/actions/runs/682543146
> [monorepo] do not pull elasticsearch and php-fpm image as they can be built locally

- packages/frontend-api/src/Model/Token/TokenAuthenticator.php
|Description, reason for the PR| Now changing just the value of the constant can make an consistent change in the behavior of TokenAuthenticator. For example, we wanted to change the used header to avoid conflict with HTTP authorization on a non-public deployment of our app (thx to @milanStano for the idea). Even better would be to use DIC parameters instead of both constants, but that would introduce a BC break into SSFW.
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Employed by Shopsys
> [frontend-api] TokenAuthenicator: use HEADER_AUTHORIZATION consistently

- packages/product-feed-heureka/easy-coding-standard.yml
|Description, reason for the PR|  Errors reported were all like this: Member variable "CATEGORY_ID" is not in valid camel caps format. Those variables are loaded from XML so we have no power over them.
> [product-feed-heureka] ignored errors reported by new squizlabs/php_codesniffer version 3.6.0

- UPGRADE.md
|Description, reason for the PR| I was really surprised that some javascript-related issues still occurred in my project despite the fact they were merged to a version of the framework that my project was already upgraded to. Then I found out I need to upgrade the npm package as well :slightly_smiling_face: 
> [monorepo] UPGRADE.md: info about updating NPM dependencies

- composer.json
- packages/coding-standards/composer.json
|Description, reason for the PR| package-builder is not our direct dependency so we do not need to require it in our coding-standards.
> [coding-standards] removed direct dependency symplify/package-builder

- packages/framework/build.xml
|Description, reason for the PR| before test-* phing targets are now properly cleaned redis in test environment so tests are not influenced with previous run and some cached data.
|Fixes issues| closes #2256 
> [framework] fixed cleaning redis in test environment

- utils/releaser/config/services.yaml
- utils/releaser/src/Command/ReleaseCommand.php
- utils/releaser/src/ReleaseWorker/ReleaseWorkerProvider.php
|Description, reason for the PR| This PR adds support for resuming release process from certain step. It is possible that some error or some other need forces you to stop release process. Until now you had to start from beginning which was pretty unpleasant.
> [releaser] added --resume-step option for release command

- packages/framework/src/Model/Product/ProductOnCurrentDomainElasticFacade.php
- upgrade/UPGRADE-v9.0.3.md
|Description, reason for the PR| `ProductFilterQueryFactory` mentioned in upgrade notes and in annotations does not exists
> [shopsys] fix incorrect deprecated annotation in ProductOnCurrentDomainElasticFacade

- packages/framework/src/Form/Admin/Customer/User/CustomerUserFormType.php
- upgrade/UPGRADE-v9.1.2-dev.md
|Description, reason for the PR| When no email was provided the app failed on strict types
|Fixes issues| fixes #2296  
> [framework] fixed validation of customer email edit in administration

- packages/framework/src/Resources/translations/messages.cs.po
- packages/framework/src/Resources/translations/messages.en.po
- packages/framework/src/Resources/views/Components/ConfirmDelete/setNewAndDelete.html.twig
|Description, reason for the PR| Title of modal window was changed to be more general as it is used on many places and everywhere is displayed title about removing "order status".
|Fixes issues| fixes #2295 
> [framework] fixed title of modal window for deleting with setting replacement

- composer.json
- packages/coding-standards/composer.json
|Description, reason for the PR| version is excluded because of high memory usage, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5695
> [shopsys] excluded friendsofphp/php-cs-fixer v2.19.0

- packages/framework/tests/Unit/Model/Security/AuthenticatorTest.php
- project-base/tests/App/Functional/Model/Administrator/AdministratorRepositoryTest.php
- project-base/tests/App/Functional/Model/Cart/CartFacadeTest.php
- upgrade/UPGRADE-v9.1.2-dev.md
|Description, reason for the PR| We want to have these usages unified. 
> [shopsys] class names are get from `::class` constant instead of FQCN string

- composer.json
- packages/coding-standards/composer.json
|Description, reason for the PR| version is excluded because of high memory usage, see FriendsOfPHP/PHP-CS-Fixer#5695d
> [shopsys] excluded friendsofphp/php-cs-fixer v2.19.0 in 7.3

- composer.json
- packages/framework/composer.json
- project-base/composer.json
- upgrade/UPGRADE-v9.1.2-dev.md
|Description, reason for the PR| due to reported security issue GHSA-h5h8-pc6h-jvvx
> [shopsys] bumped version of composer dependency composer/composer

- packages/product-feed-heureka/easy-coding-standard.yml
|Description, reason for the PR| Errors reported were all like this: Member variable "CATEGORY_ID" is not in valid camel caps format. Those variables are loaded from XML so we have no power over them.
> [product-feed-heureka] ignored errors reported by new squizlabs/php_codesniffer version 3.6.0 in 7.3

- composer.json
- packages/framework/composer.json
- project-base/composer.json
- upgrade/UPGRADE-v7.3.7-dev.md
|Description, reason for the PR| due to reported security issue GHSA-h5h8-pc6h-jvvx
> [shopsys] bumped version of composer dependency composer/composer in 7.3

- packages/framework/src/Resources/config/services.yaml
- project-base/config/packages/framework.yaml
- upgrade/UPGRADE-v9.1.2-dev.md
|Description, reason for the PR| New versions of doctrine/ and symfony/ packages throws fatal (`Argument 2 passed to Doctrine\Common\Annotations\PsrCachedReader::__construct() must implement interface Psr\Cache\CacheItemPoolInterface, instance of Doctrine\Common\Cache\ChainCache`). This PR fixes compatibility with a new  version of packages and it's a step forward to complete removal of doctrine/cache as it's prepared for removal (https://github.com/doctrine/cache/issues/354)
> [framework] annotation cache don't use doctrine file cache

- packages/framework/src/Controller/Admin/SliderController.php
- packages/framework/src/Model/Slider/SliderItemRepository.php
|Description, reason for the PR| Slider items on homepage can be ordered in administration, that change `position` attribute, but when displaying slider items on homepage, this position information is lost and the items are not ordered by it.
|Fixes issues| No 
> [framework] fix homepage slider items not ordered by position

- packages/framework/src/Model/Payment/IndependentPaymentVisibilityCalculation.php
- packages/framework/src/Model/Payment/PaymentFacade.php
- packages/framework/src/Model/Payment/PaymentRepository.php
- packages/framework/src/Model/Transport/IndependentTransportVisibilityCalculation.php
- packages/framework/src/Model/Transport/TransportFacade.php
- packages/framework/src/Model/Transport/TransportRepository.php
- packages/frontend-api/src/Component/Constraints/PaymentCanBeUsedValidator.php
- packages/frontend-api/src/Component/Constraints/TransportCanBeUsedValidator.php
- packages/frontend-api/src/Model/Order/OrderDataFactory.php
- packages/frontend-api/src/Model/Resolver/Payment/PaymentResolver.php
- packages/frontend-api/src/Model/Resolver/Transport/TransportResolver.php
- project-base/tests/App/Functional/Model/Payment/IndependentPaymentVisibilityCalculationTest.php
- project-base/tests/App/Functional/Model/Transport/IndependentTransportVisibilityCalculationTest.php
|Description, reason for the PR| Attribute deleted of transport and payment was not used in consideration during calculation of their visibilities. Also transport and payment frontend API resolvers were not taking visibility in consideration.
|Fixes issues| closes #2302 
> [shopsys] fix calculation of transport and payment visibilities

- composer.json
- packages/framework/composer.json
- packages/product-feed-google/composer.json
- packages/product-feed-heureka/composer.json
- packages/product-feed-zbozi/composer.json
- project-base/composer.json
- upgrade/UPGRADE-v7.3.7-dev.md
|Description, reason for the PR| due to security issue in previous versions https://github.com/symfony/symfony/security/advisories/GHSA-5pv8-ppvj-4h68 (CVE-2021-21424)
> [shopsys] set minimal version of symfony/symfony to 3.4.48

- packages/framework/src/Controller/Admin/DefaultController.php
|Description, reason for the PR| Crons until now could display duration of maximum 59 mins and 59 seconds. Duration lasting longer were stripped of hours and it was not clear how long did cron run. This has been fixed now.
|Fixes issues| closes #2310  
> [framework] cron overview now can display duration of crons over one hour

- upgrade/UPGRADE-v9.1.2-dev.md
|Description, reason for the PR| due to https://github.com/symfony/symfony/security/advisories/GHSA-5pv8-ppvj-4h68
> [docs] added upgrade note for upgrading symfony/security* packages

- packages/framework/src/Model/Customer/User/FrontendCustomerUserProvider.php
|Description, reason for the PR| `Shopsys\FrameworkBundle\Model\Customer\User` does not exist anymore
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| Yes
Btw, the same "problem" is in `AdministratorUserProvider` :wink:
> [framework] fix entity name in FrontendCustomerUserProvider

- packages/framework/src/Model/Statistics/StatisticsRepository.php
|Description, reason for the PR| It is confusing when there are some deleted orders in statistics but not visible on orders overview.
> [framework] admin: dashboard: deleted orders are no longer included in statistics

- packages/framework/src/Component/Image/Processing/ImageProcessor.php
|Description, reason for the PR| In one of our projects, we had to migrate about 700 images from old e-shop. We implemented Symfony command, which runs `ImageFacade::manageImages()`. Everything works normally on local PC. When the command runs on production, it fails because of memory leak. We tried to call `gc_collect_cycles` after every image migration, but it didn't work. After debugging and searching, we found a solution by freeing memory held by `Intervention\Image`. Solution is inspired by https://github.com/Intervention/image/issues/426.  …
> [framework] destroy intervention image after it is saved in filesystem in order to prevent memory leaks

- utils/releaser/src/ReleaseWorker/ReleaseCandidate/GenerateApiaryBlueprintReleaseWorker.php
|Description, reason for the PR| In past we have forgot to generate Apiary.io blueprint. This PR ensures it will not be forgotten again.
> [monorepo] added release candidate step for generating Apiary.io blueprint

- project-base/tests/App/Acceptance/acceptance/PageObject/Front/ProductFilterPage.php
- upgrade/UPGRADE-v9.1.2-dev.md
- this makes the class functions resistant to case changes of the product filter labels
|Description, reason for the PR| change from "Úhlopříčka" to "ÚHLOPŘÍČKA" during product filter styling broke `ProductFilterCest::testAllProductFilters` test
> [project-base] ProductFilterPage now uses mb_stripos instead of stripos

- packages/framework/src/Form/DisplayOnlyType.php
|Description, reason for the PR| In inline editation is not rendered DisplayOnlyType. This can be fixed by setting attribute `compound` to `false`.
> [framework] fixed rendering of DisplayOnlyType in inline data grid

- utils/releaser/config/services.yaml
- utils/releaser/src/Command/ReleaseCommand.php
- utils/releaser/src/ReleaseWorker/ReleaseWorkerProvider.php
|Description, reason for the PR| we want the "--resume-step" option available even for releasing a new 7.3 version so I cherry picked it from https://github.com/shopsys/shopsys/pull/2293
> added --resume-step option for release command

- packages/framework/src/Model/Breadcrumb/ErrorPageBreadcrumbGenerator.php
- packages/framework/src/Model/Breadcrumb/SimpleBreadcrumbGenerator.php
- packages/framework/src/Model/Cart/Watcher/CartWatcherFacade.php
- packages/framework/src/Model/LegalConditions/LegalConditionsFacade.php
- packages/framework/src/Model/Product/Listing/ProductListOrderingModeForBrandFacade.php
- packages/framework/src/Model/Product/Listing/ProductListOrderingModeForListFacade.php
- packages/framework/src/Model/Product/Listing/ProductListOrderingModeForSearchFacade.php
- project-base/config/services.yaml
- project-base/src/Controller/Front/ContactFormController.php
- project-base/src/Controller/Front/NewsletterController.php
- project-base/src/Controller/Front/OrderController.php
- project-base/src/Controller/Front/ProductController.php
- project-base/src/Controller/Front/RegistrationController.php
- project-base/src/Model/Breadcrumb/ErrorPageBreadcrumbGenerator.php
- project-base/src/Model/Breadcrumb/SimpleBreadcrumbGenerator.php
- project-base/src/Model/Cart/Watcher/CartWatcherFacade.php
- project-base/src/Model/LegalConditions/LegalConditionsFacade.php
- project-base/src/Model/Product/Listing/ProductListOrderingModeForBrandFacade.php
- project-base/src/Model/Product/Listing/ProductListOrderingModeForListFacade.php
- project-base/src/Model/Product/Listing/ProductListOrderingModeForSearchFacade.php
- project-base/translations/messages.cs.po
- project-base/translations/messages.en.po
- upgrade/UPGRADE-v9.1.2-dev.md
|Description, reason for the PR| Some translations from front could not be exported to project-base translations because they were used in classes of framework. This PR expose methods to project-base to be exported.
|Fixes issues| fixes #1383  
> [shopsys] moved translations on front to project-base

- README.md
|Description, reason for the PR| Travis is no longer used, so the failing badge is removed.
> [shopsys] removed Travis badge

- packages/framework/assets/js/common/validation/ConstraintEmail.js
- packages/framework/assets/js/common/validation/ShopsysFrameworkBundleFormConstraintsEmail.js
|Description, reason for the PR| Javascript email validation was vague and in many cases wrong email has been catched by server side validation. This PR improves Javascript email validation and it should be now same as server side validation.
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| Yes/No 
|Fixes issues| closes #747  
> [framework] javascript email validation works now same as server side validation

- composer.json
- packages/coding-standards/composer.json
- packages/coding-standards/easy-coding-standard.yml
- packages/coding-standards/src/Yaml/CheckerServiceParametersShifter.php
- project-base/symfony.lock
- symfony.lock
|Description, reason for the PR| In #2210 was locked version of symfony/dependency-injection due to bug in symplify/symplify#2872. This PR allows back installing new versions of the symfony/dependency-injection and fixes introduced bug in symplify/symplify. 
upgrade notes not added because the `project-base/symfony.lock` file is updated automatically and it's not necessary to do anything.
> [shopsys] allowed install new version of symfony/dependency-injection

- packages/frontend-api/src/Model/User/FrontendApiUserFactory.php
|Description, reason for the PR| Method `Lcobucci\JWT\Token::getClaim()` has been removed from the interface in v4.0. Inspired by @RostislavKreisinger 
> [frontend-api] removed deprecated use of `Token::getClaim` in FrontendApiUserFactory

- packages/framework/src/Model/Customer/User/CustomerUser.php
|Description, reason for the PR| Company name is return only when is not null. Inspired by @RostislavKreisinger 
> [framework] company name is return when is not null

- project-base/assets/js/frontend/validation/form/orderValidator.js
|Description, reason for the PR| When customer selected he is buying as company, tried to send order without filled info, he got stuck with disabled Send order button. This PR fixes that.
|Fixes issues| closes #2291 
> [framework] fixed order validation of company customers

- project-base/src/DataFixtures/Demo/PaymentDataFixture.php
- project-base/src/DataFixtures/Demo/TransportDataFixture.php
- upgrade/UPGRADE-v9.1.2-dev.md
|Description, reason for the PR| Transport and Payment prices have wrong price after data fixtures load. This PR fixes the problem and prices as well.
> [project-base] fixed wrong price converting in datafixtures

- packages/framework/src/Command/CronCommand.php
- packages/framework/src/Component/Elasticsearch/AbstractExportChangedCronModule.php
- packages/framework/src/Component/FileUpload/FileUpload.php
- packages/framework/src/Component/Image/Config/ImageConfig.php
- packages/framework/src/Component/Image/Config/ImageConfigLoader.php
- packages/framework/src/Component/Router/DomainRouterFactory.php
- packages/framework/src/Component/Router/FriendlyUrl/FriendlyUrlFacade.php
- packages/framework/src/Component/Router/FriendlyUrl/FriendlyUrlGenerator.php
- packages/framework/src/Component/Router/FriendlyUrl/FriendlyUrlRouterFactory.php
- packages/framework/src/Component/Router/LocalizedRouterFactory.php
- packages/framework/src/Controller/Admin/CustomerController.php
- packages/framework/src/DependencyInjection/SetterInjectionTrait.php
- packages/framework/src/Model/AdvancedSearch/Filter/ProductCategoryFilter.php
- packages/framework/src/Model/Customer/User/CustomerUserPasswordFacade.php
- packages/framework/src/Model/Product/Elasticsearch/ProductExportRepository.php
- packages/framework/src/Model/Product/ProductDataFactory.php
- packages/framework/src/Twig/UploadedFileExtension.php
- packages/frontend-api/src/Component/Constraints/ProductCanBeOrderedValidator.php
- packages/frontend-api/src/Controller/FrontendApiController.php
- packages/frontend-api/src/Model/Resolver/Category/CategoryResolver.php
- packages/frontend-api/src/Model/Resolver/Image/ImagesResolver.php
- packages/frontend-api/src/Model/Resolver/Price/PriceResolver.php
- packages/frontend-api/src/Model/Resolver/Products/ProductResolverMap.php
- packages/frontend-api/src/Model/Resolver/Products/ProductsResolver.php
- packages/read-model/src/Product/Listed/ListedProductViewElasticFacade.php
- packages/read-model/src/Product/Listed/ListedProductViewFactory.php
|Description, reason for the PR| Setter injection methods are one of the ways to maintain backward compatibility, but they're tedious to write. This PR introduces the trait to set dependency with rules we had. Every setter injection method now uses the method from this trait. 
> [shopsys] extract setter injection methods into trait

- docs/installation/installation-using-docker-linux.md
|Description, reason for the PR| In Linux installation guide is now linked a required post-installation step to be able to run docker as non-root user.
|Fixes issues| closes #2297  
> [docs] linked post-installation steps for linux installation

- packages/framework/src/Model/Pricing/PriceConverter.php
- project-base/src/DataFixtures/Demo/PaymentDataFixture.php
- project-base/src/DataFixtures/Demo/ProductDataFixture.php
- project-base/src/DataFixtures/Demo/TransportDataFixture.php
- upgrade/UPGRADE-v9.1.2-dev.md
|Description, reason for the PR| Prices were different for different input price setting. This could cause automatic tests to fail. This PR fixes that.
> [project-base] data fixtures always create same prices independently on input price setting

- composer.json
- packages/framework/composer.json
- project-base/composer.json
- upgrade/UPGRADE-v9.1.2-dev.md
|Description, reason for the PR| Lower versions of symfony/proxy-manager-bridge may fail on error. This PR increases minimum installed version of symfony/proxy-manager-bridge to prevent those errors.
> [shopsys] increase minimal supported version of symfony/proxy-manager-bridge

- docs/cookbook/basic-data-import.md
|Description, reason for the PR| ProductData::$vat does not exist anymore, it was replaced with $vatsIndexedByDomainId
> [docs] fix basic-data-import.md 

- packages/framework/composer.json
- packages/framework/phpstan.neon
|Description, reason for the PR| shopsys/framework is meant to be used exclusively with shopsys/project-base, so the Symfony dependencies were restricted to version 4 to prevent installing a newer major version after package split. 
> [framework] restrict symfony to version 4

- packages/framework/src/Twig/PriceExtension.php
|Description, reason for the PR| Wrong text in order
|Fixes issues| closes #2345  
> [framework] free text in order is now correctly translated to orders language

- composer.json
- packages/backend-api/composer.json
- packages/framework/composer.json
- packages/migrations/composer.json
- packages/product-feed-google/composer.json
- packages/product-feed-heureka/composer.json
- packages/product-feed-zbozi/composer.json
- upgrade/UPGRADE-v9.1.2-dev.md
|Description, reason for the PR| we are using `executeStatement()` from (#2148) method which was added in 2.11 (see https://github.com/doctrine/dbal/commit/524a23b045d899a620f27f369acee7accf76cb2b)
> [shopsys] bump minimal version of doctrine/dbal package

- composer.json
- packages/framework/composer.json
|Description, reason for the PR| we are using `::isGreaterThan(), ::isGreaterOrEqualTo(), ::isLessThan(), ::isLessOrEqualTo()` methods which was added in 0.8.6 (see https://github.com/Litipk/php-bignumbers/commit/68b2705b26d6f73697b37c74bb192e29e4f9e5cc)
> [framework] bump minimal version of litipk/php-bignumbers package

- packages/framework/assets/styles/admin/components/form/line.less
- packages/framework/assets/styles/admin/components/in/ckeditor.less
- packages/framework/assets/styles/admin/components/in/image.less
- packages/framework/assets/styles/admin/core/form/input.less
- packages/framework/src/Resources/views/Admin/Form/theme.html.twig
|Description, reason for the PR| Labels in the administration were bad align when the multidomain fields were added. This PR fixes this.
|Fixes issues| closes #1783
> [framework] admin: fix label alignment in multidomain fields

- composer.json
- packages/framework/composer.json
- project-base/composer.json
- upgrade/UPGRADE-v9.1.2-dev.md
|Description, reason for the PR| due to security issue https://github.com/thephpleague/flysystem/security/advisories/GHSA-9f46-5r25-5wfm
> [shopsys] increased the minimal version of `league/flysystem`

- project-base/src/Form/Front/Cart/AddProductFormType.php
- project-base/src/Form/Front/Cart/CartFormType.php
- upgrade/UPGRADE-v9.1.2-dev.md
|Description, reason for the PR| It is possible to fill value like `2a` for quantity. The app crashes because of it when trying to complete these ordrers. 
> [project-base] fix quantity validation in cart form

- project-base/phpunit.xml
- upgrade/UPGRADE-v9.1.3-dev.md
|Description, reason for the PR| memory limit has unit M instead od MB
> [project-base] fixed memory limit for phpunit

- packages/framework/composer.json
|Description, reason for the PR| extra section was duplicated, resulting in ignored branch alias 
> [framework] fixed duplicated extra section in composer

- packages/framework/.github/workflows/run-checks-tests.yaml
- packages/framework/phpstan.neon
- packages/http-smoke-testing/.github/workflows/run-checks-tests.yaml
- project-base/.github/workflows/docker-build.yaml
- project-base/phpstan.neon
- project-base/scripts/configure.sh
- project-base/scripts/install.sh
- upgrade/UPGRADE-v9.1.3-dev.md
|Description, reason for the PR| builds of split packages `shopsys/framework`, `shopsys/project-base`, and `shopsys/http-smoke-testing` are failing because of a few issues
> [shopsys] fix builds of split packages

- .github/workflows/docker-build.yaml
- composer.json
- packages/backend-api/install/composer.json.patch
- packages/backend-api/install/config/bundles.php.patch
- packages/framework/src/Component/Console/ConsoleExitCodeSubscriber.php
- packages/framework/tests/Unit/Component/Console/ConsoleExitCodeSubscriberTest.php
- project-base/composer.json
- project-base/config/bundles.php
- project-base/symfony.lock
- symfony.lock
- upgrade/UPGRADE-v9.2.0-dev.md
|Description, reason for the PR| the bundle does not support PHP 8
> remove "vasek-purchart/console-errors-bundle" dependency

- packages/coding-standards/.github/workflows/run-checks-tests.yaml
- packages/coding-standards/.travis.yml
- packages/coding-standards/composer.json
- packages/coding-standards/tests/Unit/Sniffs/ConstantVisibilityRequiredSniff/ConstantVisibilityRequiredSniffTest.php
- packages/coding-standards/tests/Unit/Sniffs/ConstantVisibilityRequiredSniff/correct/Various.php
- packages/coding-standards/tests/Unit/Sniffs/ConstantVisibilityRequiredSniff/wrong/Various.php
- packages/http-smoke-testing/.github/workflows/run-checks-tests.yaml
- packages/http-smoke-testing/.travis.yml
- packages/http-smoke-testing/composer.json
- packages/migrations/.github/workflows/run-checks-tests.yaml
- packages/migrations/.travis.yml
- packages/migrations/composer.json
- upgrade/UPGRADE-v9.2.0-dev.md
|Description, reason for the PR| PHP 7.2 and 7.3 are no longer supported, so the support of those versions was dropped in packages `shopsys/migrations`, `shopsys/coding-standards`, and `shopsys/http-smoke-testing`. Support for PHP 8.0 and 8.1 added for `shopsys/coding-standards` and `shopsys/http-smoke-testing`.
see succesfull builds:
- https://github.com/shopsys/coding-standards/actions/runs/1993697489
- https://github.com/shopsys/http-smoke-testing/actions/runs/1993753197
> [shopsys] dropped support for unsupported PHP in packages

- packages/migrations/composer.json
- packages/migrations/tests/Unit/Component/Doctrine/Migrations/AbstractMigrationLockTestCase.php
- fixed AbstractMigrationLockTestCase so it creates mock from LoggerInterface instead of Monolog\Logger
|Description, reason for the PR| the package itself should require all the dependencies it uses, otherwise, it might end non-funcioning, see https://github.com/shopsys/migrations/runs/5770698635?check_suite_focus=true
> [migrations] add psr/log dependency

- composer.json
- packages/framework/composer.json
- project-base/composer.json
- upgrade/UPGRADE-v9.2.0-dev.md
|Description, reason for the PR| reason for pinning version from #1860 was resolved in jms/translation-bundle v1.6.0. New version is necessary for update to PHP8.1
> [shopsys] upgraded jms/translation-bundle to v1.6.2

- composer.json
- packages/framework/composer.json
- packages/framework/src/Resources/config/services.yaml
|Description, reason for the PR| New version is required for support of PHP 8.1
> [framework] upgraded knplabs/knp-menu-bundle to version 3.2

- composer.json
- packages/framework/composer.json
|Description, reason for the PR| In doctrine/orm:2.12.0 is a conflicting change with prezent/doctrine-translatable package. This PR temporarily conflicts new version until https://github.com/Prezent/doctrine-translatable/pull/41 is resolved.
> [framework] new doctrine/orm version conflicted due to bc break

- packages/framework/src/Controller/Admin/FileUploadController.php
|Description, reason for the PR| if filename is not provided, null is in the end passed as 3rd argument to preg_replace() function, and this is deprecated since PHP8.1
> [framework] fix delete file action without filename

- packages/frontend-api/src/Model/Token/JwtConfigurationFactory.php
|Description, reason for the PR| In #2419 was introduced new JWT configuration factory. If Frontend API is disabled and this class is injected (typically in some tests), the application crashes. This PR fixes it by creating an unsecured signer in that case. **CREATING AN UNSECURED SIGNER IS NOT A GOOD IDEA FOR PRODUCTION ENVIRONMENT**
> [frontend-api] attempt to create jwt configuration without keys now create unsecured signer instead of error

- packages/framework/src/Command/ExtendedClassesAnnotationsCommand.php
- packages/framework/src/Component/ClassExtension/AnnotationsReplacer.php
- packages/framework/src/Component/ClassExtension/DocBlockParser.php
- packages/framework/src/Component/ClassExtension/Exception/DocBlockParserAmbiguousTagException.php
- packages/framework/src/Component/ClassExtension/Exception/DocBlockParserException.php
- packages/framework/src/Component/ClassExtension/MethodAnnotationsFactory.php
- packages/framework/tests/Unit/Component/ClassExtension/AnnotationsReplacerTest.php
- packages/framework/tests/Unit/Component/ClassExtension/DocBlockParserTest.php
- packages/framework/tests/Unit/Component/ClassExtension/MethodAnnotationsFactoryTest.php
- packages/framework/tests/Unit/Component/ClassExtension/PropertyAnnotationsFactoryTest.php
- packages/framework/tests/Unit/Component/ClassExtension/Source/DummyClassForAnnotationsReplacerTest.php
- upgrade/UPGRADE-v9.2.0-dev.md
|Description, reason for the PR|Removes all usages of methods that are no longer available in roave/better-reflection v5.x so that we can upgrade to version 5 in the future without problems. After uppgrade of roave/better-reflection phpdocumentor/reflection-docblock must be added as new dependency to composer.json
> [framework] Remove usage of deprecated methods from roave/better-reflection

- packages/framework/src/Component/ClassExtension/AnnotationsAdder.php
- packages/framework/src/Component/ClassExtension/MethodAnnotationsFactory.php
- packages/framework/tests/Unit/Component/ClassExtension/AnnotationsAdderTest.php
- packages/framework/tests/Unit/Component/ClassExtension/MethodAnnotationsFactoryTest.php
- packages/framework/tests/Unit/Component/ClassExtension/Source/AnnotationsAdderTest/DummyClassWithMethodAnnotation.php
- packages/framework/tests/Unit/Component/ClassExtension/Source/MethodAnnotationsFactoryTest/BaseClass5.php
- packages/framework/tests/Unit/Component/ClassExtension/Source/MethodAnnotationsFactoryTest/ChildClass5.php
- project-base/src/Model/Category/Category.php
- project-base/src/Model/LegalConditions/LegalConditionsFacade.php
|Description, reason for the PR| Fixes phing targets annotations-fix and annotations-check for cases when parameters have default values and cases when there already was a @method annotation but it needs an update. <br />https://github.com/shopsys/shopsys/pull/2308 won't be merged as v9.1 won't get any new versions, so I cherry picked commits from @PetrHeinz (Thank you!) and added correct behaviour for constants as default parameter. 
|Fixes issues| Closes https://github.com/shopsys/shopsys/issues/2273 
> [framework] Enhancement of check / fix method annotations

- packages/framework/src/Model/Administrator/Administrator.php
- packages/framework/src/Model/Customer/User/CustomerUser.php
- upgrade/UPGRADE-v9.2.0-dev.md
|Description, reason for the PR| Resolves deprecated usage of `Serializable` interface in `\Shopsys\FrameworkBundle\Model\Customer\User\CustomerUser` and `\Shopsys\FrameworkBundle\Model\Administrator\Administrator`<br/> For more info see notes and Example 2 here: https://www.php.net/manual/en/language.oop5.magic.php#object.unserialize
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No (But PHP >=7.4.0 is required) 
> [framework] Use magic methods instead of Serializable interface

- packages/framework/src/Command/CreateDatabaseCommand.php
- packages/framework/src/Migrations/Version20190521071335.php
- packages/framework/src/Migrations/Version20190930140221.php
- packages/framework/src/Migrations/Version20200310120000.php
- packages/framework/src/Migrations/Version20200310130000.php
- packages/framework/src/Migrations/Version20200319124638.php
- packages/framework/src/Migrations/Version20200330150340.php
- packages/framework/src/Migrations/Version20200416114815.php
- packages/framework/src/Migrations/Version20200819165818.php
- packages/framework/src/Migrations/Version20200923075659.php
- packages/framework/src/Migrations/Version20200930074334.php
- packages/framework/src/Migrations/Version20201009082139.php
- packages/framework/src/Migrations/Version20201120143414.php
- upgrade/UPGRADE-v9.2.0-dev.md
|Description, reason for the PR| current behavior break unique constraint for existing data. uuid-ossp can be removed along with the upgrade of PostgreSQL in the future.
> [framework] revert generate uuid in migrations from #2417

- packages/framework/src/Component/Console/ProgressBarFactory.php
|Description, reason for the PR| float is implicitly cast to int before modulo operand and this causes deprecation warning in PHP 8.1
> [framework] fix deprecation Implicit conversion from float to int loses precision

- packages/framework/src/Model/Administrator/Administrator.php
- packages/framework/src/Model/Cart/Cart.php
- packages/framework/src/Model/Category/Category.php
- packages/framework/src/Model/Customer/Customer.php
- packages/framework/src/Model/Order/Order.php
- packages/framework/src/Model/Payment/Payment.php
- packages/framework/src/Model/Product/Product.php
- packages/framework/src/Model/Transport/Transport.php
- packages/product-feed-heureka/src/Model/HeurekaCategory/HeurekaCategory.php
- upgrade/UPGRADE-v9.2.0-dev.md
|Description, reason for the PR| Using `toArray()` on Doctrine Collections might be problematic as described in #2409  
|[BC breaks]| No
|Fixes issues| closes #2409 
> [shopsys] Use getValues() instead of toArray() on Doctrine Collections

- docs/_theme/versions.html
- docs/index.md
- packages/backend-api/README.md
- packages/coding-standards/README.md
- packages/form-types-bundle/README.md
- packages/framework/README.md
- packages/frontend-api/README.md
- packages/google-cloud-bundle/README.md
- packages/http-smoke-testing/README.md
- packages/migrations/README.md
- packages/monorepo-tools/README.md
- packages/plugin-interface/README.md
- packages/product-feed-google/README.md
- packages/product-feed-heureka-delivery/README.md
- packages/product-feed-heureka/README.md
- packages/product-feed-zbozi/README.md
- packages/read-model/README.md
- project-base/README.md
- upgrade/money-class.md
|Description, reason for the PR| Fixed link to join our slack across the codebase. The proper link was in general README.md file, but other occurrences were fixed here.
> [shopsys] fixed join slack link across codebase

- packages/coding-standards/.github/workflows/run-checks-tests.yaml
- packages/coding-standards/composer.json
- packages/http-smoke-testing/.github/workflows/run-checks-tests.yaml
- packages/http-smoke-testing/composer.json
|Description, reason for the PR| PHP 7.4 support ends within a few months. 
> [coding-standards] [http-smoke-testing] dropped PHP 7.4 support

- packages/coding-standards/ecs.php
|Description, reason for the PR| description follows
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No (setlist introduced in the same version) 
The setList cannot be used as DeclareStrictTypesFixer forces strict types declaration in the split packages and the codebase is not ready for this.
- rule contains four fixers:
-- StrictComparisonFixer - we use DisallowEqualOperatorsSniff instead
-- StrictParamFixer - is defined in the ecs file directly
-- DeclareStrictTypesFixer - cannot be used yet
-- IsNullFixer - is not enforced
> [coding-standards] remove STRICT setList from configuration

- ecs.php
- packages/backend-api/ecs.php
- packages/coding-standards/ecs.php
- packages/form-types-bundle/ecs.php
- packages/framework/ecs.php
- packages/frontend-api/ecs.php
- packages/google-cloud-bundle/ecs.php
- packages/http-smoke-testing/ecs.php
- packages/migrations/ecs.php
- packages/plugin-interface/ecs.php
- packages/product-feed-google/ecs.php
- packages/product-feed-heureka-delivery/ecs.php
- packages/product-feed-heureka/ecs.php
- packages/product-feed-zbozi/ecs.php
- packages/read-model/ecs.php
- project-base/ecs.php
- upgrade/UPGRADE-v10.0.0-dev.md
|Description, reason for the PR| Removes deprecation notices about new config syntax<br />New config was released a week ago.<br />See: https://tomasvotruba.com/blog/new-in-ecs-simpler-config/
> [shopsys] Refactor ECS config to new syntax

- packages/framework/build.xml
- packages/framework/src/Component/Translation/ConfigConstraintMessageExtractor.php
- packages/framework/src/Resources/config/services.yaml
- packages/framework/src/Resources/translations/messages.cs.po
- packages/framework/src/Resources/translations/messages.en.po
- packages/framework/src/Resources/translations/validators.cs.po
- packages/framework/src/Resources/translations/validators.en.po
- packages/framework/tests/Unit/Component/Translation/ConfigConstraintMessageExtractorTest.php
- packages/framework/tests/Unit/Component/Translation/Resources/DummyMutation.types.yaml
- packages/frontend-api/src/Resources/translations/validators.cs.po
- packages/frontend-api/src/Resources/translations/validators.en.po
- upgrade/UPGRADE-v10.0.0-dev.md
|Description, reason for the PR| Functionality to translate custom constraint messages for GraphQL. It's possible Frontend and Backend validation are not exactly same, so you wanna FE developers to be informatied about what this is issue and they can show error message customer. P.S.: czech language is not my native speak language so please check czech translate. Thanks
> [framework] translate constraint messages in yaml files in config directory

- packages/framework/src/Component/Cron/CronModuleRepository.php
|Description, reason for the PR| running `cron` fails on the warning message
> [framework] CronModuleRepository: fix "Warning: array_pop(): Argument #1 ($array) must be passed by reference, value given"

- docs/installation/installation-using-docker-linux.md
- docs/installation/installation-using-docker-macos.md
- docs/installation/installation-using-docker-windows-10.md
- docs/introduction/basics-about-package-architecture.md
- mkdocs.yml
|Description, reason for the PR| the installation of project-base using `composer create-project` might fail unnecessarily when local PHP setup is not met with the app requirements. Also, the warning message should not be displayed as the current stable version is the latest one
> [shopsys] update docs: installation and "latest" warning message

- packages/framework/src/Component/Translation/ConstraintMessageExtractor.php
- packages/framework/src/Component/Translation/ConstraintMessagePropertyExtractor.php
- packages/framework/src/Component/Translation/ConstraintViolationExtractor.php
- packages/framework/src/Component/Translation/JsFileExtractor.php
- packages/framework/src/Component/Translation/PhpFileExtractor.php
- packages/framework/src/Component/Translation/TwigFileExtractor.php
- upgrade/UPGRADE-v11.0.0-dev.md
|Description, reason for the PR| the errors were reported by the new version of PHPStan, see eg. https://github.com/shopsys/shopsys/runs/6587756007?check_suite_focus=true
> [framework] fix implementations of FileVisitorInterface::visitTwigFile

- docs/_theme/main.html
- docs/requirements.txt
|Description, reason for the PR| the plugin was removed from configuration in 979ff2d44 but the theme was not modified, so the placeholder "### VERSION-WARNING-BANNER-PLACEHOLDER ###" was rendered
> [shopsys] docs: remove version warning placeholder from theme

- packages/framework/src/Model/Sitemap/SitemapListener.php
|Description, reason for the PR| Priority can be more than just `int`. In fact, almost every priority set is a `float`
> [framework] fixed sitemap priority type

- utils/releaser/src/ReleaseWorker/AfterRelease/CheckPackagesOnPackagistReleaseWorker.php
- utils/releaser/src/ReleaseWorker/Release/CreateAndPushGitTagReleaseWorker.php
- utils/releaser/src/ReleaseWorker/Release/CreateAndPushGitTagsExceptProjectBaseReleaseWorker.php
|Description, reason for the PR| Tags are now created with the `v` prefix as they were in the past. Backend API is now not tagged and this tag is not pushed.
> [monorepo] minor fixes in release process

- packages/framework/src/Component/Redis/RedisFacade.php
- packages/framework/src/Component/Redis/RedisVersionsFacade.php
|Description, reason for the PR| Redis::scan(): Passing null to parameter #3 ($i_count) of type int is deprecated</br>Redis::eval(): Passing null to parameter #3 ($num_keys) of type int is deprecated
> [framework] remove Redis deprecations

- packages/framework/src/Component/Router/FriendlyUrl/FriendlyUrlMatcher.php
|Description, reason for the PR| https://symfony.com/blog/new-in-symfony-4-1-deprecated-the-bundle-notation
> [framework] remove usage of deprecated FrameworkBundle:Redirect:redirect

- packages/framework/src/Component/Cron/CronFacade.php
- packages/framework/src/Component/Domain/DomainIconResizer.php
- packages/framework/src/Component/Log/SlowLogSubscriber.php
- packages/framework/src/Model/Feed/DailyFeedCronModule.php
- packages/framework/src/Model/Feed/HourlyFeedCronModule.php
- packages/framework/src/Model/Pricing/Vat/VatDeletionCronModule.php
- packages/plugin-interface/README.md
- packages/product-feed-heureka/src/Model/HeurekaCategory/HeurekaCategoryCronModule.php
|Description, reason for the PR| Usage of logger functions should be compatible with PSR-3 interface. This allows seamless logger switching and helps with future Symfony 5 update.
> [shopsys] logger usage is now compliant with PSR-3

- packages/framework/src/Component/Collector/ShopsysFrameworkDataCollector.php
- packages/framework/src/Component/Elasticsearch/Debug/ElasticsearchCollector.php
- upgrade/UPGRADE-v11.0.0-dev.md
|Description, reason for the PR| In Symfony 5, the `collect` method of the debug data collectors change its interface.  This PR make code future compatible with this change, so its easier to update to Symfony 5 in the future
> [framework] debug collectors are now future compatible with Symfony 5

- composer.json
- packages/frontend-api/composer.json
- packages/frontend-api/src/Resources/config/parameters.yaml
|Description, reason for the PR| hotfix was present due to https://github.com/overblog/GraphQLBundle/issues/588, underlying issue was resolved in the version 0.13.3, so the hotfix is not necessary anymore
> [frontend-api] removed graphql hotfix after underlying issue was resolved

- utils/releaser/src/ReleaseWorker/Release/CreateAndCommitLockFilesReleaseWorker.php
|Description, reason for the PR| `CreateAndCommitLockFilesReleaseWorker` now install dependencies in a separate folder to avoid namespace conflict while releasing
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| Yes/No 
> [releaser] lock files are now created in a separate folder

- packages/framework/src/Component/Router/Security/RouteCsrfProtector.php
- packages/framework/tests/Unit/Component/Domain/DomainSubscriberTest.php
- packages/framework/tests/Unit/Component/HttpFoundation/SubRequestListenerTest.php
- packages/framework/tests/Unit/Component/Router/Security/ControllerNotProtected.php
- packages/framework/tests/Unit/Component/Router/Security/ControllerProtected.php
- packages/framework/tests/Unit/Component/Router/Security/RouteCsrfProtectorTest.php
- packages/framework/tests/Unit/Model/Product/ProductVisibilityFacadeTest.php
- packages/framework/tests/Unit/Model/Security/LoginListenerTest.php
- project-base/tests/App/Functional/Model/Pricing/InputPriceRecalculationSchedulerTest.php
- upgrade/UPGRADE-v11.0.0-dev.md
|Description, reason for the PR| Event classes are final in Symfony 5
|Fixes issues| Allow upgrade to Symfony 5
> [shopsys] do not mock Events in tests

- packages/framework/assets/styles/admin/components/form/tree.less
- packages/framework/src/Resources/views/Admin/Content/Category/list.html.twig
|Description, reason for the PR| administrator wanst hideable category tree in admin section
> [framework] category tree in administration is now hideable

- composer.json
- packages/framework/composer.json
- packages/product-feed-google/composer.json
- packages/product-feed-heureka-delivery/composer.json
- packages/product-feed-heureka/composer.json
- packages/product-feed-zbozi/composer.json
- project-base/composer.json
- upgrade/UPGRADE-v11.0.0-dev.md
|Description, reason for the PR| update twig/twig to v2.15.4 - fix CVE-2022-39261 - https://symfony.com/blog/twig-security-release-possibility-to-load-a-template-outside-a-configured-directory-when-using-the-filesystem-loader
> [shopsys] update twig/twig to v2.15.4

- packages/framework/src/Component/DataFixture/AbstractReferenceFixture.php
|Description, reason for the PR| remove LoggingMiddleware from connection in data fixtures for faster demo data generation
> [framework] remove LoggingMiddleware from connection in data fixtures for faster demodata generation

- packages/framework/src/Model/Sitemap/SitemapFacade.php
- packages/framework/src/Model/Sitemap/SitemapListener.php
- packages/framework/src/Model/Sitemap/SitemapRepository.php
- upgrade/UPGRADE-v11.0.0-dev.md
|Description, reason for the PR| the sitemap now contains only the url addresses of the common product and the main product variants. Links to product variants do not have their own landing page, so they are not in the sitemap.
> [framework] remove product variant urls from sitemap

- packages/framework/composer.json
- packages/framework/src/Component/HttpKernel/Profiler/FileProfilerStorage.php
- packages/framework/src/Resources/config/services.yaml
|Description, reason for the PR| URLs in symfony profiler contain information about a query or mutation. ( http://127.0.0.1:8000/graphql/ - query{categories} )
> [framework] Symfony profiler contains extended URLs for graphQL API requests

- docs/cookbook/dump-variables.md
- docs/cookbook/index.md
- project-base/config/packages/dev/debug.yaml
|Description, reason for the PR| var dumps are not sent with the response, instead they are redirected to the symfony dump server. https://symfony.com/doc/current/components/var_dumper.html#var-dumper-dump-server
> [framework] Remove var dumps from API response

- packages/framework/src/Model/Cart/CartFacade.php
- project-base/config/packages/framework.yaml
- project-base/tests/App/Functional/Model/Cart/CartFacadeDeleteOldCartsTest.php
- upgrade/UPGRADE-v11.0.0-dev.md
|Description, reason for the PR|  session is valid for a year instead of relation only and the cart is now deleted after 130 days from the user's last activity
> [shopsys] update session and cart lifetime

- utils/releaser/src/ReleaseWorker/AbstractCheckShopsysInstallReleaseWorker.php
- utils/releaser/src/ReleaseWorker/AfterRelease/CheckShopsysInstallReleaseWorker.php
- utils/releaser/src/ReleaseWorker/AfterRelease/SetMutualDependenciesToDevelopmentVersionReleaseWorker.php
- added information about necessity of manually splitting monorepo when not on master branch
|Description, reason for the PR| there is a confusing moment when releasing a version that is not on master - you have tag in project-base but the tag is not in any branch until the monorepo branch is split 
**Note:** it would be nice to merge 10.0 branch into master after this PR is merged
> [releaser] improve information in after-release stage

- project-base/tests/FrontendApiBundle/Functional/Product/ProductsSearchTest.php
- upgrade/UPGRADE-v11.0.0-dev.md
|Description, reason for the PR| The test was not run when running `tests` phing target because of the missing suffix
Btw, when fixing the tests on my project that is based on the commerce cloud version, I had to fix a few more issues - `testSearchInAllProducts` is trying to search the phrase "book" but nothing is found (the first domain has Czech locale). After changing the test search phrase to "kniha", expected products were found indeed, however, their ordering was different.
> [project-base] fix tests for product searching

- packages/framework/src/Component/Error/ErrorPagesFacade.php
|Description, reason for the PR| There are three error pages generated during the deployment of the application for each domain, every error page generation opens a new DB connection that is not properly closed. That means you can easily exceed the allowed DB connections during the deployment. Calling `shutdown` should solve the issue. The original author of the solution is https://github.com/MlynekMartinCZ :wink: We have not tested the solution properly and we are not sure whether the solution is 100 % legit, so we ask you, the maintainers of SSFW, to verify this solution, thank you!
|Have you read and signed …
> [framework] shutdown kernel after generating error page

- packages/framework/src/Model/ImageSitemap/ImageSitemapCronModule.php
- packages/framework/src/Model/ImageSitemap/ImageSitemapDumper.php
- packages/framework/src/Model/ImageSitemap/ImageSitemapDumperFactory.php
- packages/framework/src/Model/ImageSitemap/ImageSitemapFacade.php
- packages/framework/src/Model/ImageSitemap/ImageSitemapFilePrefixer.php
- packages/framework/src/Model/ImageSitemap/ImageSitemapItem.php
- packages/framework/src/Model/ImageSitemap/ImageSitemapItemImage.php
- packages/framework/src/Model/ImageSitemap/ImageSitemapListener.php
- packages/framework/src/Model/ImageSitemap/ImageSitemapPopulateEvent.php
- packages/framework/src/Model/Sitemap/SitemapListener.php
- packages/framework/src/Resources/config/services.yaml
- packages/framework/src/Resources/views/Common/robots.txt.twig
- project-base/config/services/cron.yaml
- project-base/src/Controller/Front/RobotsController.php
- upgrade/UPGRADE-v11.0.0-dev.md
|Description, reason for the PR| We want the data in the sitemap to be true and relevant, or rather not be there. All information about `<lastmod>`, `<changefreq>` and `<priority>` is removed from the sitemap (page and images). Added image sitemap
> [shopsys] Sitemap updates

- packages/framework/assets/package.json
- project-base/package.json
- upgrade/UPGRADE-v11.0.0-dev.md
|Description, reason for the PR| Newer version breaks nestedSortable https://github.com/ilikenwf/nestedSortable/issues/138. This can be fixed by changing nestedSortable to https://github.com/ilikenwf/nestedSortable after they release newer version than 2.0.0
> [shopsys] locked version of jquery-ui to 1.12.1 in order to fix category ordering in admin

- packages/framework/src/Component/HttpKernel/Profiler/FileProfilerStorage.php
|Description, reason for the PR| Named queries/mutations should be parsed too. A parsing error should not fall on an silent error. 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| Yes/No 
> [framework] Symfony profiler shows query or mutation name for API requests

- packages/framework/src/Component/Translation/PhpParserNodeHelper.php
- packages/framework/src/Resources/translations/messages.cs.po
- packages/framework/src/Resources/translations/messages.en.po
- packages/framework/src/Resources/translations/validators.cs.po
- packages/framework/src/Resources/translations/validators.en.po
- project-base/translations/validators.cs.po
- project-base/translations/validators.en.po
|Description, reason for the PR| In #2549 we have started using constants for translation domains, but sadly, that change was poorly tested and we broke translations dumping. This PR fixes that.
> [framework] fixed dumping translations by adding support for translation domain constants

- packages/framework/src/Component/Translation/ConfigConstraintMessageExtractor.php
- packages/framework/src/Component/Translation/ConstraintMessageExtractor.php
- packages/framework/src/Component/Translation/ConstraintMessagePropertyExtractor.php
- packages/framework/src/Component/Translation/ConstraintViolationExtractor.php
- packages/framework/src/Component/Translation/Translator.php
- project-base/tests/App/Acceptance/acceptance/PageObject/Front/RegistrationPage.php
- project-base/tests/FrontendApiBundle/Functional/Customer/User/CurrentCustomerUserTest.php
- project-base/tests/FrontendApiBundle/Functional/Customer/User/RegisterTest.php
- project-base/tests/FrontendApiBundle/Functional/Newsletter/NewsletterTest.php
- project-base/tests/FrontendApiBundle/Functional/Order/CompanyFieldsAreValidatedTest.php
- project-base/tests/FrontendApiBundle/Functional/Order/DeliveryFieldsAreValidatedTest.php
- upgrade/UPGRADE-v11.0.0-dev.md
|Description, reason for the PR| In previous PRs we have added translation constants for messages and data fixtures but forgot about validators, this PR fixes it.
> [shopsys] added Translator constant for validators

- packages/frontend-api/src/Model/Error/EntityNotFoundUserError.php
- packages/frontend-api/src/Model/Resolver/Article/Exception/ArticleNotFoundUserError.php
- packages/frontend-api/src/Model/Resolver/Brand/Exception/BrandNotFoundUserError.php
- packages/frontend-api/src/Model/Resolver/Category/Exception/CategoryNotFoundUserError.php
- packages/frontend-api/src/Model/Resolver/Order/Exception/OrderNotFoundUserError.php
- packages/frontend-api/src/Model/Resolver/Payment/Exception/PaymentNotFoundUserError.php
- packages/frontend-api/src/Model/Resolver/Products/Exception/ProductNotFoundUserError.php
- packages/frontend-api/src/Model/Resolver/Transport/Exception/TransportNotFoundUserError.php
- upgrade/UPGRADE-v11.0.0-dev.md
|Description, reason for the PR| UserEntityNotFoundError was badly named so we fixed it.
> [frontend-api] UserEntityNotFoundError has been renamed to EntityNotFoundUserError

- .github/release.yml
- utils/releaser/config/release.php
- utils/releaser/src/ReleaseWorker/AbstractCheckPackagesGithubActionsBuildsReleaseWorker.php
- utils/releaser/src/ReleaseWorker/Release/CheckReleaseDraftAndReleaseItReleaseWorker.php
- utils/releaser/src/ReleaseWorker/ReleaseCandidate/UpdateChangelogReleaseWorker.php
|Description, reason for the PR| Old changelog generator was problematic and we found, that Github solves this for us.
> [releaser] switched from old changelog to Github Releases

- packages/framework/build.xml
- project-base/translations/dataFixtures.cs.po
- project-base/translations/dataFixtures.en.po
- upgrade/UPGRADE-v11.0.1-dev.md
|Description, reason for the PR| When there is an error during DB fixtures loading, sometimes, you need more information to find out where the problem is (see the images below)
Output without the option (old state):
Output with the option (new state):
> [framework] bin/console base phing targets are now more verbose

- packages/framework/assets/js/admin/components/OrderPreview.js
|Description, reason for the PR| After upgrading javascript codes disable loaderElement will not work with value null, so I recommend turning it off with 'none' value. If you don't like this solution, you can change 'none' value for something different or edit functionality for [loader element](https://github.com/shopsys/shopsys/blob/master/packages/framework/assets/js/common/utils/loaderOverlay.js#L2) with option for turn it off
> [framework] Do not show loader element in load order preview

- packages/framework/src/Model/Order/Mail/OrderMailFacade.php
- packages/framework/src/Model/Order/OrderFacade.php
- packages/frontend-api/src/Model/Mutation/Order/CreateOrderMutation.php
- project-base/src/Controller/Front/OrderController.php
- upgrade/UPGRADE-v11.0.1-dev.md
|Description, reason for the PR| Checking if email can be sent was done on multiple places and developers could forget to do such check. Using of sendMail method should be now more straightforward.
> [shopsys] checking if order status update email should be sent is done directly in OrderMailFacade instead in multiple places

- docs/administration/grid.md
- packages/framework/src/Component/Grid/Grid.php
- packages/framework/tests/Unit/Component/Grid/GridTest.php
|Description, reason for the PR| If project extend any existing grid (for example Product List grid in administration), it may be useful to be able to reorder columns (when it's needed to have fields in specific order)
> [framework] columns in grid can now be reordered

- packages/framework/src/Command/CronCommand.php
- packages/framework/src/Component/Cron/Config/CronConfig.php
- packages/framework/src/Component/Cron/CronModuleExecutor.php
- packages/framework/src/Component/Deprecations/DeprecationHelper.php
- upgrade/UPGRADE-v11.0.1-dev.md
|Description, reason for the PR| During the implementation of cron module runs we have introduced several BC-breaks, we are solving them here.
> [framework] fixed bc-breaks of cron module runs

- packages/framework/assets/styles/admin/components/table/col.less
- packages/framework/assets/styles/admin/todo.less
- packages/framework/src/Resources/views/Admin/Content/Order/orderItem.html.twig
- packages/framework/src/Resources/views/Admin/Form/orderItems.html.twig
|Description, reason for the PR| On bigger monitors were order items spread to full width and that did not look good.
> [framework] admin: order items table sizes are now fixed

- project-base/symfony.lock
- utils/releaser/src/ReleaseWorker/AfterRelease/RemoveLockFilesReleaseWorker.php
- utils/releaser/src/ReleaseWorker/Release/CreateAndCommitLockFilesReleaseWorker.php
|Description, reason for the PR| With the release of Shopsys Framework 11 we have removed symfony.lock from the project-base and that caused several problems.
> [project-base] returned symfony.lock to project-base as it caused problems with symfony flex installing packages again

- packages/framework/src/Controller/Admin/DefaultController.php
- packages/framework/src/Resources/config/parameters_common.yaml
- packages/framework/src/Resources/translations/messages.cs.po
- packages/framework/src/Resources/translations/messages.en.po
- packages/framework/src/Resources/views/Admin/Content/Default/index.html.twig
- project-base/config/packages/security.yaml
- project-base/tests/App/Smoke/Http/RouteConfigCustomization.php
|Description, reason for the PR| Cron overview is one of the useful features and should be available even for the admin
> [framework] cron overview is now available for admin in the default state

- docs/contributing/backward-compatibility-promise.md
|Description, reason for the PR| Currently supported version of Symfony is 5.4. Changed link to Symfony's BC promise to a supported version
> [docs] changed bc promise link to supported version

- packages/frontend-api/src/Model/Token/TokenAuthenticator.php
- project-base/tests/FrontendApiBundle/Functional/Login/LoginTest.php
- upgrade/UPGRADE-v11.0.1-dev.md
|Description, reason for the PR| `errors` should be always an array of objects, so it's the same as in other error responses
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| Possible (changes response after authentication failure in FE API) 
> [frontend-api] authentication failure now return errors as array

- packages/framework/src/Component/Error/ErrorPagesFacade.php
- project-base/config/packages/acc/monolog.yaml
- project-base/config/packages/prod/monolog.yaml
- project-base/config/packages/test/monolog.yaml
- upgrade/UPGRADE-v11.0.1-dev.md
|Description, reason for the PR| When you go URL that has allowed only POST requests you will  get 500 error page and it will be logged as error (see bottom). I recommend showing better 404 page and don't log this useless information. Thanks 🤝
full error message:
```
request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException: "No route found for "GET http://127.0.0.1:8000/search/autocomplete/": Method Not Allowed (Allow: POST)" at …
```
> don't show 500 error page when you have 405 http code

- project-base/storefront/connectors/cart/Cart.ts
- project-base/storefront/hooks/cart/useReloadCart.ts
- project-base/storefront/store/zustand/slices/createGeneralSlice.ts
- project-base/storefront/types/cart.ts
- project-base/storefront/urql/cacheExchange.ts
- project-base/storefront/urql/errorExchange.ts
|Description, reason for the PR| The Urql GraphCache did not behave correctly when it was manually updated in some specific scenarios. Namely  when he cart UUID in cache was null. New approach uses the cart UUID from mutation arguments, which should be more robust.
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)|No
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)? |Yes
> fixed cache behavior during manual updates after cart mutations

- packages/framework/src/Command/ExtendedClassesAnnotationsCommand.php
|Description, reason for the PR| Annotations fixer could update vendor classes which is not expected behavior.
> ensure only project classes are updated via annotation fixer

- project-base/storefront/helpers/errors/applicationErrors.ts
- project-base/storefront/helpers/errors/errorMessageMapper.ts
- project-base/storefront/helpers/errors/friendlyErrorMessageParser.ts
- project-base/storefront/helpers/errors/ignoredErrors.ts
- project-base/storefront/urql/errorExchange.ts
|Description, reason for the PR| We want to be able to differentiate between different error message verbosity in order to specify which errors should be showed to users, which logged in sentry, and which should be completely ignored. With this setting it's now possible.
> errors on SF can now have different verbosity

- project-base/storefront/hooks/forms/useErrorPopupVisibility.ts
|Description, reason for the PR| Error popup was not shown right after the first invalid form submission, but required 2 submissions. This PR fixes the issue.
|Fixes issues|
> error popup is now shown after the first invalid form submission
