packages/framework/.travis.yml

- composer install failed on Travis due to GitHub API limits
- uses environment variable GITHUB_TOKEN
|Description, reason for the PR| failing build of shopsys/framework on Travis CI: https://travis-ci.org/shopsys/framework
|Fixes issues| the build passed in a test branch: https://travis-ci.org/shopsys/framework/builds/365970575
|License| MIT
|Have you read and signed our [License Agreement for contributions](https://www.shopsys-framework.com/license-agreement)?| Yes

.travis.yml: added GitHub oAuth token for Composer

---

project-base/CHANGELOG.md
project-base/app/config/config.yml

|Description, reason for the PR| the former setting does not exist anymore in version 3.* (see https://github.com/symfony/swiftmailer-bundle/commit/5edfbd39eaefb176922a346c16b0ae3aaeec87e0) and causes failing of application build when delivery_address is set to null in parameters.yml
|License| MIT
|Have you read and signed our [License Agreement for contributions](https://www.shopsys-framework.com/license-agreement)?| Yes/No

[BG-2402] swiftmailer setting delivery_address renamed to delivery_addresses

---

packages/framework/CHANGELOG.md
packages/framework/src/Command/CreateDomainsDataCommand.php
packages/framework/src/DataFixtures/Base/DbIndicesDataFixture.php
packages/framework/src/Model/Localization/DbIndicesFacade.php
packages/framework/src/Model/Localization/DbIndicesRepository.php

|Description, reason for the PR| Db indices for product name were created only for the locale of the first domain (at the time of the creation, there were no other locales yet). Now indices are created after another domain (and locale) is added, see https://app.yodiz.com/plan/pages/board.vz?cid=10273#/app/bg-1710

Product name indices for all domains are now created during CreateDomainsDataCommand

---

CHANGELOG.md
docker/conf/docker-compose-mac.yml.dist
docker/conf/docker-compose.yml.dist
project-base/CHANGELOG.md
project-base/docker/conf/docker-compose-mac.yml.dist
project-base/docker/conf/docker-compose.yml.dist

|Description, reason for the PR| Images are now in concrete version, which assures that users will always download same version of environment.
|BC breaks| No

[US-3766] Concrete version of docker images

---

CHANGELOG.md
project-base/src/Shopsys/ShopBundle/Resources/views/Front/Form/theme.html.twig

|Description, reason for the PR| the absence of label html tag was causing problems with JS validation (the error message was not included in the popup overview)

[BG-2272] correct rendering of checkbox label

---

CHANGELOG.md
packages/framework/src/Resources/views/Admin/Content/Brand/detail.html.twig
packages/framework/src/Resources/views/Admin/Content/Brand/new.html.twig
project-base/src/Shopsys/ShopBundle/Resources/views/Front/Form/theme.html.twig

|Description, reason for the PR| admin: brand detail page: fixed rendering of URLs setting - brand creation: URLs setting is not rendered at all; brand editing: URLs section is rendered in the SEO section

[BG-2648] admin: brand edit page: URLs setting rendering

---

packages/framework/src/Model/Payment/Payment.php
packages/framework/src/Model/Transport/Transport.php

- the clearTransports / clearPayments method was used only once and shouldn't be a part of the class' interface
- it isn't necessary to clear the transports / payments while setting the associations
|Description, reason for the PR| the clear method was unnecessary (KISS, YAGNI), the associations shouldn't be removed and then added when calling `$transport->setPayments($transport->getPayments())` - no actual changes should be made

disallow clearing of associations between Transports and Payments

---

CHANGELOG.md
project-base/app/config/routing.yml

|Description, reason for the PR| We do not want to expose public route that allows anyone to lookup any DB table by any field
|Fixes issues| #177
|Standards and tests pass| No - due to the issue in doctrine-translatable-bundle, see https://github.com/Prezent/doctrine-translatable-bundle/pull/21

JsFormValidatorBundle security issue with Ajax validation 

---

CHANGELOG.md
packages/coding-standards/src/Sniffs/ForbiddenExitSniff.php

…ackage v3.3.0
- import of parent class of ForbiddenExitSniff was corrected
|Description, reason for the PR| fix build and ecs checks
|BC breaks| No
|Fixes issues| #221 

coding-standards package is now up to date with new PHP_codesniffer v3.3.0

---

CHANGELOG.md
project-base/docker/php-fpm/Dockerfile

|Description, reason for the PR| seems like our Docker build broke again (remove your cached images if you cannot duplicate the issue and run `docker-compose up -d --force-recreate --build`)
|Fixes issues| the originally used mirror https://dl-3.alpinelinux.org/alpine/ doesn't have the v3.4 directory anymore and the Docker build ends in an error

php-fpm/Dockerfile: switch to another mirror of alpine linux repository

---

CHANGELOG.md
build.xml

|Description, reason for the PR| Because we do not commit the composer.lock in monorepo it was necessary to execute "composer update" manually whenever composer.json was changed and that felt weird to me as it is a part of the usual workflow. Phing target "composer-dev" (e.g. as a part of "build-demo-dev") executed in monorepo will now run "composer update" instead of "composer install" if composer.lock is out-dated.
|New feature| Kinda 
|Fixes issues| Running "build-demo-dev" in monorepo now results in correct build of the application even if composer.json changes were fetched.

composer-dev updates dependencies if composer.json was changed

---

.gitignore

- the file is automatically generated during npm install, see https://docs.npmjs.com/files/package-lock.json
- the principle is the same as with composer.lock that is also gitignored in monorepo
|Description, reason for the PR| we want to unify the approach to generated lock files with composer and prevent developers from accidentally committing the generated file

monorepo: package-lock.json is gitignored

---

CHANGELOG.md
packages/framework/src/Resources/styles/admin/core/reset.less

- scrollbar normalization was disabled for sortable components (eg. sortableValues.js)
|Description, reason for the PR| misaligned cursor and dragged item when using drag&drop on Articles overview in administration
|Fixes issues| #198  

Admin: reset.less: disable scrollbar normalization in order to fix problems with jQuery UI drag&drop

---

docs/contributing/guidelines-for-creating-commits.md

|Description, reason for the PR|  we don't use internal backlog for issues anymore, issues are kept on GitHub

docs: commit msgs should not contain references to internal issues

---

CHANGELOG.md
packages/framework/src/Resources/scripts/admin/components/grid.inlineEdit.js
packages/framework/src/Resources/views/Admin/Grid/Grid.html.twig

- solved problem with failing of creation of a new row if gridInlineEdit is enabled
- drag&drob is disabled until new row is saved
|Description, reason for the PR| #179 
|Fixes issues| #179 

grid: drag&drop is supported with enabled gridInlineEdit

---

packages/framework/src/Form/Admin/Order/OrderFormType.php

- orderNumber in order detail form is solved as DisplayOnlyType that
requires label and data
|Description, reason for the PR| #279
|BC breaks| No
|Fixes issues| #279

admin: fixed missing order number in order detail

---

packages/framework/src/Component/String/TsqueryFactory.php

|Description, reason for the PR| searching for items with slash in its fields results in empty list
|Fixes issues| #196 

autocomplete returns results when search text contains slash

---

CHANGELOG.md
packages/monorepo-tools/rewrite_history_from.sh
packages/monorepo-tools/rewrite_history_into.sh

|Description, reason for the PR| Fixes non-portable tabs so they work on OS X
|BC breaks| No
|Fixes issues| #281
|Standards and tests pass| Not tested - no changes to main framework

monorepo-tools: Fix scripts to work on OS X

---

CHANGELOG.md
packages/framework/src/Controller/Admin/FeedController.php
packages/framework/src/Model/Feed/FeedFacade.php

|Description, reason for the PR| administrator needs to see time of last generation of feed and click on link to it
|Fixes issues| #307

Admin: feed items on feeds generation page contain clickable link and datetime  

---

CHANGELOG.md
project-base/src/Shopsys/ShopBundle/Resources/config/routing_front_cs.yml
project-base/src/Shopsys/ShopBundle/Resources/config/routing_front_en.yml

- route logout/ must to be called with token in every case because LogoutListener from Symfony throws exception if token generator is set in configuration of firewall but the route logout is used without csrf token parameter
|Description, reason for the PR| #195
|Fixes issues| #195

Route logout/ without csrf token returns not found

---

CHANGELOG.md
packages/framework/src/Migrations/Version20180603135340.php

|Description, reason for the PR| (#310) - Creating triggers on already existing database caused migrations to fail, this PR makes sure that triggers get deleted before created
|BC breaks| No
|Fixes issues| (#310) 

Dropped triggers before creation

---

CHANGELOG.md
packages/framework/src/Model/Cart/Watcher/CartWatcherFacade.php

| Q             | A 
| ------------- | 
|Description, reason for the PR| Messages in CartWatcherFacade has been switched
|BC breaks| No

CartWatcherFacade: fixed swapped messages

---

CHANGELOG.md
composer.json
packages/framework/composer.json
project-base/composer.json

|Description, reason for the PR| downgrade snc/redis-bundle to 2.1.4 (from 2.1.5) due to issue in phpredis extension,  issue - https://github.com/snc/SncRedisBundle/issues/442

Downgrade snc/redis-bundle to 2.1.4 due to Issue in phpredis

---

packages/framework/src/Resources/config/services_test.yml

|Description, reason for the PR| services loaded from service container directly must be public
|BC breaks| No

services_test.yml: added services used in tests so they are marked as public

---

CHANGELOG.md
composer.json
project-base/composer.json

|Description, reason for the PR| when composer installs `codecption/stub` package in version `2.0.2`, the `tests-acceptance-build` phing target fails without mentioning any reason. There is already released newer version of the package that fixes the issue but in some cases composer can resolve dependencies in a way when the `2.0.2` version is installed after all.

Composer: disable installation of broken version of codeception/stub

---

CHANGELOG.md
packages/framework/src/Model/Cookies/CookiesFacade.php
packages/framework/src/Model/Order/Mail/OrderMailService.php

|Description, reason for the PR| Static analyse of our code found out that we have some methods which are not typehinted. This PR solves it
|Fixes issues| (#333)

added missing typehints in methods of CookiesFacade and OrderMailService

---

CHANGELOG.md
packages/framework/easy-coding-standard.yml
packages/framework/src/Migrations/Version20180724060204.php

|Description, reason for the PR| procedures are now executed only if relevant columns are changed
|Fixes issues| (#245)

procedures are now executed only if relevant columns are changed

---

CHANGELOG.md
packages/framework/src/Model/Category/CategoryRepository.php

- Category entity is now extendable and extraction of class metadata are loaded from an extended entity if exists
|Description, reason for the PR| Class metadata for GedmoTree are not available in extended Category entity

Category entity in constructor of CategoryRepository is resolved via EntityNameResolver

---

composer.json
project-base/composer.json

- PHPUnit 7.2 and Conception 2.4 are incompatible, see https://github.com/Codeception/Codeception/issues/5092
- codeception/stub added compatibility with the newer version in their composer.json in 2.0.2
- with codeception/stub 2.0.2, phing target tests-acceptance-build silently fails, breaking our build (see #347)
- codeception/stub 2.0.3 reverted this change as the mainteiners saw the incompatibility issue
- codeception/stub 2.0.4 reverted the revert
- the package is marked as conflicting in version >=2.0.2 until the issue is fixed (I've added a bullet to our internal release checklist)
|Description, reason for the PR| target tests-acceptance-build fails
|Have …

composer.json: mark codeception/stub as conflicting from 2.0.2 onwards

---

CHANGELOG.md
packages/monorepo-tools/README.md
packages/monorepo-tools/monorepo_add.sh

|Description, reason for the PR| Create the ability to incrementally add a repo to an existing monorepo.
|Standards and tests pass| I have tested, but there are no standard tests for these tools.

Add `monorepo_add` to allow incremental build

---

CHANGELOG.md
packages/form-types-bundle/composer.json
packages/framework/composer.json
packages/migrations/composer.json
packages/plugin-interface/composer.json
packages/product-feed-google/composer.json
packages/product-feed-heureka-delivery/composer.json
packages/product-feed-heureka/composer.json
packages/product-feed-zbozi/composer.json
project-base/composer.json

Composer.json: require Shopsys packages in the current version (dev-master)
- revert of commit ca81a09c9bf259e91607a5dd0601ee9a5cfefcaf after release
|Description, reason for the PR| Rever of dependecies from v7.0.0-alpha4 back to dev-master after release
|BC breaks| No

Composer.json: require Shopsys packages in the current version (dev-master)

---

CHANGELOG.md
packages/framework/src/Resources/scripts/admin/categoryTree.formItem.js
packages/framework/src/Resources/scripts/admin/entityUrlList.newUrl.js
packages/framework/src/Resources/scripts/admin/orderItems.js
packages/framework/src/Resources/scripts/admin/parameters.js
packages/framework/src/Resources/scripts/common/validation/customizeBundle.js
packages/framework/src/Resources/scripts/common/validation/validation.js

|Description, reason for the PR| problem with saving forms with dynamically added parameters
|Fixes issues| #190

JS validation: dynamically added form inputs are now validated

---

CHANGELOG.md
project-base/src/Shopsys/ShopBundle/Resources/views/Front/Content/Product/ajaxSearch.html.twig
project-base/src/Shopsys/ShopBundle/Resources/views/Front/Content/Product/search.html.twig

-  variable name was used in url instead of variable value
| ------------- | ------------- 
|Description, reason for the PR| bugfix

product search: fix wrong variable usage in url to reset filter

---

build.xml
project-base/build-dev.xml

- missing the generated trait AcceptanceTesterActions would cause PHPStan check to fail
- this may happen if phing target "standards" is called immediately after "composer install"
- other coding standards checks are ignoring this file
- thanks to @ondrejmirtes for coming up with this solution
I haven't updated the changelog as I don't see this particular change noteworthy.
|Description, reason for the PR| phing Coding Standard check fails on phpstan run when run right after the composer install
|Fixes issues| #382 

phing target "phpstan" now depends on "tests-acceptance-build"

---

CHANGELOG.md
packages/framework/easy-coding-standard.yml
packages/framework/src/DataFixtures/Demo/PersonalDataAccessRequestDataFixture.php

|Description, reason for the PR| code in monorepo should apply the rules that are set via coding-standards package
|Fixes issues| #252 

classes excluded from ObjectIsCreatedByFactorySniff rule are fixed

---

CHANGELOG.md
packages/monorepo-tools/rewrite_history_into.sh

Repos created via 'git svn' always start with an empty commit that generates no rewritten index file and fails with `mv: cannot stat  .... index.new`. This is commonly reported issue on SO with a simple fix.
|Description, reason for the PR| monorepo_build/add doesn't work for reasonably common enterprise scenario of upgrading many trunks from a single svn repo into a git monorepo
|BC breaks| No
|Standards and tests pass| N/A

monorepo-tools: Handle rewriting of empty commits

---

docs/introduction/product-search-via-elasticsearch.md

|Description, reason for the PR| `ElasticsearchProductTranslator` class does not exist anymore, it was renamed to `ElasticsearchProductDataConverter` during the code review but the former name of the class was kept in the docs by mistake

docs: product-search-via-elasticsearch.md fixed to use proper classname

---

docs/installation/native-installation.md

|Description, reason for the PR| The problem is solved by upgrade to Postgres 10 so the information is now obsolete.

docs: native-installation.md: removed information about platform specific sorting from troubleshooting section

---

CHANGELOG.md
composer.json
packages/form-types-bundle/composer.json
packages/framework/composer.json
packages/http-smoke-testing/composer.json
packages/migrations/composer.json
packages/product-feed-google/composer.json
packages/product-feed-heureka-delivery/composer.json
packages/product-feed-heureka/composer.json
packages/product-feed-zbozi/composer.json
project-base/composer.json

|Description, reason for the PR| bug https://github.com/symfony/symfony/issues/28296 in Symfony 3.4.15 version that causes application build to fail

Symfony >=3.4.15 marked as conflicting in composer.json

---

project-base/build-dev.xml

|Description, reason for the PR| phing target `tests` fails after change dependencies in container or change ORM mappings.  It is a extension of https://git.shopsys-framework.com/shopsys/shopsys-framework/issues/21
|BC breaks| No

Clean cache before run test db rebuild

---

microservices/product-search-export/docker/php-ini-overrides.ini
microservices/product-search/docker/php-ini-overrides.ini
project-base/docker/php-fpm/php-ini-overrides.ini

- "always_populate_raw_post_data = -1" can be removed as we do not support PHP 5.6 anymore
- "upload_max_filesize" and "post_max_size" can be removed from microservices as they do not use file uploads
- "opcache.max_accelerated_files" can be lowered to 20k in microservices as it's the exact value recommended in Symfony docs
- see https://symfony.com/doc/4.1/performance.html
- the value was increased in the main app of Shopsys Framework as the application is rather big
|Fixes issues| having PHP 5.6 mentioned in our recommended php.ini config cast a rather unpleasant light on us :smirk:  …

remove unnecessary configuration from php.ini files

---

packages/framework/src/Component/FileUpload/FileUpload.php

|Description, reason for the PR| When upload of file contains errors, application will faill. UploadFailedException will not be thrown because wrong second parameter expected instance of Exception or null -  integer given. Method getError() of class UploadedFile returns int only.

FileUpload wrong second parameter for UploadFailedException

---

CHANGELOG.md
packages/framework/src/Component/Javascript/Compiler/JsCompiler.php

|Description, reason for the PR| compiling of javascript consumes a lot of memory. It takes over 256 MB during `phing error-pages-generate` on eshop with 5 domains and a lot of javascripts.
|BC breaks| No
|Fixes issues| Yes
I did not update CHANGELOG.md, I did not know link to this futured pull request :( I am demotivated about updating of it twice (befor pull request and after their creating...)

javascript compiling: lower memory consumption

---

docker/conf/docker-compose-mac.yml.dist

docker-compose-mac.yml.dist: added a missing shopsys-framework-microservice-product-search-export-sync
|BC breaks| No

Docker-compose-mac.yml.dist: fix a missing sync external volume

---

docs/introduction/phing-targets.md
project-base/build.xml

|Description, reason for the PR| CSS files are build **from** LESS files, not **into** them

[shopsys] fixed typo in description of "grunt" phing task

---

packages/monorepo-tools/README.md

|Description, reason for the PR| We should be more explicit about the behavior of monorepo-tools in respect to keeping the history intact. GitHub signs all commits made via its web UI (even the init commit during repository creation) by default, so it's likely that people will run into issues at this step. It would be nice to explore the possibility of re-signing the commits (see #435), but until then we should document the current state and the commonly used workaround.
|Fixes issues| fixes #445 

monorepo-tools: add note about splitting signed commits

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md
changelog-linker.yml
composer.json
docs/contributing/guidelines-for-pull-request.md

|Description, reason for the PR| Automate work with CHANGELOG.md
|BC breaks| No
|Fixes issues| [US-4575](https://app.yodiz.com/plan/pages/detail.vz?cid=10273#/us-4575)
**Feedback needed**! [ChangelogLinker](https://github.com/symplify/changeloglinker) is quite fresh package and this is its first live testing on humans. 
So please do report *WTFs* you found and what do you expect to happen. It might have some reason, but it might be also easy to resolve it and improve it.  
<br>
```bash
vendor/bin/changelog-linker dump-merges --in-packages --in-categories --since-id 432 --token XXX …
```

[shopsys] Generate CHANGELOG.md with ChangelogLinker

---

packages/framework/src/Component/Microservice/MicroserviceClient.php

|Description, reason for the PR| the low limits were causing failures of build process as export of products data into elasticsearch can take a while

[shopsys] MicroserviceClient: timeout limits are now less strict

---

packages/framework/src/Twig/FormThemeExtension.php

|Description, reason for the PR| After extending admin controller, forms are rendered in the same fashion as in framework
|BC breaks| No

[framework] Fixed rendering forms in extended admin controller to be as same as in framework

---

packages/framework/src/Command/RouterDebugCommandForDomain.php
packages/framework/src/Command/ServerRunForDomainCommand.php
packages/framework/src/Component/Console/DomainChoiceHandler.php
packages/framework/src/Component/Console/Exception/ConsoleException.php
packages/framework/src/Component/Console/Exception/NoDomainSetException.php

- routes are domain-specific in Shopsys Framework but there is no current domain in console environment
- RouterDebugCommandForDomain extends the original Symfony RouterDebugCommand
- the logic of choosing a domain used in ServerRunForDomain extracted into DomainChoiceHandler for reuse
- the debug:router now asks for domain in interactive mode (or chooses the first domain by default)
|Description, reason for the PR| when trying to dump all routes via `debug:router` command, the execution fails on NoDomainSelectedException
|New feature| Kinda 
|Fixes issues| `debug:router` does not fail

[framework] fixed command "debug:router" by asking for domain

---

microservices/product-search-export/docker/Dockerfile
microservices/product-search/docker/Dockerfile
project-base/docker/php-fpm/Dockerfile

|Description, reason for the PR| Our composer install takes too long because of number of dependencies. hirak/prestisimo package allows paralel installation of dependencies. This cause dramatic improvement of composer install performance
|BC breaks| No
|Fixes issues| #440
I did performance tests of our composer install after few optimalizations.
I tested 4 scenarios and used this process to make sure that installation is clear without any cache:
```
git checkout <branch-name>
docker-compose up -d --build --force-recreate
docker-exec -it shopsys-framework-php-fpm sh
rm -rf vendor/
rm …
```

Require global package hirak/prestisimo in docker images

---

UPGRADE.md
docs/installation/native-installation.md
microservices/product-search-export/.gitignore
microservices/product-search-export/README.md
microservices/product-search-export/composer.json
microservices/product-search-export/config/bundles.php
microservices/product-search-export/docker/Dockerfile
microservices/product-search-export/docker/docker-after-start
microservices/product-search-export/docker/nginx/nginx-site.conf
microservices/product-search-export/docker/nginx/nginx.conf
microservices/product-search/.gitignore
microservices/product-search/README.md
microservices/product-search/composer.json
microservices/product-search/config/bundles.php
microservices/product-search/docker/Dockerfile
microservices/product-search/docker/docker-after-start
microservices/product-search/docker/nginx/nginx-site.conf
microservices/product-search/docker/nginx/nginx.conf
project-base/app/config/parameters.yml.dist
project-base/kubernetes/services/microservice-product-search-export.yml
project-base/kubernetes/services/microservice-product-search.yml

|Description, reason for the PR| Microservices were started by symfony integrated server, this is not a good practice for production environment. This PR adds nginx and starts php-fpm during dockerfile build.
|BC breaks| No

[shopsys] Microservices webserver using nginx + php-fpm

---

UPGRADE.md
project-base/tests/ShopBundle/Acceptance/acceptance.suite.yml

|Description, reason for the PR| since codeception v 2.5.0 `populate` option is checked also during `_loadDump` ([see the code](https://github.com/Codeception/Codeception/blame/2.5.0/src/Codeception/Module/Db.php#L603-L605), [see Populator docs](https://codeception.com/docs/modules/Db#Populator))
|BC breaks| No

[project-base] fixed acceptance tests (loading DB dump)

---

.ci/build_kubernetes.sh
UPGRADE.md
docker/conf/docker-compose-mac.yml.dist
docker/conf/docker-compose-win.yml.dist
docker/conf/docker-compose.yml.dist
project-base/docker/conf/docker-compose-mac.yml.dist
project-base/docker/conf/docker-compose-win.yml.dist
project-base/docker/conf/docker-compose.yml.dist
project-base/docker/php-fpm/Dockerfile
project-base/docker/php-fpm/ci/Dockerfile
project-base/kubernetes/deployments/microservice-product-search-export.yml
project-base/kubernetes/deployments/microservice-product-search.yml
project-base/kubernetes/deployments/webserver-php-fpm.yml

|Description, reason for the PR| Mounting of php.ini using volumes does not apply the changes without manually restarting the php-fpm process. Because of that, the mounting is not used anymore and instead it is added using COPY during Docker image build. That way, if anything changes in php.ini, it is added to the image during build and loaded when the container starts.
|BC breaks| No

[project-base] adding php.ini to image is now done only in dockerfiles

---

UPGRADE.md
composer.json
packages/framework/composer.json
packages/product-feed-google/composer.json
packages/product-feed-heureka-delivery/composer.json
packages/product-feed-heureka/composer.json
packages/product-feed-zbozi/composer.json
project-base/composer.json

|Description, reason for the PR| Use shopsys packages instead of hacking composer.json to speed up installation
|BC breaks| No
|Fixes issues| #421

[shopsys] Use shopsys packages instead of hacking composer.json to speed up installation

---

packages/migrations/src/Command/GetCountOfMigrationsToExecuteCommand.php

|Description, reason for the PR| migration command shopsys:migrations:count is not initialized with migration configuration and some of the methods that depends on validate() method are failing.
|Fixes issues| #469 

[migrations] migration count command is now fixed and initialized with correct configuration

---

packages/framework/src/Model/Feed/DailyFeedCronModule.php
packages/framework/src/Model/Feed/FeedExport.php
packages/framework/src/Model/Feed/FeedExportFactory.php
packages/framework/src/Model/Feed/FeedPathProvider.php
packages/framework/src/Resources/config/services.yml

- feeds are now generated on local filesystem and moved to abstract filesystem after generation is complete
- feeds files are moved also to the abstract filesystem in case that generation of feed is put to sleep and moved back on feed wakeup
|Description, reason for the PR| Generating of feeds was problematic around 50k+ products

[framework] feeds generation now works with performance data

---

packages/framework/src/Component/Setting/Exception/SettingValueTypeNotMatchValueException.php
packages/framework/src/Component/Setting/SettingValue.php
packages/framework/src/Migrations/Version20181008000001.php

|Description, reason for the PR| if the shop is created with build-new phing target, which should be state when there are basic data needed to create new shop, there are some pages that don't work because of inconsistency with the records of SettingsValue table when null value is converted into number 0.
|Fixes issues| #508 [Demoshop_17](https://github.com/shopsys/demoshop/issues/17)

[framework] Records of SettingValues table need to be valid with application

---

UPGRADE.md
docs/index.md
docs/introduction/how-to-set-up-domains-and-locales.md
packages/framework/easy-coding-standard.yml
packages/framework/src/Command/CreateDomainsDataCommand.php
packages/framework/src/Command/CreateDomainsDbFunctionsCommand.php
packages/framework/src/Component/Domain/DomainDataCreator.php
packages/framework/src/DataFixtures/Demo/ProductDataFixtureLoader.php
packages/framework/src/DataFixtures/DemoMultidomain/PricingGroupDataFixture.php
packages/framework/tests/Unit/Component/Domain/DomainDataCreatorTest.php
project-base/build-dev.xml
project-base/build.xml
project-base/tests/ShopBundle/Database/Model/Category/CategoryRepositoryTest.php
project-base/tests/ShopBundle/Database/Model/Product/ProductRepositoryTest.php

- now the CreateDomainsDataCommand creates new default pricing group for every new domain
- for pricing groups that are not filled in demo data, the manual price is set to 0 while importing demo data
- data fixtures of products for single domain are imported in locale according to the domains locale
|Description, reason for the PR| Testing of phing targets for manipulation with domains to confirm consistency database after some modifications of domains. Documenting manipulation with domains for project developers.
|BC breaks| No

[framework] Manipulation with domains is modified and documented now

---

UPGRADE.md

|Description, reason for the PR| Since improving upgrade notes from alpha5 to beta1 there were some upgrade notes left unimproved.
|BC breaks| No

UPGRADE.md: improved unreleased instructions

---

packages/framework/src/Component/Translation/ConstraintViolationExtractor.php
packages/framework/src/Resources/config/services.yml
packages/framework/src/Resources/translations/validators.cs.po
packages/framework/src/Resources/translations/validators.en.po
project-base/src/Shopsys/ShopBundle/Resources/translations/validators.cs.po
project-base/src/Shopsys/ShopBundle/Resources/translations/validators.en.po

|Description, reason for the PR| On constraints with callback missing violation text in translation files
|BC breaks| No
|Fixes issues| #369 
As i promised, i create next constraint extractor, which extracting text from methods `->addViolation()` called to `ExecutionContextInterface`. I will be glad when you check names is okay and please check czech translation, because my czech language in text form is not good 😄
PS: thanks @Miroslav-Stopka for help with docker on windows 10 home (thas was suffering) 😄

[framework] Added translation extractor for custom constraint violation messages

---

UPGRADE.md
docker/conf/docker-compose-mac.yml.dist
docker/conf/docker-compose-win.yml.dist
docker/conf/docker-compose.yml.dist
docs/introduction/shopsys-framework-on-docker.md
project-base/docker/conf/docker-compose-mac.yml.dist
project-base/docker/conf/docker-compose-win.yml.dist
project-base/docker/conf/docker-compose.prod.yml.dist
project-base/docker/conf/docker-compose.yml.dist

|Description, reason for the PR| Links are deprecated in docker and depends_on is not necessary. To keep docker-compose files simple and consistent, deleted `links` and `depends_on` from docker-compose files
|BC breaks| No
|Fixes issues| resolves #505 

[shopsys] Removed depends_on and links from docker-compose.yml files

---

UPGRADE.md
docker/conf/docker-compose-mac.yml.dist
docker/conf/docker-sync.yml.dist
project-base/docker/conf/docker-compose-mac.yml.dist
project-base/docker/conf/docker-sync.yml.dist

|Description, reason for the PR| After enhancements of docker-sync there were some redundant volumes left
|BC breaks| No

[shopsys] Updated docker-sync configuration

---

UPGRADE.md
project-base/build-dev.xml
project-base/build.xml

|Description, reason for the PR| This is a fix of https://github.com/shopsys/shopsys/pull/513/commits/36717a3c75180865c30923e5a58232950418ed7f. In the linked commit, creation of db functions was extracted from `create-domains-data` target but new target was not used in all places where the original target was used

[shopsys] phing targets: create-domains-data is now dependent on create-domains-db-functions

---

UPGRADE.md
build.xml
docs/installation/installation-using-docker-on-production-server.md
packages/framework/src/DependencyInjection/Compiler/LazyRedisCompilerPass.php
packages/framework/src/ShopsysFrameworkBundle.php
project-base/build-dev.xml
project-base/docker/php-fpm/Dockerfile
project-base/docker/php-fpm/docker-php-entrypoint

- phing build targets are added for ci and production targets
- session handler for framework is temporarily overriden during execution of phing targets
|Description, reason for the PR| to have faster deployment on CI and Production we can move some of the phing build targets into the Dockerfile that builds php-fpm image 

[shopsys] Part of the application build is now contained in the build of the image

---

UPGRADE.md
project-base/docker/php-fpm/Dockerfile

|Description, reason for the PR|  After #545 merge, checking of standards vanished from CI build process. The phing target `standards` should be located in the Dockerfile as a part of the image build.

[project-base] Missing standards check in CI build process

---

build.xml
composer.json

- composer.json of monorepo now sets psr-4 autoload for packages/coding-standards/tests
|Description, reason for the PR| The phing target `tests-packages` does not include `coding-standards` package at all even though there are tests in the package :frowning_face: 

monorepo: tests-packages now include tests of coding-standards package

---

docs/introduction/framework-extensibility.md
packages/framework/src/Resources/config/services.yml
packages/framework/src/Resources/views/Admin/Layout/base.html.twig
packages/framework/src/Twig/Javascript/JavascriptCompilerService.php

|Description, reason for the PR| it used to be difficult to add JS to admin instead of rewriting all admin JS
|BC breaks| No

[framework] eased adding JS to admin

---

UPGRADE.md
docker/nginx/nginx.conf
docs/installation/native-installation.md
packages/framework/src/Command/CreateApplicationDirectoriesCommand.php
packages/framework/src/Resources/config/services/commands.yml
project-base/app/config/parameters_test.yml.dist
project-base/app/config/paths.yml
project-base/build-dev.xml
project-base/build.xml
project-base/docker/nginx/nginx.conf
project-base/docker/php-fpm/Dockerfile
project-base/src/Shopsys/ShopBundle/Resources/config/routing_front.yml
project-base/web/.gitignore

web/content-test/ directory is used instead of web/content/ during the tests
|Description, reason for the PR| We observed some strange behavior of the images after smoke tests are finished. Problem was caused because of overriding of content images during the tests or in test environment. This is solved with modification when web/content-test/ directory is used instead of web/content/ during the tests. Similar principle is used for database when shopsys-test database is used in test environment instead of shopsys database
|BC breaks| No
|Fixes issues| #488 

[project-base] content-test directory is used instead of content during the tests

---

UPGRADE.md
project-base/docker/php-fpm/Dockerfile
project-base/kubernetes/deployments/webserver-php-fpm.yml

- this commit just removes an inconsistency between the stages
- previously, the workdir was set to /source-code, so it can be copied into a mounted volume in an init container in Kubernetes
- this can be also achieved by mounting the volume into different directory of the init container (/tmp/source-codes)
- in the final container, the same volume should be of course mounted to its final destination (/var/www/html)
- because the path is not changed, the autoload cache cleaning should not be necessary
|Description, reason for the PR| removal of a hacky solution
|BC breaks| Yes, but only for a CI stage  …

[project-base] php-fpm image has standard workdir (/var/www/html) in ci stage

---

UPGRADE.md
packages/framework/src/Model/Product/ProductFacade.php
packages/framework/src/Model/Product/ProductFactory.php
packages/framework/tests/Unit/Model/Product/ProductVariantServiceTest.php

- `ProductFactory` is now responsible for setting calculated availability to the new product (if necessary)
|Description, reason for the PR| When a developer is trying to create the main variant from a product that has nullable availability, the null value is then propagated to `$calculatedAvailability` attribute of the new product. This is a problem as the property is not nullable - therefore application fails when trying to persist the new product. It was already (hot)fixed in `ProductFacade::create()` but not in `ProductVariantFacade::createVariant()`
|Fixes issues| fixes #189 …

[framework] Product creation: calculated availability is set additionally if necessary

---

UPGRADE.md
project-base/docker/php-fpm/Dockerfile

|Description, reason for the PR| current stable version of docker doesn't allow building targeted stage but it builds stages from top to bottom until targeted stage occurs, so we can speed up build for development target because development target do not need to build images with the source code because all the code is mounted as a volume.

[project-base] Set development docker build target before production and CI targets

---

.github/stale.yml

|Description, reason for the PR| Stalebot closed issues after short period of time. Time for marked as stale prolonged to 4 months and time to close was reduced to 2 months. Stalebot messages updated.

[shopsys] Stale bot for GitHub issues delayed

---

UPGRADE.md
packages/framework/src/Model/Product/ProductOnCurrentDomainFacade.php
project-base/src/Shopsys/ShopBundle/Controller/Front/ProductController.php
project-base/tests/ShopBundle/Functional/Model/Product/ProductOnCurrentDomainFacadeTest.php

Created because of feedback from @Miroslav-Stopka.
I could've keep the original methods annotated with `@deprecated` and triggering an `E_USER_DEPRECATED` error and calling the new method. This would avoid the BC break, but I'm not sure if we wanna do that during beta releases.
|Description, reason for the PR| `ProductDetail` class was removed along with the whole concept of `*Detail` classes during #276, the method names should reflect that for clarity.

[shopsys] ProductOnCurrentDomainFacade: rename getPaginatedProductDetails* methods

---

project-base/docker/conf/docker-compose.prod.yml.dist

|Description, reason for the PR| SMTP server should be restarted after crash on production server

restart smtp server after crash on production

---

UPGRADE.md
project-base/docker/conf/docker-compose.prod.yml.dist

|Description, reason for the PR| Volumes on production are not shared well. Webserver container mounts empty folders, but we need data from php-fpm container.

[project-base] fix folder sharing for production docker-compose

---

.ci/restart_kubernetes.sh

- the error pages are not a part of neither the built Docker images nor build-demo-dev-quick target
- generation takes just 2-4 s so it doesn't delay the task
|Description, reason for the PR| Application does not handle errors correctly when restarted on CI using .ci/restart_kubernetes.sh

[shopsys] generate error pages in restart_kubernetes.sh

---

UPGRADE.md
docs/installation/installation-using-docker-application-setup.md
docs/installation/native-installation.md
docs/introduction/faq-and-common-issues.md
packages/framework/src/Component/Environment/EnvironmentFileSetting.php
project-base/app/Environment.php
project-base/docker/php-fpm/Dockerfile

- "composer install" previously created `PRODUCTION`/`DEVELOPMENT` file only in interactive mode, based on user's input
- now the file is created even in non-interactive mode, base on whether `composer install` or `composer install --no-dev` was called
- the file is still created only if there is no environment file yet
|Description, reason for the PR| current behavior needs user interaction, even when unnecessary (user already used either dev build or production build), also it leads to unspecified environment when installed non-interactively (`prod` is used by default)
|BC breaks| default non-interactive installation changed from `prod` to `dev`  …

[project-base] the environment setting during "composer install" is not interactive

---

docs/wip_glassbox/form-extension.md

|Description, reason for the PR| non-breakable spaces (0xc2a0) were used instead of regular spaces (0x20) thus breaking the formatting<br>*(introduced in 4f3ed87fd4a78a74ce2298cb74bb6da195393c37 and b7b3fd874c9c69753ba1712460721fee48d0c1d7)*
**Before:**
---
**After:**
---
*Check the question [How to disable non-breaking space with altgr+space](https://stackoverflow.com/questions/31383074/how-to-disable-non-breaking-space-with-altgrspace) on StackOverflow to see how to stop introducing 0xc2a0 to the repo by accident.*

[shopsys] form-extension.md: fix formatting of headings (nbsp issue)

---

packages/framework/src/Resources/scripts/admin/components/autocompleteSelectbox.js
packages/framework/src/Resources/scripts/admin/components/view.js

|Description, reason for the PR| in some cases in admin forms when dev env is enabled selectboxes are scrolled under bottom box and last option is hidden for user.
|Fixes issues| resolve #604 
|Standards and tests pass| No

[framework] selectboxes rollout problem for dev env

---

docs/introduction/product-search-via-elasticsearch.md
microservices/product-search-export/src/Resources/definition/1.json
microservices/product-search-export/src/Resources/definition/2.json

You'll need to recreate the structure in Elasticsearch and export the products for the change to take place in production environment (otherwise the issue described in #398 will still occur):
```sh
php phing microservice-product-search-recreate-structure \
microservice-product-search-export-products
```
|Description, reason for the PR| #398
|Fixes issues| closes #398

[microservice-product-search-export] fixed search in EAN, partno, catnum

---

UPGRADE.md
docs/wip_glassbox/form-extension.md
packages/framework/src/Component/Plugin/PluginCrudExtensionFacade.php
packages/framework/src/Form/Admin/Article/ArticleFormType.php
packages/framework/src/Form/Admin/CustomerCommunication/CustomerCommunicationFormType.php
packages/framework/src/Form/Admin/Heureka/HeurekaShopCertificationFormType.php
packages/framework/src/Form/Admin/LegalConditions/LegalConditionsSettingFormType.php
packages/framework/src/Form/Admin/Mail/MailSettingFormType.php
packages/framework/src/Form/Admin/Payment/PaymentFormType.php
packages/framework/src/Form/Admin/Product/Brand/BrandFormType.php
packages/framework/src/Form/Admin/Product/ProductFormType.php
packages/framework/src/Form/Admin/Seo/SeoSettingFormType.php
packages/framework/src/Form/Admin/ShopInfo/ShopInfoSettingFormType.php
packages/framework/src/Form/Admin/Slider/SliderItemFormType.php
packages/framework/src/Form/Admin/Transport/TransportFormType.php
packages/framework/src/Form/FormRenderingConfigurationExtension.php
packages/framework/src/Form/GroupType.php

|Description, reason for the PR| the separators are rendered automatically since #619 was merged and the option hasn't been used anymore
|BC breaks| Yes, but simple to upgrade 

[framework] FormGroup: unused option "is_group_container_to_render_as_the_last_one" removed

---

packages/framework/src/DataFixtures/Demo/SliderItemDataFixture.php

|Description, reason for the PR| Twitter link in our demo data was pointing to the account of Mike Spreeman by mistake (Twitter handle `@shopsys`, unrelated to Shopsys company), instead of https://twitter.com/ShopsysFW. Thanks @PatrikBajer for noticing!<br>(introduced in https://github.com/shopsys/shopsys/commit/94dd01d29ef976c185659718b441642562f27160#diff-0ab370d2228934110df950452854beca)

[framework] fixed link to our Twitter account @ShopsysFW in demo data

---

docs/index.md

|Description, reason for the PR| there was no link to the cookbook

[shopsys] docs: added missing link to Adding an Icon into a Button cookbook

---

UPGRADE.md
project-base/app/Bootstrap.php

- the Kernel boot was done to build DIC so `%trusted_proxies%` parameter is available
- setting trusted proxies is not required when running in console, as there are no Requests involved
- this stops excessive logging in console environment
|Description, reason for the PR| console commands output excessive log messages after #596 was merged
|BC breaks| No, but it's a project-base change, so users will have to replicate it 
|Fixes issues| fixes #658  

[project-base] Bootstrap: do not prematurely boot Kernel when running in console

---

UPGRADE.md

|Description, reason for the PR| When using monorepo, it's required to provide the environment variable `ELASTIC_SEARCH_INDEX_PREFIX` in both microservices to upgrade to #651 as it doesn't have any default value (see [docs](https://symfony.com/blog/new-in-symfony-3-2-runtime-environment-variables)), but there were no upgrade notes for that. Remember, that monorepo upgrade requires no action by default (just following notes in `shopsys/shopsys` section, as [written in the UPGRADE.md](https://github.com/shopsys/shopsys/blob/ph-monorepo-upgrade-note/UPGRADE.md#you-are-using-monorepo)). …

[shopsys] add missing upgrade note for #651 when using monorepo

---

packages/framework/src/Model/Product/ProductOnCurrentDomainFacade.php

Created because of feedback from @Miroslav-Stopka.
Created as a separate PR from #610 as this change is backward compatible.
|Description, reason for the PR| Historically, the reinstantiation was used to convert instances of `Product` to `ProductDetails`, but the concept of `*Detail` classes was removed in #276 (more specifically in 88972833fb0c9e87db14267fcbf29c185b3e0093). There is no need for this and and it just confuses people.

[framework] remove redundant PaginationResult instantiation

---

.dockerignore
UPGRADE.md
project-base/.dockerignore

|Description, reason for the PR| We are trying to create production using Shopsys Framework documentation and nginx configuration files needs to be part of the production image

[project-base] Dockerignore no longer excludes docker/nginx folder

---

UPGRADE.md
project-base/src/Shopsys/ShopBundle/Controller/Front/OrderController.php
project-base/src/Shopsys/ShopBundle/Resources/translations/messages.cs.po
project-base/src/Shopsys/ShopBundle/Resources/translations/messages.en.po

|Description, reason for the PR| When a price of a payment is changed during the ordering process, flash message should be shown, however, there was an undefined variable `transportName` in the message that caused 500 error is such a situation.
|BC breaks| Yes - translatable message ID has changed 

[project-base] fix wrong variable name in flash message

---

packages/framework/src/Form/JsFormValidatorFactory.php
packages/framework/src/Resources/scripts/common/validation/customizeBundle.js

- thanks to @pk16011990 for this fix
- the parent was missing in collections with `allow_add=true` inside `FormFlow`, causing error in the JS validation of newly added fields
- `FormFlow` creates more form instances (eg. because of multiple calls to `Form::submit()` for restoring form data from session in `OrderFlow`)
- `CollectionType` sets parent to prototype in `buildView()` (`buildForm()` creates the prototype, but parent is unknown yet as there is no instance of `Form`, which is the reason for setting it during `buildView()`)
- JS validation in `JsFormValidatorFactory` collects metadata about all forms and fields during request, but multiple instances of `FormFlow` (eg. `OrderFlow`) call `buildView()` only on one instance (in `OrderController`) and `JsFormValidatorFactory` override …

[framework] JsFormValidatorFactory: make sure prototype's parent is set in CollectionType

---

packages/framework/src/Resources/views/Mail/Order/products.html.twig

In my point of view, in Mail/Order/products.html.twig is missing orderLocale variable in formatNumber filter, that formats item.quantity. 
This variable is supplied to all other filters in this template.
Moreover, if you try to submit this email from CLI task, it throws exception due to getCurrentDomainConfig method call.
| Q | A
| -| -
|Standards and tests pass| No

[framework] formatNumber filter supplied with missing orderLocale variable

---

UPGRADE.md
docker/conf/docker-compose-mac.yml.dist
docker/conf/docker-compose-win.yml.dist
docker/conf/docker-compose.yml.dist
project-base/docker/conf/docker-compose-mac.yml.dist
project-base/docker/conf/docker-compose-win.yml.dist
project-base/docker/conf/docker-compose.yml.dist

- all docker-compose files are fixed with depends_on attribute for webserver
- webserver doesn't fail on "host not found in upstream php-fpm:9000"
|Description, reason for the PR| during testing of special jobs there emerged error once per 30 minutes on 32 core CPU and 130GB server that webserver didn't start on error nginx: host not found in upstream php-fpm:9000

[shopsys] webserver container starts after php-fpm is started

---

packages/framework/src/Resources/config/services.yml
project-base/tests/ShopBundle/Functional/Controller/ContainerControllerResolverTest.php
project-base/tests/ShopBundle/Functional/Controller/ProductRenameRedirectPreviousUrlTest.php

- ContainerControllerResolver fetch controllers from the container, therefore it must be a public service
|Description, reason for the PR| Fixes problem with malfunctioning previous URL after product is renamed.
|Fixes issues| closes #677  

[framework] redirectController is now registered as a public container service

---

packages/coding-standards/easy-coding-standard.yml

|Description, reason for the PR| Solves issue with coding standards introduced with 2.13.2 release of FriendsOfPHP/PHP-CS-Fixer 
Following import order is fine and cause no problems with version FriendsOfPHP/PHP-CS-Fixer v2.13.1, but in 2.13.2 (due to FriendsOfPHP/PHP-CS-Fixer#4116) suggest a different sorting (`function` first)
```php
use Symfony\Bundle\FrameworkBundle\Controller\RedirectController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Controller\ContainerControllerResolver;
use …
```

[coding-standards] order of imports and sort algorithm is now explicitly set

---

packages/framework/src/Form/JsFormValidatorFactory.php

It is caused by remove unsafe route `fp_js_form_validator.check_unique_entity` to configuration of js validation.
Replaces #298
|Fixes issues| closes #298 

[framework] Stop generating url for unsafe route 'fp_js_form_validator.check_unique_entity'

---

docs/upgrade/UPGRADE-unreleased.md
packages/framework/src/Form/Admin/Customer/UserFormType.php
packages/framework/src/Form/Constraints/UniqueEmail.php
packages/framework/src/Form/Constraints/UniqueEmailValidator.php
packages/framework/src/Model/Customer/User.php
packages/framework/src/Model/Customer/UserFactory.php
packages/framework/tests/Unit/Model/Customer/CurrentCustomerTest.php
packages/framework/tests/Unit/Model/Customer/CustomerDataFactoryTest.php
packages/framework/tests/Unit/Model/Customer/UserFactoryTest.php
packages/framework/tests/Unit/Model/Customer/UserTest.php
packages/framework/tests/Unit/Model/Product/Pricing/ProductPriceCalculationForUserTest.php
project-base/src/Shopsys/ShopBundle/Model/Customer/User.php
project-base/tests/ShopBundle/Functional/PersonalData/PersonalDataExportXmlTest.php

|Description, reason for the PR| checking for duplicated e-mail was in two places - UserFactory and User entity, now it is only in entity. Fixed UniqueEmail validator in administration.
|Fixes issues| ... closes #661

[framework] refactored checking duplicated e-mail to User constructor

---

build.xml
project-base/build-dev.xml

|Description, reason for the PR| In monorepo PHPStan now checks packages and src as a separate targets to prevent memory exhaustion.
|Fixes issues| closes #704 

[shopsys] Phing: PHPStan analysis of packages is separated into another target

---

composer.json
packages/framework/composer.json
packages/product-feed-google/composer.json
packages/product-feed-heureka-delivery/composer.json
packages/product-feed-heureka/composer.json
packages/product-feed-zbozi/composer.json
project-base/composer.json

|Description, reason for the PR| due to https://github.com/twigphp/Twig/issues/2810 we have to ignore version 2.6.1 of twig/twig package

[shopsys] twig/twig v2.6.1 is now ignored

---

docs/docker/docker-troubleshooting.md
docs/installation/installation-using-docker-application-setup.md

- Debian version with bash is not released yet
- added TODOs for the next release
|Description, reason for the PR| When someone tries to install project-base by the current installation guide, he will encounter an error - `OCI runtime exec failed: exec failed: container_linux.go:344: starting container process caused "exec: \"bash\": executable file not found in $PATH": unknown`

[shopsys] docs: use "sh" instead of "bash" in docker exec commands

---

docs/upgrade/UPGRADE-unreleased.md
project-base/src/Shopsys/ShopBundle/Resources/styles/front/common/layout/layout.less

|Description, reason for the PR| This PR remove blank space at right side of the page when the popup is active. 
|BC breaks| No
|Fixes issues| closes #695 

[project-base] Removed blank space when popup is active

---

.ci/monorepo_force_split_branch.sh
.ci/monorepo_functions.sh
.ci/monorepo_remove_branch.sh
.ci/monorepo_split.sh
docs/introduction/monorepo.md

- basically copy-pasted from our Jenkins configuration so we can change it with the codebase (eg. add a package inside a PR as a modification of `get_all_packages()` in `monorepo_functions.sh` and let it be split automatically after the PR is merged)
- `monorepo_split.sh` splits master into all subrepositories
- should be executed automatically after `master` is successfully built
- `monorepo_force_split_branch.sh` splits and force pushes selected branch into all subrepositories
- should be executed manually as a parameterized build
- `monorepo_remove_branch.sh` removes selected branch from all subrepositories
- should be executed manually as a parameterized build
- cleans up after `monorepo_force_split_branch.sh`
- `monorepo_functions.sh` contains reusable functions
- related to #698 and …

[shopsys] added scripts for monorepo maintenance into /.ci directory

---

composer.json
docs/contributing/upgrading-monorepo.md
docs/installation/native-installation.md
docs/introduction/shopsys-framework-on-docker.md
docs/upgrade/UPGRADE-unreleased.md
microservices/product-search-export/.travis.yml
microservices/product-search-export/docker/Dockerfile
microservices/product-search/docker/Dockerfile
packages/coding-standards/.travis.yml
packages/coding-standards/composer.json
packages/form-types-bundle/.travis.yml
packages/framework/.travis.yml
packages/http-smoke-testing/.travis.yml
packages/migrations/.travis.yml
packages/plugin-interface/.travis.yml
packages/product-feed-google/.travis.yml
packages/product-feed-heureka-delivery/.travis.yml
packages/product-feed-heureka/.travis.yml
packages/product-feed-zbozi/.travis.yml
project-base/docker/php-fpm/Dockerfile

|Description, reason for the PR| Support new version of PHP

[shopsys] Updated PHP to version 7.3

---

microservices/product-search-export/LICENSE-docker-image
microservices/product-search-export/README.md
microservices/product-search/LICENSE-docker-image
microservices/product-search/README.md

|Description, reason for the PR| Docker images can not be distributed under MIT license while containing software licensed under GPL license. Because of that we license images under GPL license while source code stays under MIT license
|BC breaks| No

Microservice images are now licensed under GPL license

---

.ci/monorepo_functions.sh

|Description, reason for the PR| This should be added with #730, so with split of monorepo, our new package google-cloud-bundle will be split too
|BC breaks| No

added missing shopsys/google-cloud-bundle into monorepo split package list

---

docs/index.md
docs/kubernetes/how-to-set-smtp-server-container.md
docs/upgrade/UPGRADE-unreleased.md
project-base/kubernetes/deployments/smtp-server.yml

|Description, reason for the PR| k8s deploy doesn't want to send mails via smtp container because of relay permissions and sending mail for shop is very important thing
|Fixes issues| resolves #537 

[project-base] kubernetes uses relay setting for sending mails

---

docs/kubernetes/continuous-integration-using-kubernetes.md
docs/kubernetes/how-to-set-smtp-server-container.md
docs/kubernetes/logging-on-continuous-integration-server-running-kubernetes.md
docs/upgrade/UPGRADE-unreleased.md

- we don't abbreviate Kuberenetes to k8s (see [Terminology section in Introduction to Kubernetes](https://github.com/shopsys/shopsys/blob/v7.0.0-beta5/docs/kubernetes/introduction-to-kubernetes.md#terminology-of-kubernetes))
- "pod" and "namespace" are just regular words, no need to use code style or capitals
- reworded the *Problem* section in *Logging on Continuous Integration server running Kubernetes* so it makes more sense
|Description, reason for the PR| in #777, there were introduced some inconsistencies in terminology

[shopsys] fixed kubernetes naming

---

docker/conf/docker-compose-win.yml.dist
docker/conf/docker-sync-win.yml.dist
docs/installation/installation-using-docker-windows-10-pro-higher.md

|Description, reason for the PR| seems that web volume is mounted the same way as in project-base so it needs to be corrected and docker-sync volumes for microservices could be used in php-fpm container 

fix and enhance configuration of docker-compose and docker-sync for windows development

---

packages/coding-standards/src/Sniffs/ObjectIsCreatedByFactorySniff.php

|Description, reason for the PR| Shopsys Framework customization is mostly based on class inheritance, it makes sense to allow using classes that extend the original factories for object instantiation
|New feature| Kinda? 
|BC breaks| No (the rule is loosened) 
|Fixes issues| resolves #795 

[coding-standards] ObjectIsCreatedByFactorySniff: allow using descendant factories

---

CHANGELOG.md
changelog-linker.yml
docs/introduction/monorepo.md

|Description, reason for the PR| Added missign references to GoogleCloudBundle that was forgottone during implementation of #730 
|BC breaks| No
|Fixes issues|

[shopsys] added missing references to shopsys/google-cloud-bundle

---

open-source-license-acknowledgements-and-third-party-copyrights.md

**Before:**
**After:**
|Description, reason for the PR| formatting of the 3rd party copyrights (#563) was broken due to missing line breaks

[shopsys] markdown formatting fixes in 3rd party copyrights

---

docs/index.md
docs/introduction/directories.md
docs/upgrade/UPGRADE-unreleased.md
packages/framework/src/Command/CreateApplicationDirectoriesCommand.php
packages/framework/src/DependencyInjection/ShopsysFrameworkExtension.php
packages/framework/src/Resources/config/directories.yml
packages/framework/src/Resources/config/services/commands.yml
project-base/app/AppKernel.php
project-base/app/config/directories.yml

|Description, reason for the PR| Adding a new directory to be created during `shopsys:create-directories` was only able to add by extending `CreateApplicationDirectoriesCommand::CreateMiscellaneousDirectories()`. Because of that there was created `directories.yml` that defines directories and can be easily extended.
|Fixes issues| #349

[framework] Directories created during shopsys:create-directories command are configurable in yml configuration

---

docs/introduction/faq-and-common-issues.md
docs/introduction/how-to-set-up-domains-and-locales.md
docs/upgrade/UPGRADE-unreleased.md
packages/framework/src/Model/Localization/Exception/AdminLocaleNotFoundException.php
packages/framework/src/Model/Localization/Localization.php
packages/framework/src/Resources/config/services.yml
packages/framework/src/Resources/config/services_test.yml

|Description, reason for the PR| Administration locale was possible to change only by inherit Localization class and override method getAdminLocale(). That is too many steps for such an easy change. So now the developer can set parameter `shopsys.admin_locale` to the desired locale. If selected locale is not one of domains registered locales, an exception is thrown because in that case application behaved funny.
|Fixes issues| closes #589 

[framework] now it is possible to set administration locale in parameters

---

packages/coding-standards/src/CsFixer/OrmJoinColumnRequireNullableFixer.php

- according to our Coding Standards (change done via `./phing standards-fix`)
- the violation started to trigger an error after upgrade of "friendsofphp/php-cs-fixer" from 2.14.0 to 2.14.1
- only the closing identifier of heredoc syntax must be on the beginning of a line (see [heredoc docs](http://php.net/manual/en/language.types.string.php#language.types.string.syntax.heredoc))
|Description, reason for the PR| CS check of coding-standards repository failed

[coding-standards] fix whitespace before method argument

---

docs/upgrade/UPGRADE-unreleased.md
project-base/build.xml

- The `ErrorPagesFacade::generateAllErrorPagesForProduction()` method uses production DIC for generating the pages.
- After #788 was merged, generating the cache for production consumes more memory (because protected and public methods of services are inspected using reflection).
- When the production cache was not generated, `./phing error-pages-generate` started to fail on memory usage.
- Phing targets with specified environment are prefixed with the environemnt (see `test-*` targets), that's why the new target is named `prod-warmup`.
|Description, reason for the PR| Execution of `./phing error-pages-generate` fails on memory limit. …

[project-base] warm up production cache before generating error pages

---

docs/upgrade/UPGRADE-unreleased.md
project-base/src/Shopsys/ShopBundle/Resources/scripts/frontend/promoCode.js

|Description, reason for the PR| Implemented reload function after the promo code is set as a fix of npm upgrade implementation in #755 
|BC breaks| No

[project-base] Reload page after promocode is set

---

docs/installation/installation-using-docker-linux.md
docs/installation/installation-using-docker-macos.md
docs/installation/installation-using-docker-on-production-server.md
docs/installation/installation-using-docker-windows-10-pro-higher.md
utils/releaser/src/FileManipulator/InstallationGuideFileManipulator.php
utils/releaser/src/FilesProvider/InstallationGuideFilesProvider.php
utils/releaser/src/ReleaseWorker/AfterRelease/SetUnreleasedNoteInInstallationGuidesReleaseWorker.php
utils/releaser/src/ReleaseWorker/ReleaseCandidate/SetReleasedVersionNoteInInstallationGuidesReleaseWorker.php

|Description, reason for the PR| On Github, the installation guide version is not clear at a first sight
|Fixes issues| closes #794 

[shopsys] added warnings about version to installation guides

---

build.xml
composer.json
docs/upgrade/UPGRADE-unreleased.md
packages/framework/composer.json
packages/framework/src/Component/Translation/ConstraintViolationExtractor.php
packages/framework/src/Twig/Exception/HoneyPotRenderedBeforePasswordException.php
packages/framework/tests/Unit/Component/Translation/ConstraintViolationExtractorTest.php
packages/framework/tests/Unit/Component/Translation/Resources/ConstraintViolationClass.php
packages/framework/tests/Unit/Model/Security/AuthenticatorTest.php
project-base/composer.json
project-base/phpstan.neon
project-base/tests/ShopBundle/Functional/Component/Grid/Ordering/GridOrderingFacadeTest.php

|Description, reason for the PR| Updated PHPStan due to old version and persistent travis build fails.
This PR contains 5 almost independent commits, but they all changes needs to be applied before update of PHPStan is even possible and creating separate pull requests only raise the difficulty of update.
- new version of PHPStan reveal incorrect letter case in stdClass
- new version of PHPStan reveal different placeholders and values count
- due to update of nikic/php-parser I added test for …

[shopsys] phpstan updated and resolved dependencies

---

composer.json
docs/upgrade/UPGRADE-unreleased.md
packages/framework/composer.json
project-base/composer.json

|Description, reason for the PR| When installing project-base there was version conflict in snc/redis-bundle introduced in #815. #549 was resolved also as there should not be reason not to have ^ version constraint.
|[BC breaks](/docs/contributing/backward-compatibility-promise.md)| Yes 
|Fixes issues| closes #549 

[shopsys] fixed project-base install conflict due to snc/redis-bundle version

---

docs/upgrade/UPGRADE-unreleased.md
packages/framework/src/Resources/scripts/common/validation/customizeBundle.js
packages/framework/src/Resources/translations/messages.cs.po
packages/framework/src/Resources/translations/messages.en.po
project-base/src/Shopsys/ShopBundle/Controller/Front/LoginController.php
project-base/src/Shopsys/ShopBundle/Resources/config/routing_front.yml
project-base/src/Shopsys/ShopBundle/Resources/scripts/frontend/login.js
project-base/src/Shopsys/ShopBundle/Resources/scripts/frontend/window.js
project-base/src/Shopsys/ShopBundle/Resources/styles/front/common/components/box/login.less
project-base/src/Shopsys/ShopBundle/Resources/translations/messages.cs.po
project-base/src/Shopsys/ShopBundle/Resources/translations/messages.en.po
project-base/src/Shopsys/ShopBundle/Resources/views/Front/Content/Login/loginForm.html.twig
project-base/src/Shopsys/ShopBundle/Resources/views/Front/Content/Login/windowForm.html.twig
project-base/src/Shopsys/ShopBundle/Resources/views/Front/Layout/header.html.twig

|Description, reason for the PR| JS validation doesn't work with forms in popups, because it closes the original popup to show errors
|Fixes issues| closes #361  
|Standards and tests pass| No
When solving #361 I found out that there are 3 problems, that should be solved.
1. We don't have any form in popup with working JS validation
Solution: I changed login form in popup so it is loaded by AJAX and therefore works with JS validation
2. JS validation opens popup with error messages that closes popup with form
Solution: I Added hidden div to popup and changed `showFormErrorsWindow` function in a way …

[shopsys] change forms in popup so they work with js validation

---

docs/cookbook/working-with-multiple-cron-instances.md
docs/index.md
docs/introduction/console-commands-for-application-management-phing-targets.md
docs/introduction/cron.md
packages/framework/src/Command/CronCommand.php
packages/framework/src/Component/Cron/Config/CronConfig.php
packages/framework/src/Component/Cron/Config/CronModuleConfig.php
packages/framework/src/Component/Cron/CronFacade.php
packages/framework/src/Component/Cron/MutexFactory.php
packages/framework/src/DependencyInjection/Compiler/RegisterCronModulesCompilerPass.php
packages/framework/tests/Unit/Component/Cron/CronFacadeTest.php

|Description, reason for the PR| Cron services now can be tagged with `instanceName` tag and then a cron command runner can run only cron with specific instanceName. This is a way how to run, for example, lots of transfers from/into ERP systems and do not block other quicker cron jobs from running.
|Fixes issues| closes #356 

[framework] now it is possible to run multiple cron commands

---

docs/upgrade/UPGRADE-unreleased.md
packages/framework/src/Model/Cart/CartFacade.php
project-base/tests/ShopBundle/Functional/Model/Cart/CartFacadeTest.php

|Description, reason for the PR| Log in as user with only not-listable products in cart (products that are no longer available for any reason) caused exception. This is fixed in this PR. More informations can be found in #842.
|Fixes issues| closes #842  
During consultation with @vitek-rostislav, we thought the changes will be made in `CartWatcherFacade`, but after some prototyping, I've decided to update `CartFacade` instead.
I need to delete Cart from the database and doing it in `CartWatcherFacade` would mean …

[framework] fixed empty cart when no listable product left in cart

---

.github/PULL_REQUEST_TEMPLATE.md

- in PR description the link was relative to github.com, not the repository root
- that meant the link was directed to https://github.com/docs/contributing/backward-compatibility-promise.md instead of https://github.com/shopsys/shopsys/blob/master/docs/contributing/backward-compatibility-promise.md
- see the link *BC breaks* in the table below (not fixed yet as the fix is not merged)
|Description, reason for the PR| Link in all PR descriptions created after #800 was merged returned 404

[shopsys] make link to BC promise absolute in PR template

---

docs/introduction/translations.md
docs/upgrade/UPGRADE-unreleased.md
packages/framework/src/Resources/translations/messages.cs.po
packages/framework/src/Resources/translations/validators.cs.po
project-base/src/Shopsys/ShopBundle/Controller/Front/PromoCodeController.php
project-base/src/Shopsys/ShopBundle/Resources/scripts/frontend/promoCode.js
project-base/src/Shopsys/ShopBundle/Resources/translations/messages.cs.po
project-base/src/Shopsys/ShopBundle/Resources/translations/messages.en.po
project-base/src/Shopsys/ShopBundle/Resources/views/Front/Content/Order/PromoCode/index.html.twig

- discount code keywords were renamed into promo code
- translations were fixed
- documentation was fixed
|Description, reason for the PR| project should contain unified naming of the entities and their usages
|[BC breaks](/docs/contributing/backward-compatibility-promise.md)| Yes 
|Fixes issues| resolves #786 

naming of promo code and discount code is unified

---

docs/upgrade/UPGRADE-unreleased.md
packages/framework/src/Component/Image/ImageFacade.php

|Description, reason for the PR| ImageFacade::copyImages is used during creation of the main variant from nonVariant product and all images need to be copied into newly created entity and there was bug when first step of copying copied files into cache on external filesystem instead into local one so the second step could use it and copied it back with the new filenames for newly created entities
|Fixes issues| resolves #686   

flysystem for ImageFacade::copyImages and FileUpload::postFlushEntity is unified

---

docs/upgrade/UPGRADE-unreleased.md
packages/framework/src/Component/Image/ImageFacade.php
packages/framework/src/Component/Image/ImageFactory.php
packages/framework/src/Component/Image/ImageFactoryInterface.php
packages/framework/src/Component/Image/Processing/ImageProcessor.php

|Description, reason for the PR| weird behavior of file uploads (see #863), also renaming from jpeg to jpg was not working
|Fixes issues| closes #863 

[framework] fixed files uploading

---

docs/contributing/releasing-a-new-version-of-shopsys-framework.md

|Description, reason for the PR| the success message is not confusing anymore (fixed by https://github.com/Symplify/Symplify/pull/1323)

[shopsys] releaser docs: removed note about confusing message

---

packages/framework/composer.json

- otherwise the helper classes cannot be used in unit tests in projects depending on `shopsys/framework` (as [autoload-dev is root-only](https://getcomposer.org/doc/04-schema.md#autoload-dev))
- the namespace currently contains only 2 classes (`IsMoneyEqual` and `MoneyExporter`)
- a cleaner solution (that does not pollute autoload rules for production build) would be to extract the namespace into its own package (eg. `shopsys/unit-testing`) and use it inside `require-dev` (similarly to `shopsys/http-smoke-testing`)
|Description, reason for the PR| Unit tests of packages using shopsys/framework as a dependency cannot use `IsMoneyEqual` constraint
|[BC breaks](https://github.com/shopsys/shopsys/blob/master/docs/contributing/backward …

[framework] autoload helper classes from Tests\FrameworkBundle\Test namespace

---

packages/framework/src/Model/Article/Article.php

Fixed var annotation in Article::$hidden, colum is boolean and variable appears to be string.

[framework] Fix typo, $hidden is boolean, not string

---

docs/contributing/coding-standards.md
docs/upgrade/UPGRADE-unreleased.md
packages/coding-standards/easy-coding-standard.yml
packages/coding-standards/src/Sniffs/ForbiddenDoctrineInheritanceSniff.php
packages/coding-standards/tests/Unit/Sniffs/ForbiddenDoctrineInheritanceSniff/Correct/ClassWithoutComment.php
packages/coding-standards/tests/Unit/Sniffs/ForbiddenDoctrineInheritanceSniff/Correct/EntityWithoutInheritanceMapping.php
packages/coding-standards/tests/Unit/Sniffs/ForbiddenDoctrineInheritanceSniff/Correct/fileWithoutClass.php
packages/coding-standards/tests/Unit/Sniffs/ForbiddenDoctrineInheritanceSniff/ForbiddenDoctrineInheritanceSniffTest.php
packages/coding-standards/tests/Unit/Sniffs/ForbiddenDoctrineInheritanceSniff/Wrong/ClassWithFullNamespaceInheritanceMapping.php
packages/coding-standards/tests/Unit/Sniffs/ForbiddenDoctrineInheritanceSniff/Wrong/EntityWithOrmInheritanceMapping.php
packages/coding-standards/tests/Unit/Sniffs/ForbiddenDoctrineInheritanceSniff/config.yml
project-base/easy-coding-standard.yml

|Description, reason for the PR| We have a rule that forbids Doctrine inheritance and now we have a sniff that checks it
|Fixes issues|

[coding-standards] sniff that forbids Doctrine Inheritance mapping

---

docs/upgrade/UPGRADE-unreleased.md
packages/framework/src/Component/Redis/RedisFacade.php
project-base/app/config/packages/test/snc_redis.yml
project-base/tests/ShopBundle/Functional/Component/Redis/RedisFacadeTest.php

|Description, reason for the PR| #767 
|Fixes issues| resolves #767

[framework] cleaning empty Redis cache doesn't cause an error anymore

---

composer.json
packages/coding-standards/composer.json

|Description, reason for the PR| https://travis-ci.org/shopsys/coding-standards/jobs/501932502 & https://travis-ci.org/Symplify/CodingStandard/builds/501418213

[coding-standards] marked symplify/better-phpdoc-parser in version >=5.4.14 as conflicting

---

docs/contributing/coding-standards.md
docs/cookbook/basic-data-import.md
docs/index.md
docs/introduction/entities.md
docs/introduction/framework-extensibility.md
docs/introduction/how-to-work-with-money.md
docs/upgrade/UPGRADE-v7.0.0.md
docs/upgrade/money-class.md

In this PR, we're adding documentation and upgrade notes related to the `Money` object (#821).
|Description, reason for the PR| PR for easier review and management of #821

[shopsys] new class for representing monetary values PHASE 6

---

packages/framework/src/Resources/styles/admin/libs/selectize/selectize-custom.less

|Description, reason for the PR| Select boxes have adaptive width. This can be applied to very long text in the select box.
|Fixes issues| closes #862

[framework] Set adaptive width to selectboxes created by selectize

---

docs/upgrade/UPGRADE-unreleased.md
project-base/src/Shopsys/ShopBundle/Form/Front/Registration/RegistrationFormType.php
project-base/src/Shopsys/ShopBundle/Resources/translations/validators.cs.po
project-base/src/Shopsys/ShopBundle/Resources/translations/validators.en.po
project-base/tests/ShopBundle/Acceptance/acceptance/CustomerRegistrationCest.php

- validation message was changed to not use e-mail value because long e-mails were cut from the popup message
|Description, reason for the PR| during registration of customer if customer want to create account with already registered mail the validation message print also input value and the long mails are cut of in the design so we decided to not use input value into validation message
|Fixes issues| #832 

[project-base] overflow of long e-mail for unique e-mail validation

---

docs/upgrade/UPGRADE-unreleased.md
packages/framework/src/Form/JsFormValidatorFactory.php
project-base/src/Shopsys/ShopBundle/Form/Front/Product/ProductFilterFormType.php

|Description, reason for the PR| Javascript validation throws error when you have ChoiceType with checkboxes
|Fixes issues| #374  

[shopsys] fix error in javascript validation of ChoiceType

---

CHANGELOG.md
docs/contributing/releasing-a-new-version-of-shopsys-framework.md
docs/introduction/monorepo.md
docs/introduction/product-search-via-elasticsearch.md
packages/framework/src/Command/ServerRunWithCustomRouterCommand.php
packages/framework/src/Command/ServerStartWithCustomRouterCommand.php
packages/framework/src/Model/Customer/CustomerIdentifierFactory.php
packages/framework/src/Resources/translations/messages.en.po
packages/framework/src/Resources/views/Admin/Content/Superadmin/cssDocumentation.html.twig

|Description, reason for the PR| We're using American spelling, not British, but there were occurrences of *behaviour* and *colour*. Fixed in all comments, markdown and translation messages.
|[BC breaks](https://github.com/shopsys/shopsys/blob/master/docs/contributing/backward-compatibility-promise.md)| No (only the English translation was changed, not the message ID) 

[shopsys] consistent spelling: behavior, color

---

docs/upgrade/UPGRADE-unreleased.md
project-base/src/Shopsys/ShopBundle/DataFixtures/Performance/CategoryDataFixture.php

- the numbers in the array `$categoryCountsByLevel` define how many categories should be created on each level
- private method `recursivelyCountCategoriesInCategoryTree` should be used instead of `array_sum`
- error introduced in 25d65995199621f960107ac2d1dc80a79f5e719e when the `ProgressBarFactory` class was created
|Description, reason for the PR| progress bar for performance data of categories wasn't working

[project-base] Performance\CategoryDataFixture: fix maximum count in progress bar

---

packages/framework/src/Resources/config/services_test.yml

`FeedRegistry` service is public in test environment now
It would be best if we wouldn't have to make every service that is taken from DIC in tests public. These copy-pasted service definitions can cause a lot of trouble. Either stop using the container directly (can we autowire services in integration tests?), or have all services public in test env by default (maybe via a compiler pass?)...
|Description, reason for the PR| Having the service private causes an error during the execution of `tests-performance` phing target. It is taken from the DIC directly in `AllFeedsTest::getAllFeedGenerationData`.
|Fixes …

[framework] fix missing service in performance tests of feeds

---

docs/upgrade/UPGRADE-unreleased.md
project-base/app/config/packages/snc_redis.yml
project-base/app/config/packages/test/snc_redis.yml

|Description, reason for the PR| Redis prefixes should use standard format that is described here https://redis.io/topics/data-types-intro

[project-base] Use redis standard prefix delimiter

---

.ci/build_kubernetes.sh

|Description, reason for the PR| Kubernetes CI build script was building test database twice. This PR remove useless phing target test-db-demo that is called in checks-ci target

[shopsys] Remove duplication test database build in kubernetes ci script

---

docs/cookbook/adding-new-attribute-to-an-entity.md
project-base/src/Shopsys/ShopBundle/Model/Article/Article.php
project-base/src/Shopsys/ShopBundle/Model/Article/ArticleData.php

|Description, reason for the PR| When adding a new attribute to an entity or a data object, developers should call the parent methods first, and then add the extended code so it has the final say. This should avoid unexpected behavior if there were some manipulations with the given attribute in the parent class.

[shopsys] demonstrational extended code in project-base should have the final say over the parent method calls

---

docs/introduction/console-commands-for-application-management-phing-targets.md
docs/introduction/running-acceptance-tests.md
docs/upgrade/UPGRADE-v8.0.0.md
packages/framework/src/Resources/config/services_test.yml
project-base/build-dev.xml

|Description, reason for the PR| Tests do not export data to elasticsearch. That would be problem if i have some products changed. This PR supports export products to elasticsearch with his own index for tests.
|Fixes issues| closes #865, closes #866 

[shopsys] phing target test-db-demo now exports products into elasticsearch with different index

---

packages/framework/src/Resources/config/services.yml

|Description, reason for the PR| Fake exception that is used for generating error pages is written to logs and it shouldn't be
After you run `php bin/console shopsys:cron --module="Shopsys\FrameworkBundle\Component\Error\ErrorPageCronModule"` in `PRODUCTION` mode, then is logged exeption: 
```
request.CRITICAL: Uncaught PHP Exception Shopsys\FrameworkBundle\Component\Error\Exception\FakeHttpException: "" at …
```

[framework] cron: Error page: don't log fake exception after generate error page

---

docs/installation/installation-using-docker-linux.md
docs/installation/installation-using-docker-macos.md
docs/installation/installation-using-docker-windows-10-pro-higher.md

|Description, reason for the PR| Composer requires version of PHP 7.1 or newer when creating project

required version of PHP is mentioned in installation guides

---

utils/releaser/src/ReleaseWorker/ReleaseCandidate/UpdateChangelogReleaseWorker.php

- only merged PRs that actually target this version should be mentioned in the changelog
- the automated tool mentions all merged PRs so they have to be deleted manually
|Description, reason for the PR| when releasing a new version you must not forget to remove changes that were merged into other branches

[shopsys] UpdateChangelogReleaseWorker: add note about PR targets

---

docs/upgrade/UPGRADE-unreleased.md
packages/framework/src/Component/FileUpload/FileUpload.php
packages/framework/src/Component/Image/ImageFacade.php
packages/framework/src/Component/String/TransformString.php
packages/framework/src/Model/Feed/FeedExport.php
packages/framework/src/Model/Sitemap/SitemapDumper.php
project-base/src/Shopsys/ShopBundle/DataFixtures/Demo/ImageDataFixture.php

|Description, reason for the PR| methods of flysystem should not use absolute paths. Absolute path should be set in the process of creating the adapter. The problem that occurs for example windows file system uses drive letters and LocalAdapter needs to be initialised with path like `/` or `C:\` but if there is used absolute path like `C:\data\project-base\var\cache` via `LocalAdapter::has` method or others there is appended `/C:\data\project-base\var\cache` or 'C:\C:\data\project-base\var\cache' and used fopen function so the path is not correctly generated.
|Fixes issues| resolves #913 
|Standards and tests …

absolute paths used via local filesystem flysystem now uses paths without drive letters

---

docs/contributing/backward-compatibility-promise.md

|Description, reason for the PR| We are well past the 7.0.0 release so there is no reason for further keeping this note. Also, we are still extending and refining the promise, so saying that it is effective since 7.0.0 may be even misleading in the future.

[shopsys] obsolete note in BC promise removed

---

packages/framework/src/Component/HttpFoundation/ResponseListener.php

|Description, reason for the PR| we are proud of our work and we want to know who use shopsys framework

[framework] added x-powered-by to response headers

---

docs/upgrade/UPGRADE-unreleased.md
project-base/build-dev.xml

|Description, reason for the PR| There were no translations extracted from overwritten templates
|New feature|No 

[project-base] fixed: translations are now extracted also from overwritten templates in `app/Resources`

---

composer.json
docs/cookbook/adding-new-attribute-to-an-entity.md
docs/extensibility/form-extension.md
docs/upgrade/UPGRADE-unreleased.md
packages/framework/composer.json
packages/framework/src/Form/Admin/Payment/PaymentFormType.php
packages/framework/src/Form/Admin/Transport/TransportFormType.php
packages/framework/src/Resources/config/services.yml
packages/framework/src/Resources/config/services/forms.yml
project-base/tests/ShopBundle/Functional/Form/PositionExtensionTest.php

|Description, reason for the PR| If i wanted to change order of form fields in administration after i extended form i wasn't able to do it easily. With this feature it takes less time and i do not need render form manually.

fields in forms can be ordered

---

docs/contributing/guidelines-for-pull-request.md

|Description, reason for the PR| Contributors should be aware of our process when creating a PR that contains a BC break.

[shopsys] guidelines-for-pull-request.md: added note about branch targeting

---

docs/upgrade/UPGRADE-unreleased.md
packages/framework/tests/Unit/Component/DataFixture/PersistentReferenceFacadeTest.php
packages/framework/tests/Unit/Component/Domain/DomainSubscriberTest.php
packages/framework/tests/Unit/Component/Domain/DomainTest.php
packages/framework/tests/Unit/Component/Form/FormTimeProviderTest.php
packages/framework/tests/Unit/Component/Grid/GridTest.php
packages/framework/tests/Unit/Component/HttpFoundation/FragmentHandlerTest.php
packages/framework/tests/Unit/Component/HttpFoundation/SubRequestListenerTest.php
packages/framework/tests/Unit/Model/Payment/PaymentPriceCalculationTest.php
packages/framework/tests/Unit/Model/Pricing/BasePriceCalculationTest.php
packages/framework/tests/Unit/Model/Pricing/PriceCalculationTest.php
packages/framework/tests/Unit/Model/Pricing/RoundingTest.php
packages/framework/tests/Unit/Model/Pricing/Vat/VatFacadeTest.php
packages/framework/tests/Unit/Model/Product/Availability/ProductAvailabilityRecalculatorTest.php
packages/framework/tests/Unit/Model/Product/Pricing/ProductPriceCalculationTest.php
packages/framework/tests/Unit/Model/Product/Pricing/ProductPriceRecalculatorTest.php
packages/framework/tests/Unit/Model/Security/AuthenticatorTest.php
packages/framework/tests/Unit/Model/Security/LoginListenerTest.php
packages/framework/tests/Unit/Model/Transport/TransportPriceCalculationTest.php
project-base/tests/ShopBundle/Functional/Model/Order/Preview/OrderPreviewCalculationTest.php
project-base/tests/ShopBundle/Functional/Model/Product/Availability/ProductAvailabilityCalculationTest.php
project-base/tests/ShopBundle/Functional/Twig/PriceExtensionTest.php

|Description, reason for the PR| remove wrong annotations and use smarter method in tests
|[BC breaks](https://github.com/shopsys/shopsys/blob/master/docs/contributing/backward-compatibility-promise.md)| I hope that No 
|Fixes issues| nope 
Sorry, I didnt update UPGRADE.md...

Tests refactoring - remove wrong annotations and use shorter way of writing return value

---

docker/nginx/nginx.conf
docs/upgrade/UPGRADE-unreleased.md
project-base/docker/nginx/google-cloud/nginx.conf
project-base/docker/nginx/nginx.conf
project-base/kubernetes/ingress.yml

|Description, reason for the PR| Default limit of client_max_body_size that affects uploaded files in Nginx is 1MB. In php-ini-overrides.ini is limit set to 32MB. Default file size in administration is set to 2MB. We want to have services configured the same by default to 32MB and for appliacation configuration in administration forms we will keep limit of 2MB.

[shopsys] nginx has now same limit for file size as is set in php.ini

---

docs/introduction/using-form-types.md
packages/framework/src/Component/Plugin/PluginCrudExtensionFacade.php
packages/framework/src/Form/Admin/Category/CategoryFormType.php
packages/framework/src/Form/Admin/Product/ProductFormType.php
packages/framework/src/Form/FormRenderingConfigurationExtension.php

|Description, reason for the PR| There was no dividing line between new Group added at the bottom of the form and plugin extensions. This PR simplifies the from structure which helps with the rendering of the separators.
This PR also deprecates the option `is_plugin_data_group` as it is no longer used and can be removed in the next major version.

[framework] fixed wrong behaviour while extending ProductFormType and CategoryFormType

---

UPGRADE.md
docs/contributing/guidelines-for-writing-upgrade.md
docs/upgrade/UPGRADE-unreleased.md
docs/upgrade/UPGRADE-v7.0.0-alpha5.md
docs/upgrade/UPGRADE-v7.0.0-alpha6.md
docs/upgrade/UPGRADE-v7.0.0-beta1.md
docs/upgrade/UPGRADE-v7.0.0-beta2.md
docs/upgrade/UPGRADE-v7.0.0-beta3.md
docs/upgrade/UPGRADE-v7.0.0-beta4.md
docs/upgrade/UPGRADE-v7.0.0-beta5.md
docs/upgrade/UPGRADE-v7.0.0-beta6.md
docs/upgrade/UPGRADE-v7.0.0.md
docs/upgrade/UPGRADE-v7.1.0.md

|Description, reason for the PR| Upgrading to each minor version should be achievable without any additional steps so all upgrading instructions are somewhat optional. Therefore, using "low priority" tag is useless, confusing for project developers and the discussions about using this tag for particular upgrading notes are a burden for the developers of the framework itself. 

upgrading notes: "low prioity" tag is not used anymore (after the stable release)

---

docs/upgrade/UPGRADE-unreleased.md
packages/framework/src/Component/Doctrine/Cache/FallbackCacheFactory.php
packages/framework/src/Resources/config/services.yml
packages/framework/src/Resources/config/services_test.yml
project-base/app/config/packages/dev/doctrine.yml
project-base/app/config/packages/doctrine.yml
project-base/app/config/packages/framework.yml
project-base/app/config/packages/snc_redis.yml
project-base/app/config/packages/test/doctrine.yml

|Description, reason for the PR| Moving doctrine and framework cache to redis storage will increase performance.

[shopsys] use redis for doctrine and framework cache

---

docs/introduction/faq-and-common-issues.md
docs/introduction/how-to-set-up-domains-and-locales.md
docs/upgrade/UPGRADE-v7.0.0-beta6.md

|Description, reason for the PR| In documentation, we advised to change admin locale (the language of the administration) in a `parameters.yml` configuration file. This file should be used for environment dependent configurations as database credentials, Redis host, etc. `parameters.yml` file is ignored by git resulting in the need for every developer to set the locale itself. It makes more sense to have the language set in `parameters_common.yml` file, as usually is no need to have the administration in a different language in production and on (for example) a developer machine.
|Standards and …

[docs] admin locale is now recommended to be changed in parameters_common.yml

---

docker/conf/docker-compose-mac.yml.dist
docker/conf/docker-compose-win.yml.dist
docker/conf/docker-compose.yml.dist
docs/upgrade/UPGRADE-unreleased.md
project-base/docker/conf/docker-compose-mac.yml.dist
project-base/docker/conf/docker-compose-win.yml.dist
project-base/docker/conf/docker-compose.yml.dist
project-base/kubernetes/deployments/postgres.yml

- solution found in https://github.com/docker-library/postgres/issues/105
|Description, reason for the PR| I found out, that changing configuration in postgresql.conf and restarting container had no effect. After some searching I found this solution that repair that problem.

[shopsys] postgresql.conf is now used by Postgres

---

packages/framework/src/Model/Administrator/Security/AdministratorUserProvider.php

|Description, reason for the PR| don't log inactive administrator logout
If admin is inactive for a certain time (https://github.com/shopsys/shopsys/blob/master/packages/framework/src/Model/Administrator/Security/AdministratorUserProvider.php#L79) and he reload page, then is logged error message:
```
[2019-04-17 10:37:55] security.WARNING: Username could not be found in the selected user provider. …
```

[framework] don't log administrator was disconnected because admin was too long inactive

---

docs/upgrade/UPGRADE-unreleased.md
project-base/src/Shopsys/ShopBundle/Controller/Front/ErrorController.php

error now tells you about active TEST environment which overwrites
domain url
|Description, reason for the PR| Having active TEST environment is not obvious when having `UnableToResolveDomainResponse`
|BC breaks| No
|Fixes issues|

[project-base] be more descriptive about UnableToResolveDomainResponse

---

packages/coding-standards/src/Helper/PhpToDocTypeTransformer.php

|Description, reason for the PR| after update of `friendsofphp/php-cs-fixer` to patch version 2.14.3 there were many changes https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/tag/v2.14.3 and one of them was change in  `\PhpCsFixer\Tokenizer\Analyzer\Analysis\TypeAnalysis` so we need to fix our `CodingStandards\Helper\PhpToDocTypeTransformer` so nullable docblock can be generated from typehint ?(int,string,bool) and since we have caret notation `"friendsofphp/php-cs-fixer": "^2.14.0"` this will be compatible with previous version. …

[coding-standards] helper PhpToDocTypeTransformer is updated for use with new version of phpcs-fixer package

---

packages/framework/src/Component/Router/CurrentDomainRouter.php
packages/framework/src/Component/Router/DomainRouterFactory.php
packages/framework/src/Resources/config/services.yml
packages/framework/tests/Unit/Component/Router/DomainRouterFactoryTest.php

|Description, reason for the PR| Previously for domain-specific front route with ajax condition and POST method, the 404 exception was thrown, even if the route should be matched. This is fixed now.
**If I declare route in routing_%locale%.yml:**
```
front_contact_form_send:
path: /contactForm/
defaults: { _controller: ShopsysShopBundle:Front\ContactForm:send }
methods: [POST]
condition: "request.isXmlHttpRequest()"
```
This route not found in …

[framework] Current domain router match route for POST and ajax condition

---

docker/conf/docker-compose-mac.yml.dist
docker/conf/docker-compose-win.yml.dist
docker/conf/docker-compose.yml.dist
docs/upgrade/UPGRADE-unreleased.md
project-base/docker/conf/docker-compose-mac.yml.dist
project-base/docker/conf/docker-compose-win.yml.dist
project-base/docker/conf/docker-compose.yml.dist
project-base/kubernetes/deployments/postgres.yml

|Description, reason for the PR| In #946, Docker command for the Postgres container were changed and the entrypoint call was included as well. This leads to duplicate call of the entrypoint which can lead to unforeseen consequences. See [the upstream Dockerfile](https://github.com/docker-library/postgres/blob/master/10/Dockerfile#L173-L176) to verify that only `postgres` command should be listed as the container's command.
**Links to docs:**
- …

[shopsys] remove duplicate entrypoint call in commands in postgres container

---

docs/contributing/upgrading-monorepo.md

|Description, reason for the PR| In #946 monorepo `docker-compose.yml` templates were changed, but the monorepo upgrade note was missing.This could lead to contributors not using the Postgres configuration after the upgrade to current `master`,

[shopsys] add missing upgrade instruction for monorepo

---

docs/upgrade/UPGRADE-unreleased.md
project-base/build-dev.xml

|Description, reason for the PR| during native installation generalization we encountered that ecs-fix from project-base does not fix ShopBundle/Tests namespace so it was added into project-base/build-dev.xml

[project-base] ecs-fix phing target fixes result of ecs phing target

---

packages/framework/src/Command/CreateDatabaseCommand.php
packages/framework/src/Model/Localization/Localization.php

|Description, reason for the PR| According to https://www.2ndquadrant.com/en/blog/icu-support-postgresql-10/, it is much more better to use ICU collations. These colllations are always available, not like ones we are using now. Also for example, for current collations letter "Ú" is sorted behind letter "Z"

[framework] used ICU collations to assure correct sorting throughout OSs

---

docs/contributing/upgrading-monorepo.md
docs/installation/application-configuration.md
docs/upgrade/UPGRADE-unreleased.md
project-base/app/config/parameters.yml.dist
project-base/app/config/parameters_common.yml

|Description, reason for the PR| In `parameters.yml` there should be only parameters that you want to change by environment. Database server version should be same for all environments to prevent some unexpected behaviour.
|Fixes issues| #988 

[project-base] move database_server_version to parameters_common.yml

---

packages/framework/src/Component/Router/FriendlyUrl/FriendlyUrlFactory.php

|Description, reason for the PR| In framework there was a bug in method FriendlyUrlFactory::createIfValid. Name for URL was created with dash (e.g. entityname-) even if there was not postfix. This issue was originally posted on our slack (http://slack.shopsys-framework.com/).

[framework] fix correct creating friendly url without indexPostfix

---

packages/framework/src/Resources/config/services_test.yml

|Description, reason for the PR| Fixes BC break introduced in #943. This PR revert removal of service from services.yml

[framework] revert removed service from #943

---

packages/coding-standards/easy-coding-standard.yml
packages/coding-standards/tests/Unit/CsFixer/ForbiddenDumpFixer/config.yml
packages/coding-standards/tests/Unit/CsFixer/ForbiddenPrivateVisibilityFixer/config.yml
packages/coding-standards/tests/Unit/CsFixer/MissingButtonTypeFixer/config.yml
packages/coding-standards/tests/Unit/CsFixer/OrmJoinColumnRequireNullableFixer/config.yml
packages/coding-standards/tests/Unit/CsFixer/Phpdoc/FunctionAnnotationFixer/config.yml
packages/coding-standards/tests/Unit/CsFixer/Phpdoc/MissingParamAnnotationsFixer/config.yml
packages/coding-standards/tests/Unit/CsFixer/Phpdoc/MissingReturnAnnotationFixer/config.yml
packages/coding-standards/tests/Unit/CsFixer/Phpdoc/NoUselessAccessFixer/config.yml
packages/coding-standards/tests/Unit/CsFixer/Phpdoc/OrderedParamAnnotationsFixer/config.yml
packages/coding-standards/tests/Unit/CsFixer/RedundantMarkDownTrailingSpacesFixer/config.yml
packages/coding-standards/tests/Unit/Sniffs/ConstantVisibilityRequiredSniff/config.yml
packages/coding-standards/tests/Unit/Sniffs/ForbiddenDoctrineInheritanceSniff/config.yml
packages/coding-standards/tests/Unit/Sniffs/ForbiddenDumpSniff/config.yml
packages/coding-standards/tests/Unit/Sniffs/ForbiddenExitSniff/config.yml
packages/coding-standards/tests/Unit/Sniffs/ForbiddenSuperGlobalSniff/config.yml
packages/coding-standards/tests/Unit/Sniffs/ForceLateStaticBindingForProtectedConstantsSniff/config.yml
packages/coding-standards/tests/Unit/Sniffs/ObjectIsCreatedByFactorySniff/config.yml
packages/coding-standards/tests/Unit/Sniffs/ValidVariableNameSniff/config.yml
packages/coding-standards/tests/config.yml

|Description, reason for the PR| Travis builds fail on broken autowiring of services (see #957) due to using different versions of `symplify/better-phpdoc-parser`. This PR fixes the builds of the isolated packages by providing a link to DI service configuration.
|Fixes issues| fixes #957, closes #923 and closes #962 
:heavy_check_mark: `shopsys/framework` package passes the Travis build when using the `dev-ph-travis-ecs-fix` version of `shopsys/coding-standards`, see …

[coding-standards] include config of better-phpdoc-parser in ECS config

---

packages/http-smoke-testing/.travis.yml
packages/http-smoke-testing/composer.json
packages/http-smoke-testing/easy-coding-standard.yml

|Description, reason for the PR| Travis build failed because of coding standard conflict (it uses legacy 3.0.2 version of shopsys/coding-standards because of support for PHP 5.6, see #194)
|[BC breaks](https://github.com/shopsys/shopsys/blob/master/docs/contributing/backward-compatibility-promise.md)| No (only dev dependencies were changed) 
|Fixes issues| finally fixes the stale #194 
After this PR:
- the shopsys/http-smoke-testing package still supports PHP 5.6
- Travis now runs PHP lint and unit tests in all supported versions
- Travis now runs coding standards check only in PHP …

[http-smoke-testing] use current shopsys/coding-standards package

---

.travis.yml
composer.json
packages/framework/composer.json
project-base/composer.json

|Description, reason for the PR| In #978 the supported versions of `snc/redis-bundle` package were changed which breaks backward compatibility. Even though we don't define BC in terms of dependencies precisely (see #872), you cannot use `shopsys/framework` in version `dev-master` using the `shopsys/project-base` in the `7.0.0` version as a base repository without further changes (see below).
When using `shopsys/project-base` in version `7.0.0` and …

[shopsys] composer.json: revert BC breaking change of snc/redis-bundle dependency

---

README.md

|Description, reason for the PR| The Travis build badge had no link in the monorepo README.md. Clicking on the badge on the Github web UI opened the badge image in a new tab. It should lead to the build details on Travis (just as in the other readmes of our packages).
Thanks @boris-brtan for mentioning this issue in https://github.com/shopsys/shopsys/pull/1013#issuecomment-491305888

[shopsys] README.md: add a link to the Travis build badge

---

.ci/build_kubernetes.sh
docs/upgrade/UPGRADE-unreleased.md
project-base/kubernetes/kustomize/overlays/ci/ingress-patch.yaml
project-base/kubernetes/kustomize/overlays/ci/kustomization.yaml
project-base/kubernetes/services/adminer.yml
project-base/kubernetes/services/redis-admin.yml
project-base/kubernetes/services/webserver-php-fpm.yml

|Description, reason for the PR| now for ci kustomize overlays, there are redis-admin, adminer, webserver-php-fpm bound as NodePort accessible and ingress is used only for webserver-php-fpm service in CI deployment. All NodePort services should be bound as ClusterIP and ingress should route redis-admin, adminer, webserver-php-fpm, elasticsearch so Testing and Business Validation could be done easily for the specific Pull Requests. `adminer.${FIRST_DOMAIN_URL}`<br>`elasticsearch.${FIRST_DOMAIN_URL}`<br>`redis-admin.${FIRST_DOMAIN_URL}` …

[project-base] kubernetes containers accesspoints are routed via ingress

---

docs/installation/installation-using-docker-on-production-server.md

|Description, reason for the PR| During container start there were started 2 processes for logging into pipe with the same path (`tail -f /tmp/pipe`).<br />Similiar to #992.

[shopsys] remove duplicate entrypoint call in production guide

---

utils/releaser/src/ReleaseWorker/ReleaseCandidate/UpdateChangelogReleaseWorker.php

|Description, reason for the PR| Filtering by target branch (base) is very useful when updating the changelog during the release process (see [article Searching issues and pull requests](https://help.github.com/en/articles/searching-issues-and-pull-requests#search-by-branch-name))

[shopsys] UpdateChangelogReleaseWorker: add tip about filtering on Github

---

utils/releaser/src/ReleaseWorker/AbstractShopsysReleaseWorker.php

|Description, reason for the PR| Release process fails if git identity is not configured as it creates commits. Because release is usually executed within a Docker container, it may be empty if the developer has identity configured globally on the host machine. Now, git identity is checked before making a commit - if it's empty, the user is prompted to configure it (see below).
Example:

[shopsys] AbstractShopsysReleaseWorker: git identity can be configured if empty

---

utils/releaser/src/ReleaseWorker/ReleaseCandidate/UpdateUpgradeReleaseWorker.php

|Description, reason for the PR| The release worker creates a file but doesn't add it to the staging area, which might be confusing for the developer. All changed files are added to the staging area automatically now.

[shopsys] UpdateUpgradeReleaseWorker adds the changed files to staging area automatically

---

utils/releaser/src/ReleaseWorker/AfterRelease/EnableMergingToMasterReleaseWorker.php
utils/releaser/src/ReleaseWorker/AfterRelease/SetUnreleasedNoteInInstallationGuidesReleaseWorker.php

|Description, reason for the PR| Releaser during its `after-release` stage tells you to enable merging to `master` and in the following release worker (`SetUnreleasedNoteInInstallationGuidesReleaseWorker`) makes some changes and commits them. This commit can be easily forgotten without being pushed. I've switched the order of the two release workers and added a prompt for pushing the changes.

[shopsys] merging to master is enabled after all changes are pushed during release

---

docs/upgrade/UPGRADE-unreleased.md
docs/upgrade/UPGRADE-v7.0.0-beta6.md
docs/upgrade/UPGRADE-v7.0.0.md
docs/upgrade/UPGRADE-v7.1.0.md
docs/upgrade/UPGRADE-v7.2.0.md
docs/upgrade/template/UPGRADE-unreleased.md.twig

|Description, reason for the PR| This format is easier to work with during automated release process (see [VersionUpgradeFileManipulator](https://github.com/shopsys/shopsys/blob/v7.2.0/utils/releaser/src/FileManipulator/VersionUpgradeFileManipulator.php) and [its unit test](https://github.com/shopsys/shopsys/blob/v7.2.0/utils/releaser/tests/FileManipulator/UpgradeFileManipulator/VersionUpgradeFileManipulatorTest.php)).<br />Otherwise the headings are not properly updated by releaser. …

[shopsys] use inline links in upgrade note headings

---

docs/upgrade/UPGRADE-unreleased.md
project-base/src/Shopsys/ShopBundle/Controller/Front/PersonalDataController.php

If the form is not submitted, method Form::isValid() will throw an exception in Symfony 4.0

[project-base] Form::isValid() should be called after Form::isSubmitted()

---

docs/upgrade/interchangeable-filtering.md

|Description, reason for the PR| during the upgrade of `shopsys/demoshop` I recreated the structure locally, but I forgot to recreate it during the deployment (as it is not a standard part of the deployment process). This lead to a *500 Internal Server Error* on the product list page.

[shopsys] added note about recreating structure during deployment in upgrade guide for v7.2.0

---

docs/upgrade/UPGRADE-unreleased.md
project-base/src/Shopsys/ShopBundle/Resources/views/Front/Content/Category/panel.html.twig

rename variable `categoriyWithLazyLoadedVisibleChildren` to `categoryWithLazyLoadedVisibleChildren` in 
`Front/Content/Category/panel.html.twig`

[project-base] fix typo in twig template

---

packages/framework/src/Component/Image/ImageFacade.php
packages/framework/src/Component/Image/ImageLocator.php

|Description, reason for the PR| Arguments with default null value have to have nullable typehint. This was violated in recently added methods and fixed in this PR.
|[BC breaks](https://github.com/shopsys/shopsys/blob/master/docs/contributing/backward-compatibility-promise.md)| No* 
*not considered BC break even if it changes method declaration as it's changed only in methods that are not yet released (added in #1018).

[framework] fixed nullable arguments with default value

---

packages/framework/src/Command/ProductSearchCreateStructureCommand.php
packages/framework/src/Component/Elasticsearch/ElasticsearchStructureManager.php

|Description, reason for the PR| ProductSearchCreateStructureCommand was outputting successful exit codes even if it failed. This PR makes sure that developer will not overlook errors that this command can output.
|Fixes issues| fixes #936 

ProductSearchCreateStructureCommand exits on error

---

.travis.yml

|Description, reason for the PR| `tests-unit` only executes unit tests of project-base, missing `tests-packages` and `tests-utils` - using `tests-static` which depends on all three
related to #969

[shopsys] .travis.yml: run unit tests in packages and utils

---

packages/migrations/src/Component/Doctrine/Migrations/Configuration.php

- wrong return type annotation from doctrine/migrations package was overriden with the correct one
- wrongly implemented call of getVersion method for string instance was fixed
|Description, reason for the PR| after merge of #1040 phing target db-migrations started to fail because of the wrong return type annotation of method from doctrine/migrations one method was wrongly implemented when we simplifying it.

[migrations] Configuration::shouldExecuteMigration is fixed

---

build.xml
docs/upgrade/UPGRADE-unreleased.md

|Description, reason for the PR| After #931, `dump-translation` phing target in project repository fails on missing folder. Translations in this folder are now dumped in monorepo as well for consistency.

[project-base] created an empty folder app/Resources/ for overwritten templates

---

packages/read-model/composer.json

|Description, reason for the PR| In read-model package was wrong license. This is fixed now (as it's licensed under Shopsys Community License) 

[read-model] updated license in composer in read-model package

---

docs/upgrade/UPGRADE-unreleased.md
project-base/infrastructure/google-cloud/nginx-ingress.tf

|Description, reason for the PR| when https://github.com/kubernetes/ingress-nginx/tree/master/deploy changed the structure of its configs after the merge of this kubernetes/ingress-nginx#4055 PR we encountered that our project contains link onto master branch, thus we changed the URL of the mandatory.yaml config into last released stable version where the config is functional with our terraform configuration scripts.

[project-base] ingress-nginx deployment config loads now tagged version instead of master branch version

---

packages/framework/tests/Unit/Model/Order/PromoCode/CurrentPromoCodeFacadeTest.php

|Description, reason for the PR| The second parameter of `TestCase::getMockForAbstractClass()` is `$arguments`, not `$methods` - the $arguments parameter is used to instantiate the mock class (which does not have a constructor and that makes our unit tests fail, seemingly since upgrade to `phpunit/phpunit: 7.5.12` from `7.5.11`).

[framework] CurrentPromoCodeFacadeTest: fixed call of getMockForAbstractClass

---

composer.json
packages/framework/composer.json

|Description, reason for the PR| class-map autoloader property refuses to load extended FlysystemVolumeDriver (introduced in #932) so the autoloading is fixed by files property of autoloader in composer.json.<br/>This fixes generation of thumbnails inside the file manager and URLs of the contents.
**Before:**
**After:**

[framework] custom extension of FlysystemVolumeDriver is loaded via files instead of classmap

---

docs/upgrade/UPGRADE-unreleased.md
project-base/kubernetes/deployments/webserver-php-fpm.yml

- creating or recreating of folders and files duting initialization phase was changed to run via www-data(33) user
|Description, reason for the PR| after last check of the deploy script onto google-cloud we encountered a problem with non-functional administration. The problem occurred during initialization of php-fpm container where the assets, Doctrine migrations and other folders were under root ownership. So we needed to add chroot to www-data or user id 33 also for other phases of the php-fpm container build in webserver-php-fpm POD. …

[project-base] initialization of php-fpm container via kubernetes is now done via www-data user

---

docs/upgrade/UPGRADE-unreleased.md
docs/upgrade/interchangeable-filtering.md
project-base/tests/ShopBundle/Functional/Model/Product/Search/FilterQueryTest.php

|Description, reason for the PR| `FilterQueryTest` was not using Elasticsearch index prefix if specified, resulting in possible failing tests. This is fixed now.

[project-base] fixed FilterQueryTest to properly use Elasticsearch index

---

packages/framework/src/Model/Product/ProductFacade.php
packages/framework/src/Model/Product/Search/Export/ProductSearchExportWithFilterRepository.php

|Description, reason for the PR| If main variant was not sellable on certain domain, export products to Elastic failed (`MainVariantPriceCalculationException`). `ProductSearchExportWithFilterRepository` extracted prices for products on all domains, even on domains where they were not sellable.  

[framework] ProductSearchExportWithFilterRepository: get product selling prices only for certain domain

---

docs/upgrade/UPGRADE-unreleased.md
phpstan.neon
project-base/phpstan.neon

|Description, reason for the PR| after small change in package phpstan/phpdoc-parser in version 0.3.4 phpstan/phpdoc-parser#26 parsing of docblock was changed so we need to update our ingoreError section of phpstan.neon

[shopsys] ignoring of phpstan rule is updated after release of phpstan/phpdoc-parser:0.3.4

---

build.xml
packages/framework/build.xml
packages/framework/src/Command/SortPhingTargetsCommand.php

|Description, reason for the PR| According to our new [Guidelines for Phing Targets](https://github.com/shopsys/shopsys/blob/master/docs/contributing/guidelines-for-phing-targets.md#sorting) introduced in #1068, targets should be sorted alphabetically. As there were a lot of them, I've implemneted an automated sorting command and applied it. It is even a part of the coding standards in monorepo. The command is not robust enough to be included in project repository coding standards imo. …

[shopsys] phing targets are sorted alphabetically

---

packages/framework/src/Model/Mail/MailTemplateAttachmentFilepathProvider.php
packages/framework/src/Model/Mail/MailTemplateFacade.php
packages/framework/src/Resources/config/services.yml

|Description, reason for the PR| E-mails with attachment(s) was not sent. This is fixed now.
|[BC breaks](https://github.com/shopsys/shopsys/blob/master/docs/contributing/backward-compatibility-promise.md)| No (used setter injection) 
|Fixes issues| closes #858, closes #805 

[framework] fixed sending emails with attachment

---

packages/framework/src/DependencyInjection/ShopsysFrameworkExtension.php
packages/framework/src/Resources/config/services/twig.yml
packages/framework/src/Twig/NoVarDumperExtension.php

- twig functions `d()` and `dump()` are now defined in all environments
- `d()` and `dump()` now do nothing in prod and test environments
|Description, reason for the PR| Phing target `twig-lint` fails if the application is in `prod` environemnt with a confusing message (see below) after #1068 because it now checks more Twig templates. Also, using `dump()` Twig function causes a 500 error in `prod` environment.
Output of target `twig-lint` executed in morepo in `prod` application …

[framework] configure VarDumperExtension in all environments

---

packages/framework/composer.json

|Description, reason for the PR| due to the BC reasons there was a need to keep support for old version of package with missing flysystem driver support, but there will be no need, since version 8.x is not backward compatible. 

[framework] end of support for helios-ag/fm-elfinder-bundle:^6.2.1

---

packages/framework/src/Resources/translations/messages.cs.po
packages/framework/src/Resources/translations/messages.en.po
packages/framework/src/Resources/views/Admin/Content/Product/listGrid.html.twig
packages/framework/src/Resources/views/Admin/Content/ProductPicker/listGrid.html.twig

|Description, reason for the PR| Variant abbreviation should be a translation so you can change it if you want to

[framework] changed variant abbreviation to a translation in administration

---

packages/framework/LICENSE
packages/read-model/LICENSE
project-base/LICENSE

|Description, reason for the PR| Community license of shopsys/shopsys was updated 05/2018 but the license in packages was forgotten. The license in read-model, project-base and framework was updated as well.
|[BC breaks](https://github.com/shopsys/shopsys/blob/master/docs/contributing/backward-compatibility-promise.md)| no

[shopsys] Update of community license in packages

---

docs/frontend/configuring-image-sizes-for-individual-devices-width.md
docs/index.md

|Description, reason for the PR| Unification - all the first letters in all the article names should be capitalized (see [Guidelines for Writing Documentation](https://github.com/shopsys/shopsys/blob/v7.2.1/docs/contributing/guidelines-for-writing-documentation.md))

docs/index.md: first letters capitalization for all the article names

---

docs/upgrade/UPGRADE-unreleased.md
packages/framework/src/Model/Product/Availability/ProductAvailabilityCalculation.php
project-base/tests/ShopBundle/Functional/Model/Product/Availability/ProductAvailabilityCalculationTest.php
project-base/tests/ShopBundle/Functional/Model/Product/ProductVariantCreationTest.php

- added new functional test for product variant creation to avoid regression (the issue is related to the one mentioned in #581)
- mocks of `EntityManager` that are used in the calculation class have to have the `contains` method return `true` in tests
|Description, reason for the PR| An unhandled exception was thrown when a variant is created from a product which has no availability set (i.e. newly created product using stock).
|Fixes issues| fixes #1112 

[shopsys] ProductAvailabilityCalculation: fix calculation of not-yet-persisted products

---

docs/upgrade/UPGRADE-unreleased.md
project-base/src/Shopsys/ShopBundle/Resources/views/Front/Content/Registration/setNewPassword.html.twig

|Description, reason for the PR| All pages secured by an URL hash should have `noindex` in their robots metadata to prevent indexing them by search engines in case such URL gets leaked.

[project-base] prevent indexing `CustomerPassword:setNewPassword` by robots

---

build.xml
packages/framework/src/Command/PhingConfigFixerCommand.php
packages/framework/src/Command/SortPhingTargetsCommand.php

- renamed to `shopsys:phing-config:fix`
- the class was renamed to `PhingConfigFixerCommand`
- `SymfonyStyle` is used for input / output
- return codes are used instead of throwing Exceptions (Exceptions are still thrown for actual errors)
- messages were tweaked for better understandability
- the command also normalizes the whitespace in XML
|Description, reason for the PR| Usage of shopsys:phing-targets:sort introduced in #1104 was clumsy and caused a lot of hard-to-find errors.
|[BC breaks](https://github.com/shopsys/shopsys/blob/master/docs/contributing/backward-compatibility-promise.md)| No (the class was not released yet)  …

[framework] rewrite of shopsys:phing-targets:sort command

---

.travis.yml

|Description, reason for the PR| in travis script was one bug via yq command rewrite where uid was overwriten by gid value and thus gid wasnt intruduced at all into docker-compose php-fpm image build

.travis.yml: overwriting of travis user id by group id in docker-compose is fixed

---

docs/upgrade/UPGRADE-unreleased.md
packages/framework/src/Form/Admin/Administrator/AdministratorFormType.php
packages/framework/src/Form/Admin/Customer/UserFormType.php
project-base/src/Shopsys/ShopBundle/Form/Front/Customer/Password/NewPasswordFormType.php
project-base/src/Shopsys/ShopBundle/Form/Front/Customer/UserFormType.php
project-base/src/Shopsys/ShopBundle/Form/Front/Registration/RegistrationFormType.php

For browser compatibility, see https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete#Browser_compatibility
|Description, reason for the PR| Prevents browsers from filling the input for changing the password.
When you are registered as a customer, have the password remembered in the browser (and it's the only password remembered on that domain) and visit the *Personal data* page, the input *Changing password > Password* gets filled in automatically, which …

[shopsys] use autocomplete="new-password" attribute for password inputs

---

docs/upgrade/UPGRADE-unreleased.md
packages/framework/src/Command/ProductSearchExportProductsCommand.php
packages/framework/src/Model/Product/Search/Export/ProductSearchExportFacade.php
packages/framework/src/Model/Product/Search/Export/ProductSearchExportRepository.php
packages/framework/src/Model/Product/Search/Export/ProductSearchExporter.php
packages/framework/src/Resources/config/services.yml

|Description, reason for the PR| Exporting products to Elasticsearch needed more memory, the more products was present. Now the memory usage is stable and low enough (< 100MB). Progressbar representing the number of exported products was added.
|Fixes issues| closes #1021 
Disabling SQL logging is in our documentation as [best practice for working with many records](https://github.com/shopsys/shopsys/blob/master/docs/cookbook/basic-data-import.md#best-practices) and it can be found as a known …

[framework] fixed memory leak on shopsys:product-search:export-products command

---

packages/framework/easy-coding-standard.yml
packages/framework/src/Twig/CookiesExtension.php
packages/framework/src/Twig/CssExtension.php
packages/framework/src/Twig/DateTimeFormatterExtension.php
packages/framework/src/Twig/DomainExtension.php
packages/framework/src/Twig/FileThumbnail/FileThumbnailExtension.php
packages/framework/src/Twig/FileThumbnail/FileThumbnailInfo.php
packages/framework/src/Twig/FileUploadExtension.php
packages/framework/src/Twig/FormDetailExtension.php
packages/framework/src/Twig/FormThemeExtension.php
packages/framework/src/Twig/HoneyPotExtension.php
packages/framework/src/Twig/ImageExtension.php
packages/framework/src/Twig/InputPriceLabelExtension.php
packages/framework/src/Twig/Javascript/JavascriptCompiler.php
packages/framework/src/Twig/Javascript/JavascriptExtension.php
packages/framework/src/Twig/LocalizationExtension.php
packages/framework/src/Twig/MailerSettingExtension.php
packages/framework/src/Twig/ModuleExtension.php
packages/framework/src/Twig/NumberFormatterExtension.php
packages/framework/src/Twig/PriceExtension.php
packages/framework/src/Twig/ProductExtension.php
packages/framework/src/Twig/ProductVisibilityExtension.php
packages/framework/src/Twig/RequestExtension.php
packages/framework/src/Twig/RouterExtension.php
packages/framework/src/Twig/SeoExtension.php
packages/framework/src/Twig/ShopInfoExtension.php
packages/framework/src/Twig/TranslationExtension.php
packages/framework/src/Twig/UploadedFileExtension.php

- done to allow extensibility by inheritance
- watched by Shopsys\CodingStandards\CsFixer\ForbiddenPrivateVisibilityFixer
|Description, reason for the PR| Twig extensions are not extendable easily
|Fixes issues| fixes #1098 

[framework] private -> protected in Shopsys\FrameworkBundle\Twig namespace

---

CHANGELOG.md

|Description, reason for the PR| in CHANGELOG, there should be listed all packages maintined by monorepo

read-model package is now listed in CHANGELOG.md

---

packages/framework/src/Controller/Admin/DefaultController.php
packages/framework/src/Resources/translations/messages.cs.po
packages/framework/src/Resources/translations/messages.en.po
packages/framework/src/Resources/views/Admin/Content/Default/index.html.twig
packages/framework/src/Resources/views/Admin/Content/Product/quickSearchFormContent.html.twig

|Description, reason for the PR| for the speed purposes and better UX we would like to have direct connection between products and dashboard (default page after administrator is logged in)

[framework] administration: quicksearch for products via dashboard

---

docs/upgrade/UPGRADE-unreleased.md
packages/framework/src/Model/Product/Availability/ProductAvailabilityCalculation.php
project-base/tests/ShopBundle/Functional/Model/Product/Availability/ProductAvailabilityCalculationTest.php

- the patch in https://github.com/shopsys/shopsys/pull/1113 requried different EntityManager mock creation
- strict comparison of the result of `EntityManager::contains()` with `false` instead of a simple negation removes this requirement (because the mocked method will return `null`)
- tests require no changes to pass successfully after upgrade to a new version of `shopsys/framework` package
- the changes in `ProductAvailabilityCalculationTest` were reverted
|Description, reason for the PR| All tests should pass in `shopsys/project-base` in `v7.0.0` when upgrading all used `shopsys/*` packages via Composer. This was not true after merging #1113 as the functional tests required minor changes to pass.
|[BC …

[shopsys] improve backward compatibility of ProductAvailabilityCalculation patch

---

docs/cookbook/adding-new-attribute-to-an-entity.md
docs/cookbook/extending-product-list.md
docs/model/elasticsearch.md
docs/model/introduction-to-read-model.md
docs/upgrade/upgrade-instructions-for-read-model-for-product-lists.md
packages/framework/src/Model/Product/ProductOnCurrentDomainElasticFacade.php
packages/framework/src/Model/Product/ProductVisibility.php
packages/framework/src/Model/Product/ProductVisibilityRepository.php
packages/framework/src/Model/Product/Search/Export/ProductSearchExportWithFilterRepository.php
packages/framework/src/Model/Product/Search/FilterQuery.php
packages/framework/src/Model/Product/Search/ProductElasticsearchRepository.php
packages/framework/src/Model/Product/Search/ProductsResult.php
packages/framework/src/Resources/config/services/cron.yml
packages/read-model/src/Product/Action/ProductActionViewFacade.php
packages/read-model/src/Product/Action/ProductActionViewFactory.php
packages/read-model/src/Product/Listed/ListedProductViewElasticFacade.php
packages/read-model/src/Product/Listed/ListedProductViewFacade.php
packages/read-model/src/Product/Listed/ListedProductViewFactory.php
project-base/src/Shopsys/ShopBundle/Resources/config/services.yml
project-base/src/Shopsys/ShopBundle/Resources/config/services_test.yml
project-base/src/Shopsys/ShopBundle/Resources/definition/product/1.json
project-base/src/Shopsys/ShopBundle/Resources/definition/product/2.json
project-base/tests/ReadModelBundle/Functional/Product/Listed/ListedProductViewFacadeTest.php
project-base/tests/ShopBundle/Functional/Model/Product/Search/ProductSearchExportRepositoryTest.php

|Description, reason for the PR| We want to ensure fastest load time on product lists so the data in readmodel is loaded from Elasticsearch and not database

[shopsys] use ElasticSearch to get data to readmodel

---

docs/upgrade/UPGRADE-unreleased.md
packages/framework/src/Resources/config/services_test.yml
project-base/tests/ShopBundle/Functional/Controller/ProductRenameRedirectPreviousUrlTest.php
project-base/tests/ShopBundle/Functional/Model/Cart/CartFacadeDeleteOldCartsTest.php
project-base/tests/ShopBundle/Functional/Model/Cart/CartFacadeTest.php
project-base/tests/ShopBundle/Functional/Model/Cart/CartTest.php
project-base/tests/ShopBundle/Functional/Model/Category/CategoryDomainTest.php
project-base/tests/ShopBundle/Functional/Model/Order/OrderFacadeTest.php
project-base/tests/ShopBundle/Functional/Model/Payment/PaymentDomainTest.php
project-base/tests/ShopBundle/Functional/Model/Pricing/Group/PricingGroupFacadeTest.php
project-base/tests/ShopBundle/Functional/Model/Product/Brand/BrandDomainTest.php
project-base/tests/ShopBundle/Functional/Model/Product/ProductDomainTest.php
project-base/tests/ShopBundle/Functional/Model/Product/ProductVariantCreationTest.php
project-base/tests/ShopBundle/Functional/Model/Transport/TransportDomainTest.php

|Description, reason for the PR| When man overwrites factories in their project they need to update all tests, that use such factory. This PR prevents such need.

[shopsys] factories that use interfaces are now fetched from container via their interface in tests

---

docs/upgrade/UPGRADE-unreleased.md
project-base/.ci/deploy-to-google-cloud.sh

|Description, reason for the PR| we want to use the same elasticsearch plugin for cloud deploy of project-base as in monorepo as was introduced in #1069 

[project-base] deploy-to-google-cloud.sh: script sets correct elasticsearch image from dockerhub

---

packages/framework/src/Model/Sitemap/SitemapDumper.php

- removing of old sitemap files was separated for each domain
- copying of newly generated files from tmp to mainfilesystem was limited for sitemap domain prefix
|Description, reason for the PR| during generating sitemaps for multidomain shop, previous domain sitemaps were removed from mainfilesystem. Now there are just removed only those that are processed in the current item from cycle of domains list and also uploaded based on their prefix that contains unique name with domain id.
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| …

[framework] generating of multidomain sitemaps

---

UPGRADE.md
docs/contributing/upgrading-monorepo.md

|Description, reason for the PR| There might be situation when Docker build cache prevents to build images well and leads to unexpected errors.

updated UPGRADE.md to include information about need to rebuild docker images without cache

---

packages/framework/src/Resources/config/services_test.yml

|Description, reason for the PR| In #970 was created BC break in tests that causes errors in tests. This PR fixes that.

[shopsys] removed BC break in tests

---

composer.json
docs/upgrade/UPGRADE-unreleased.md
packages/framework/composer.json
project-base/composer.json

- see https://github.com/symfony/monolog-bundle/issues/309
|Description, reason for the PR| new minor release of monolog-bundle
|Fixes issues| should fix bc breaking of all versions 

[shopsys] composer.json: symfony/monolog-bundle >= 3.4.0 is set as conflicting

---

docs/upgrade/UPGRADE-v7.0.1.md
docs/upgrade/UPGRADE-v7.1.1.md
docs/upgrade/UPGRADE-v7.2.2.md

|Description, reason for the PR| hotfix of problem with BC of project using newest monolog-bundle version 3.4.0

[shopsys] UPGRADE-v7.x.x tweak because of conflict with symfony/monolog-bundle:3.4.0

---

composer.json
docs/upgrade/UPGRADE-unreleased.md
packages/framework/composer.json
project-base/app/config/packages/dev/monolog.yml
project-base/app/config/packages/test/monolog.yml
project-base/composer.json

|Description, reason for the PR| Package `symfony/monolog-bundle` throws an error when using `excluded_404s` or `excluded_http_codes` configuration in types other than `fingers_crossed` since `v3.4.0`, as explained in https://github.com/symfony/monolog-bundle/issues/309 - this PR fixes the configuration on our side. Also, reverts https://github.com/shopsys/shopsys/pull/1148 as it fixes the incompatibility.

[shopsys] stop using excluded_404s in monolog config for incompatible types

---

packages/framework/src/Form/ProductCalculatedPricesType.php
packages/framework/src/Model/Product/ProductFacade.php

|Description, reason for the PR| `ProductFacade::getAllProductSellingPricesByDomainId()` now returns zero prices for main variant without a sellable variant instead of throwing an exception.<br>Products with zero prices should not be visible, see [functional docs of Product Visibility](https://github.com/shopsys/shopsys/blob/v7.2.2/docs/functional/product-visibility-and-exclude-from-sale.md#parameters-that-impact-product-visibility) (this currently does not work correctly in Elasticsearch product search/filtering, but at least it's consistent for variants).
|Fixes issues| fixes #1142  …

[framework] product variants without a price for a pricing group are exportable to elastic

---

packages/framework/src/Model/Order/FrontOrderDataMapper.php

|Description, reason for the PR| if user is logged-in and order frontend of the last order of customer contains deleted shipping of payment method prefill functionality for new order fails on error about non existent payment/shipping method item. 
|Fixes issues| #1101  

[framework] FrontOrderDataMapper::prefillTransportAndPaymentFromOrder prefills methods that are not deleted

---

docs/upgrade/UPGRADE-v8.0.0.md
packages/framework/src/Model/Product/Product.php
packages/framework/src/Model/Product/Search/Export/ProductSearchExportWithFilterRepository.php
packages/framework/tests/Unit/Model/Order/Item/OrderProductFacadeTest.php
project-base/src/Shopsys/ShopBundle/Resources/config/services_test.yml
project-base/tests/ShopBundle/Functional/Model/Product/Availability/AvailabilityFacadeTest.php

- this behavior is consistent with the actual product creation and editting via adminsitration
- having availability set even when using stock can hide issues and cause inconsistencies
- ~this PR will fail during loading data fixures and tests because of #1112 until #1113 is merged~
|Description, reason for the PR| Products were created and edited inconsistently.

[shopsys] Product: availability cannot be set when using stock (and vice versa)

---

packages/framework/src/Model/Product/ProductOnCurrentDomainElasticFacade.php
packages/framework/src/Model/Product/Search/FilterQuery.php

|Description, reason for the PR| product with zero price for pricing group was returned from Elasticsearch and that for that "Total number of products" was not consistent with shown products. This is fixed now – products with zero price for current pricing group are not returned from Elasticsearch anymore

[framework] products with zero price are now not returned from Elasticsearch

---

packages/framework/src/Resources/config/services.yml

|Description, reason for the PR| clean-redis and redis-check phing targets should use also framework_annotations snc_redis client
|Fixes issues| just partially #1108 

[framework] phing targets redis-check and clean-redis clean also items of framework_annotations client

---

docs/contributing/backward-compatibility-promise.md

|Description, reason for the PR| Our BC promise is currently unnecessary restrictive about constructor parameters. Weakening such restrictions will help us to be more flexible and provide helpful changes without compromising the ease of upgrading.
|[BC breaks](https://github.com/shopsys/shopsys/blob/master/docs/contributing/backward-compatibility-promise.md)| No (*or is changing the promise a BC break?*) 

[shopsys] added exceptions for constructor parameters in BC promise

---

docs/upgrade/UPGRADE-unreleased.md
packages/framework/src/Component/Router/DomainRouterFactory.php
packages/framework/src/Model/Mail/MailTemplateFacade.php
packages/framework/src/Model/Order/Item/OrderItemDataFactory.php
packages/framework/src/Model/Product/Search/Export/ProductSearchExporter.php
packages/framework/src/Model/Product/Search/ProductElasticsearchRepository.php
packages/framework/src/Resources/config/services.yml

- all services has been added to constructors but might be nullable and set via setters
|Description, reason for the PR| Service injections are now all solved same way. There are understandable deprecation errors triggered when services are injected via setter injection and users now can use constructor injection and avoid this deprecation errors.  Note: the removed method validateInjectedDependencies() does not cause a violation of a BC promise as the method was not yet part of any released version …

[shopsys] all services injected in order to prevent BC breaks are now injected same way

---

packages/framework/src/Resources/config/services.yml

|Description, reason for the PR| In our `services.yml` there were either redundantly defined services or services referring to a missing class. Such service definitions can be safely removed.

[framework] remove redundant service definitions

---

docs/upgrade/UPGRADE-unreleased.md
packages/framework/src/Command/CheckRedisCommand.php
packages/framework/src/Command/Exception/RedisNotRunningException.php
packages/framework/src/Component/Redis/RedisFacade.php
packages/framework/src/DependencyInjection/Compiler/RedisFacadeClientFilterCompilerPass.php
packages/framework/src/Resources/config/services.yml
packages/framework/src/Resources/config/services/commands.yml
packages/framework/src/ShopsysFrameworkBundle.php
packages/framework/tests/Unit/Command/CheckRedisCommandTest.php
project-base/tests/ShopBundle/Functional/Component/Redis/RedisFacadeTest.php

- all `Redis` clients are injected into the facade via service tag
- clients that should not be cleaned are injected via manual service configuration, minimizing errors
- `CheckRedisCommand` uses `RedisFacade` for the pinging
- mentioning a Redis client that was not defined in previous versions (`@snc_redis.global` or `@snc_redis.framework_annotations`) explicitly in arguments would cause a BC break - this issue has been resolved by `RedisFacadeClientFilterCompilerPass` that removes such undefined services from `RedisFacade`
|Description, reason for the PR| This PR tries to resolve the same issue as in #1158, but tries to do so without expecting users to hard-code everything, making the solution less error-prone (hopefully).
|[BC …

[framework] RedisFacade: unification of used clients

---

docker/conf/docker-sync-win.yml.dist
docker/conf/docker-sync.yml.dist
docs/contributing/upgrading-monorepo.md

|Description, reason for the PR| Running any `ecs` phing target was failing on missing `project-base/docs` folder.

[shopsys] docker-sync now does not exclude project-base/docs in monorepo

---

open-source-license-acknowledgements-and-third-party-copyrights.md

|Description, reason for the PR| In 3rd part SW overview there was link to obsolete version of elastic license. Now it is fixed to elasticserach/master/license.txt

Fixed link to elasticsearch license file

---

docs/upgrade/UPGRADE-unreleased.md
packages/framework/build.xml
project-base/docker/php-fpm/Dockerfile

- redis-check was moved from part-1-db-independet into part-2-db-dependent
- part-1-db-independent was used in production stage build in Dockerfile for php-fpm image so installation guide now make sense and build-version-generate is contained
|Description, reason for the PR| installation guide for production was not accurate since build-version was introduced and other thins were bound to it. Also production stage build is now simplified, since it is dependent on the things that were removed from old version of installation guide for production. phing target `build-deploy-part-1-db-independent` was fixed since redis-check is db-dependent target.
|[BC breaks](https://github.com/shopsys/shopsys/blob/master/docs/contributing/backward …

[shopsys] build.xml: build-deploy-* are fixed

---

project-base/app/config/parameters_version.yml.dist

|Description, reason for the PR| The parameter `%build-version%` is sometimes string and sometimes can be cast to integer, which might be problematic.

DI parameter %build-version% is always string now

---

packages/framework/src/DependencyInjection/ShopsysFrameworkExtension.php
packages/framework/src/Resources/config/parameters_common.yml
packages/framework/src/Resources/config/services.yml

|Description, reason for the PR| Now it's easier to be aware of possible parameters that can be overriden from framework in a project, because now they're in separate file.
|Fixes issues| closes #976 

[framework] parameters moved from services to parameters_common

---

docs/upgrade/UPGRADE-unreleased.md
packages/framework/src/Model/Product/Search/Export/ProductSearchExportWithFilterRepository.php
packages/framework/tests/Unit/Model/Product/Search/ProductElasticsearchConverterTest.php
project-base/tests/ShopBundle/Functional/Model/Product/Search/ProductSearchExportRepositoryTest.php

|Description, reason for the PR| Changed `shortDescription` to `short_description` in the export of products. It was already called `short_description` in the structure definition and queries and all other fields use underscore.
|[BC breaks](https://github.com/shopsys/shopsys/blob/master/docs/contributing/backward-compatibility-promise.md)| Yes - functional tests will fail after upgrade (the fix is very easy to do and doing this the backward-compatible way would be harder and more confusing for both us and the end users) 
|Fixes issues| Fixes searching in `Product::$shortDescription` (for this to be fixed, a new product export must be executed)  …

[shopsys] [BC-BREAK] fixed wrong field in exporting products to Elasticsearch

---

packages/framework/src/Component/Collector/ShopsysFrameworkDataCollector.php
packages/framework/src/Resources/config/services.yml
packages/framework/src/Resources/views/Components/Collector/shopsysFramework.html.twig
packages/framework/src/ShopsysFrameworkBundle.php
utils/releaser/src/FileManipulator/FrameworkBundleVersionFileManipulator.php
utils/releaser/src/ReleaseWorker/AfterRelease/SetFrameworkBundleVersionToDevReleaseWorker.php
utils/releaser/src/ReleaseWorker/AfterRelease/SetMutualDependenciesToDevMasterReleaseWorker.php
utils/releaser/src/ReleaseWorker/ReleaseCandidate/SetFrameworkBundleVersionReleaseWorker.php

|Description, reason for the PR| After I started work with more projects, I was asking my colleagues to tell me which version of framework project has. So I created toolbar with version and basic information about project. I also upgraded releaser which will update version automatically.

[framework] show information about project in debug toolbar

---

docs/installation/installation-using-docker-on-production-server.md
docs/introduction/console-commands-for-application-management-phing-targets.md
docs/upgrade/UPGRADE-unreleased.md
packages/framework/build.xml
packages/framework/src/Command/ProductSearchMigrateIfNecessaryCommand.php
packages/framework/src/Component/ArrayUtils/RecursiveArraySorter.php
packages/framework/src/Component/Elasticsearch/ElasticsearchStructureManager.php
packages/framework/src/Component/Elasticsearch/ElasticsearchStructureUpdateChecker.php
packages/framework/src/Component/Elasticsearch/Exception/ElasticsearchException.php
packages/framework/src/Component/Elasticsearch/Exception/ElasticsearchMoreThanOneCurrentIndexException.php
packages/framework/src/Component/Elasticsearch/Exception/ElasticsearchNoCurrentIndexException.php
packages/framework/src/Component/Elasticsearch/Exception/ElasticsearchStructureException.php
packages/framework/src/Model/Product/ProductOnCurrentDomainElasticFacade.php
packages/framework/src/Model/Product/Search/Export/ProductSearchExportStructureFacade.php
packages/framework/src/Model/Product/Search/ProductElasticsearchRepository.php
packages/framework/src/Resources/config/services.yml
packages/framework/src/Resources/config/services_test.yml
packages/framework/tests/Unit/Component/Elasticsearch/ElasticsearchStructureManagerTest.php
project-base/tests/ShopBundle/Functional/Component/Elasticsearch/ElasticsearchStructureUpdateCheckerTest.php
project-base/tests/ShopBundle/Functional/Model/Product/Search/FilterQueryTest.php

|Description, reason for the PR| this PR lowers the downtime of eshop when deploying by reindexing to a new index elasticsearch that is created only if the structure has changed

[shopsys] added Elasticsearch structure migration via reindexing for easier deployment

---

packages/framework/src/Component/Elasticsearch/ElasticsearchStructureUpdateChecker.php

|Description, reason for the PR| In PHP 7.1 and PHP 7.2 trailing comma in function calls is invalid syntax.  Problem was introduced in #1133. This trailing comma is removed now.

[framework] trailing comma in function call is now removed

---

composer.json
docs/upgrade/UPGRADE-unreleased.md
packages/framework/composer.json
packages/framework/src/Form/Admin/Pricing/Currency/CurrencyFormType.php
packages/framework/src/Model/Localization/Exception/UndefinedLegacyCurrencyException.php
packages/framework/src/Model/Localization/IntlCurrencyRepository.php
packages/framework/src/Twig/NumberFormatterExtension.php
packages/framework/src/Twig/PriceExtension.php
project-base/composer.json

- the library dropped support for a few currencies (BYR, MRO, STD, VEF)
- the legacy currencies are now provided by Shopsys implementation of
IntlCurrencyRepository to keep BC
- the library usages modified in accordance with the changes in the new
version
- see https://github.com/commerceguys/intl/compare/v0.7.4...v1.0.4
|Description, reason for the PR| https://github.com/shopsys/shopsys/issues/164
|Fixes issues| closes #164  

[shopsys] commerceguys/intl is now upgraded to ^1.0.0

---

packages/framework/src/Resources/views/Admin/Layout/layout.html.twig

|Description, reason for the PR| Webpage logos usually link to the homepage. In admin, it should link to the dashboard.

[framework] admin: logo is now a link to dashboard

---

docs/cookbook/extending-product-list.md
packages/framework/src/Model/Product/Search/ProductElasticsearchConverter.php
packages/framework/src/Model/Product/Search/ProductElasticsearchRepository.php
packages/framework/tests/Unit/Model/Product/Search/ProductElasticsearchConverterTest.php

|Description, reason for the PR| When a new elasticsearch field is added, old documents (product data) doesn't contain this field and there is no way elasticsearch can provide this field without reindexing from database. This behavior caused problems when a View object (read model) required a new field but data were not reindexed from database. The solution is to fill empty default values for all fields
We wanted Elasticsearch provide ["default …

[framework] changing elasticsearch data structure is safe even in production environment

---

packages/framework/src/Model/Product/Search/Export/ProductSearchExportCronModule.php

|Description, reason for the PR| Exporting products to Elasticsearch needed more memory, the more products were present. Now the memory usage is stable and low enough (< 100MB). This solves the same problem as #1122 does but for export with cron module.

[framework] fixed memory leak in cron ProductSearchExportCronModule

---

docs/installation/installation-using-docker-on-production-server.md
docs/model/introduction-to-read-model.md
docs/upgrade/UPGRADE-unreleased.md
docs/upgrade/UPGRADE-v7.0.1.md
docs/upgrade/UPGRADE-v7.1.1.md
docs/upgrade/UPGRADE-v7.2.2.md
docs/upgrade/UPGRADE-v7.3.0.md
docs/upgrade/phpstan-level-4.md
docs/upgrade/upgrade-instructions-for-read-model-for-product-lists-from-elasticsearch.md
docs/upgrade/upgrade-instructions-for-read-model-for-product-lists.md

|Description, reason for the PR| Upgrade notes to upgrade from v7.2.2 to v7.3.0 has been updated with experience from upgrading. Documentation updated along.
- PHPStan instructions are part of another PR – #1199 as there are more things to consider
- Read Model instructions separated into multiple files because the introduction of the read model is a part of 7.3.0 release, but data from Elasticsearch into Read Model will take place in 8.0.0 release and this was now very confusing …

[shopsys] updated documentation and upgrade notes for v7.3.0 release

---

docs/upgrade/UPGRADE-unreleased.md
packages/framework/src/Component/Domain/DomainIconResizer.php
packages/framework/src/Controller/Admin/DomainController.php
packages/framework/src/Resources/styles/admin/components/form/line-box.less
packages/framework/src/Resources/styles/admin/components/form/line.less
packages/framework/src/Resources/translations/messages.cs.po
packages/framework/src/Resources/translations/messages.en.po
project-base/app/config/paths.yml

|Description, reason for the PR| Icons for domains were not loaded as part of demo data fixtures. This is fixed now

[shopsys] fixed path for domain icons directory

---

packages/framework/src/Resources/scripts/admin/product.js
packages/framework/src/Resources/scripts/admin/sideMenu.js
packages/framework/src/Resources/styles/admin/core/variables.less
packages/framework/src/Resources/styles/admin/layout/panel/side-menu.less
packages/framework/src/Resources/views/Admin/Content/Product/detail.html.twig
packages/framework/src/Resources/views/Admin/Menu/side_menu.html.twig

|Description, reason for the PR| Quick menu for product detail was removed in #1168, now it can be returned back. Side menu navigation is collapsed by default (showing only icons) and will appear on mouse hover. After menu is collapsed again, all submenus are closed.

[framework] admin: added quick menu for product detail

---

packages/backend-api/install/build.xml.patch

|Description, reason for the PR| In #1199 was updated build.xml file causing backend-api installation to fail. This change is now applied in backend-api installer, so it's now possible to install backend-api again without problem 

[backend-api] backend-api installer is now updated with latest changes in build.xml file

---

docs/index.md
docs/installation/installation-using-docker-application-setup.md
docs/installation/native-installation.md
docs/introduction/start-building-your-application.md

|Description, reason for the PR| Implementator didn't know what to do after installation. Now we have a starting point explaining the most important steps and concepts

[shopsys] Start Building Your Application article

---

docs/upgrade/UPGRADE-unreleased.md
packages/coding-standards/easy-coding-standard.yml
packages/framework/src/Command/ComposerScriptHandler.php
packages/framework/src/Component/Doctrine/FieldFunction.php
packages/framework/src/Component/Form/ResizeFormListener.php
packages/framework/src/Component/Translation/JsFileExtractor.php
packages/framework/src/Model/Administrator/Security/AdministratorUserProvider.php
packages/framework/src/Model/Customer/FrontendUserProvider.php
project-base/src/Shopsys/ShopBundle/Controller/Front/ErrorController.php

|Description, reason for the PR| In SSFW we don't use Yoda style for comparison. This is now automatically checked with coding standards.

[coding-standards] Yoda style for comparison is now disallowed

---

packages/framework/src/Controller/Admin/DefaultController.php

|Description, reason for the PR| Admin dashboard was displaying wrong trend when no data were present for calculation

[framework] dashboard statistics display zero trend when there are no data in previous week

---

packages/framework/src/Controller/Admin/CustomerController.php

|Description, reason for the PR| Customers in administration could not be sorted by the phone. This is fixed now.

[framework] fixed ordering cutomers by telephone in administration

---

packages/framework/src/Model/AdvancedSearch/AdvancedSearchProductFacade.php
packages/framework/src/Model/AdvancedSearchOrder/AdvancedSearchOrderFacade.php
packages/framework/src/Resources/views/Admin/Content/Order/AdvancedSearch/advancedSearch.html.twig
packages/framework/src/Resources/views/Admin/Content/Product/AdvancedSearch/advancedSearch.html.twig

|Description, reason for the PR| When advanced search is reset (in order list or product list), it should not be closed. This was achieved in a similar way as the link to product AS from dashboard (in `master`).<br>Then I generalized the solution so it's not dependant on knowing the first filter that should be opened (using `{as: true}` instead of eg. `{as: [{subject: 'productName'}]}` to open empty product advanced search)

[framework] admin advanced search: reset button will not close the filter

---

packages/framework/src/Model/Administrator/AdministratorFacade.php

|Description, reason for the PR| In #1123 the check was moved from `Administrator::edit()` into `AdministratorFacade::checkUsername()` without changing the `$this` reference.

[framework] AdministratorFacade: fix duplicate user name check

---

packages/framework/src/Resources/views/Admin/Content/Order/orderItem.html.twig

|Description, reason for the PR| There was a bug introduced during #1129 when the checkbox was inverted - the default value wasn't inverted (see https://github.com/shopsys/shopsys/pull/1129/commits/801b88ccb9b1a1a3615561668388ee9244b48f30#diff-8f6c88d8ce48d96fe646f558e7e66726).

[framework] admin: new order items have "Set prices manually" unchecked by default

---

packages/framework/src/Resources/styles/admin/components/box/dropdown.less
packages/framework/src/Resources/views/Admin/Inline/Menu/menu.html.twig

|Description, reason for the PR| Displaying real name of logged administrator in the account menu (upper right corner) makes much more sense than just displaying an icon.
**Before:**
**After:**

[framework] admin: display real name of logged user instead of icon

---

packages/framework/src/Resources/views/Admin/Content/Availability/list.html.twig
packages/framework/src/Resources/views/Admin/Content/Currency/currencySettings.html.twig
packages/framework/src/Resources/views/Admin/Content/Currency/list.html.twig
packages/framework/src/Resources/views/Admin/Content/Pricing/Groups/list.html.twig
packages/framework/src/Resources/views/Admin/Content/Pricing/Groups/pricingGroupSettings.html.twig
packages/framework/src/Resources/views/Admin/Content/Unit/list.html.twig
packages/framework/src/Resources/views/Admin/Content/Vat/list.html.twig

|Description, reason for the PR| There were inconsistencies among different pages with inline editation and some setting at the same time (eg. units, currencies, pricing group)
- all setting form with grid below are contained in `.wrap-divider`
- the `.wrap-divider` div is never defined inside the settings template
- it is created because of the grid below it, so it should be in the same template as the grid (`list.html.twig`)
- whitespace normalized

[framework] admin: consistency in separators in setting form

---

docs/upgrade/UPGRADE-unreleased.md
packages/framework/src/Form/OrderItemsType.php
packages/framework/src/Resources/views/Admin/Content/Order/orderItem.html.twig
packages/framework/src/Resources/views/Admin/Form/orderItems.html.twig

|Description, reason for the PR| Having all inputs with currencies behind them was a 
|[BC breaks](https://github.com/shopsys/shopsys/blob/master/docs/contributing/backward-compatibility-promise.md)| Yes (simplification of Twig macros) 
**Before:**
**After:**

[framework] admin: currency is displayed in the order table header instead of behind every input

---

packages/framework/src/Controller/Admin/DomainController.php

|Description, reason for the PR| The route `admin_dashboard` does not exist, changed to `admin_default_dashboard`. The domain switcher didn't work in some edge cases. Thanks for noticing @PatrikBajer!

[framework] DomainController: fix non-existing route

---

packages/framework/src/Model/LegalConditions/LegalConditionsFacade.php

|Description, reason for the PR| Repository and facade methods starting with `find` should return the entity or `null`. Methods starting with `get` should return the entity or throw an exception (see [our Coding Standards that are not checked automatically](https://github.com/shopsys/shopsys/blob/master/docs/contributing/coding-standards.md#standards-that-are-not-checked-automatically)). Here `get` was called from within a `find`, failing with error when the expected `Article` was not found. …

[framework] LegalConditionsFacade::findArticle() returns null when the Article doesn't exist

---

packages/framework/src/Form/Admin/Country/CountryFormType.php

|Description, reason for the PR| The `NotBlank` constraint is duplicate for the default language (defined both in `main_constraints` and `entry_options.constraints`).

[framework] CountryFormType: removal of duplicate constraint

---

build.xml

|Description, reason for the PR| When someone installs Composer dependencies in project-base directory in monorepo, the autoloader will start failing on duplicate class definitions. I added a check that will fail in such a case and tell the dev what to do. Only added to monorepo build.xml as it is only relevant there.

[shopsys] added Phing target that checks whether there is a project-base/vendor dir

---

packages/framework/src/Resources/config/services/cron.yml

|Description, reason for the PR| As explained in https://github.com/shopsys/shopsys/pull/1207#issuecomment-511810553, this allows to list all commands using `bin/console` without connection to DB in a BC manner.<br>Thanks @hason for bringing this issue up in #1207!

[framework] DailyFeedCronModule set as lazy to avoid side-effects in constructor

---

docs/upgrade/UPGRADE-unreleased.md
packages/framework/src/Model/Feed/DailyFeedCronModule.php
packages/framework/src/Resources/config/services/cron.yml

|Description, reason for the PR| I want to run `bin/console` to list all commands even if the database schema is not yet created.
|[BC breaks](https://github.com/shopsys/shopsys/blob/master/docs/contributing/backward-compatibility-promise.md)| Yes

[framework] DailyFeedCronModule: use getter for queue to eliminate side effects in constructor

---

docs/upgrade/UPGRADE-unreleased.md
easy-coding-standard.yml
packages/backend-api/easy-coding-standard.yml
packages/coding-standards/easy-coding-standard.yml
packages/form-types-bundle/easy-coding-standard.yml
packages/framework/easy-coding-standard.yml
packages/google-cloud-bundle/easy-coding-standard.yml
packages/http-smoke-testing/easy-coding-standard.yml
packages/migrations/easy-coding-standard.yml
packages/plugin-interface/easy-coding-standard.yml
packages/product-feed-google/easy-coding-standard.yml
packages/product-feed-heureka-delivery/easy-coding-standard.yml
packages/product-feed-heureka/easy-coding-standard.yml
packages/product-feed-zbozi/easy-coding-standard.yml
packages/read-model/easy-coding-standard.yml

|Description, reason for the PR| Having explicit visibility for `const`, `method`, and `property` is now required even in project repositories. It leads to clearer code which will help our users and there is an automatic fixer for it, so it will not require extra work from them.
|[BC breaks](https://github.com/shopsys/shopsys/blob/master/docs/contributing/backward-compatibility-promise.md)| Not sure, actually 

[coding-standards] explicit visibility is part of the general coding-standards

---

docs/upgrade/UPGRADE-unreleased.md
packages/coding-standards/easy-coding-standard.yml
packages/framework/src/Migrations/Version20180724060204.php
packages/framework/src/Migrations/Version20181114102106.php
packages/framework/src/Migrations/Version20181114120915.php
packages/framework/src/Migrations/Version20181114134959.php
packages/framework/src/Twig/FormThemeExtension.php
project-base/tests/ShopBundle/Functional/Model/Order/OrderFacadeEditTest.php

|Description, reason for the PR| Having a standard way of writing return type hints (`): int`) makes work easier for developers. It leads to more consistent code which will help our users and there is an automatic fixer for it, so it will not require extra work from them.
|[BC breaks](https://github.com/shopsys/shopsys/blob/master/docs/contributing/backward-compatibility-promise.md)| Not sure, actually 

[coding-standards] added return type hint spacing fixer

---

packages/migrations/src/Resources/views/Migration/migration.php.twig

|Description, reason for the PR| Add missing strict types and return types for migration template.
I know it's a little stupid thing because it doesn't bring anything new, but I like the order in the code 😄 If you don't want this PR, I will accept it.

[migrations] add missing strict types and return types into template

---

docker/conf/docker-compose-win.yml.dist
docs/upgrade/UPGRADE-unreleased.md
project-base/docker/conf/docker-compose-win.yml.dist

|Description, reason for the PR| The mounting of `php.ini` is not necessary as it is copied into the Docker image during build (the mounting was removed in #497 but reappeared 3 weeks later in #499 - possibly during a rebase?).

[shopsys] docker-compose-win.yml.dist: remove php.ini volume mount

---

packages/framework/src/Component/Domain/DomainFactory.php

|Description, reason for the PR| getenv returns only a string

[framework] convert DOMAIN environment variable to integer

---

README.md

|Description, reason for the PR| License info about particular repositories in monorepo readme was obsolete after adding new repositories like read-model and backend-api (those repositories has also Shopsys license).

[shopsys] Updated license information in readme file

---

docs/upgrade/UPGRADE-v9.0.0-dev.md
packages/framework/src/Resources/views/Admin/Content/Article/detail.html.twig
packages/framework/src/Resources/views/Admin/Content/Brand/detail.html.twig
packages/framework/src/Resources/views/Admin/Content/Category/detail.html.twig
packages/framework/src/Resources/views/Admin/Content/Product/detail.html.twig
project-base/src/Shopsys/ShopBundle/Resources/views/Front/Content/Product/list.html.twig
project-base/src/Shopsys/ShopBundle/Resources/views/Front/Content/Product/listByBrand.html.twig
project-base/src/Shopsys/ShopBundle/Resources/views/Front/Content/Product/productListMacro.html.twig
project-base/src/Shopsys/ShopBundle/Resources/views/Front/Content/Product/search.html.twig

|Description, reason for the PR| There were some legacy parts of code that imported no longer necessary macros.
|[BC breaks](https://github.com/shopsys/shopsys/blob/master/docs/contributing/backward-compatibility-promise.md)| Yes
|Fixes issues| #561 

[shopsys] unused macros has been removed from multiple twig templates

---

UPGRADE.md
docs/contributing/guidelines-for-writing-upgrade.md
docs/model/front-end-product-filtering.md
docs/model/introduction-to-read-model.md
docs/upgrade/UPGRADE-v7.3.0.md
docs/upgrade/UPGRADE-v8.0.0.md
docs/upgrade/upgrade-instructions-for-entities-simplification.md
docs/upgrade/upgrade-instructions-for-read-model-for-product-lists-from-elasticsearch.md

|Description, reason for the PR| During the actual upgrade of demoshop in https://github.com/shopsys/demoshop/pull/56 we gain a lot of insight about the upgrade process. Using this we can tweak the upgrade notes so they are more helpful to developers upgrading their projects.

[shopsys] improve upgrade notes for 8.0.0

---

composer.json
packages/framework/composer.json

- it is required by XmlNormalizer class
|Description, reason for the PR| This fix is extracted from https://github.com/shopsys/shopsys/pull/1289, see https://github.com/shopsys/shopsys/pull/1289#issuecomment-519443668

[framework] composer.json: added missing PHP extension dom

---

docs/contributing/backward-compatibility-promise.md

|Description, reason for the PR| In https://github.com/shopsys/shopsys/pull/1284, we were discussing whether removal of imports of Twig macros from templates should be considered a BC breaking change. It was not explicitly mentioned in our BC promise, however, I believe it should be. Imagine a situation when a project developer extends a template and uses the imported macro from the parent in his child template. Then if we remove the import in the parent template, it causes an error in the child template. …

[shopsys] BC promise: added info about Twig macros

---

build.xml
docs/introduction/how-to-set-up-domains-and-locales.md
docs/upgrade/UPGRADE-v8.1.0-dev.md
packages/backend-api/install/build.xml.patch
packages/framework/build.xml
packages/framework/src/Command/DomainInfoCommand.php
project-base/build.xml

|Description, reason for the PR| The `is-multidomain` and `translations.dump.locales` properties are now loaded automatically using a new Symfony command `shopsys:domains:info` instead of having developers set them up manually. Simplifies configuration of domains and locales. Also provides a way to show info about domains via CLI.
|Fixes issues| closes #941

[shopsys] domain configuration is autoloaded in build.xml

---

packages/framework/src/Resources/scripts/admin/advancedSearch.js

|Description, reason for the PR| If not destroyed, the control elements would get duplicated during `Shopsys.advancedSearch.addRule()` (see #1279).<br><br>Now, the template contains only pure `<select>` tags and can be copied freely - the Select2 will initialize with the correct data during execution of `Shopsys.register.registerNewContent()`.<br><br>See [Select2 docs](https://select2.org/programmatic-control/methods) for details on the implementation.
|Fixes issues| fixes #1279, closes #1301  

[framework] advancedSearch.js: destroy Select2 control in rule template during initialization

---

packages/migrations/src/Component/Doctrine/Migrations/AbstractMigration.php

|Description, reason for the PR| The method is not in fact deprecated, it's rather forbidden as explained in https://github.com/shopsys/shopsys/issues/1213#issuecomment-512242620
|Fixes issues| ~resolves~ *helps with* #1213 

[framework] AbstractMigration: removed deprecation annotation

---

docs/contributing/backward-compatibility-promise.md
docs/contributing/guidelines-for-pull-request.md
utils/releaser/src/ReleaseWorker/ReleaseCandidate/UpdateListOfSupportedVersionsReleaseWorker.php

- backward-compatibility-promise.md: added information about currently supported versions
|Description, reason for the PR| We were missing information about proper PR tergeting and currently supported versions in our docs. This PR should help developers of Shopsys Framework, as well as the external contributors to avoid confusion.

[shopsys] guidelines-for-pull-request.md: added note about proper PR targeting

---

docs/upgrade/UPGRADE-v7.3.2-dev.md
project-base/docker/php-fpm/Dockerfile

|Description, reason for the PR| Docker compose failed on install `libpg-dev` without update package repository. The console output is attached below.
Run `docker-compose up -d --build --force-recreate` failed on:
```bash
E: Failed to fetch http://cdn-fastly.deb.debian.org/debian/pool/main/p/postgresql-9.6/libpq5_9.6.11-0+deb9u1_amd64.deb  404  Not Found
E: Failed to fetch http://cdn-fastly.deb.debian.org/debian/pool/main/p/postgresql-9.6/libpq-dev_9.6.11-0+deb9u1_amd64.deb  404 …
```

[shopsys] php-fpm Dockerfile: update repository before install `libpg-dev`

---

.travis.yml
composer.json
docker/conf/docker-compose-mac.yml.dist
docker/conf/docker-compose-win.yml.dist
docker/conf/docker-compose.yml.dist
docs/upgrade/UPGRADE-v8.0.1-dev.md
packages/framework/composer.json
project-base/composer.json
project-base/docker/conf/docker-compose-mac.yml.dist
project-base/docker/conf/docker-compose-win.yml.dist
project-base/docker/conf/docker-compose.prod.yml.dist
project-base/docker/conf/docker-compose.yml.dist

|Description, reason for the PR| YAML standards library has been changed (a bug has been fixed) in `v4.2.5` (see https://github.com/sspooky13/yaml-standards/pull/35). This requires fixing the files using `phing yaml-standards-fix`.

[shopsys] fix standards in YAML files

---

docs/introduction/database-migrations.md
docs/introduction/start-building-your-application.md

|Description, reason for the PR| after #1323 notes about committing `migrations-lock.yml` will be useless, so they are removed

[shopsys] remove notes about committing migrations-lock.yml in documentation

---

packages/framework/src/Model/AdvancedSearch/AdvancedSearchProductFacade.php
packages/framework/src/Model/AdvancedSearchOrder/AdvancedSearchOrderFacade.php
packages/framework/src/Resources/views/Admin/Content/Order/AdvancedSearch/advancedSearch.html.twig
packages/framework/src/Resources/views/Admin/Content/Product/AdvancedSearch/advancedSearch.html.twig

|Description, reason for the PR| Administration > Product > Product Detail I am trying to add new accessories. I click to "Add Products", open "Advanced Filter" and click "Reset Filter". Then the content of popup window reloads and standard product overview appears in the popup so I am not allowed to finish assigning accessories.
|Fixes issues| closes #1274

[framework] AdvancedSearch respects current route on reset form

---

docs/upgrade/UPGRADE-v8.1.0-dev.md
project-base/app/Bootstrap.php
project-base/tests/ShopBundle/Unit/NumberFormattingTest.php

|Description, reason for the PR| When server has "wrong" locale, `Money` or sitemap does not work properly. For more info see #1184
|Fixes issues| closes #1184

[project-base] force locale for number formatting

---

project-base/src/Shopsys/ShopBundle/Model/Administrator/Administrator.php

|Description, reason for the PR| we have wrong annotation for AdministratorData in Administrator class

[project-base] fix wrong annotation in Administrator

---

docs/introduction/faq-and-common-issues.md
docs/introduction/start-building-your-application.md

|Description, reason for the PR| There were questions about the forced version of PHP in the `config.platform.php` option in Composer configuration.
|Fixes issues| resolves #1178 
To see that all dependencies support higher versions of PHP you can search for `"php":` in your `composer.lock`. You'll see all version requirements defined in the dependencies' `composer.json` config.
They all use wider intervals such as `>=5.3.0`, `^5.3.2 || ^7.0 || ^8.0`, `^7.1`...

[shopsys] docs: explain forced version of PHP in config.platform.php

---

packages/framework/phpstan.neon
phpstan.neon

|Description, reason for the PR| After update of `symfony/symfony` to `v3.4.31` Travis started failing on `phing phpstan` because of property type mismatch when filled from the DIC (see [failing build](https://travis-ci.org/shopsys/shopsys/jobs/576955885)) due to https://github.com/symfony/symfony/pull/33149. Also, some cleanup of the `phpstan.neon` was made (see commits messages for details).
|Fixes issues| failing check on Travis CI 

[shopsys] fix configuration of PhpStan

---

packages/backend-api/tests/Unit/Component/HeaderLinks/HeaderLinksTransformerTest.php
packages/framework/src/Model/Customer/UserFactory.php

|Description, reason for the PR| There were two violations of our coding standards in `8.0` which were cuaght by ECS only after the changes in `7.3` were merged. You can check that both #1123 and #1055 which introduced the violations passed on Travis CI.<br>Failures were probably caused by some new version of ECS or the used sniffs that fixes them (you can see that #1328 passed on Travis CI, but the 6feb368ca is failing atm).

[shopsys] fix coding standards via 'phing standards-fix'

---

project-base/src/Shopsys/ShopBundle/Resources/translations/validators.en.po

|Description, reason for the PR| No need to define translation that is the same as the message ID as there is a fallback to `IdentityTranslator`. Redundant messages were introduced in #1335, its upgrade notes are sufficient, this change requires no further upgrade note, even when it modifies the `project-base` package.

[project-base] remove unnecessary English translations

---

packages/framework/src/Migrations/MultidomainMigrationTrait.php
packages/framework/src/Migrations/Version20160129122637.php
packages/framework/src/Migrations/Version20160531080553.php
packages/framework/src/Migrations/Version20180409100239.php
packages/framework/src/Migrations/Version20181008000001.php

|Description, reason for the PR| What I know it's not good to use constants which can be changed in time and migrations must not adjust over time, right? So I changed these constants to their value.
P.S.: I didn't change classes with which I was not sure:
- [here](https://github.com/shopsys/shopsys/blob/master/packages/framework/src/Migrations/Version20190121094400.php#L107) is used `Doctrine\DBAL\Connection\Connection::PARAM_INT_ARRAY` constant and I don't know that is ok
- [I …

[framework] replace constant from other classes for value

---

docs/upgrade/UPGRADE-v8.1.0-dev.md
packages/framework/src/Component/Doctrine/Cache/RedisCacheFactory.php
packages/framework/src/Resources/config/services.yml

|Description, reason for the PR| The `RedisCacheFactory` is trivial and can be removed altogether and replaced by a one line YAML configuration. This would mean one less class (and DIC service) in the project.

[framework] use DIC configuration instead of factory class to create Redis caches

---

docker/nginx/nginx.conf
docs/upgrade/UPGRADE-v7.3.2-dev.md
project-base/docker/nginx/google-cloud/nginx.conf
project-base/docker/nginx/nginx.conf

|Description, reason for the PR| Configuring the access log filepath is not neccessary, `/var/log/nginx/access.log` is used by default.<br>In `nginx` Docker image, the `/var/log/nginx/access.log` is a symlink to `/dev/stdout` which means that using the path is in accordance with [12-factor app recommendation](https://12factor.net/logs).<br><br>There is still an open related issue #1337
|New feature| Yes (access logs are now on standard output which can be seen as a feature, but if we agree it's a bugfix we should retarget to `7.3` instead) 
|Fixes issues| resolves #1326  …

[shopsys] nginx.conf: remove access_log directive and use default settings

---

docs/upgrade/UPGRADE-v8.1.0-dev.md
packages/framework/src/Controller/Admin/PromoCodeController.php

|Description, reason for the PR| To extend promo codes you should not need to extend PromoCodeController just because of wrong argument type hint.

ProductCodeController now autowires PromoCodeDataFactoryInterface instead of PromoCodeDataFactory

---

docs/extensibility/framework-extensibility.md

|Description, reason for the PR| All forms in administration has been refactored so they can be extended without the need of the template overriding and our docs didn't reflect that.

Removed info about not extensible admin forms in docs

---

docs/introduction/running-acceptance-tests.md
packages/framework/src/Model/Security/AdministratorChecker.php
packages/framework/src/Resources/config/parameters_common.yml
packages/framework/src/Resources/config/services.yml
project-base/app/Environment.php
upgrade/UPGRADE-v8.1.0-dev.md

|Description, reason for the PR| Fixes environment resolving in #1360 as described in [review comment](https://github.com/shopsys/shopsys/pull/1360/files#r321710747).
- Shopsys\Environment should be used only in Shopsys\Bootstrap
- fixed incorrect info in upgrade notes and docs
- changed default value of IGNORE_DEFAULT_ADMIN_PASSWORD_CHECK to a string to be consistent with other environment variables

[framework] AdministratorChecker uses environment from DIC parameter

---

build.xml
docs/upgrade/UPGRADE-v9.0.0-dev.md
packages/framework/build.xml
project-base/app/AppCache.php
project-base/app/AppKernel.php
project-base/app/Bootstrap.php
project-base/app/Environment.php
project-base/app/autoload.php
project-base/app/maintenance.php
project-base/app/router.php
project-base/easy-coding-standard.yml

- fixed all the violations
- router.php is skipped for ValidVariableNameSniff and ForbiddenSuperGlobalSniff as it needs to use superglobals
|Description, reason for the PR| I see no reason why the folder should be excluded from the checks :slightly_smiling_face: I believe it just have been forgotten

[project-base] app folder is now included in coding standards checks

---

composer.json
utils/releaser/config/services.yaml

|Description, reason for the PR| We want to allow releasing of a lower tag than the newest one as we we are supporting multiple versions. This is now allowed by the usage of our own fork of MonorepoBuilder (see https://github.com/Symplify/MonorepoBuilder/pull/4), however, I found out that it is completely unnecessary. The desired result can be achieved by configuration :man_facepalming: Thanks to that, I could also simplify my PR https://github.com/Symplify/Symplify/pull/1589 …

[shopsys] releaser simplification

---

build.xml
packages/framework/build.xml
project-base/build.xml
upgrade/UPGRADE-v8.1.0-dev.md

- existing projects now must opt-in for this feature by enabling it in their build.xml
- new projects have this feature enabled by default
- in monorepo, the feature is turned on as well
|Description, reason for the PR| after discussion with @DavidOstrozlik, I relized that adding this feature to standards would be a BC break as standards on current projects start to fail after upgrading. Therefore I changed the default setting as described above.

[shopsys] "annotations-check" and "annotations-fix" are turned off by default for existing projects to avoid BC-breaks

---

phpstan.neon
project-base/phpstan.neon
project-base/src/Shopsys/ShopBundle/DataFixtures/Demo/MailTemplateDataFixture.php
project-base/src/Shopsys/ShopBundle/DataFixtures/Demo/UserDataFixture.php
project-base/tests/ShopBundle/Test/Codeception/Helper/WebDriverHelper.php
upgrade/UPGRADE-v8.1.0-dev.md

|Description, reason for the PR| In #1344, level of PHPStan was raised to 4 in project base, however, from monorepo there were no errors reported. The problem occured lately, after the project-base was split, see https://travis-ci.org/shopsys/project-base/jobs/581096169

[project-base] resolved (either fixed or ignored) all the errors reported by phpstan level 4

---

packages/framework/src/Resources/styles/admin/components/in/icon.less
packages/framework/src/Resources/views/Admin/Content/Vat/listGrid.html.twig

|Description, reason for the PR| Unify icons element in action icons. Muted items uses same html as non-muted items. Fix warning icon position in text - when VAT is marked to delete action.
|Fixes issues| fixes #1292, fixes #1295   
Screen before:
Sceen after:

[framework] VAT - use same icons for market action icons

---

packages/framework/src/Resources/views/Admin/Form/theme.html.twig

|Description, reason for the PR| Fix display of yes/no element in one domain admin
|Fixes issues| fixes #1333  
Screen before: https://user-images.githubusercontent.com/33071107/63157608-9fd79f80-c017-11e9-9d07-48278928af8e.png
Screen after:

[framework] - product detail - Fix display of yes/no element in one domain admin

---

packages/framework/src/Resources/styles/admin/components/in/message.less
packages/framework/src/Resources/views/Admin/Form/theme.html.twig

|Description, reason for the PR| Fixes text position in form error messages
|Fixes issues| fixes #1296  
Screen before:
Screen after:

[framework] fix admin error messages text position

---

project-base/infrastructure/google-cloud/gke-cluster.tf
upgrade/UPGRADE-v7.3.2-dev.md

|Description, reason for the PR| Avoids error during `terraform apply`: `google_container_cluster.primary: node_version and min_master_version must be set to equivalent values on create`, for details, see [the docs](https://www.terraform.io/docs/providers/google/r/container_cluster.html#node_version).<br>As we don't really need running on the latest version of Kubernetes, it's safer to omit the whole data source and let GKE resolve version automatically.<br>Also, it makes the config simpler, which is nice. …

[project-base] gke-cluster.tf: remove 'google_container_engine_versions' data source

---

packages/framework/src/Model/Security/AdministratorChecker.php

|Description, reason for the PR| When this check is done before real authentication (as introduced in #1360), it will throw `LoginWithDefaultPasswordException` any time someone tries to login as admin who has the default password. Now, it's thrown only when someone successfully logs in as admin using the default password.
|[BC breaks](https://github.com/shopsys/shopsys/blob/master/docs/contributing/backward-compatibility-promise.md)| No  

[framework] AdministratorChecker: verify default password after regular authentication

---

docs/introduction/faq-and-common-issues.md

|Description, reason for the PR| This FAQ entry helps the people strugling with sending emails from SMTP container with `Helo command rejected: need fully-qualified hostname` log entry

[shopsys] added FAQ entry about setting hostname for SMTP container

---

utils/releaser/src/Travis/TravisStatusReporter.php

|Description, reason for the PR| In #1244 we introduced new forked package, but Travis status of all shopsys packages is checked while releasing the new version. Forked packages should be excluded from these checks and this PR exclude newly added shopsys/changelog-linker fork.

releaser: excluded forked shopsys/changelog-linker from travis check

---

utils/releaser/src/Travis/TravisStatusReporter.php

|Description, reason for the PR| In #1244 we introduced new forked package, but Travis status of all shopsys packages is checked while releasing the new version. Forked packages should be excluded from these checks and this PR exclude newly added shopsys/monorepo-builder fork.

releaser: excluded forked shopsys/monorepo-builder from travis check

---

utils/releaser/src/ReleaseWorker/ReleaseCandidate/UpdateUpgradeReleaseWorker.php

|Description, reason for the PR| In #1350 the upgrade notes were moved outside from the docs folder to the root as it's not the documentation. Upgrade file for monorepo was moved also, but release worker altering this file was not updated with the new file path. This PR fixes it.

[shopsys] releaser: fixed path for upgrading-monorepo file

---

packages/framework/src/Resources/config/parameters_common.yml
project-base/docker/php-fpm/Dockerfile
upgrade/UPGRADE-v8.1.0-dev.md

|Description, reason for the PR| Default values moved into `parameters_common.yml` in `shopsys/framework`. This allows modifying the project defaults in `parameters.yml` (otherwise, the values set in Docker image have priority). There's no reason to overwrite the env vars in Docker image as well and it might lead to confusion...

[shopsys] Dockerfile: stop defining default env vars

---

docker/conf/docker-sync-win.yml.dist

|Description, reason for the PR| remove forgotten apostrophes from `sync_excludes`
Please, fix/accept this issue high priority because `docker-sync start` on windows doesn't work.
This command `docker-sync start` write now:
```bash
$ docker-sync start
ok  Starting unison for sync shopsys-framework-sync
doing initial sync with unison
unison: Garbled argument -ignore.
real    0m 0.13s
user    0m 0.06s
sys     0m 0.01s
chown ing file to uid 1000
Traceback (most recent call last): …
```

[shopsys] fix start docker sync on windows

---

docs/installation/installation-using-docker-windows-10-pro-higher.md

|Description, reason for the PR| Removed version of docker-sync from install guide because we want to install newest version of this library
P.S.: if you tell me you want tested version then I accept it but I will be no happy 😐 Solution can be run builds on windows too 😄

[shopsys] remove docker-sync version from install guide

---

.ci/export_logs.sh

|Description, reason for the PR| This PR removes printing of each executed command in `export_logs.sh` script as it's not useful and just clutters the console log output on the CI server

[shopsys] executed commands in export logs from container script are not now printed

---

docs/installation/installation-using-docker-on-production-server.md

|Description, reason for the PR| One of the essentials steps is the need to rebuild the image, but information about this step can be easily missed (see more in #841). This PR turn the sentence into admonition which is nicely rendered on the documentation website (https://docs.shopsys.com)
|Fixes issues| closes #841 
output:

[shopsys] Highlight info about rebuilding image on next deploys

---

upgrade/UPGRADE-v8.0.0.md
upgrade/upgrade-instructions-for-read-model-for-product-lists-from-elasticsearch.md

|Description, reason for the PR| In #1350 the upgrade notes were moved outside from the docs folder to the root as it's not the documentation. In some upgrade files remained old (invalid) links. This PR fixes it.

[shopsys] fixed links to moved upgrade files

---

packages/backend-api/install/build.xml.patch

- the file should have been updated in https://github.com/shopsys/shopsys/pull/1379
|Description, reason for the PR| I have forgotten to update the patch file needed for API install in #1379 :man_facepalming: 

[shopsys] fixed build.xml.patch

---

docs/installation/installation-using-docker-linux.md
docs/installation/installation-using-docker-macos.md
docs/installation/installation-using-docker-windows-10-pro-higher.md

|Description, reason for the PR| When using lists, there must be a blank line above the list (or a headline) to be formatted properly on readthedocs. Moreover, headlines are more suitable here than simple bold text.
The page on readthedocs before:
The page on readthedocs after:

[shopsys] docs: installation guides: fixed formatting

---

README.md

|Description, reason for the PR| The information on readme was obsolete and the image of package architecture has no such big added value for initial understanding SSFW.

Readme update to current state and removed package architecture image

---

packages/http-smoke-testing/src/HttpSmokeTestCase.php

|Description, reason for the PR| Allows easy modification of the default options (eg. running in debug mode).

[http-smoke-testing] HttpSmokeTestCase uses constants for kernel options

---

project-base/src/Shopsys/ShopBundle/Controller/Front/ErrorController.php
project-base/src/Shopsys/ShopBundle/Resources/config/services.yml
upgrade/UPGRADE-v7.3.3-dev.md

|Description, reason for the PR| Shopsys\Environment should be used only in Shopsys\Bootstrap

[project-base] ErrorController uses environment from DIC parameter

---

packages/framework/src/Component/Error/ErrorIdProvider.php
packages/framework/src/Component/Error/ErrorPagesFacade.php
packages/framework/src/Component/Error/NotLogFakeHttpExceptionsExceptionListener.php
packages/framework/src/Resources/config/services.yml
project-base/src/Shopsys/ShopBundle/Controller/Front/ErrorController.php
project-base/src/Shopsys/ShopBundle/Resources/views/Front/Content/Error/error.html.twig
project-base/tests/ShopBundle/Acceptance/acceptance/ErrorHandlingCest.php
upgrade/UPGRADE-v8.1.0-dev.md

|Description, reason for the PR| When application dies on 500 error it is hard to find out why it happend.
|Fixes issues| closes #1365 

[shopsys] added error ID to 500 error page

---

.ci/build_kubernetes.sh
docker/conf/docker-compose-mac.yml.dist
docker/conf/docker-compose-win.yml.dist
docker/conf/docker-compose.yml.dist
docker/mkdocs/Dockerfile
docker/nginx/nginx.conf
docs/index.md
docs/requirements.txt
upgrade/upgrading-monorepo.md

|Description, reason for the PR| This PR allows to see generated documentation on the local machine and on CI server. 
|New feature| Yes (for writing documentation) 
Documentation for local development is available on http://127.0.0.1:1300 and each change in documentation is immediately propagated (no need to restart containers).
On the CI server is documentation generated into `./documentation`folder and nginx is configured to show this generated documentation on …

[shopsys] documentation is now available on CI and local

---

project-base/tests/ShopBundle/Functional/Model/Cart/CartItemTest.php
project-base/tests/ShopBundle/Functional/Model/Cart/CartTest.php
project-base/tests/ShopBundle/Functional/Model/Cart/Watcher/CartWatcherTest.php
upgrade/UPGRADE-v7.3.3-dev.md

|Description, reason for the PR| Fixing forgotten occurrences of property `ProductData::$price` which no longer exists.<br> (Came from https://github.com/shopsys/shopsys/pull/1392)<br> Bug introduced in https://github.com/shopsys/shopsys/commit/ba446bf83f06906ef68aa3df04ffab03d35d8431

[project-base] removed usage of non-existing property ProductData::$price

---

.ci/build_kubernetes.sh
.ci/restart_kubernetes.sh
.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md
CONTRIBUTING.md
README.md
UPGRADE.md
packages/framework/README.md
packages/read-model/README.md
packages/read-model/src/Image/ImageView.php
packages/read-model/src/Product/Action/ProductActionView.php
packages/read-model/src/Product/Listed/ListedProductView.php
project-base/README.md
project-base/docs/index.md
upgrade/UPGRADE-v7.0.0-alpha4.md
upgrade/UPGRADE-v7.0.0-alpha6.md
upgrade/UPGRADE-v7.0.0-beta5.md
upgrade/UPGRADE-v7.0.0.md
upgrade/UPGRADE-v7.2.1.md
upgrade/UPGRADE-v7.3.0.md
upgrade/interchangeable-filtering.md
upgrade/money-class.md
upgrade/phpstan-level-1.md
upgrade/upgrade-instructions-for-read-model-for-product-lists.md
upgrade/upgrading-monorepo.md
utils/releaser/src/ReleaseWorker/Release/MergeReleaseCandidateBranchReleaseWorker.php
utils/releaser/src/ReleaseWorker/ReleaseCandidate/UpdateUpgradeReleaseWorker.php

|Description, reason for the PR| We have a new website (https://docs.shopsys.com/) where the documentation should be viewed primarly so it is sutiable to link the documentation on the site, not in github

files outside the docs now link the docs on docs.shopsys.com

---

packages/coding-standards/easy-coding-standard.yml

|Description, reason for the PR| FunctionCallSignatureSniff.Indent (added in https://github.com/squizlabs/PHP_CodeSniffer/releases/tag/3.5.1) was disabled because it was setting wrong indentation and MethodArgumentSpaceFixer was fixing it back.
|Fixes issues| No 

[coding-standards] FunctionCallSignatureSniff.Indent is now disabled

---

.ci/build_kubernetes.sh
.ci/restart_kubernetes.sh
CONTRIBUTING.md
README.md
UPGRADE.md
packages/framework/README.md
packages/read-model/README.md
packages/read-model/src/Image/ImageView.php
packages/read-model/src/Product/Action/ProductActionView.php
packages/read-model/src/Product/Listed/ListedProductView.php
project-base/README.md
project-base/docs/index.md
upgrade/UPGRADE-v7.0.0-alpha4.md
upgrade/UPGRADE-v7.0.0-alpha6.md
upgrade/UPGRADE-v7.0.0-beta5.md
upgrade/UPGRADE-v7.0.0.md
upgrade/UPGRADE-v7.2.1.md
upgrade/UPGRADE-v7.3.0.md
upgrade/interchangeable-filtering.md
upgrade/money-class.md
upgrade/phpstan-level-1.md
upgrade/upgrade-instructions-for-read-model-for-product-lists.md
upgrade/upgrading-monorepo.md

|Description, reason for the PR| wrongy merged `7.3` branch to `8.0` after https://github.com/shopsys/shopsys/pull/1428 was merged.

[shopsys] fixed links to docs in 8.0 branch

---

utils/releaser/src/ReleaseWorker/AfterRelease/MergeBranchToTheHigherBranchesReleaseWorker.php

|Description, reason for the PR| https://github.com/shopsys/shopsys/issues/1442 - this PR does not add the desired automation, however, at least it should ensure the links in docs are checked (and fixed) on a regular basis

[shopsys] release process: added instruction for fixing docs links when merging to higher branches

---

packages/framework/src/Component/Image/ImageFacade.php
packages/framework/src/Form/Admin/Advert/AdvertFormType.php
packages/framework/src/Form/Admin/Category/CategoryFormType.php
packages/framework/src/Form/Admin/Payment/PaymentFormType.php
packages/framework/src/Form/Admin/Product/Brand/BrandFormType.php
packages/framework/src/Form/Admin/Product/ProductFormType.php
packages/framework/src/Form/Admin/Slider/SliderItemFormType.php
packages/framework/src/Form/Admin/Transport/TransportFormType.php
packages/framework/src/Form/ImageUploadType.php
packages/framework/src/Model/Advert/AdvertDataFactory.php
packages/framework/src/Model/Advert/AdvertFacade.php
packages/framework/src/Model/Category/CategoryDataFactory.php
packages/framework/src/Model/Category/CategoryFacade.php
packages/framework/src/Model/Payment/PaymentDataFactory.php
packages/framework/src/Model/Payment/PaymentFacade.php
packages/framework/src/Model/Product/Brand/BrandDataFactory.php
packages/framework/src/Model/Product/Brand/BrandFacade.php
packages/framework/src/Model/Product/ProductFacade.php
packages/framework/src/Model/Slider/SliderItemDataFactory.php
packages/framework/src/Model/Slider/SliderItemFacade.php
packages/framework/src/Model/Transport/TransportDataFactory.php
packages/framework/src/Model/Transport/TransportFacade.php
packages/framework/src/Resources/styles/admin/todo.less
packages/framework/src/Resources/views/Admin/Form/imageuploadFields.html.twig
project-base/src/Shopsys/ShopBundle/Model/Payment/PaymentDataFactory.php
project-base/src/Shopsys/ShopBundle/Model/Product/Brand/BrandDataFactory.php
upgrade/UPGRADE-v8.1.0-dev.md

|Description, reason for the PR| Working with single image is the same as working with multiple images. There exists a new function `ImageFacade::manageImages`, which unites the calling of the orginal methods. It gives an advantage to easily switch between multiple and single image support for the entities. Moreover, it allows admin to delete single image.
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| Yes
|Have you read and signed our [License Agreement for contributions]| Yes

[shopsys] Unify working with images

---

packages/framework/src/Resources/config/services_test.yml
project-base/tests/ShopBundle/Functional/Model/Pricing/InputPriceRecalculationSchedulerTest.php
project-base/tests/ShopBundle/Functional/Twig/PriceExtensionTest.php
upgrade/upgrade-instructions-for-improved-data-fixtures-and-tests.md

|Description, reason for the PR| Some tests were failing, because they were expecting exact two currencies. This is no longer problem.

[project-base] fix functional tests for single domain

---

packages/framework/src/Resources/styles/admin/components/box/advanced-search.less
packages/framework/src/Resources/styles/admin/components/window/fixed-bar.less
packages/framework/src/Resources/views/Admin/Layout/base.html.twig
project-base/package.json
project-base/src/Shopsys/ShopBundle/Resources/styles/front/common/components/box/cart-empty.less
project-base/src/Shopsys/ShopBundle/Resources/styles/front/common/components/box/chooser.less
project-base/src/Shopsys/ShopBundle/Resources/styles/front/common/components/box/cookies.less
project-base/src/Shopsys/ShopBundle/Resources/styles/front/common/components/box/error-page.less
project-base/src/Shopsys/ShopBundle/Resources/styles/front/common/components/box/order.less
project-base/src/Shopsys/ShopBundle/Resources/styles/front/common/components/box/progress.less
project-base/src/Shopsys/ShopBundle/Resources/styles/front/common/components/in/action.less
project-base/src/Shopsys/ShopBundle/Resources/styles/front/common/components/list/categories.less
project-base/src/Shopsys/ShopBundle/Resources/styles/front/common/components/list/products-line.less
project-base/src/Shopsys/ShopBundle/Resources/styles/front/common/components/list/products.less
project-base/src/Shopsys/ShopBundle/Resources/styles/front/common/components/table/variants.less
project-base/src/Shopsys/ShopBundle/Resources/styles/front/common/components/window/popup.less
project-base/src/Shopsys/ShopBundle/Resources/styles/front/common/layout/footer.less
project-base/src/Shopsys/ShopBundle/Resources/styles/front/common/layout/header/search.less
project-base/src/Shopsys/ShopBundle/Resources/styles/front/common/layout/layout.less
project-base/src/Shopsys/ShopBundle/Resources/views/Front/Layout/base.html.twig
project-base/src/Shopsys/ShopBundle/Resources/views/Front/Layout/blank.html.twig
project-base/src/Shopsys/ShopBundle/Resources/views/Grunt/gruntfile.js.twig
upgrade/UPGRADE-v8.1.0-dev.md

|Description, reason for the PR| Removed old IE special css hacks, unifyed using flex width, old IE support removed from gruntile - generating special css ie file, updated autopreffixer settings for last browser 3 versions (removes red sign with using browserlist option name too).  
Result before changes:
CSS file size: 84kb + 95kb for old IE
CSS file size: 66.8kb (no other css files)

[shopsys] remove old IE support

---

packages/framework/src/Model/Product/ProductOnCurrentDomainFacade.php
packages/framework/src/Model/Product/ProductRepository.php
packages/frontend-api/src/Model/Resolver/Products/ProductResolver.php
packages/frontend-api/src/Model/Resolver/Products/ProductResolverMap.php
packages/frontend-api/src/Model/Resolver/Products/ProductsResolver.php
packages/frontend-api/src/Resources/config/graphql-types/MainVariantDecorator.types.yml
packages/frontend-api/src/Resources/config/graphql-types/ProductDecorator.types.yml
packages/frontend-api/src/Resources/config/graphql-types/QueryDecorator.types.yml
packages/frontend-api/src/Resources/config/graphql-types/RegularProductDecorator.types.yml
packages/frontend-api/src/Resources/config/graphql-types/VariantDecorator.types.yml
project-base/src/Shopsys/ShopBundle/Resources/graphql-types/MainVariant.types.yml
project-base/src/Shopsys/ShopBundle/Resources/graphql-types/Product.types.yml
project-base/src/Shopsys/ShopBundle/Resources/graphql-types/RegularProduct.types.yml
project-base/src/Shopsys/ShopBundle/Resources/graphql-types/Variant.types.yml
project-base/tests/FrontendApiBundle/Functional/Product/ProductVariantTest.php
upgrade/UPGRADE-v9.0.0-dev.md

|Description, reason for the PR| Added support for loading product variants and main variant via frontend API

[frontend-api] Product variants and main variant can now be loaded via frontend API

---

packages/framework/src/Component/Image/Image.php
packages/frontend-api/src/Model/Resolver/Image/ImagesResolver.php
packages/frontend-api/src/Resources/config/graphql-types/CategoryDecorator.types.yml
packages/frontend-api/src/Resources/config/graphql-types/ImageDecorator.types.yml
packages/frontend-api/src/Resources/config/graphql-types/ProductDecorator.types.yml
project-base/easy-coding-standard.yml
project-base/src/Shopsys/ShopBundle/Resources/graphql-types/Image.types.yml
project-base/tests/FrontendApiBundle/Functional/Image/ProductImagesTest.php
upgrade/UPGRADE-v9.0.0-dev.md

|Description, reason for the PR| Images are necessary part of e-commerce solutions. This PR enabled possibility to load images of all current entities with images.

[frontend-api] Entity images can now be loaded via fronted API

---

project-base/composer.json

|Description, reason for the PR| In #1392 we forgot to add the dependency to compose.json in project-base. This one fixing it.

[project-base] Fixed missing zalas/phpunit-injector into project-base

---

phpstan.neon
project-base/phpstan.neon
project-base/tests/FrontendApiBundle/Functional/Product/ProductTest.php
project-base/tests/FrontendApiBundle/Functional/Product/ProductVariantTest.php
project-base/tests/FrontendApiBundle/Functional/Product/ProductsTest.php
upgrade/UPGRADE-v9.0.0-dev.md

|Description, reason for the PR| Since #1392, `$domain` is available from parent class and should not be rewritten. Moreover, in parent class it's with protected visibility, and in these child classes with private, which is forbidden.  

[frontend-api] Removed unnecessary domain property from fe api tests

---

packages/http-smoke-testing/README.md
packages/http-smoke-testing/composer.json
packages/http-smoke-testing/src/Annotation/DataSet.php
packages/http-smoke-testing/src/Annotation/Parameter.php
packages/http-smoke-testing/src/Annotation/Skipped.php
packages/http-smoke-testing/src/HttpSmokeTestCase.php
packages/http-smoke-testing/src/RequestDataSetGenerator.php
packages/http-smoke-testing/src/RequestDataSetGeneratorFactory.php
packages/http-smoke-testing/src/RouteInfo.php
packages/http-smoke-testing/src/RouterAdapter/SymfonyRouterAdapter.php
packages/http-smoke-testing/src/Test/TestController.php
packages/http-smoke-testing/tests/Unit/RequestDataSetGeneratorTest.php
packages/http-smoke-testing/tests/Unit/RouterAdapter/SymfonyRouterAdapterTest.php
project-base/tests/ShopBundle/Performance/Page/AllPagesTest.php

|Description, reason for the PR| I wanted a solution for configuring my smoke tests directly on the controllers.

[shopsys] Add annotation based configuration for smoke tests

---

.ci/export_logs.sh

|Description, reason for the PR| When there were no codeception logs `.ci/export_logs.sh` failed on non-existing directory.

[shopsys] fixed copying codeception logs from pod

---

packages/framework/src/Model/Cart/CartFacade.php
packages/framework/src/Model/Cart/Exception/CartIsEmptyException.php
upgrade/UPGRADE-v7.3.3-dev.md

|Description, reason for the PR| Handle error when the last cart item has been removed
|Fixes issues| closes #1438  

[framework] handle error when the last cart item has been removed

---

composer.json
project-base/composer.json
upgrade/UPGRADE-v8.1.0-dev.md

|Description, reason for the PR| Hotfix. After releasing `symfony/monolog-bundle v3.5.0` the composer installs `monolog/monolog v2` which results in `Symfony 5 is required for Monolog 2 support. Please downgrade Monolog to version 1.`

[shopsys] fixed version of symfony/monolog-bundle

---

upgrade/UPGRADE-v8.1.0-dev.md

|Description, reason for the PR| this PR adding upgrade notes for added support for image and iframe lazy loading introduced in #1483

[project-base] - upgrade notes for lazyload

---

packages/framework/src/Controller/Admin/AccessController.php
packages/framework/src/Migrations/Version20191113133455.php
packages/framework/src/Migrations/Version20191113212555.php
packages/framework/src/Migrations/Version20191113231735.php
packages/framework/src/Model/Administrator/Administrator.php
packages/framework/src/Model/Administrator/AdministratorData.php
packages/framework/src/Model/Administrator/AdministratorDataFactory.php
packages/framework/src/Model/Administrator/AdministratorFacade.php
packages/framework/src/Model/Administrator/AdministratorRepository.php
packages/framework/src/Model/Administrator/Exception/EditingSuperadminException.php
packages/framework/src/Model/Administrator/Exception/MandatoryAdministratorRoleIsMissingException.php
packages/framework/src/Model/Administrator/Role/AdministratorRole.php
packages/framework/src/Model/Administrator/Role/AdministratorRoleData.php
packages/framework/src/Model/Administrator/Role/AdministratorRoleDataFactory.php
packages/framework/src/Model/Administrator/Role/AdministratorRoleDataFactoryInterface.php
packages/framework/src/Model/Administrator/Role/AdministratorRoleFacade.php
packages/framework/src/Model/Administrator/Role/AdministratorRoleFactory.php
packages/framework/src/Model/Administrator/Role/AdministratorRoleFactoryInterface.php
packages/framework/src/Model/Administrator/Security/AdministratorRolesChangedSubscriber.php
packages/framework/src/Model/Administrator/Security/AdministratorUserProvider.php
packages/framework/src/Model/Security/Roles.php
packages/framework/src/Resources/config/services.yml
packages/framework/tests/Unit/Model/Administrator/AdministratorTest.php
project-base/app/config/packages/security.yml
project-base/tests/ShopBundle/Smoke/Http/RouteConfigCustomization.php
upgrade/UPGRADE-v9.0.0-dev.md

|Description, reason for the PR| Roles are now stored in database so it is possible to easily add other roles to restrict access to some sections of administration.
|[BC breaks] Yes 
|Fixes issues| closes #1347, closes #1349  

[framework] administrator roles are stored in database

---

composer.json
packages/framework/composer.json
project-base/composer.json
upgrade/UPGRADE-v8.0.1-dev.md

|Description, reason for the PR| Hotfix. After releasing `symfony/monolog-bundle` `v3.5.0` the composer installs `monolog/monolog` v2 which results in `Symfony 5 is required for Monolog 2 support. Please downgrade Monolog to version 1.`

[shopsys] fixed monolog-bundle dependency

---

project-base/.travis.yml
project-base/scripts/install.sh
upgrade/UPGRADE-v8.1.0-dev.md

|Description, reason for the PR| On MacOS when running script `install.sh` there was created duplicity of `docker-compose.yml` named as `docker-compose.yml-E` because of wrong usage of `sed` command. This PR will fix it.

[project-base] fixed usage of sed command on macos

---

project-base/src/Shopsys/ShopBundle/Resources/views/Front/Form/theme.html.twig
upgrade/UPGRADE-v8.1.0-dev.md

|Description, reason for the PR| preserve custom checkbox CSS classes
|Fixes issues| closes  #1520  

preserve custom checkbox CSS classes

---

packages/framework/build.xml

|Description, reason for the PR| This PR fixes failing `./phing translations-dump` command due to parse error in minified JS files. In #1485 we introduced basic styleguide. This styleguide has minified js files in plugins folder (similarly as in frontend folder). These files should not be taken into account when dumping translations.

[framework] exclude styleguide plugins from dumping translations

---

docs/frontend/lazyload.md
packages/backend-api/install/app/config/parameters_common.yml.patch
packages/framework/src/Resources/config/parameters_common.yml
packages/framework/src/Resources/config/services/twig.yml
packages/framework/src/Twig/ImageExtension.php
packages/read-model/src/Resources/config/services.yml
project-base/app/config/parameters_common.yml
project-base/tests/ReadModelBundle/Functional/Twig/ImageExtensionTest.php
project-base/tests/ShopBundle/Functional/Twig/ImageExtensionTest.php
upgrade/UPGRADE-v8.1.0-dev.md

|Description, reason for the PR| PR #1483 introduced a BC break. This PR fixes it and making a lazyload configurable.

[shopsys] made image lazy loading configurable

---

project-base/src/Shopsys/ShopBundle/Resources/styles/styleguide/main.less

|Description, reason for the PR| We are importing css files for styleguide like a less file even they are css. This cause troubles for older grunt-contrib-less package which results in wrong calculations.

[project-base] fixed importing css files for styleguide

---

upgrade/UPGRADE-v9.0.0-dev.md
upgrade/upgrade-instructions-for-symfony-flex.md

|Description, reason for the PR| In #1492 we introduced Symfony Flex. This PR adds upgrade instructions to upgrade application to Symfony Flex structure and namespaces
already existing upgrade notes were updated as they are meant to be done after

[shopsys] added upgrade notes for Symfony Flex

---

packages/framework/src/Component/Log/SlowLogSubscriber.php

|Description, reason for the PR| When request was redirected or ends with error (`404`, `500`) then slow log didn't correctly calculate requestTime. This PR increases `initStartTime` priority, so it will be always called even if there is error or redirect and `SlowLogSubscriber` will correctly log message.
Example output on 404 page:
```
[2019-09-19 10:21:43] slow.NOTICE: 1568881303.373  /image.php?id=635&width=294&height=487
```
Example output on redirect:
```
[2019-09-19 …
```

Increase slow log priority to prevent miscalculation request time

---

composer.json
packages/framework/composer.json
packages/product-feed-google/composer.json
packages/product-feed-heureka/composer.json
packages/product-feed-zbozi/composer.json
project-base/composer.json

|Description, reason for the PR| doctrine/persistence 1.3 seems to be released prematurely and includes BC breaks that were not intended so we decided to restrict i to version 1.2

[shopsys] restricted doctrine/persistence to version 1.2

---

project-base/tests/ShopBundle/Acceptance/acceptance/OrderCest.php
upgrade/UPGRADE-v7.3.3-dev.md

|Description, reason for the PR| Sometimes OrderCast failed on selecting right payment method. This PR should fix it.

[project-base] OrderCest is now more reliable

---

.ci/export_logs.sh

|Description, reason for the PR| In #1492 we changed log folder name to match Symfony's standard (logs -> log). In export_logs script this change was not taken into account and this PR fixes it.

[shopsys] fixed exporting logs from acceptance tests in kubernetes

---

packages/framework/src/Resources/translations/messages.cs.po

|Description, reason for the PR| In #1425 were added translation keys without translations. This PR fixes this.

[framework] added missing translations for promo codes

---

project-base/src/Resources/scripts/frontend/cart/cartRecalculator.js
project-base/src/Resources/scripts/frontend/components/ajaxMoreLoader.js
project-base/src/Resources/scripts/frontend/lazyLoadInit.js
project-base/src/Resources/scripts/frontend/product/productList.AjaxFilter.js
project-base/templates/Front/Content/Cart/index.html.twig

|Description, reason for the PR| After adding lazyload, we need to call lazyload function manually after cart recalculation. Price with VAT position in table was too on right. Now it is correct.
|Fixes issues| closes #1570 
Screen before:
https://www.screencast.com/t/M4lCCmm4
Screen after:

[project-base] - lazyload call after cart recalculation, price with VAT table position

---

docs/frontend-api/introduction-to-frontend-api.md
docs/model/front-end-product-filtering.md
packages/framework/src/Component/Image/ImageFacade.php
packages/framework/src/Model/Product/ProductOnCurrentDomainElasticFacade.php
packages/framework/src/Model/Product/ProductOnCurrentDomainFacade.php
packages/framework/src/Model/Product/ProductOnCurrentDomainFacadeInterface.php
packages/framework/src/Model/Product/Search/Export/ProductSearchExportWithFilterRepository.php
packages/framework/src/Model/Product/Search/FilterQuery.php
packages/frontend-api/src/Model/Resolver/Image/ImagesResolver.php
packages/frontend-api/src/Model/Resolver/Price/PriceResolver.php
packages/frontend-api/src/Model/Resolver/Products/ProductResolverMap.php
packages/frontend-api/src/Model/Resolver/Products/ProductsResolver.php
project-base/src/Resources/definition/product/1.json
project-base/src/Resources/definition/product/2.json
project-base/tests/App/Functional/Model/Product/Search/ProductSearchExportWithFilterRepositoryTest.php
project-base/tests/FrontendApiBundle/Functional/Image/ProductImagesTest.php
project-base/tests/FrontendApiBundle/Functional/Product/ProductTest.php
project-base/tests/FrontendApiBundle/Functional/Product/ProductsTest.php
project-base/tests/FrontendApiBundle/Test/GraphQlTestCase.php
upgrade/UPGRADE-v9.0.0-dev.md

|Description, reason for the PR| Our FE API used ProductOnCurrentDomainFacade and not ProductOnCurrentDomainFacadeInterface so there was no way to choose if the data should be taken from database or elasticsearch

[shopsys] Added possibility to change source that FE API gets data from

---

packages/framework/src/Component/AnnotatedRouteControllerLoader.php

|Description, reason for the PR| routes do not have prefix `shopsys_shop_` yet from using flex. It caused duplication of routes after override controller without overriden action (one with prefix `app_admin_` and another one only with prefix `admin_`). It could cause problems with breadcumb etc... Another problem is all new routes in administration have annoying and inconsistent prefix `app_`

[framework] remove route prefix (app_) for project-base

---

packages/framework/composer.json

|Description, reason for the PR| In #1492 `symfony/symfony` dependency was removed and replaced with individual packages. Unfortunatelly `symfony/stopwatch` was forgotten in project composer file causing installation of packages without dev dependencies fails on non-existing classes. This PR fixes it.
Upgrade notes not written as previous change is not part of any released version.

[project-base] added missing symfony/stopwatch dependency

---

packages/framework/src/Resources/views/Admin/Content/Vat/listGrid.html.twig

|Description, reason for the PR| Fixes tooltip position and size in VAT edit form.
|Fixes issues| closes #1556  

[framework] VAT edit form tooltip

---

packages/framework/src/Controller/Admin/AdvertController.php
packages/framework/src/Controller/Admin/BrandController.php
packages/framework/src/Controller/Admin/SliderController.php

|Description, reason for the PR| This PR added variable annotation to help PhpStan understand returned variable. More description follows.
Symfony/symfony#34949 (on the line  https://github.com/symfony/symfony/pull/34949/files#diff-064e58dbe11951327d614e6922caaae5R418) added annotation of multiple types, but the correct type depends on the version of installed `doctrine/persistence` package. 
The other type is always incorrect. 
PhpStan checks return types and fail with error
```
Call to method …
```

[framework] fixed phpstan issue with changed namespace of doctrine/persistence

---

project-base/composer.json

|Description, reason for the PR| In #1545  was introduced webpack encore and package `webpack-encore-bundle` that is needed to build application was forgotten to add to project-base `composer.json`. That means you will be not able to build new application after you will release SSFW 9.0.

[project-base] add missing dependency for webpack encore in composer.json

---

upgrade/UPGRADE-v9.0.0-dev.md

|Description, reason for the PR| Fix of NPM permission was accidentaly merged in #1584. This PR adds missing upgrade notes.

[shopsys] added upgrade notes to fix npm permission issue

---

packages/backend-api/composer.json
packages/coding-standards/composer.json
packages/form-types-bundle/composer.json
packages/framework/composer.json
packages/frontend-api/composer.json
packages/google-cloud-bundle/composer.json
packages/http-smoke-testing/composer.json
packages/migrations/composer.json
packages/plugin-interface/composer.json
packages/product-feed-google/composer.json
packages/product-feed-heureka-delivery/composer.json
packages/product-feed-heureka/composer.json
packages/product-feed-zbozi/composer.json
packages/read-model/composer.json
project-base/composer.json

|Description, reason for the PR| This PR aliases `master` branch as version `9.0.x-dev`. More description follows.
Master branch is now the development version of release 9.0. Anyone who already has `9.0.x-dev`  as the version constraint in their composer.json file will get outdated code as new features and fixes will be merged into master and not into branch 9.0. (version 9.0.x-dev is created automatically if branch 9.0 exists).
To ensure a smooth developer experience, `master` branch will be from …

[shopsys] added branch-alias master - 9.0.x-dev for all packages

---

packages/framework/src/Resources/views/Admin/Content/Customer/detail.html.twig

|Description, reason for the PR| Fixes wrong variable name. From Controller comes `customerUser`, but template used `user`. That caused the save button was labeled "Create" even on edit page.

[framework] fixed wrong variable name in customer detail template

---

packages/framework/assets/js/admin/components/fixedBar.js
packages/framework/assets/js/admin/components/symfonyToolbarSupport.js

|Description, reason for the PR| When I have enable development mode and have  active symfony tool bar I don't see full window-fixed-bar element with action buttons in admin (on product detail page I don't see button for save changes). However when I hide/show symfony tool bar, window-fixed-bar element is moved. We moved window-fixed-bar element after page is loaded (and when symfony toolbar is enable)
|Fixes issues| closes #1631 

[framework] fixed window fix bar in development mode

---

upgrade/upgrade-instructions-for-symfony-flex.md

|Description, reason for the PR| Fixed wrong filename of migrations-lock.yml file in upgrade instructions for flex.

[shopsys] fix typo in upgrade-instructions-for-symfony-flex.md

---

upgrade/upgrade-instructions-for-symfony-flex.md

|Description, reason for the PR| Fixed upgrade notes for Symfony Flex (path of source codes in easy-coding-standards.yml). Just a small typo, however it can make developers very sad :laughing: 

[shopsys] upgrade-instructions-for-symfony-flex.md - typo

---

project-base/config/shopsys-routing/routing_front_cs.yml
project-base/config/shopsys-routing/routing_front_en.yml
upgrade/UPGRADE-v9.0.0-dev.md

|Description, reason for the PR| paths for localized routes `front_product_search` are missing trailing slash - this is inconsistent with the other paths in the application and might cause potential troubles, see https://shopsysframework.slack.com/archives/C5Q2MM677/p1558522300005100 for more information
|[BC breaks](https://github.com/shopsys/shopsys/blob/master/docs/contributing/backward-compatibility-promise.md)| Possibly - there might be a problem if a project already contains `hledani/`, or `search/` paths, e.g. when there is a product with such a name (and friendly URL). The change might also cause problems with SEO  …

[project-base] unification of URL paths

---

packages/framework/src/Component/Elasticsearch/ElasticsearchStructureManager.php

- "generate-build-version" phing target was deprecated in 7.3.0 and removed in 8.0.0
- it was replaced by "build-version-generate" phing target
|Description, reason for the PR| fixed misleading hint as the target does not exist anymore
|Fixes issues| closes #1443  

[framework] ElasticsearchStructureManager: fix error message hint

---

upgrade/UPGRADE-v8.1.0.md

|Description, reason for the PR| redirect of logged user from registration page (#1285) the behavior was changed after code review, but upgrade note has not been updated

UPGRADE-v8.1.0.md: fix typo

---

project-base/config/paths.yml
project-base/src/DataFixtures/Demo/ImageDataFixture.php
upgrade/UPGRADE-v9.0.0-dev.md

- when trailing slash was used in the path, there were two slashes in the path to domain icon (see DomainExtension::getDomainIconHtml())
- when using abstract filesystem (S3), the icon was not found when there were two slashes in the path
|Description, reason for the PR| I could not see domain icons on my project that uses S3 filesystem

[project-base] fix path resolving for domain icons

---

project-base/src/DataFixtures/Demo/ProductDataFixture.php

|Description, reason for the PR| Product sellable in the future should be in the future even after 11.2.2020 :trollface: 

[project-base] sellingFrom moved to the future for not yet sellable product in data fixtures

---

packages/framework/src/Model/AdvancedSearch/Filter/ProductCategoryFilter.php

|Description, reason for the PR| Categories in advanced search have only one level of nesting. This PR simply adds spaces before the category name according to the nesting level.

[framework] Padding categories by level in advanced search
