shopsys/shopsys

composer.json, packages/form-types-bundle/composer.json, packages/framework/composer.json, packages/http-smoke-testing/composer.json, packages/migrations/composer.json, packages/plugin-interface/composer.json, packages/product-feed-google/composer.json, packages/product-feed-heureka-delivery/composer.json, packages/product-feed-heureka/composer.json, packages/product-feed-interface/composer.json, packages/product-feed-zbozi/composer.json
|Description, reason for the PR| Cleaner reading of `composer.json`
|BC breaks| No
|License| MIT
|Have you read and signed our [License Agreement for contributions](https://www.shopsys-framework.com/license-agreement)?| Yes
=> composer: simplify autoloading paths to make it more readable

docs/contributing/guidelines-for-dependencies.md
|Description, reason for the PR| typo
|BC breaks| No
|Fixes issues| typo
=> fixed typo in docs

CHANGELOG.md, docs/introduction/required-php-configuration.md
=> Documentation: add redis extension to required php extensions

packages/framework/src/Form/Admin/Advert/AdvertFormType.php, packages/framework/src/Form/Admin/Heureka/HeurekaShopCertificationFormType.php, packages/framework/src/Form/Admin/Script/ScriptFormType.php, packages/framework/src/Resources/styles/admin/components/form/line.less, packages/framework/src/Resources/styles/admin/core/form/input.less, packages/framework/src/Resources/styles/admin/todo.less, packages/framework/src/Resources/views/Admin/Content/Product/edit.html.twig, packages/framework/src/Resources/views/Admin/Content/Superadmin/cssDocumentation.html.twig, packages/framework/src/Resources/views/Admin/Form/theme.html.twig
|BC breaks| No
|Standards and tests pass| ?
|License| MIT
|Have you read and signed our [License Agreement for contributions](https://www.shopsys-framework.com/license-agreement)?| Yes
=> Tg bg 1294

CHANGELOG.md, packages/framework/src/Resources/scripts/common/validation/ConstraintUniqueEmail.js, packages/framework/src/Resources/views/Admin/Layout/base.html.twig
=> [BG-2696] Admin: Customer cannot be saved + fixed js error from administration console (wrong order of javascripts loaded)

packages/framework/src/Resources/styles/admin/todo.less, project-base/docker/php-fpm/Dockerfile, project-base/src/Shopsys/ShopBundle/Resources/styles/front/common/components/box/slider.less
|BC breaks| No
|Standards and tests pass| ?
|License| MIT
|Have you read and signed our [License Agreement for contributions](https://www.shopsys-framework.com/license-agreement)?| Yes
=> Tg bg 2140

docs/introduction/required-php-configuration.md, project-base/docker/php-fpm/php-ini-overrides.ini
- change of configuration of OPCache should provide performance boost
|Description, reason for the PR| [US-3964]
=> [US-3964] Changed recommended configuration of PHP - OPCache

CHANGELOG.md, UPGRADE.md
|Description, reason for the PR| markdown links are broken
=> fix links in CHANGELOG.md and UPGRADE.md

docs/cookbook/jenkins-configuration.md, docs/installation/installation-using-docker-application-setup.md
|Description, reason for the PR| US-3970
|BC breaks| No
|Fixes issues| US-3970
=> [US-3970] Recommended to optimize composer autoload in production

docs/index.md
|Description, reason for the PR| the link was missing so the cookbook was hard to discover
=> docs: added link to "Adding New Attribute to an Entity" cookbook to knowledgebase index

docs/installation/installation-using-docker-linux.md, docs/installation/installation-using-docker-macos.md, docs/installation/installation-using-docker-windows-10-pro-higher.md, docs/installation/native-installation.md
|Description, reason for the PR| all other options are explained so there should be explanation for "stability" option as well
|Fixes issues| https://github.com/shopsys/shopsys/issues/151
=> installation guides: added explanation of composer create-project "stability" option

packages/framework/src/Resources/styles/admin/components/form/line.less
=> admin: thinner lines between form lines using .form-line__js

packages/framework/src/Command/LoadDataFixturesCommand.php, packages/framework/src/Model/AdvancedSearchOrder/Filter/OrderEmailFilter.php
|Description, reason for the PR| fix build
|BC breaks| No
|Fixes issues| phpcs_fixer standards check
=> Removed unused use statements

CHANGELOG.md, UPGRADE.md, composer.json, packages/framework/composer.json, packages/framework/src/Component/Grid/GridView.php, packages/framework/src/Model/Feed/FeedXmlWriter.php, packages/framework/src/Resources/views/Admin/Content/BestsellingProduct/list.html.twig, packages/framework/src/Resources/views/Admin/Content/Category/list.html.twig, packages/framework/src/Resources/views/Admin/Content/Feed/listGrid.html.twig, packages/framework/src/Resources/views/Admin/Content/Image/overview.html.twig, packages/framework/src/Resources/views/Admin/Content/Mail/template.html.twig, packages/framework/src/Resources/views/Admin/Content/Product/detail.html.twig, packages/framework/src/Resources/views/Admin/Form/fileuploadFields.html.twig, packages/framework/src/Resources/views/Admin/Form/theme.html.twig, packages/product-feed-google/composer.json, packages/product-feed-google/src/Resources/views/feed.xml.twig, packages/product-feed-heureka-delivery/composer.json, packages/product-feed-heureka/composer.json, packages/product-feed-heureka/src/Resources/views/feed.xml.twig, packages/product-feed-zbozi/composer.json, packages/product-feed-zbozi/src/Resources/views/feed.xml.twig, project-base/composer.json, project-base/src/Shopsys/ShopBundle/Resources/views/Front/Form/theme.html.twig
=> [US-3323] Update to twig 2.x

CHANGELOG.md, packages/framework/src/Resources/views/Admin/Content/TransportAndPayment/freeTransportAndPaymentLimitSetting.html.twig
|Description, reason for the PR| .
|BC breaks| No
|Fixes issues| #158
=> [BG-2820] Admin: Validation for free shipping is inconsistent

CHANGELOG.md, packages/framework/src/Resources/scripts/admin/components/autocompleteSelectbox.js, packages/framework/src/Resources/views/Admin/Inline/FixedBar/fixedBar.html.twig
|BC breaks| No
|Fixes issues| #139 
=> show selectbox options

CHANGELOG.md, packages/framework/src/Controller/Admin/DomainController.php
|Description, reason for the PR| fix bug for domain icon upload save
|Fixes issues| #239 
=> Admin: changed domain icon in e-shop domain administration can be saved

packages/monorepo-tools/README.md
|Description, reason for the PR| the package is mentioned in the curated list https://github.com/korfuri/awesome-monorepo#migration-tools
=> Monorepo Tools: Awesome mentioned badge

CHANGELOG.md, packages/coding-standards/README.md, packages/coding-standards/shopsys-coding-standard.yml, packages/coding-standards/src/Sniffs/ObjectIsCreatedByFactorySniff.php, packages/framework/autoload-easy-coding-standard.yml, project-base/autoload-easy-coding-standard.yml
|Description, reason for the PR| code needs to follow agreed rules
|BC breaks| No
=> First architectonical codesniff

packages/framework/src/Model/Cart/Watcher/CartWatcherFacade.php
=> optimize check of modifications in cart

.gitignore, CHANGELOG.md, build.xml, docs/cookbook/adding-new-attribute-to-an-entity.md, docs/index.md, docs/introduction/database-migrations.md, docs/introduction/phing-targets.md, packages/framework/src/Resources/config/services.yml, packages/migrations/README.md, packages/migrations/src/Command/AbstractCommand.php, packages/migrations/src/Command/CheckDatabaseSchemaCommand.php, packages/migrations/src/Command/CheckOrmMappingCommand.php, packages/migrations/src/Command/GenerateMigrationCommand.php, packages/migrations/src/Command/GetCountOfMigrationsToExecuteCommand.php, packages/migrations/src/Command/MigrateCommand.php, packages/migrations/src/Component/Doctrine/Migrations/Configuration.php, packages/migrations/src/Component/Doctrine/Migrations/MigrationsFinder.php, packages/migrations/src/Component/Doctrine/Migrations/MigrationsLocator.php, packages/migrations/src/Component/Doctrine/Migrations/MigrationsLock.php, packages/migrations/src/Resources/config/services.yml, packages/migrations/tests/Unit/Component/Doctrine/Migrations/MigrationsLocatorTest.php, packages/migrations/tests/Unit/Component/Doctrine/Migrations/MigrationsLockTest.php, packages/migrations/tests/Unit/Component/Doctrine/Migrations/Resources/Version20180101000001.php, packages/migrations/tests/Unit/Component/Doctrine/Migrations/Resources/Version20180101000002.php, packages/migrations/tests/Unit/Component/Doctrine/Migrations/Resources/Version20180101000003.php, packages/migrations/tests/Unit/Component/Doctrine/Migrations/Resources/Version20180101000004.php, packages/migrations/tests/Unit/Component/Doctrine/Migrations/Resources/migrations-lock.yml
=> [US-3636] Maintaining the order of database migration

CHANGELOG.md, packages/framework/src/Model/Order/FrontOrderData.php, packages/framework/src/Model/Order/OrderFacade.php, packages/framework/tests/Unit/Model/Order/OrderFacadeHeurekaTest.php, project-base/src/Shopsys/ShopBundle/Controller/Front/OrderController.php, project-base/src/Shopsys/ShopBundle/Form/Front/Order/PersonalInfoFormType.php, project-base/src/Shopsys/ShopBundle/Resources/translations/messages.cs.po, project-base/src/Shopsys/ShopBundle/Resources/translations/messages.en.po, project-base/src/Shopsys/ShopBundle/Resources/views/Front/Content/Order/step3.html.twig, project-base/tests/ShopBundle/Unit/Form/Front/Order/PersonalInfoFormTypeTest.php
|Description, reason for the PR| US-4121
|BC breaks| No
=> US-4121 Sending personal data to Heureka can be disabled

packages/migrations/src/Command/GenerateMigrationCommand.php
|Description, reason for the PR| The grammatical error was really annoying for me :slightly_smiling_face: 
=> GenerateMigrationCommand: fixed grammar in info message

docs/installation/native-installation.md
|Description, reason for the PR| Behavior of sort by name is platform specific 
|BC breaks| No
|Fixes issues| #170
=> docs: sorting is different on different platforms

docs/introduction/monorepo.md
|Description, reason for the PR| we want docs to be up to date :slightly_smiling_face: 
=> docs minor update (monorepo.md)

CHANGELOG.md, packages/monorepo-tools/README.md, packages/monorepo-tools/rewrite_history_from.sh, packages/monorepo-tools/rewrite_history_into.sh, packages/monorepo-tools/tag_refs_backup.sh, packages/monorepo-tools/tag_refs_move_to_original.sh
|Description, reason for the PR| US-3861
|BC breaks| No
=> [US-3861] Monorepo split allow adding new package when monorepo is already tagged

packages/framework/src/Resources/styles/admin/core/form/inline.less, packages/framework/src/Resources/styles/admin/main.less
|Description, reason for the PR| Fixed alignment button with input
|Fixes issues| #144
=> Fixed alignment button with input

CHANGELOG.md, packages/product-feed-google/.travis.yml, packages/product-feed-heureka-delivery/.travis.yml, packages/product-feed-heureka/.travis.yml, packages/product-feed-zbozi/.travis.yml
|Description, reason for the PR| to have travis build passing
|Fixes issues| #321 
=> Packages that depend on shopsys/framework need redis extension enabled

CHANGELOG.md, packages/product-feed-heureka/src/Model/Product/HeurekaProductDomainFacade.php, packages/product-feed-zbozi/src/Model/Product/ZboziProductDomainFacade.php
- execution of flush inside loop is bad practice
- execution of flush outside of loop will increase performance
|Description, reason for the PR|  execution of flush inside loop is bad practice
|Fixes issues| (#326)
=> flushes executed in loops are now executed outside of loop

CHANGELOG.md, project-base/.gitignore
|Description, reason for the PR| To allow indidual changes to docker-sync file without need to change file in the repository itself
=> docker-sync.yml added to gitignore to allow individual configuration

CHANGELOG.md, docs/contributing/guidelines-for-pull-request.md
|Description, reason for the PR| document was really badly formatted, so I tried to make it better
|BC breaks| No -->
=> guidelines-for-pull-request.md: fixed indentation of lines and code blocks

project-base/build.xml
|Description, reason for the PR| The descriptions were just wrong and misleading.
=> fix phing target descriptions

CHANGELOG.md, docs/wip_glassbox/form-extension.md, packages/framework/src/Form/Admin/Product/Brand/BrandFormType.php, packages/framework/src/Resources/views/Admin/Content/Brand/detail.html.twig
|Description, reason for the PR| brand form should be fully extensible via BrandFormType
=> Admin: brand form is rendered via BrandFormType

CHANGELOG.md, UPGRADE.md, packages/form-types-bundle/composer.json, packages/framework/composer.json, packages/migrations/composer.json, packages/plugin-interface/composer.json, packages/product-feed-google/composer.json, packages/product-feed-heureka-delivery/composer.json, packages/product-feed-heureka/composer.json, packages/product-feed-zbozi/composer.json, project-base/composer.json
|Description, reason for the PR| Release of 7.0.0-alpha4
|BC breaks| No
=> Release of 7.0.0-alpha4

UPGRADE.md, docker/conf/docker-compose-mac.yml.dist, docker/conf/docker-compose-win.yml.dist, docker/conf/docker-compose.yml.dist, docs/docker/docker-troubleshooting.md, project-base/docker/conf/docker-compose-mac.yml.dist, project-base/docker/conf/docker-compose-win.yml.dist, project-base/docker/conf/docker-compose.yml.dist
|Description, reason for the PR| add info to upgrade.md how to make Elasticsearch run
=> UPGRADE.md: added information how to make Elasticsearch work

CHANGELOG.md, UPGRADE.md, docker/conf/docker-compose-mac.yml.dist, docker/conf/docker-compose-win.yml.dist, docker/conf/docker-compose.yml.dist, docs/installation/native-installation.md, project-base/app/config/parameters.yml.dist, project-base/docker/conf/docker-compose-mac.yml.dist, project-base/docker/conf/docker-compose-win.yml.dist, project-base/docker/conf/docker-compose.yml.dist, project-base/docker/php-fpm/Dockerfile
|Description, reason for the PR| .Upgrading PostgreSQL version to 10 so we are up to current version of postgres, to fix some incompatibilities using lower version
=> Upgrade PostgreSQL to version 10

CHANGELOG.md, packages/coding-standards/easy-coding-standard.yml, packages/framework/src/Component/Grid/InlineEdit/InlineEditService.php, packages/framework/src/Component/Image/ImageDeleteDoctrineListener.php, packages/framework/src/Component/UploadedFile/UploadedFileDeleteDoctrineListener.php, packages/framework/src/DataFixtures/Demo/AdministratorDataFixture.php, packages/framework/src/Form/Admin/Product/ProductEditFormType.php, packages/framework/src/Model/Payment/IndependentPaymentVisibilityCalculation.php, packages/framework/src/Model/Transport/IndependentTransportVisibilityCalculation.php, packages/framework/src/Twig/DomainExtension.php, packages/framework/src/Twig/ImageExtension.php, packages/framework/src/Twig/SeoExtension.php, packages/framework/src/Twig/ShopInfoExtension.php, packages/framework/tests/Unit/Component/EntityExtension/EntityNameResolverTest.php, packages/product-feed-heureka/src/DataFixtures/HeurekaProductDataFixture.php, project-base/app/Environment.php, project-base/easy-coding-standard.yml, project-base/src/Shopsys/ShopBundle/Form/Front/Order/DomainAwareOrderFlowFactory.php
|Description, reason for the PR| Removing forgotten dependencies that are never called
|BC breaks| No
Found with following sniff:
```yaml
services:
SlevomatCodingStandard\Sniffs\Classes\UnusedPrivateElementsSniff: ~
```
Must have to keep your code clean from this
=> Remove unused dependencies + Add UnusedPrivateElementsSniff

CHANGELOG.md, UPGRADE.md, packages/form-types-bundle/composer.json, packages/framework/composer.json, packages/framework/src/Form/Admin/Product/ProductFormType.php, packages/framework/src/Resources/translations/messages.cs.po, packages/framework/src/Resources/translations/messages.en.po, packages/migrations/composer.json, packages/plugin-interface/composer.json, packages/product-feed-google/composer.json, packages/product-feed-heureka-delivery/composer.json, packages/product-feed-heureka/composer.json, packages/product-feed-zbozi/composer.json, project-base/composer.json
|Description, reason for the PR| new version of Shopsys Framework  will be released
=> release alpha5

CHANGELOG.md, project-base/src/Shopsys/ShopBundle/Form/Front/Order/OrderFlow.php
|Description, reason for the PR|.see #419 
|BC breaks| No
|Fixes issues| #419 
=> Order flow fix - function call on string (#419)

docs/cookbook/adding-a-new-advert-position.md
|Description, reason for the PR| The cookbook is missing this information - there is a section with images overwiew in admin that should be modified when adding new banner position
|Standards and tests pass| No (they fail on master)
=> adding-a-new-advert-position.md: added instructions for editing images.yml config file

project-base/src/Shopsys/ShopBundle/Resources/config/services_test.yml, project-base/tests/ShopBundle/Database/Model/Article/ArticleTest.php, project-base/tests/ShopBundle/Unit/Model/Article/ArticleTest.php
|Description, reason for the PR| to have proof that extension is working
|Fixes issues| #153
=> project-base: extended Article tests

CHANGELOG.md, project-base/src/Shopsys/ShopBundle/Controller/Front/ErrorController.php, project-base/src/Shopsys/ShopBundle/Controller/Test/ErrorHandlerController.php, project-base/tests/ShopBundle/Acceptance/acceptance/ErrorHandlingCest.php
|Description, reason for the PR| US-3664
|BC breaks| No
=> [US-3664] Unable to resolve domain error page

docs/installation/installation-using-docker-linux.md, docs/installation/installation-using-docker-macos.md, docs/installation/installation-using-docker-windows-10-pro-higher.md, docs/installation/native-installation.md
|Description, reason for the PR| I couln't finish installation because install guide is for dev-master but you download last release.
|BC breaks| ???
|Fixes issues| #441 
=> Change recommended stability to dev for installation

CHANGELOG.md, UPGRADE.md, docker/conf/docker-compose-mac.yml.dist, docker/conf/docker-compose-win.yml.dist, docker/conf/docker-compose.yml.dist, project-base/docker/conf/docker-compose-mac.yml.dist, project-base/docker/conf/docker-compose-win.yml.dist, project-base/docker/conf/docker-compose.yml.dist, project-base/docker/postgres/postgres.conf
|Description, reason for the PR| #426
|BC breaks| No
|Fixes issues|  #426
=> Improve Postgres configuration to improve performance

project-base/src/Shopsys/ShopBundle/Resources/styles/front/common/components/form/error.less, project-base/src/Shopsys/ShopBundle/Resources/styles/front/common/layout/footer.less, project-base/src/Shopsys/ShopBundle/Resources/views/Front/Content/ContactForm/contactForm.html.twig, project-base/src/Shopsys/ShopBundle/Resources/views/Front/Content/Registration/register.html.twig
|Fixes issues| https://github.com/shopsys/shopsys/issues/142
=> Fixes error notice in choice label: issue #142

docs/introduction/framework-extensibility.md, docs/wip_glassbox/entity-extension.md
|Description, reason for the PR| US-4563
|BC breaks| No
=> [US-4563] Demoshop experiences documentation

microservices/product-search-export/docker/Dockerfile, microservices/product-search-export/docker/docker-after-start, microservices/product-search/docker/Dockerfile, microservices/product-search/docker/docker-after-start
|Description, reason for the PR| this should make the first request on the microservice significantly faster, preventing hitting the occasional timeout during CI builds
=> microservices: warm up Symfony cache during start-up

docs/kubernetes/continuous-integration-using-kubernetes.md
|Description, reason for the PR| There is a typo in link to another file :slightly_smiling_face: 
=> [framework] fixed typo in continuous-integration-using-kubernetes.md

docs/index.md
|Description, reason for the PR| The information about the second microservice was missing
=> [shopsys] Microservice Product Search Export added to docs index

docs/installation/installation-using-docker-windows-10-pro-higher.md
|Description, reason for the PR| We have current info about performance on Windows so it is good to update it.
=> [shopsys] Info about performance on Windows updated in installation guide

UPGRADE.md, docker/conf/docker-compose-mac.yml.dist, docker/conf/docker-sync.yml.dist, docs/docker/docker-troubleshooting.md, docs/installation/installation-using-docker-macos.md, project-base/docker/conf/docker-compose-mac.yml.dist, project-base/docker/conf/docker-sync.yml.dist
A solution of a need to improve application performance in the docker on Mac as well as the solution of the problem of frequent freezing of the docker sync
|Description, reason for the PR| A solution of a need to improve application performance in the docker on Mac as well as the solution of the problem of frequent freezing of the docker sync
|BC breaks| No
=> [shopsys] Settings for docker on mac are now more optimized

README.md
|Description, reason for the PR| -
=> Basic info in readme updated according to current USPs

README.md
|Description, reason for the PR| -
=> [shopsys] Current state updated and roadmap removed from readme

README.md
|Description, reason for the PR| In readme there is no info about future of this project
=> [shopsys] Added info about stable release into readme

packages/framework/src/Form/Admin/Product/ProductFormType.php
- `mapped=false` was replaced by `inherit_data=true`, the submitted data are passed into the data object correctly now
- `variantGroup` is displayed below the product name for both main variants and variants (previously, it was displayed only for variants and above the product name)
- for variants, `mainVariantUrl` with a link to the main variant and `variantAlias` for setting the alias are shown
- for main variants, a products picker `variants` is shown
|Description, reason for the PR| product variants are not working as intended - no variant-specific data are mapped to the data object and fields for main variant are not even shown properly
|Have you read and signed …
=> [framework] admin: fix product form for product variants

UPGRADE.md, docs/installation/installation-using-docker-macos.md
|Description, reason for the PR| We were missing the information about recommended setting for Docker for Mac
=> docs: added info about recommended settings for Docker for Mac

docs/installation/installation-using-docker-linux.md, docs/installation/installation-using-docker-macos.md, docs/installation/installation-using-docker-windows-10-pro-higher.md, docs/installation/native-installation.md, docs/introduction/basics-about-package-architecture.md
|Description, reason for the PR| The latest release is beta already
=> [shopsys] docs: minimal stability flag for composer create-project changed from alpha to beta in installation guides

3rd-party-licenses.md, CONTRIBUTING.md, README.md, license-overview-of-included-3rd-party-libraries.md
|Description, the reason for the PR| Shopsys Framework uses some third-party components and images which are licensed under their own respective licenses. List of these licenses needs to be available for the users of Shopsys Framework.
|BC breaks| No
=> [shopsys] Added list of 3rd party licenses

docs/index.md
|Description, reason for the PR| Not everyone know that upgrade instructions are in UPGRADE.md file in root of project so I added link into knowledgebase index.
=> Added link to upgrade.md file in knowledgebase index

docs/index.md, docs/installation/installation-using-docker-on-production-server.md, project-base/app/maintenance.html, project-base/app/maintenance.php, project-base/docker/conf/docker-compose.prod.yml.dist, project-base/docker/nginx/nginx.conf, project-base/docker/php-fpm/Dockerfile-production
|Description, reason for the PR| Find the way how to build and deploy project-base for production
=> [project-base] docker for production

CONTRIBUTING.md, UPGRADE.md, docs/contributing/guidelines-for-writing-upgrade.md
|Description, reason for the PR| During upgrading demoshop to shopsys alpha5 we discovered couple of issues. We want to improve upgrade notes to make the world for for our users easier.
=> [shopsys] Improved upgrade instruction

microservices/product-search-export/docker/php-ini-overrides.ini, microservices/product-search/docker/php-ini-overrides.ini, project-base/docker/php-fpm/php-ini-overrides.ini
=> [shopsys] Enable logging of errors in all php containers

.ci/build_kubernetes.sh, docker/conf/docker-compose-mac.yml.dist, docker/conf/docker-compose-win.yml.dist, docker/conf/docker-compose.yml.dist, microservices/product-search-export/composer.json, microservices/product-search-export/docker/Dockerfile, microservices/product-search-export/docker/docker-cmd-development, microservices/product-search-export/docker/hooks/build, microservices/product-search/composer.json, microservices/product-search/docker/Dockerfile, microservices/product-search/docker/docker-cmd-development, microservices/product-search/docker/hooks/build
- environment variables has been moved to Dockerfiles so they can be changed via docker-compose in future
- symfony/dotenv is no longer in use
=> [shopsys] Dockerfiles of microservices now use multi-stage build feature

.github/ISSUE_TEMPLATE.md
|Description, reason for the PR| I am a #grammar_nazi :innocent: 
=> [shopsys] fixed typo in .github/ISSUE_TEMPLATE.md

docker/conf/docker-compose-win.yml.dist, docker/conf/docker-sync-win.yml.dist, docs/installation/installation-using-docker-windows-10-pro-higher.md, project-base/docker/conf/docker-compose-win.yml.dist, project-base/docker/conf/docker-sync-win.yml.dist, project-base/docker/php-fpm/Dockerfile
|Description, reason for the PR| development on windows os is very slow. for instance build-demo-dev lasts 45 minutes instead of 6 minutes and load of the page 20 seconds.
|Fixes issues| #477 
=> [shopsys] Docker-sync for Windows development is added

CHANGELOG.md, UPGRADE.md, composer.json, microservices/product-search-export/composer.json, packages/form-types-bundle/composer.json, packages/framework/composer.json, packages/http-smoke-testing/composer.json, packages/migrations/composer.json, packages/plugin-interface/composer.json, packages/product-feed-google/composer.json, packages/product-feed-heureka-delivery/composer.json, packages/product-feed-heureka/composer.json, packages/product-feed-zbozi/composer.json, project-base/composer.json, project-base/docker/conf/docker-compose-mac.yml.dist, project-base/docker/conf/docker-compose-win.yml.dist, project-base/docker/conf/docker-compose.yml.dist
|Description, reason for the PR| release beta2
|BC breaks| No
=> Release v7.0.0-beta2

docs/introduction/phing-targets.md
|Description, reason for the PR| The phing targets were renamed some time ago (and the definition files were moved into microservice) but the docs do not reflect the changes
=> [shopsys] updated docs/introduction/phing-targets.md

UPGRADE.md
|Description, reason for the PR| fixes a mistake from #533
=> [shopsys] UPGRADE.md: moved note from PR #533 to proper section

UPGRADE.md, docs/installation/installation-using-docker-on-production-server.md, project-base/docker/conf/docker-compose.prod.yml.dist, project-base/docker/nginx/nginx.conf
|Description, reason for the PR| some instructions in the documentation were not accurate and based on demoshop production implementation, some things can be improved.
=> [shopsys] Update of installation for production via docker

packages/framework/src/Command/ChangeEnvironmentCommand.php, packages/framework/src/Component/Environment/EnvironmentFileSetting.php, packages/framework/src/Resources/config/services.yml
|Description, reason for the PR| previously, the way of changing enviroments was not clear enough
=> [framework] added new Symfony command "shopsys:environment:change"

CHANGELOG.md, CONTRIBUTING.md, docs/contributing/coding-standards.md, docs/contributing/guidelines-for-pull-request.md, docs/cookbook/adding-new-attribute-to-an-entity.md, docs/cookbook/dumping-and-importing-the-database.md, docs/cookbook/jenkins-configuration.md, docs/index.md, docs/installation/installation-using-docker-application-setup.md, docs/installation/installation-using-docker-on-production-server.md, docs/installation/native-installation.md, docs/introduction/automated-testing.md, docs/introduction/console-commands-for-application-management-phing-targets.md, docs/introduction/custom-entities.md, docs/introduction/database-migrations.md, docs/introduction/how-to-set-up-domains-and-locales.md, docs/introduction/product-feeds.md, docs/introduction/product-search-via-elasticsearch.md, docs/introduction/running-acceptance-tests.md, docs/introduction/shopsys-framework-development-workflow.md
|Description, reason for the PR| Phing targets and local development are not well documented
=> [shopsys] Updated documentation about phing targets and added article about development on Shopsys Framework

UPGRADE.md
|Description, reason for the PR| https://github.com/shopsys/shopsys/pull/538#discussion_r230324919
=> [shopsys] improved upgrading instructions for #538

docs/introduction/faq-and-common-issues.md
- added some helpful details to the explanations of https and cron
- fixed the answer to "How do I change the environment", as #543 is not merged yet
=> [shopsys] docs: update FAQ

packages/coding-standards/easy-coding-standard.yml, packages/coding-standards/tests/Unit/CsFixer/Phpdoc/FunctionAnnotationFixer/config.yml, packages/coding-standards/tests/Unit/CsFixer/Phpdoc/MissingParamAnnotationsFixer/config.yml, packages/coding-standards/tests/Unit/CsFixer/Phpdoc/MissingReturnAnnotationFixer/config.yml, packages/coding-standards/tests/Unit/CsFixer/Phpdoc/OrderedParamAnnotationsFixer/config.yml
Fixes https://travis-ci.org/shopsys/coding-standards/jobs/451327993#L637
|Fixes issues| https://travis-ci.org/shopsys/coding-standards/jobs/451327993#L637
=> [coding-standards] fix missing services magically autowired by Symfony - now explicit

.github/PULL_REQUEST_TEMPLATE.md
|Description, reason for the PR| simplifies issue maintenance<br>(see [GitHub Help](https://help.github.com/articles/closing-issues-using-keywords/) for details)
=> [shopsys] PULL_REQUEST_TEMPLATE.md: issue auto-closing mentioned

docs/contributing/coding-standards.md
|Description, reason for the PR| The docs are not up to date
=> [shopsys] coding-standards.md: the rule about protected methods updated with missing types of classes

UPGRADE.md, packages/framework/phpunit.xml, project-base/phpunit.xml
|Description, reason for the PR| #437
|BC breaks| No
|Fixes issues| closes #437
=> phpunit: remove unsupported syntaxCheck attribute

.ci/build_kubernetes.sh, UPGRADE.md, docker/conf/docker-compose-mac.yml.dist, docker/conf/docker-compose-win.yml.dist, docker/conf/docker-compose.yml.dist, docs/installation/installation-using-docker-linux.md, docs/installation/installation-using-docker-macos.md, docs/installation/installation-using-docker-on-production-server.md, docs/installation/installation-using-docker-windows-10-pro-higher.md, docs/kubernetes/continuous-integration-using-kubernetes.md, microservices/product-search-export/.travis.yml, microservices/product-search-export/docker/Dockerfile, microservices/product-search-export/docker/hooks/build, microservices/product-search/docker/Dockerfile, microservices/product-search/docker/hooks/build, packages/coding-standards/.travis.yml, packages/framework/.travis.yml, packages/http-smoke-testing/.travis.yml, packages/migrations/.travis.yml, packages/product-feed-google/.travis.yml, packages/product-feed-heureka-delivery/.travis.yml, packages/product-feed-heureka/.travis.yml, packages/product-feed-zbozi/.travis.yml, project-base/docker/conf/docker-compose-mac.yml.dist, project-base/docker/conf/docker-compose-win.yml.dist, project-base/docker/conf/docker-compose.yml.dist, project-base/docker/php-fpm/Dockerfile
|Description, reason for the PR| #518 
|Fixes issues| closes #518 
=> [shopsys] github token erase

CONTRIBUTING.md, README.md, open-source-license-acknowledgements-and-third-party-copyrights.md
Changes for the compliance with the law and for the consistency with our Commercial License.
Modifications according to compliance with the law + example of added copyrights for first 3 items + correction of the Grunt license URL
TODO:
|Description, reason for the PR| Changes for the compliance with the law
|BC breaks| No
|Standards and tests pass| Don't know
=>  Open Source License Acknowledgements and Third-Party Copyrights

docs/installation/installation-using-docker-application-setup.md, docs/installation/installation-using-docker-on-production-server.md, docs/introduction/logging.md
- logging.md is now linked from installation guides
- logging.md: added link to the article about logging on CI using Kubernetes
|Description, reason for the PR| @henzigo reported that he did not know how to deal with logs after he installed the application by following https://github.com/shopsys/shopsys/blob/master/docs/installation/installation-using-docker-on-production-server.md. He had no idea that there are some articles about logging in our knowledgbase.
=> docs: information about logging are more discoverable now

docs/installation/installation-using-docker-on-production-server.md
|Description, reason for the PR| there are commands that create config for firewalld service with no content and also into folder that can be replaced during upgrade
|Fixes issues| closes #597 
=> [shopsys] Update of installation docs for production

CHANGELOG.md, UPGRADE.md, changelog-linker.yml, composer.json, docs/installation/installation-using-docker-application-setup.md, docs/installation/installation-using-docker-linux.md, docs/installation/installation-using-docker-macos.md, docs/installation/installation-using-docker-on-production-server.md, docs/installation/installation-using-docker-windows-10-pro-higher.md, docs/installation/native-installation.md, microservices/product-search-export/composer.json, packages/form-types-bundle/composer.json, packages/framework/composer.json, packages/migrations/composer.json, packages/plugin-interface/composer.json, packages/product-feed-google/composer.json, packages/product-feed-heureka-delivery/composer.json, packages/product-feed-heureka/composer.json, packages/product-feed-zbozi/composer.json, project-base/composer.json, project-base/docker/conf/docker-compose-mac.yml.dist, project-base/docker/conf/docker-compose-win.yml.dist, project-base/docker/conf/docker-compose.yml.dist
|Description, reason for the PR| new release
=> preparation for 7.0.0-beta3 release 

CHANGELOG.md, UPGRADE.md, microservices/product-search-export/composer.json, packages/form-types-bundle/composer.json, packages/framework/composer.json, packages/migrations/composer.json, packages/plugin-interface/composer.json, packages/product-feed-google/composer.json, packages/product-feed-heureka-delivery/composer.json, packages/product-feed-heureka/composer.json, packages/product-feed-zbozi/composer.json, project-base/composer.json, project-base/docker/conf/docker-compose-mac.yml.dist, project-base/docker/conf/docker-compose-win.yml.dist, project-base/docker/conf/docker-compose.yml.dist
|Description, reason for the PR| Release of `v7.0.0-beta4`
=> preparation for release of 7.0.0-beta4

CHANGELOG.md
|Description, reason for the PR| The heading were in the wrong format so the links to diffs was not applied
=> [shopsys] fixed headings for the last two releases to make them links

UPGRADE.md, docs/installation/native-installation.md, project-base/app/Bootstrap.php, project-base/app/config/parameters.yml.dist
|Description, reason for the PR| To be able to configure trusted proxies used for production in parameters.yml file
|BC breaks| No
=> [project-base] Trusted proxies are now configurable in parameters.yml file

packages/framework/src/Model/Customer/CustomerPasswordService.php, packages/framework/src/Model/Payment/IndependentPaymentVisibilityCalculation.php, packages/framework/src/Model/Transport/IndependentTransportVisibilityCalculation.php
|Description, reason for the PR| Small cleanup of unused variable assigns found by static analysis
|BC breaks| No
=> [framework] remove unused bool conditions

docs/wip_glassbox/entity-extension.md
|Description, reason for the PR| Extending OrderItem is very problematic at the moment so users should about that. See https://github.com/shopsys/shopsys/issues/621#issuecomment-442098935 for details.
=> [shopsys] entity-extension.md: added warning about extending OrderItem and its descendants

docs/frontend/introduction-to-less.md, docs/index.md
|Description, reason for the PR| Created new directory 'frontend' at folder docs/ and added documentation clarifying how does works command @import at CSS pre-processor LESS.
|Fixes issues| resolves #146 
=> [shopsys] document behavior of less compiling 

docs/index.md
|Description, reason for the PR| after merge of 2 PRs with the new section for frontend documentation there is duplicated frontend section
=> docs: duplicated frontend sections are fixed and joint into one

CONTRIBUTING.md, docs/installation/installation-using-docker-linux.md, docs/installation/installation-using-docker-macos.md, docs/installation/installation-using-docker-windows-10-pro-higher.md, docs/installation/native-installation.md, docs/introduction/monorepo.md
|Description, reason for the PR| Clarifies documentation from a view of a developer interested in contributing to Shopsys Framework.
|Fixes issues| closes #454 
=> [shopsys] Docs: Updated informations about monorepo (#454)

UPGRADE.md
|Description, reason for the PR|  it makes more sense to link the commits in the split repository as they contain only the relevant changes, maybe we should do something like this automatically
=> [shopsys] UPGRADE.md: diff links point to shopsys/project-base

packages/framework/src/Model/Cart/CartService.php, packages/framework/src/Model/Security/LoginService.php, project-base/tests/ShopBundle/Functional/Model/Cart/CartServiceTest.php, project-base/tests/ShopBundle/Functional/Model/Security/LoginServiceTest.php
| Q| A
| - | -
|Description, reason for the PR| #588 & US-4997
|BC breaks| No
|Fixes issues| "closes #588"
=> [framework] Fixed cart merging after login (closes #588)

packages/framework/src/Model/Product/ProductHiddenRecalculator.php
|Description, reason for the PR| #654 
| New feature | No
| BC breaks | No
| Fixes issues | closes #654
| Standards and tests pass | No
| Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)? | Yes
=> [framework] calculatedHidden attribute of a main variant is taken over from the hidden attribute

changelog-linker.yml
|Description, reason for the PR| Update list of Shopsys Framework members
=> [shopsys] update authors to ignore in changelog linker

packages/framework/src/Form/ImageUploadType.php, packages/framework/src/Resources/views/Admin/Form/imageuploadFields.html.twig
|Description, reason for the PR| Need to upload multiple types of images for Product
=> [framework] ImageUploadType now can be used for uploading specific image types

.ci/build_kubernetes.sh, .ci/restart_kubernetes.sh, .dockerignore, UPGRADE.md, docs/index.md, docs/kubernetes/continuous-integration-using-kubernetes.md, docs/kubernetes/deploy-your-application-to-google-cloud-on-your-ci-cd.md, docs/kubernetes/domains-in-google-cloud-infrastructure.md, docs/kubernetes/how-to-deploy-ssfw-to-google-cloud-platform.md, docs/kubernetes/set-up-google-cloud.md, project-base/.ci/deploy-to-google-cloud.sh, project-base/.ci/destroy-google-cloud-infrastructure.sh, project-base/.dockerignore, project-base/docker/php-fpm/Dockerfile, project-base/infrastructure/google-cloud/gke-cluster.tf, project-base/infrastructure/google-cloud/networking.tf, project-base/infrastructure/google-cloud/nginx-ingress.tf, project-base/infrastructure/google-cloud/providers.tf, project-base/infrastructure/google-cloud/stateful-services.tf, project-base/infrastructure/google-cloud/tfstate.tf, project-base/infrastructure/google-cloud/variables.tf, project-base/kubernetes/deployments/microservice-product-search-export.yml, project-base/kubernetes/deployments/microservice-product-search.yml, project-base/kubernetes/deployments/webserver-php-fpm.yml, project-base/kubernetes/ingress.yml, project-base/kubernetes/kustomize/base/kustomization.yaml, project-base/kubernetes/kustomize/overlays/ci/kustomization.yaml, project-base/kubernetes/kustomize/overlays/production/ingress-patch.yaml, project-base/kubernetes/kustomize/overlays/production/kustomization.yaml, project-base/kubernetes/kustomize/overlays/production/namespace.yaml
|Description, reason for the PR| ability to deploy to Google Cloud using infrastructure written as a code
|BC breaks| No
|Fixes issues|
=> [shopsys] Google Cloud deploy using Terraform, Kustomize and Kubernetes

docs/kubernetes/how-to-get-a-cluster-running.md
|Description, reason for the PR| During installation of cluster I found few steps that were missing in the guide
=> [shopsys] how-to-get-a-cluster-running.md updated

UPGRADE.md, docs/installation/installation-using-docker-on-production-server.md, project-base/app/config/packages/snc_redis.yml, project-base/app/config/parameters.yml.dist, project-base/docker/php-fpm/Dockerfile
|Description, reason for the PR| Need to run multiple instances of Shopsys Framework application on same machine
=> added support for custom prefixing in redis

packages/framework/src/Form/Admin/AdvancedSearch/AdvancedSearchOrderFilterTranslation.php, packages/framework/src/Form/Admin/AdvancedSearch/AdvancedSearchProductFilterTranslation.php, packages/framework/src/Model/AdvancedSearch/Filter/ProductAvailabilityFilter.php, packages/framework/src/Model/AdvancedSearch/Filter/ProductBrandFilter.php, packages/framework/src/Model/AdvancedSearch/Filter/ProductCalculatedSellingDeniedFilter.php, packages/framework/src/Model/AdvancedSearch/Filter/ProductCatnumFilter.php, packages/framework/src/Model/AdvancedSearch/Filter/ProductFlagFilter.php, packages/framework/src/Model/AdvancedSearch/Filter/ProductPartnoFilter.php, packages/framework/src/Model/AdvancedSearch/Filter/ProductStockFilter.php, packages/framework/src/Model/AdvancedSearchOrder/Filter/OrderCityFilter.php, packages/framework/src/Model/AdvancedSearchOrder/Filter/OrderCreateDateFilter.php, packages/framework/src/Model/AdvancedSearchOrder/Filter/OrderDomainFilter.php, packages/framework/src/Model/AdvancedSearchOrder/Filter/OrderEmailFilter.php, packages/framework/src/Model/AdvancedSearchOrder/Filter/OrderLastNameFilter.php, packages/framework/src/Model/AdvancedSearchOrder/Filter/OrderNameFilter.php, packages/framework/src/Model/AdvancedSearchOrder/Filter/OrderNumberFilter.php, packages/framework/src/Model/AdvancedSearchOrder/Filter/OrderPhoneNumberFilter.php, packages/framework/src/Model/AdvancedSearchOrder/Filter/OrderProductFilter.php, packages/framework/src/Model/AdvancedSearchOrder/Filter/OrderStatusFilter.php, packages/framework/src/Model/AdvancedSearchOrder/Filter/OrderStreetFilter.php
|Description, reason for the PR| removed duplication of hardcoded strings in filters
|BC breaks| No
|Fixes issues| ... closes #684
=> [framework] refactored AdvancedSearch filter names to Filter classes

UPGRADE.md, packages/framework/src/Model/Administrator/AdministratorRepository.php, packages/framework/src/Model/Administrator/Security/AdministratorUserProvider.php
|Description, reason for the PR| #204
|Fixes issues| #204
=> [framework] fix unnecessary log error after login as admin on second PC

UPGRADE.md
|Description, reason for the PR| fixed links leading to 404 on github
|Fixes issues|
=> fixed links to UPGRADE.md instruction files

docs/index.md, docs/introduction/console-commands-for-application-management-phing-targets.md, docs/introduction/faq-and-common-issues.md, docs/introduction/how-to-set-up-domains-and-locales.md, docs/introduction/translations.md
|Description, reason for the PR| we need documentation for translations (and it is also useful for implementators)
|BC breaks| No
=> [shopsys] documentation of translations

docs/contributing/upgrading-monorepo.md
|Description, reason for the PR| feedback from real life upgrading by @PetrHeinz 
=> [shopsys] upgrading-monorepo.md: improved instructions

docs/introduction/basics-about-model-architecture.md, docs/introduction/entities.md, docs/introduction/faq-and-common-issues.md
|Description, reason for the PR| We want to provide better documentation for beginners
|Fixes issues| closes #287 
=> [shopsys] Improved entity data objects documentation

docs/upgrade/UPGRADE-7.0.0-alpha2.md, docs/upgrade/UPGRADE-7.0.0-alpha3.md, docs/upgrade/UPGRADE-7.0.0-alpha4.md, docs/upgrade/UPGRADE-7.0.0-alpha5.md, docs/upgrade/UPGRADE-7.0.0-alpha6.md, docs/upgrade/UPGRADE-7.0.0-beta1.md, docs/upgrade/UPGRADE-7.0.0-beta2.md, docs/upgrade/UPGRADE-7.0.0-beta3.md, docs/upgrade/UPGRADE-7.0.0-beta4.md, docs/upgrade/UPGRADE-unreleased.md, docs/upgrade/before-monorepo.md
|Description, reason for the PR| fixed note about version in upgrade files
=> [shopsys] fixed note about version in upgrade files

packages/framework/src/Component/Domain/Multidomain/DefaultMultidomainEntityClassProvider.php, packages/framework/src/Resources/config/services.yml, packages/migrations/src/Component/Doctrine/Migrations/AbstractMigration.php
|Description, reason for the PR| Fixes some deprecation warning to ease further upgrades
=> [framework] fixed symfony deprecation warnings

README.md
|Description, reason for the PR| New Shopsys references was not in readme file, so I added it. 
|BC breaks| No
=> [shopsys] New SSFW references added to readme.md

LICENSE, packages/coding-standards/LICENSE, packages/form-types-bundle/LICENSE, packages/framework/LICENSE, packages/http-smoke-testing/LICENSE, packages/migrations/LICENSE, packages/monorepo-tools/LICENSE, packages/plugin-interface/LICENSE, packages/product-feed-google/LICENSE, packages/product-feed-heureka-delivery/LICENSE, packages/product-feed-heureka/LICENSE, packages/product-feed-zbozi/LICENSE, project-base/LICENSE
|Description, reason for the PR| New year is here so we need to update it in our code
|BC breaks| No
=> Updated year in license files

docs/docker/docker-troubleshooting.md, docs/installation/installation-using-docker-application-setup.md, docs/introduction/shopsys-framework-on-docker.md, docs/upgrade/UPGRADE-unreleased.md, open-source-license-acknowledgements-and-third-party-copyrights.md, project-base/docker/php-fpm/Dockerfile, project-base/kubernetes/deployments/webserver-php-fpm.yml
- debian commands are easier to understand
- alpine cannot connect to MSSQL databases
|Description, reason for the PR| debian commands are easier to understand, alpine cannot connect to MSSQL databases
|BC breaks| Yes - I will upgrade `UPGRADE.md` if we will decide to go on with debian
=> [project-base] switched to Debian php-fpm image

docs/upgrade/UPGRADE-unreleased.md, project-base/docker/php-fpm/Dockerfile
- generation of image previews for brands, products, ... is fixed
|Fixes issues| #739  
=> generation of jpeg previews for php-fpm debian container

microservices/product-search-export/composer.json
|Description, reason for the PR| missing dependency in composer.json of microservice product search export which is important for testing
|Standards and tests pass| No
=> [microservice-product-search-export] added symfony/dotenv to composer.json

docs/upgrade/UPGRADE-unreleased.md, packages/framework/easy-coding-standard.yml, packages/framework/src/Component/Image/AdditionalImageData.php, packages/framework/src/Component/Image/Config/Exception/DuplicateMediaException.php, packages/framework/src/Component/Image/Config/Exception/ImageAdditionalSizeNotFoundException.php, packages/framework/src/Component/Image/Config/Exception/WidthAndHeightMissingException.php, packages/framework/src/Component/Image/Config/ImageAdditionalSizeConfig.php, packages/framework/src/Component/Image/Config/ImageConfigDefinition.php, packages/framework/src/Component/Image/Config/ImageConfigLoader.php, packages/framework/src/Component/Image/Config/ImageSizeConfig.php, packages/framework/src/Component/Image/ImageFacade.php, packages/framework/src/Component/Image/ImageLocator.php, packages/framework/src/Component/Image/Processing/ImageGenerator.php, packages/framework/src/Component/Image/Processing/ImageGeneratorFacade.php, packages/framework/src/Component/Image/Processing/ImageProcessor.php, packages/framework/src/Resources/views/Admin/Content/Image/overview.html.twig, packages/framework/src/Resources/views/Common/image.html.twig, packages/framework/src/Twig/ImageExtension.php, packages/framework/tests/Unit/Component/Image/Config/ImageConfigLoaderTest.php, packages/framework/tests/Unit/Component/Image/Config/ImageConfigTest.php, packages/framework/tests/Unit/Component/Image/Config/ImageEntityConfigTest.php, packages/framework/tests/Unit/Component/Image/DirectoryStructureCreatorTest.php, packages/framework/tests/Unit/Component/Image/ImageLocatorTest.php, project-base/src/Shopsys/ShopBundle/Controller/Front/ImageController.php, project-base/src/Shopsys/ShopBundle/Resources/config/images.yml, project-base/src/Shopsys/ShopBundle/Resources/config/routing_front.yml, project-base/tests/ShopBundle/Functional/Twig/ImageExtensionTest.php, project-base/tests/ShopBundle/Functional/Twig/Resources/picture.twig, project-base/tests/ShopBundle/Smoke/Http/RouteConfigCustomization.php
|Description, reason for the PR| Adding support for multiple image sizes to be able to work better with pictures on frontend.
|Fixes issues| closes #159 
=> [shopsys] added support for multiple image sizes (picture element)

docs/installation/installation-using-docker-linux.md, docs/installation/installation-using-docker-macos.md, docs/installation/installation-using-docker-windows-10-pro-higher.md, docs/upgrade/UPGRADE-unreleased.md, project-base/scripts/install.sh
|Description, reason for the PR| To ease installlation process, we can extract commands required to execute in order to install the Shopsys Framework into shell script that will install fully functional demo version of Shopsys Framework in container.
|BC breaks| No
|Fixes issues| #495
=> [project-base] Created install script for mac and linux distribution

docs/cookbook/adding-new-attribute-to-an-entity.md, docs/cookbook/basic-data-import.md, docs/introduction/faq-and-common-issues.md
|Description, reason for the PR| just a few things I have encountered when going through `adding-new-attribute-to-an-entity.md` and `basic-data-import.md` during preparation for the workshop day
|Standards and tests pass| Yes :crossed_fingers: 
=> [shopsys] docs tweaks

docs/installation/installation-using-docker-on-production-server.md, docs/upgrade/UPGRADE-v7.0.0-beta5.md
|Description, reason for the PR| Fixes few mistakes in production guide. 
=> Fixed production installation documentation

docs/contributing/guidelines-for-creating-commits.md
Mostly, we use PR numbers instead now and it makes much more sense.
|Description, reason for the PR| we don't use the IDs much anymore and it brings no value to our users and contributors (as the backlog is private)
As an example, see currently merged commits into `master` since `v7.0.0-beta5`:
```
* production installation documentation is now compatible with Debian used (#783)
* [project-base] kubernetes uses relay setting for sending mails (#777)
*   docs tweaks (#743)
|\  
| * docs: information about services_test.yml
| * …
```
=> [shopsys] use PR # instead of internal backlog IDs in contributing guide for commits

docs/installation/installation-using-docker-linux.md, docs/installation/installation-using-docker-macos.md, docs/installation/installation-using-docker-windows-10-pro-higher.md
|Description, reason for the PR| #734 
|Fixes issues| closes #734  
=> [docs] Added minimal requirements to instalation guides

UPGRADE.md, docs/contributing/guidelines-for-writing-upgrade.md, docs/contributing/upgrading-monorepo.md, docs/upgrade/UPGRADE-unreleased.md, docs/upgrade/UPGRADE-v7.0.0-alpha5.md, docs/upgrade/UPGRADE-v7.0.0-alpha6.md, docs/upgrade/UPGRADE-v7.0.0-beta1.md, docs/upgrade/UPGRADE-v7.0.0-beta2.md, docs/upgrade/UPGRADE-v7.0.0-beta3.md, docs/upgrade/UPGRADE-v7.0.0-beta4.md, docs/upgrade/UPGRADE-v7.0.0-beta5.md
|Description, reason for the PR| we have some feedback from upgraders about upgrade instructions and about need for upgrade notes improvement and we decided to make upgrade notes better.
=> Upgrade notes are extended and fixed

docs/cookbook/creating-a-multidomain-design.md, docs/frontend/design-implementation-and-customization.md, docs/index.md, docs/introduction/how-to-set-up-domains-and-locales.md, packages/framework/src/Component/Domain/Config/DomainConfig.php, packages/framework/src/Component/Domain/Config/DomainsConfigDefinition.php, packages/framework/src/Component/Domain/Config/DomainsConfigLoader.php, packages/framework/src/Component/Domain/Domain.php, packages/framework/src/Component/Domain/Multidomain/Twig/Exception/MissingDependencyException.php, packages/framework/src/Component/Domain/Multidomain/Twig/FilesystemLoader.php, packages/framework/src/Resources/config/services.yml
|Description, reason for the PR| We want to enable project developers implementation of different designs on multiple domains
=> [framework] added ability to use distinct templates for the other domains

docs/upgrade/UPGRADE-unreleased.md
|Description, reason for the PR| Wrong formatting of UPGRADE instructions
=> [shopsys] upgrade instructions of cart as entity has been updated to be more format consistent

docs/introduction/how-to-set-up-domains-and-locales.md
|Description, reason for the PR| After testing the documentation, I found small parts that were not 100% clear
=> [shopsys] improve documentation "How to set up domains and locales"

docs/frontend/configuring-image-sizes-for-individual-devices-width.md, docs/index.md, docs/upgrade/UPGRADE-unreleased.md, project-base/src/Shopsys/ShopBundle/Resources/config/images.yml, project-base/src/Shopsys/ShopBundle/Resources/views/Front/Content/Advert/box.html.twig
|Description, reason for the PR| Updated current image sizes and implemented base additional sizes for the product, slider item and advert images
|[BC breaks](/docs/contributing/backward-compatibility-promise.md)| No
=> [project-base] implemented picture element

docs/upgrade/UPGRADE-v7.0.0-beta6.md
|Description, reason for the PR| Upgrade to beta6 on demoshop discovered some missing records in UPGRADE.md
|Fixes issues|
=> upgraded UPGRADE.md with experience from upgrading

docs/extensibility/form-extension.md, docs/index.md
|Description, reason for the PR| I am missing the link to the new article and the formatting of a paragraph is broken
=> [shopsys] form types docs tweaks

docs/introduction/faq-and-common-issues.md, docs/upgrade/UPGRADE-unreleased.md, docs/upgrade/UPGRADE-v8.0.0.md, packages/framework/src/Component/Cron/CronFacade.php, packages/framework/src/Model/Mail/Mailer.php, packages/framework/src/Resources/config/services.yml, packages/framework/tests/Unit/Component/Cron/CronFacadeTest.php
|Description, reason for the PR| based on implementation of project for targeted group we decided to document behavior of mail spooling and make some changes for CronModules 
|Fixes issues| closes #728 
=> [framework] mail spooling

packages/product-feed-google/src/Model/FeedItem/GoogleFeedItemFactory.php, packages/product-feed-google/tests/Unit/GoogleFeedItemTest.php, packages/product-feed-heureka/src/Model/Product/HeurekaProductRepository.php, packages/product-feed-zbozi/src/Model/Product/ZboziProductRepository.php
|Description, reason for the PR| #855
|Fixes issues| closes #855
=> [shopsys] feeds: using correct calculatedSellingDenied

CHANGELOG.md, UPGRADE.md, docs/upgrade/UPGRADE-v7.0.0.md
|Description, reason for the PR| improvement of UPGRADE from beta6 into stable based on [shopsys/demoshop#39]
=> UPGRADE.md fixes

docs/upgrade/UPGRADE-unreleased.md, packages/framework/src/Form/Admin/AdvancedSearch/AdvancedSearchProductFilterTranslation.php, packages/framework/src/Model/AdvancedSearch/Filter/ProductCategoryFilter.php, packages/framework/src/Resources/styles/admin/libs/selectize/selectize-custom.less, project-base/src/Shopsys/ShopBundle/Model/AdvancedSearch/ProductAdvancedSearchConfig.php, project-base/src/Shopsys/ShopBundle/Resources/config/services.yml, project-base/src/Shopsys/ShopBundle/Resources/config/services_test.yml
|Description, reason for the PR| implementators would like to have implemented category advanced search with autocomplete by default 
=> [shopsys] advanced search category

project-base/tests/ShopBundle/Functional/EntityExtension/EntityExtensionTest.php
|Description, reason for the PR| There were errors thrown when some entity related to Product has been extended
|Fixes issues| resolves #843 
=> [project-base] fix EntityExtensionTest when extending entity related to Product

utils/releaser/src/ReleaseWorker/AbstractCheckShopsysInstallReleaseWorker.php, utils/releaser/src/ReleaseWorker/AbstractCheckUncommittedChangesReleaseWorker.php, utils/releaser/src/ReleaseWorker/AbstractShopsysReleaseWorker.php, utils/releaser/src/ReleaseWorker/AfterRelease/CheckHeimdallBuildReleaseWorker.php, utils/releaser/src/ReleaseWorker/AfterRelease/CheckShopsysInstallReleaseWorker.php, utils/releaser/src/ReleaseWorker/AfterRelease/CheckUncommittedChangesReleaseWorker.php, utils/releaser/src/ReleaseWorker/AfterRelease/CreateReleaseNotesReleaseWorker.php, utils/releaser/src/ReleaseWorker/AfterRelease/EnableMergingToMasterReleaseWorker.php, utils/releaser/src/ReleaseWorker/AfterRelease/PostInfoToSlackReleaseWorker.php, utils/releaser/src/ReleaseWorker/AfterRelease/SetMutualDependenciesToDevMasterReleaseWorker.php, utils/releaser/src/ReleaseWorker/Release/CheckUncommittedChangesReleaseWorker.php, utils/releaser/src/ReleaseWorker/Release/CreateAndPushGitTagReleaseWorker.php, utils/releaser/src/ReleaseWorker/Release/MergeBranchToMasterReleaseWorker.php, utils/releaser/src/ReleaseWorker/ReleaseCandidate/CheckShopsysInstallReleaseWorker.php, utils/releaser/src/ReleaseWorker/ReleaseCandidate/CheckUncommittedChangesReleaseWorker.php, utils/releaser/src/ReleaseWorker/ReleaseCandidate/CreateBranchReleaseWorker.php, utils/releaser/src/ReleaseWorker/ReleaseCandidate/DumpTranslationsReleaseWorker.php, utils/releaser/src/ReleaseWorker/ReleaseCandidate/ForceYourBranchSplitReleaseWorker.php, utils/releaser/src/ReleaseWorker/ReleaseCandidate/ResolveDocsTodoReleaseWorker.php, utils/releaser/src/ReleaseWorker/ReleaseCandidate/SendBranchForReviewAndTestsReleaseWorker.php, utils/releaser/src/ReleaseWorker/ReleaseCandidate/StopMergingToMasterReleaseWorker.php, utils/releaser/src/ReleaseWorker/ReleaseCandidate/UpdateChangelogReleaseWorker.php, utils/releaser/src/ReleaseWorker/ReleaseCandidate/UpdateUpgradeReleaseWorker.php, utils/releaser/src/ReleaseWorker/ReleaseCandidate/VerifyMinorUpgradeReleaseWorker.php
|Description, reason for the PR| We want to have releaser as descriptive as possible so even newbies are able to perform the release using the tool
=> [shopsys] releaser tweaks

docs/functional/cart.md, docs/index.md
|Description, reason for the PR| Description of cart behavior.
=> [shopsys] Functional documentation cart.md

docs/upgrade/UPGRADE-v7.1.0.md
=> add missing step in upgrade instructions to v7.1.0

README.md
|Description, reason for the PR| removed outdated site from readme
=> [shopsys] updated list of sites in README.md

docker/conf/docker-compose-win.yml.dist, packages/framework/src/Command/ProductSearchCreateStructureCommand.php, packages/framework/src/Command/ProductSearchDeleteStructureCommand.php, packages/framework/src/Command/ProductSearchExportProductsCommand.php, packages/framework/src/Resources/config/services.yml
=> [shopsys] removed mentions about microservices from product search export command

docs/introduction/faq-and-common-issues.md
|Description, reason for the PR| People asks how to change behavior of search but there is no cookbook because all info are in Elasticsearch article.
|[BC breaks](https://github.com/shopsys/shopsys/blob/master/docs/contributing/backward-compatibility-promise.md)| Yes
|Fixes issues| closes #632
|Standards and tests pass| ?
=> [shopsys] Added link to elastic instruction to FAQ section

docs/introduction/faq-and-common-issues.md
|Description, reason for the PR| the path of the article was changed in #883, but #912 was merged with the original link -> now it leads to 404
=> [shopsys] FAQ: fix path to Product Searching via Elasticsearch

project-base/scripts/install.sh
|Description, reason for the PR| If docker is not running or user is not allowed to run docker, installation fail on more descriptive message.
|Fixes issues| closes #908 
=> [project-base] availability of docker is now checked before installation

docs/kubernetes/how-to-get-a-cluster-running.md, docs/kubernetes/how-to-set-smtp-server-container.md
|Description, reason for the PR| friendsofphp/php-cs-fixer released a new version that doesn't allow non breaking spaces in checked files. This PR removes these occurences
|Standards and tests pass| No, but it's a step in the right direction
=> [shopsys] fixed typo non-breaking space -> space

.travis.yml, README.md, composer.json, packages/framework/composer.json, project-base/composer.json
|Description, reason for the PR| Travis will check every push to PR. It will not allow to merge PR without  successful check.
=> Configure travis to check standards and unit tests in monorepo

docs/cookbook/basic-data-import.md, docs/cookbook/working-with-multiple-cron-instances.md, docs/introduction/cron.md, docs/upgrade/UPGRADE-unreleased.md, project-base/src/Shopsys/ShopBundle/Resources/config/services.yml, project-base/src/Shopsys/ShopBundle/Resources/config/services/cron.yml
|Description, reason for the PR| Most of new projects creates custom crons, so they need to create file and search how they can configure own cron. This PR prepare `cron.yml` in project base with example how they can use that.
=> [project-base] create configuration file for crons to project base

CONTRIBUTING.md, docs/contributing/code-quality-principles.md
|Description, reason for the PR| We need formalized principles to delivery quality code consistently
=> [shopsys] code quality principles article

docs/upgrade/UPGRADE-v7.2.0.md, docs/upgrade/interchangeable-filtering.md
|Description, reason for the PR| Some tweaks of upgrade instructions suggested after the experience with demoshop upgrade (in https://github.com/shopsys/demoshop/pull/47).
=> [shopsys] tweak upgrade instructions for v7.2.0

.ci/monorepo_functions.sh
|Description, reason for the PR| When adding or removing a package from monorepo, there are a few places that you need to update. I just listed these places in a comment to help maintainers.
=> [shopsys] note about list of packages added for easier maintenance

docs/contributing/code-quality-principles.md
|Description, reason for the PR| typos
=> code-quality-principles.md: fixed typos

docs/introduction/framework-extensibility.md
|Description, reason for the PR| The original heading sounded discouraging...
=> [shopsys] framework-extensibility.md: change heading

docs/contributing/guidelines-for-pull-request.md
|Description, reason for the PR| fix typo in Guidelines for Pull Request
=> [shopsys] typo

packages/framework/src/Resources/views/Admin/Content/Order/preview.html.twig
|Description, reason for the PR| info in issue #1100
|Fixes issues| fixes #1100 
=> [framework] checking of order item type is fixed by using type getters

docs/upgrade/UPGRADE-unreleased.md, project-base/src/Shopsys/ShopBundle/Resources/config/services.yml, project-base/src/Shopsys/ShopBundle/Resources/config/services/twig.yml
|Description, reason for the PR| Developer wants extend/override/use more services that only Facade/Factory/Repository in model. Namespaces Component and Twig are used too...
|[BC breaks](https://github.com/shopsys/shopsys/blob/master/docs/contributing/backward-compatibility-promise.md)| no 
=> prepare DI configuration for project-base like framework

packages/framework/easy-coding-standard.yml, packages/framework/src/Component/Elasticsearch/Debug/ElasticsearchCollector.php, packages/framework/src/Component/Elasticsearch/Debug/ElasticsearchDebugStack.php, packages/framework/src/Component/Elasticsearch/Debug/ElasticsearchRequestCollection.php, packages/framework/src/Component/Elasticsearch/Debug/ElasticsearchTracer.php, packages/framework/src/Component/Elasticsearch/Debug/Exception/NotSupportedException.php, packages/framework/src/DependencyInjection/ShopsysFrameworkExtension.php, packages/framework/src/Resources/config/services.yml, packages/framework/src/Resources/config/services_dev.yml, packages/framework/src/Resources/views/Debug/Elasticsearch/template.html.twig
|Description, reason for the PR| Because developers want it and need it
=> [framework] Elasticsearch debug toolbar

packages/framework/src/Component/Image/ImageFacade.php
|Description, reason for the PR| Method `ImageEntityConfig::getSizeConfig()` only accesses size configs of the default (null) image type, which meant deleting images of a particular type using `ImageFacade::deleteImages()` and displaying an image of a particular type using `{{ image(realGalleryImage, {size: 'detail', type: 'gallery'}) }}` did not work.
I've made a prototype of a product "gallery" image type when testing #1092 (using the image definition from the example in …
=> [framework] ImageFacade: use provided "type" when accessing size config

docs/extensibility/entity-extension.md
|Description, reason for the PR| New users of Shopsys Framework are looking for ways to extend entity. This information has been moved to beginning of the article and slightly improved.
=> [shopsys] entity-extension.md has been updated to be more useful by new users

packages/framework/src/Resources/config/services_test.yml
|Description, reason for the PR| There was error found in checking no BC breaks in master.
=> [shopsys] services_test.yml added CustomerDataFactory to be registered as service

docs/upgrade/UPGRADE-v8.0.0.md, packages/framework/src/Controller/Admin/DefaultController.php, packages/framework/src/Model/Statistics/StatisticsFacade.php, packages/framework/src/Model/Statistics/StatisticsRepository.php, packages/framework/src/Resources/scripts/admin/plugins/jquery.counterup.js, packages/framework/src/Resources/styles/admin/components/box/overview.less, packages/framework/src/Resources/views/Admin/Content/Default/index.html.twig, project-base/src/Shopsys/ShopBundle/DataFixtures/Demo/OrderDataFixture.php, project-base/src/Shopsys/ShopBundle/DataFixtures/Demo/UserDataFixture.php
|Description, reason for the PR| As administrator I want to see basic stats of my store to easily check if everything is OK.
=> [shopsys] added statistics about new customers, orders and orders value on administration dashboard

docs/upgrade/UPGRADE-unreleased.md, project-base/src/Shopsys/ShopBundle/Resources/config/routing_front.yml
=> remove unused route "front_category_panel"

docs/installation/installation-guide.md, docs/installation/installation-using-docker-macos.md, docs/installation/installation-using-docker-windows-10-pro-higher.md
|Description, reason for the PR| Developers should be aware of the possible problems when using docker-sync
=> docs: added warning about docker-sync usage

docs/upgrade/UPGRADE-unreleased.md, packages/framework/src/Component/Router/FriendlyUrl/FriendlyUrlDataFactory.php, packages/framework/src/Component/Router/FriendlyUrl/FriendlyUrlDataFactoryInterface.php, packages/framework/src/Model/Article/ArticleDetailFriendlyUrlDataProvider.php, packages/framework/src/Model/Product/Brand/BrandDetailFriendlyUrlDataProvider.php, packages/framework/src/Model/Product/ProductDetailFriendlyUrlDataProvider.php, packages/framework/src/Model/Product/ProductListFriendlyUrlDataProvider.php
|Description, reason for the PR| mismatch in variables assignments reported in #945 
|Fixes issues| closes #945, closes #1174 
=> fix friendly url data providers

docs/upgrade/UPGRADE-v8.0.0.md, packages/framework/src/Model/Administrator/Administrator.php, packages/framework/src/Model/Cart/Cart.php, packages/framework/src/Model/Category/Category.php, packages/framework/src/Model/Country/Country.php, packages/framework/src/Model/Order/Order.php, packages/framework/src/Model/Order/Status/OrderStatus.php, packages/framework/src/Model/Payment/Payment.php, packages/framework/src/Model/Payment/PaymentDataFactory.php, packages/framework/src/Model/Product/Availability/Availability.php, packages/framework/src/Model/Product/Brand/Brand.php, packages/framework/src/Model/Product/Flag/Flag.php, packages/framework/src/Model/Product/Parameter/Parameter.php, packages/framework/src/Model/Product/Product.php, packages/framework/src/Model/Product/ProductDataFactory.php, packages/framework/src/Model/Product/Unit/Unit.php, packages/framework/src/Model/Transport/Transport.php, packages/framework/src/Model/Transport/TransportDataFactory.php, packages/framework/src/Model/Transport/TransportFacade.php, packages/framework/src/Model/Transport/TransportVisibilityCalculation.php, packages/framework/tests/Unit/Model/Transport/TransportVisibilityCalculationTest.php, packages/product-feed-google/src/Model/Product/GoogleProductRepository.php, packages/product-feed-heureka/src/Model/HeurekaCategory/HeurekaCategory.php, packages/product-feed-heureka/src/Model/Product/HeurekaProductRepository.php, packages/product-feed-zbozi/src/Model/Product/ZboziProductRepository.php, packages/read-model/tests/Unit/Product/Listed/ListedProductViewFactoryTest.php, project-base/src/Shopsys/ShopBundle/Form/Front/Order/TransportAndPaymentFormType.php, project-base/tests/ShopBundle/Functional/Model/Payment/PaymentTest.php
|Description, reason for the PR| https://ocramius.github.io/doctrine-best-practices/#/43
=> [shopsys] encapsulation of collections inside of entities

docs/introduction/how-to-set-up-domains-and-locales.md, packages/backend-api/README.md, packages/coding-standards/README.md, packages/form-types-bundle/README.md, packages/framework/README.md, packages/google-cloud-bundle/README.md, packages/http-smoke-testing/README.md, packages/migrations/README.md, packages/monorepo-tools/README.md, packages/plugin-interface/README.md, packages/product-feed-google/README.md, packages/product-feed-heureka-delivery/README.md, packages/product-feed-heureka/README.md, packages/product-feed-zbozi/README.md, packages/read-model/README.md, project-base/README.md
|Description, reason for the PR| based on grammar fixers result
=> [shopsys] fix grammar connected with "information" word

docs/upgrade/UPGRADE-unreleased.md, project-base/docker/php-fpm/Dockerfile
|Description, reason for the PR| During development and on production this tools help developer with work in php-fpm container
=> php-fpm dockerfile contains useful tools (vim, nano, mc, htop)

docs/backend-api/introduction-to-backend-api.md, docs/cookbook/backend-api/adding-an-attribute-to-product-export.md, packages/backend-api/install/install.sh, packages/backend-api/src/Controller/V1/Product/ApiProductTransformer.php, packages/backend-api/src/Controller/V1/Product/ProductController.php, packages/backend-api/tests/Unit/Controller/V1/Product/ProductControllerTest.php
|Description, reason for the PR| This change will be done anyway in #1203 and if we do it before 8.0 is release, then we make life for the implementation teams brighter
=> [backend-api] moved backend API Product Controller classes to subdirectory

docs/upgrade/UPGRADE-unreleased.md, packages/framework/src/Model/Product/Filter/ParameterFilterRepository.php
|Description, reason for the PR| [KISS principle](https://en.wikipedia.org/wiki/KISS_principle)
=> [framework] remove unnecessary passing parameter as a reference

build.xml, docs/backend-api/api-methods.md, docs/backend-api/introduction-to-backend-api.md, docs/cookbook/adding-new-attribute-to-an-entity.md, docs/cookbook/backend-api/adding-an-attribute-to-product-import.md, docs/cookbook/backend-api/creating-custom-api-endpoint.md, docs/index.md, packages/backend-api/.travis.yml, packages/backend-api/easy-coding-standard.yml, packages/backend-api/install/app/config/packages/fos_rest.yml, packages/backend-api/install/app/config/packages/test/fos_rest.yml, packages/backend-api/install/install.sh, packages/backend-api/install/tests/ShopBundle/Smoke/BackendApiCreateProductTest.php, packages/backend-api/install/tests/ShopBundle/Smoke/BackendApiDeleteProductTest.php, packages/backend-api/install/tests/ShopBundle/Smoke/BackendApiTest.php, packages/backend-api/install/tests/ShopBundle/Smoke/BackendApiUpdateProductTest.php, packages/backend-api/install/tests/ShopBundle/Test/OauthTestCase.php, packages/backend-api/install/uninstall.sh, packages/backend-api/src/Component/DataSetter/ApiDataSetter.php, packages/backend-api/src/Component/Validation/HttpUuidValidator.php, packages/backend-api/src/Component/Validation/ValidationRunner.php, packages/backend-api/src/Controller/V1/Product/ProductApiDataValidator.php, packages/backend-api/src/Controller/V1/Product/ProductApiDataValidatorInterface.php, packages/backend-api/src/Controller/V1/Product/ProductController.php, packages/backend-api/src/Controller/V1/Product/ProductDataFactory.php, packages/backend-api/src/Controller/V1/Product/ProductDataFactoryInterface.php, packages/backend-api/src/Resources/config/services.yml, packages/backend-api/tests/Unit/Controller/V1/Product/ProductControllerTest.php
|Description, reason for the PR| Backend API supports writing operation for products - create, update (even partially), delete
=> [backend-api] create, update, delete products

docs/upgrade/UPGRADE-unreleased.md
|Description, reason for the PR| Part of our release process is revision of the upgrade notes so they make sense as a whole
=> [shopsys] upgrade notes prepared for v8.0.0 release

utils/releaser/src/ReleaseWorker/AfterRelease/RemoveLockFilesReleaseWorker.php, utils/releaser/src/ReleaseWorker/Release/CreateAndCommitComposerLockAndPackageLockReleaseWorker.php, utils/releaser/src/ReleaseWorker/Release/CreateAndPushGitTagReleaseWorker.php, utils/releaser/src/ReleaseWorker/Release/CreateAndPushGitTagsExceptProjectBaseReleaseWorker.php
|Description, reason for the PR| We want to ensure that there are no problems with versions of dependencies so we lock them when releasing
=> [shopsys] releaser now commits package and composer locks

packages/framework/src/Component/UploadedFile/UploadedFileDeleteDoctrineListener.php, packages/framework/src/Component/UploadedFile/UploadedFileFacade.php, packages/framework/tests/Unit/Component/UploadedFile/UploadedFileDeleteDoctrineListenerTest.php
|Description| if add entity to config for uploading file and then i have optional file for this entity .. remove from db throw not found exception
=> [framework] UploadedFileDeleteDoctrineListener not throw not found enitity 

docs/introduction/faq-and-common-issues.md
|Description, reason for the PR| a tip from @adamtyron :+1: There is a nice tool that can be used for debugging emails when using Docker - thanks to the tool, you can see all the emails sent by the application (including their headers) in a web UI
=> [shopsys] faq: added tip for emails debugging

docs/introduction/faq-and-common-issues.md, docs/introduction/running-acceptance-tests.md
|Description, reason for the PR| We want our users to know this very handy information (on how to see the progress of acceptance tests when using Docker) that has been discovered by @PetrHeinz during implementation of https://github.com/shopsys/shopsys/pull/1245
=> [shopsys] docs: added quick guide on how to see the progress of acceptance tests when using Docker

docs/installation/installation-using-docker-linux.md, docs/installation/installation-using-docker-macos.md, docs/installation/installation-using-docker-windows-10-pro-higher.md
|Description, reason for the PR| https://github.com/shopsys/shopsys/issues/1151
|Fixes issues| closes #1151  
=> [shopsys] clarification of docker instalation guides

docs/introduction/start-building-your-application.md
|Description, reason for the PR| After installation developer might not know that to use the whole potential and feature of SSFW as presented and advertised, he might need to install additional parts as Backend API.
|Fixes issues| closes #1212 
=> [shopsys] Info about backend API installation added to 'Start you project' guide

packages/framework/src/Resources/views/Admin/Content/Order/addProduct.html.twig
=> [framework] fixed: product now can be added to order

README.md
|Description, reason for the PR| The list of sites build on Shopsys Framework is not updated, The new interesting projects are missing.
=> Update list of references in readme file

docs/upgrade/UPGRADE-v7.3.2-dev.md, project-base/app/config/packages/doctrine.yml
|Description, reason for the PR| setup mappings for entities in project components.  It saves a lot of time searching, why e.g extension of Image doesn't work :slightly_smiling_face: I followed instructions from [Entity extension](https://github.com/shopsys/shopsys/blob/master/docs/extensibility/entity-extension.md) but I was not able to make it work. 
=> [project-base] enable entity extension from components

docs/introduction/start-building-your-application.md
- the files are already committed to project base in the released versions
|Description, reason for the PR| We are now commiting the lock files in released versions of `project-base` so the information is redundant and might be even confusing
=> [shopsys] start-building-your-application.md: removed info about commiting lock files

docs/upgrade/UPGRADE-v8.1.0-dev.md, project-base/src/Shopsys/ShopBundle/Controller/Front/RegistrationController.php, project-base/tests/ShopBundle/Smoke/Http/RouteConfigCustomization.php
=> [project-base] redirect logged user from registration page to homepage

utils/releaser/src/ReleaseWorker/AfterRelease/RemoveLockFilesReleaseWorker.php, utils/releaser/src/ReleaseWorker/Release/CreateAndCommitLockFilesReleaseWorker.php
|Description, reason for the PR| We want to have migrations-lock.yml present in every version so you don't need to commit it every time you start a new project
=> [shopsys] commit migrations-lock.yml with other lock files when releasing

docs/installation/installation-using-docker-macos.md, docs/upgrade/UPGRADE-v8.1.0-dev.md, project-base/.travis.yml, project-base/scripts/install.sh
|Description, reason for the PR| We want automated tests for instalation script on various platforms
|Fixes issues| closes #1150 
Result of test is available through travis in [`shopsys/project-base`](https://travis-ci.org/shopsys/project-base) repository.
=> [project-base] added travis build for automated testing of installation script to project-base

docker/conf/docker-compose-mac.yml.dist, docker/conf/docker-compose-win.yml.dist, docker/conf/docker-compose.yml.dist, docs/upgrade/UPGRADE-v8.1.0-dev.md, open-source-license-acknowledgements-and-third-party-copyrights.md, project-base/docker/conf/docker-compose-mac.yml.dist, project-base/docker/conf/docker-compose-win.yml.dist, project-base/docker/conf/docker-compose.yml.dist, project-base/kubernetes/deployments/adminer.yml
|Description, reason for the PR| Let's keep our tools up to date! See [the changelog of Adminer](https://github.com/vrana/adminer/blob/master/changes.txt) to know what has changed.
|Fixes issues| Various bugs in Adminer 
=> [shopsys] upgrade the Adminer Docker image to 4.7

project-base/src/Shopsys/ShopBundle/Resources/styles/front/common/components/list/images.less, project-base/src/Shopsys/ShopBundle/Resources/views/Front/Content/Brand/list.html.twig, upgrade/UPGRADE-v7.3.2-dev.md
|Description, reason for the PR| Display correctly two line brand name  or with long one word name
|Fixes issues| fixes #897 
Screen before change:
Screen after change:
=> [project-base] brand list - brand label in two rows with label text wrapping

packages/framework/src/Resources/views/Admin/Content/Default/index.html.twig
|Description, reason for the PR| fixes unreachable advanced search at admin dashboard quick search on right side.
|Fixes issues| closes https://github.com/shopsys/shopsys/issues/1293 
=> [framework] fix unreachable advanced search link on dashboard

.ci/restart_kubernetes.sh, docs/cookbook/jenkins-configuration.md, docs/upgrade/UPGRADE-v9.0.0-dev.md, packages/framework/build.xml, project-base/app/getEnvironment.php, project-base/kubernetes/deployments/webserver-php-fpm.yml
|Description, reason for the PR| Many phing targets should not be run in production environment unless really intended.
|Fixes issues| closes #1236 
=> [framework] all phing targets that should not be run in production now ask for permission if in production environment

packages/framework/src/Controller/Admin/LoginController.php, packages/framework/src/Model/Security/Authenticator.php, packages/framework/src/Resources/translations/messages.cs.po, packages/framework/src/Resources/translations/messages.en.po
|Description, reason for the PR| `php phing translations-dump` cannot resolve variable introduced in  #1360
=> [framework] fixed dumping translation

.sonarcloud.properties
|Description, reason for the PR| Introduces SonarCloud for checking PRs to improve code quality.
|New feature| Yes (for monorepo devs) 
=> [shopsys] Allow to scan PRs with SonarCloud

docs/cookbook/adding-a-new-entity.md, docs/cookbook/adding-new-attribute-to-an-entity.md, docs/introduction/how-to-set-up-domains-and-locales.md
|Description, reason for the PR| We need to use relative links among the files in the docs in order to make the links work properly on http://docs.shopsys.com
=> [shopsys] fix links in docs

docs/introduction/start-building-your-application.md
|Description, reason for the PR| We want to have this page rendered corectly on docs.shopsys.com
=> [shopsys] start-building-your-application.md: fixed formatting and minor tweaks

docs/backend-api/api-methods.md, docs/backend-api/backend-api-installation.md
|Description, reason for the PR| We want to have the pages rendered corectly on docs.shopsys.com
=> [shopsys] docs: fixed formatting in backend-api section

packages/framework/src/Resources/styles/admin/components/in/sort-arrows.less
|Description, reason for the PR| Fixes sort arrow in table header so, now it don´t change columns width.
|Fixes issues| #1278  
=> [framework] design - admin - sorting arrows not changing column width

packages/framework/src/Resources/styles/admin/components/form/error.less, packages/framework/src/Resources/styles/admin/components/form/line.less, packages/framework/src/Resources/styles/admin/components/table/main.less, packages/framework/src/Resources/views/Admin/Content/Order/orderItem.html.twig, packages/framework/src/Resources/views/Admin/Form/orderItems.html.twig
|Description, reason for the PR| Fix block form error messages at order detail in table. Table headers centering to right.
|Fixes issues| fixes #1294  
Screen before:
Screen after:
=> [framework] refactoring error messages at admin order detail form

packages/framework/src/Controller/Admin/FeedController.php, packages/framework/src/Resources/styles/admin/components/form/error.less, packages/framework/src/Resources/styles/admin/components/in/icon.less, packages/framework/src/Resources/styles/admin/components/in/product-visibility.less, packages/framework/src/Resources/styles/admin/components/list/domain.less, packages/framework/src/Resources/styles/admin/components/window/overlay.less, packages/framework/src/Resources/styles/admin/helpers/base.less, packages/framework/src/Resources/styles/admin/main.less, packages/framework/src/Resources/styles/admin/todo.less, packages/framework/src/Resources/views/Admin/Content/Product/listGrid.html.twig, packages/framework/src/Resources/views/Admin/Content/Product/visibility.html.twig
|Description, reason for the PR| Clean temporary css classes, remove unneded classes from todo.less file
Places to check after changes:
1) Feeds - right column with button
2) Forms - error icon - has pointer cursor
3) Product list - visibility icon - help cursor on hover
4) Product list - visibility popup window - specially title and domain icon
5) Admin - popup overlay
=> [framework] todo.less is incorporated properly into framework

packages/framework/src/Resources/styles/admin/components/list/images.less
|Description, reason for the PR| small refactoring of image list due to drag image position misplacement on right side
|Fixes issues| #1146  
=> [framework] fixed image drag&drop in product gallery

packages/framework/src/Resources/styles/admin/core/form/input.less
|Description, reason for the PR| Fix cursor size when input is focused at Apple devices.
|Fixes issues| #1322  
=> [framework] fix cursor size in form inputs for Apple devices

packages/framework/src/Resources/views/Admin/Content/Slider/edit.html.twig, upgrade/UPGRADE-v9.0.0-dev.md
|Description, reason for the PR| I think this block is not necessary so I tried to remove it and nothing happened.
=> [framework] removed unnecessary domain block in Admin Slider

README.md, docs/introduction/using-form-types.md
|Description, reason for the PR| I overlooked the conflict signs when I was merging `8.0` to master previously :man_facepalming: 
=> [shopsys] fixed wrongly resolved conflicts when 8.0 branch was merged to master

docs/cookbook/jenkins-configuration.md, docs/installation/installation-using-docker-application-setup.md, docs/installation/installation-using-docker-linux.md, docs/installation/installation-using-docker-on-production-server.md, docs/installation/installation-using-docker-windows-10-pro-higher.md, docs/installation/native-installation.md, docs/introduction/console-commands-for-application-management-phing-targets.md, docs/introduction/how-to-set-up-domains-and-locales.md
|Description, reason for the PR| The article can change over the time and should be linked properly, see https://github.com/shopsys/shopsys/pull/1436#discussion_r330241686
=> [shopsys] docs: copyrights article is linked in the proper version

docs/contributing/guidelines-for-writing-documentation.md
|Description, reason for the PR| There are new information that our docs writers need to know
=> [shopsys] guidelines-for-writing-documentation: added information about mkdocs and readthedocs

docs/frontend-api/introduction-to-frontend-api.md, packages/framework/src/Model/Product/ProductOnCurrentDomainFacade.php, packages/framework/src/Model/Product/ProductRepository.php, packages/frontend-api/src/Model/Money/MoneyType.php, packages/frontend-api/src/Model/Resolver/Price/PriceResolver.php, packages/frontend-api/src/Model/Resolver/Products/ProductResolver.php, packages/frontend-api/src/Model/Resolver/Products/ProductResolverMap.php, packages/frontend-api/src/Model/Resolver/Products/ProductsResolver.php, packages/frontend-api/src/Resources/config/graphql-types/AvailabilityDecorator.types.yml, packages/frontend-api/src/Resources/config/graphql-types/FlagDecorator.types.yml, packages/frontend-api/src/Resources/config/graphql-types/MoneyDecorator.types.yml, packages/frontend-api/src/Resources/config/graphql-types/PriceDecorator.types.yml, packages/frontend-api/src/Resources/config/graphql-types/ProductDecorator.types.yml, packages/frontend-api/src/Resources/config/graphql-types/QueryDecorator.types.yml, packages/frontend-api/src/Resources/config/graphql-types/UnitDecorator.types.yml, packages/frontend-api/src/Resources/config/services.yml, phpstan.neon, project-base/app/config/packages/shopsys_frontend_api.yml, project-base/phpstan.neon, project-base/src/Shopsys/ShopBundle/Resources/graphql-types/Availability.types.yml, project-base/src/Shopsys/ShopBundle/Resources/graphql-types/Flag.types.yml, project-base/src/Shopsys/ShopBundle/Resources/graphql-types/Money.types.yml, project-base/src/Shopsys/ShopBundle/Resources/graphql-types/Price.types.yml, project-base/src/Shopsys/ShopBundle/Resources/graphql-types/Product.types.yml, project-base/src/Shopsys/ShopBundle/Resources/graphql-types/Unit.types.yml, project-base/tests/FrontendApiBundle/Functional/Product/ProductTest.php, project-base/tests/FrontendApiBundle/Functional/Product/ProductsTest.php, project-base/tests/FrontendApiBundle/Test/GraphQlTestCase.php, project-base/tests/ShopBundle/Test/FunctionalTestCase.php, upgrade/UPGRADE-v9.0.0-dev.md
|Description, reason for the PR| Added support for loading all products via frontend API
|[BC breaks]|No
=> [frontend-api] Products can now be loaded via frontend API

.travis.yml
|Description, reason for the PR| User permissions in travis build was set wrong. This PR fixes it 
=> Fixed setting user permissions for travis

packages/framework/src/Resources/views/Components/Collector/shopsysFramework.html.twig
|Description, reason for the PR| In toolbar resources was added link to style guide
=> [framework] add link to styleguide in toolbar

upgrade/UPGRADE-v8.1.0-dev.md
|Description, reason for the PR| adds upgrage notes for styleguide introduced in #1463
=> [docs] upgrade notes for styleguide

packages/framework/src/Component/Collector/ShopsysFrameworkDataCollector.php, packages/framework/src/Resources/views/Components/Collector/shopsysFramework.html.twig
|Description, reason for the PR| Since we have new documentation page we want to share it whith others.
=> [framework] changed link to docs.shopsys.com

docs/frontend-api/pagination.md, packages/framework/easy-coding-standard.yml, packages/framework/src/Model/Category/CategoryFacade.php, packages/framework/src/Model/Category/CategoryRepository.php, packages/framework/src/Model/Product/ProductOnCurrentDomainFacade.php, packages/framework/src/Model/Product/ProductRepository.php, packages/frontend-api/src/Model/Resolver/Category/CategoryResolver.php, packages/frontend-api/src/Model/Resolver/Products/ProductsResolver.php, packages/frontend-api/src/Resources/config/graphql-types/CategoryDecorator.types.yml, packages/frontend-api/src/Resources/config/graphql-types/Pagination/ProductDecoratorConnection.types.yml, packages/frontend-api/src/Resources/config/graphql-types/ProductDecorator.types.yml, packages/frontend-api/src/Resources/config/graphql-types/QueryDecorator.types.yml, project-base/src/Shopsys/ShopBundle/Resources/graphql-types/Pagination/ProductConnection.types.yml, project-base/tests/FrontendApiBundle/Functional/Category/CategoryTest.php, project-base/tests/FrontendApiBundle/Functional/Product/ProductsTest.php, upgrade/UPGRADE-v9.0.0-dev.md
|Description, reason for the PR| products in fe api weren't paginated so developers had no chance of getting just a certain page of products and not all of them. This PR adds pagination
=> [shopsys] added pagination to frontend api

upgrade/upgrade-instructions-for-currency-rounding.md
|Description, reason for the PR| update upgrade notes for currencies, fix diff marking
=> update upgrade notes for currencies

upgrade/UPGRADE-v8.1.0-dev.md
|Description, reason for the PR| This PR fixes path and diff colorisation for PR #1472 
=> [docs] fixed upgrade notes for cleaning admin styles

upgrade/UPGRADE-v8.1.0-dev.md
|Description, reason for the PR| This PR improves upgrade notes for PR #1392 
=> [docs] fixed upgrade notes phpunit injector

upgrade/UPGRADE-v8.1.0-dev.md
|Description, reason for the PR| This PR adds missing informations for checkbox updates and fixes mistakes in code. Also fixed diff colorisation.
=> [docs] fix upgrade notes 8.1

README.md
|Description, reason for the PR| Extension of reference list
=> [shopsys] Added reference to bushman.cz into readme

upgrade/UPGRADE-v8.1.0-dev.md
|Description, reason for the PR| add better scope to less files, add more info about webline layout task
=> [docs] update upgrade notes

project-base/src/Resources/scripts/frontend/product/productFilterBox.js, project-base/src/Resources/styles/front/common/components/box/filter.less, project-base/src/Resources/styles/front/common/components/box/list.less, project-base/src/Resources/styles/front/common/components/in/paging.less, project-base/src/Resources/styles/front/common/layout/layout.less, project-base/templates/Front/Content/Product/filterFormMacro.html.twig, project-base/templates/Front/Content/Product/list.html.twig, project-base/templates/Front/Content/Product/search.html.twig, project-base/tests/App/Acceptance/acceptance/CustomerLoginCest.php, upgrade/UPGRADE-v9.0.0-dev.md, upgrade/upgrade-instructions-for-base-layout.md
|Description, reason for the PR| Move product list filter and add open/close function to sections. Add open button on mobile devices
=> [project-base] - Move product list filter to left panel

project-base/config/images.yml, upgrade/UPGRADE-v9.0.0-dev.md, upgrade/upgrade-instruction-for-vats-per-domain.md, upgrade/upgrade-instructions-for-base-layout.md
|Description, reason for the PR| Fixed insufficient upgrade notes found during upgrade.
=> [shopsys] update upgrade notes

project-base/src/Shopsys/ShopBundle/Resources/views/Front/Inline/FlashMessage/index.html.twig, upgrade/UPGRADE-v8.1.0-dev.md
|Description, reason for the PR| Add correct type of flash message to show text in correct colours.
=> [project-base] - error flash messages - add correct type to template

packages/framework/src/Resources/styles/admin/components/in/message.less
|Description, reason for the PR| Enables form error messages with long words (e.g filepaths)
=> [framework] message error with long words

packages/framework/src/Component/Redis/RedisFacade.php
|Description, reason for the PR| Finding keys by pattern must be done via SCAN, not KEYS. KEYS is blocking command and It causes performance problems for traffic in production.
=> [framework] Clean redis cache via scan and unlink

packages/framework/src/Model/Customer/User/CustomerUserFacade.php, packages/framework/src/Model/Order/OrderFacade.php, project-base/src/Controller/Front/CustomerController.php
|Description, reason for the PR| In #1543 there were forgotten methods with wrong name for a new structure which might be confusing.
=> [framework] fix customer structure method names

upgrade/UPGRADE-v9.0.0-dev.md
|Description, reason for the PR| #1543, #1573 was merged without upgrade notes. This PR adds them.
=> [docs] added upgrade notes for customer structure

packages/framework/src/Resources/styles/admin/components/form/type-and-go.less, packages/framework/src/Resources/styles/admin/components/in/paging.less, packages/framework/src/Resources/views/Admin/Content/Order/AdvancedSearch/ruleForm.html.twig, packages/framework/src/Resources/views/Admin/Grid/Grid.html.twig
|Description, reason for the PR| Adds smaller gap under pagination, fixes pagination next and preveiw button arrow position, fixes go to page button arrow position.
|Fixes issues| closes #1519  
=> [framework] - admin pagination grafic issues

docs/frontend/hover-intent.md, docs/frontend/index.md, docs/frontend/navigation.yml, project-base/src/Resources/scripts/frontend/categoryPanel.js, project-base/src/Resources/scripts/frontend/components/hoverIntent.js, project-base/src/Resources/scripts/frontend/plugins/jquery.hoverIntent.js, project-base/src/Resources/styles/front/common/components/list/menu.less, project-base/templates/Front/Content/Category/panel.html.twig, upgrade/UPGRADE-v9.0.0-dev.md
|Description, reason for the PR| Add hover in / hover out timeout for horizontal menu. 
=> [project-base] - add hover timeout to horizontal menu

changelog-linker.yml
|Description, reason for the PR| Core developers of Shopsys Framework should not be mentioned in changelog.
=> [shopsys] updated list of authors to generate changelog

project-base/src/Resources/styles/front/common/components/box/list.less, project-base/templates/Front/Content/Product/listByBrand.html.twig
|Description, reason for the PR| After removing left panel from frontend, there was bad layout of product list by brand.
Before: 
After:
=> [project-base] - fix brand list without panel

upgrade/UPGRADE-v8.0.0.md
|Description, reason for the PR| typo
=> [shopsys] UPGRADE-v8.0.0.md - fix typo

docs/frontend/index.md, docs/frontend/navigation.yml, docs/frontend/npm-and-webpack.md, docs/introduction/console-commands-for-application-management-phing-targets.md, docs/introduction/translations.md, packages/framework/build.xml, project-base/assets/js/frontend.js, project-base/assets/js/frontend/components/lazyLoadInit.js, project-base/docker/php-fpm/Dockerfile, project-base/package.json, project-base/templates/Front/Layout/base.html.twig, project-base/webpack.config.js, symfony.lock, upgrade/UPGRADE-v9.0.0-dev.md, upgrade/upgrade-instruction-for-webpack.md
|Description, reason for the PR| Added docs and upgrades for webpack introduced in #1545 
=> Webpack docs and upgrade notes

docs/cookbook/extending-product-list.md
|Description, reason for the PR| based on my experience during upgrading
=> [shopsys] extending-product-list.md fixes

upgrade/upgrade-instructions-for-entities-simplification.md
|Description, reason for the PR| the instruction was wrong :)
=> [shopsys] upgrade-instructions-for-entities-simplification.md: fix instruction

project-base/src/Resources/styles/front/common/components/in/place.less, project-base/src/Resources/styles/front/common/todo.less, project-base/templates/Front/Layout/footer.html.twig, upgrade/UPGRADE-v9.0.0-dev.md
|Description, reason for the PR| Fix footer advert webline background and image advert position to get advert image more visible.
|Fixes issues| closes #1546  
Screen before:
Screen after:
=> [project-base] footer advert background

upgrade/upgrade-instruction-for-webpack.md
|Description, reason for the PR| A little fixes in webpack doc
=> [framework] Webpack doc fix

project-base/assets/js/frontend/cart/cartBox.js, project-base/assets/js/frontend/cart/cartBoxItemRemover.js, project-base/assets/js/frontend/cart/index.js, project-base/assets/js/frontend/components/hoverIntent.js, project-base/config/routes/shopsys_front.yml, project-base/src/Controller/Front/CartController.php, project-base/src/Resources/styles/front/common/layout/header/cart-detail.less, project-base/src/Resources/styles/front/common/layout/header/cart.less, project-base/src/Resources/styles/front/common/main.less, project-base/templates/Front/Inline/Cart/cartBox.html.twig, project-base/templates/Front/Inline/Cart/cartBoxItemMacro.html.twig, project-base/templates/Front/Layout/header.html.twig, project-base/tests/App/Acceptance/acceptance/CartCest.php, project-base/tests/App/Acceptance/acceptance/OrderCest.php, project-base/tests/App/Acceptance/acceptance/PageObject/Front/CartPage.php, project-base/tests/App/Acceptance/acceptance/PageObject/Front/OrderPage.php, upgrade/UPGRADE-v9.0.0-dev.md
|Description, reason for the PR| This pull request adds cart summary with items into page header.
|Internal ID| US-7313|
=> [project-base] cart detail on hover

LICENSE, packages/backend-api/LICENSE, packages/coding-standards/LICENSE, packages/form-types-bundle/LICENSE, packages/framework/LICENSE, packages/frontend-api/LICENSE, packages/google-cloud-bundle/LICENSE, packages/http-smoke-testing/LICENSE, packages/migrations/LICENSE, packages/monorepo-tools/LICENSE, packages/plugin-interface/LICENSE, packages/product-feed-google/LICENSE, packages/product-feed-heureka-delivery/LICENSE, packages/product-feed-heureka/LICENSE, packages/product-feed-zbozi/LICENSE, packages/read-model/LICENSE, project-base/LICENSE
|Description, reason for the PR| There should be current year mentioned in license files but after year 2020 came, there were no changes...
=> [shopsys] New year for license files

upgrade/upgrade-instructions-for-read-model-for-product-lists.md
|Description, reason for the PR| typo
=> [shopsys] upgrade-instructions-for-read-model-for-product-lists: fix typo

upgrade/UPGRADE-v7.3.2.md
|Description, reason for the PR| typo in filename
=> [shopsys] fix typo in upgrade notes

upgrade/upgrade-instructions-for-entities-simplification.md
|Description, reason for the PR| It does not make sense to instruct users to "move" or "remove" tests from vendor (moreover when the tests are moved already :slightly_smiling_face: ) 
=> [shopsys] upgrade-instructions-for-entities-simplification: minor tweaks

upgrade/UPGRADE-v8.1.0.md
|Description, reason for the PR| there is no "project-base" folder in the actual project
=> [shopsys] UPGRADE-v8.1.0.md tweak

upgrade/UPGRADE-v9.0.0-dev.md
|Description, reason for the PR| just to fix links
=> [shopsys] UPGRADE-v9.0.0-dev.md - formatting fixes

upgrade/UPGRADE-v8.1.0.md
|Description, reason for the PR| fixed bad links in upgrade guide to v8.1.0 
=> [shopsys] UPGRADE-v8.1.0.md: fix links to docs

upgrade/upgrade-instructions-for-entities-simplification.md
|Description, reason for the PR| just to be exact...see https://github.com/shopsys/project-base/commit/b508c08213932aee2a1a8a71cae2c42ccffa4da1
=> [shopsys] upgrade-instructions-for-entities-simplification.md: simple fix

project-base/assets/js/styleguide/styleguide.js, upgrade/upgrade-instruction-for-webpack.md
|Description, reason for the PR| We had bug in styleguide js file. We assign scope into undeclared property. This PR fix it.
=> [project-base] removed global from styleguide js

project-base/tests/App/Functional/Model/Order/OrderTransportAndPaymentTest.php, project-base/tests/App/Functional/Model/Payment/IndependentPaymentVisibilityCalculationTest.php, project-base/tests/App/Functional/Model/Payment/PaymentDomainTest.php, project-base/tests/App/Functional/Model/Transport/IndependentTransportVisibilityCalculationTest.php, project-base/tests/App/Functional/Model/Transport/TransportDomainTest.php, upgrade/UPGRADE-v9.0.0-dev.md
|Description, reason for the PR| There are failing tests on single domain. This PR makes tests more bulletproof.
=> [shopsys] fixed Payment and Transport tests for single domain

packages/framework/assets/js/admin/components/OrderPreview.js, packages/framework/src/Form/Admin/Category/CategoryFormType.php, packages/framework/src/Resources/styles/admin/components/form/line.less, packages/framework/src/Resources/styles/admin/components/form/tree.less, packages/framework/src/Resources/styles/admin/components/in/domain.less, packages/framework/src/Resources/styles/admin/components/in/image.less, packages/framework/src/Resources/styles/admin/components/table/touch-always.less, packages/framework/src/Resources/styles/admin/components/window/preview.less, packages/framework/src/Resources/styles/admin/core/variables.less, packages/framework/src/Resources/styles/admin/helpers/base.less, packages/framework/src/Resources/translations/messages.cs.po, packages/framework/src/Resources/translations/messages.en.po, packages/framework/src/Resources/views/Admin/Content/Category/list.html.twig, packages/framework/src/Resources/views/Admin/Content/Order/orderItem.html.twig, packages/framework/src/Resources/views/Admin/Form/orderItems.html.twig, packages/framework/src/Resources/views/Admin/Grid/Grid.html.twig, project-base/templates/Front/Content/Product/detail.html.twig, upgrade/UPGRADE-v9.0.0-dev.md
|Description, reason for the PR| Fixes: domain icon position, order detail form better display, cursor on dragable and non dragable categories, product detail - hide header of variants when no variant is displayed
|Fixes issues| closes #1555  
=> [framework] admin issues after v 9 release

docker/conf/docker-compose-mac.yml.dist, docker/conf/docker-compose-win.yml.dist, docker/conf/docker-compose.yml.dist, docs/installation/application-requirements.md, docs/installation/installation-using-docker-on-production-server.md, open-source-license-acknowledgements-and-third-party-copyrights.md, project-base/config/parameters_common.yml, project-base/docker/conf/docker-compose-mac.yml.dist, project-base/docker/conf/docker-compose-win.yml.dist, project-base/docker/conf/docker-compose.yml.dist, project-base/docker/php-fpm/Dockerfile, project-base/kubernetes/deployments/postgres.yml, project-base/tests/App/Test/Codeception/Module/Db.php, upgrade/UPGRADE-v9.0.0-dev.md, upgrade/upgrading-monorepo.md
|Description, reason for the PR| PostgreSQL server is now in version 12. In this PR we have upgraded PostgreSQL to latest |New feature| Yes 
I didn't update UPGRADE.md
=> [shopsys] Update to Postgres 12

project-base/config/forms.yml
=> [project-base] extension of user form is now working correctly

packages/framework/src/Model/Slider/SliderItem.php
|Description, reason for the PR| This PR fixed editing of SliderItem's domain id
|Fixes issues| #1449 
=> [framework] fixed editing of SliderItem's domain id

packages/framework/src/Controller/Admin/AdministratorController.php, packages/framework/src/Model/Administrator/Security/AdministratorRolesChangedFacade.php, packages/framework/src/Model/Administrator/Security/AdministratorRolesChangedSubscriber.php, upgrade/UPGRADE-v9.0.0-dev.md
|Description, reason for the PR| refresh administrator roles after edit own profile
=> [framework] refresh administrator roles after edit own profile

packages/framework/src/Migrations/Version20200225102504.php, packages/framework/src/Model/Customer/BillingAddress.php, packages/framework/src/Model/Customer/BillingAddressFacade.php, packages/framework/src/Model/Customer/BillingAddressRepository.php, packages/framework/src/Model/Customer/Customer.php, packages/framework/src/Model/Customer/CustomerData.php, packages/framework/src/Model/Customer/CustomerDataFactory.php, packages/framework/src/Model/Customer/CustomerDataFactoryInterface.php, packages/framework/src/Model/Customer/CustomerFacade.php, packages/framework/src/Model/Customer/CustomerFactory.php, packages/framework/src/Model/Customer/CustomerFactoryInterface.php, packages/framework/src/Model/Customer/CustomerRepository.php, packages/framework/src/Model/Customer/Exception/BillingAddressException.php, packages/framework/src/Model/Customer/Exception/BillingAddressNotFoundException.php, packages/framework/src/Model/Customer/Exception/CustomerException.php, packages/framework/src/Model/Customer/Exception/CustomerNotFoundException.php, packages/framework/src/Model/Customer/User/CustomerUserFacade.php, packages/framework/src/Resources/config/services.yml, packages/framework/tests/Unit/Model/Customer/CustomerUserUpdateDataFactoryTest.php, packages/framework/tests/Unit/Model/Customer/UserTest.php, project-base/tests/App/Functional/PersonalData/PersonalDataExportXmlTest.php, upgrade/UPGRADE-v9.0.0-dev.md
|Description, reason for the PR| There were some irregularities in managing customers and billing addresses. This has been united, so these entities are now managed via their facades.
=> [framework] customer structure refactoring

.ci/build_kubernetes.sh, composer.json, docker/conf/docker-compose-mac.yml.dist, docker/conf/docker-compose-win.yml.dist, docker/conf/docker-compose.yml.dist, docs/cookbook/adding-a-new-elasticsearch-index.md, docs/cookbook/extending-product-list.md, docs/model/elasticsearch.md, packages/framework/src/Component/Elasticsearch/IndexRepository.php, packages/framework/src/Model/Product/Search/FilterQuery.php, packages/framework/src/Model/Product/Search/ProductElasticsearchRepository.php, project-base/docker/conf/docker-compose-mac.yml.dist, project-base/docker/conf/docker-compose-win.yml.dist, project-base/docker/conf/docker-compose.yml.dist, project-base/docker/elasticsearch/Dockerfile, project-base/src/Resources/definition/product/1.json, project-base/src/Resources/definition/product/2.json, upgrade/UPGRADE-v9.0.0-dev.md, upgrade/upgrade-instructions-for-read-model-for-product-lists-from-elasticsearch.md
|Description, reason for the PR| As SSFW developer I need Elasticsearch updated to current version. Also developers need Kibana for local development.
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| Yes
I didn't update UPGRADE.md
=> Upgrade to Elasticsearch 7

packages/product-feed-heureka/src/Model/HeurekaCategory/HeurekaCategoryFacade.php
=> [product-feed-heureka] Preserve relation between categories and Heureka categories

packages/framework/src/Resources/translations/messages.cs.po, packages/framework/src/Resources/translations/messages.en.po, packages/framework/src/Resources/translations/validators.cs.po, packages/framework/src/Resources/translations/validators.en.po
|Description, reason for the PR| Some translations were missing or in wrong place. This PR fixes that.
=> [framework] added missing translations

packages/framework/src/Form/WysiwygTypeExtension.php, project-base/webpack.config.js
|Description, reason for the PR| Fixed webpack config when the same style directory is set for multiple domains.
=> [shopsys] fixed common styles in webpack config

docs/frontend-api/index.md, packages/frontend-api/apiary.apib, packages/frontend-api/src/Resources/config/graphql-types/Mutation.types.yml, packages/frontend-api/src/Resources/config/graphql-types/QueryDecorator.types.yml
|Description, reason for the PR| Frontend API methods were not documented, this has been fixed by this PR.
=> [frontend-api] added frontend api methods docs for apiary

packages/framework/assets/js/admin/utils/constant.js, packages/framework/assets/js/admin/validation/form/validationMailTemplate.js, packages/framework/assets/js/common/validation/customizeBundle.js, packages/framework/src/Resources/views/Admin/Form/abstractFileuploadFields.html.twig
|Description, reason for the PR| validation errors for the uploadedFilenames and currentFilenamesIndexedById are displayed
|Fixes issues|  closes #1558 
=> [framework] validation errors for the uploadedFilenames are displayed

packages/framework/src/Resources/translations/messages.cs.po
|Description, reason for the PR| typo
=> [framework] messages.cs.po: fix typo

docs/extensibility/entity-extension.md, packages/backend-api/install/config/parameters_common.yml.patch, packages/framework/easy-coding-standard.yml, packages/framework/src/DependencyInjection/Compiler/RegisterExtendedEntitiesCompilerPass.php, packages/framework/src/ShopsysFrameworkBundle.php, project-base/config/parameters_common.yml, upgrade/UPGRADE-v9.0.0-dev.md
|Description, reason for the PR| It saves time and prevents bugs. It was annoying and unnecessary.
=> [shopsys] automatically generated entity extension map

project-base/templates/Front/Content/Category/panel.html.twig, upgrade/UPGRADE-v9.0.0-dev.md
|Description, reason for the PR| strict comparison of objects in twig template
|Fixes issues| closes #1780 
=> [project-base] strict comparison for categories in Category/panel.html.twig template

project-base/assets/js/frontend/components/index.js, project-base/assets/js/frontend/components/popup.js, upgrade/UPGRADE-v9.0.0-dev.md
|Description, reason for the PR|add missing javasrcipt for popup single image for class: js-popup-image
|New feature|No
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)|No 
|Fixes issues|popup window on single image don't work 
=> [project-base] fixed not working popup window on single image

project-base/assets/js/frontend/validation/form/customerValidator.js, project-base/templates/Front/Content/Customer/edit.html.twig, upgrade/UPGRADE-v9.0.0-dev.md
|Description, reason for the PR| During extension of delivery addresses there were validations not updated. This has been fixed by this PR.
=> [project-base] fixed customer section validation

upgrade/UPGRADE-v9.0.0-dev.md
|Description, reason for the PR| There were some missing info in upgrade notes.
=> [framework] fix upgrade notes of multiple delivery addresses

packages/framework/src/Migrations/Version20200416114815.php, packages/framework/src/Model/Customer/User/CustomerUserFacade.php, packages/framework/src/Model/Customer/User/CustomerUserRefreshTokenChain.php, packages/framework/src/Model/Customer/User/CustomerUserRefreshTokenChainData.php, packages/framework/src/Model/Customer/User/CustomerUserRefreshTokenChainFacade.php, packages/framework/src/Model/Customer/User/CustomerUserRefreshTokenChainRepository.php, packages/frontend-api/apiary.apib, packages/frontend-api/src/Model/Mutation/Login/LoginMutation.php, packages/frontend-api/src/Model/Mutation/Login/RefreshTokensMutation.php, packages/frontend-api/src/Model/Mutation/Logout/LogoutMutation.php, packages/frontend-api/src/Model/Token/TokenFacade.php, packages/frontend-api/src/Model/User/FrontendApiUser.php, packages/frontend-api/src/Model/User/FrontendApiUserFactory.php, packages/frontend-api/src/Resources/config/graphql-types/Mutation.types.yml, project-base/tests/FrontendApiBundle/Functional/Login/LoginTest.php, project-base/tests/FrontendApiBundle/Functional/Logout/LogoutTest.php, project-base/tests/FrontendApiBundle/Functional/Order/Resources/companyFieldsAreValidated.graphql, project-base/tests/FrontendApiBundle/Functional/Order/Resources/deliveryFieldsAreValidated.graphql, project-base/tests/FrontendApiBundle/Functional/Order/Resources/dynamicFieldsInOrder.graphql, project-base/tests/FrontendApiBundle/Functional/Order/Resources/fullOrder.graphql, project-base/tests/FrontendApiBundle/Functional/Order/Resources/minimalOrder.graphql, project-base/tests/FrontendApiBundle/Functional/Order/Resources/multipleProductsInOrder.graphql, upgrade/UPGRADE-v9.0.0-dev.md
|Description, reason for the PR| Using frontend api, users can now log out as well.
=> [shopsys] FE API: logout

composer.json, docker/conf/docker-compose-mac.yml.dist, docker/conf/docker-compose-win.yml.dist, docker/conf/docker-compose.yml.dist, docs/installation/installation-using-docker-on-production-server.md, open-source-license-acknowledgements-and-third-party-copyrights.md, packages/framework/composer.json, packages/framework/src/DependencyInjection/Compiler/LazyRedisCompilerPass.php, project-base/composer.json, project-base/docker/conf/docker-compose-mac.yml.dist, project-base/docker/conf/docker-compose-win.yml.dist, project-base/docker/conf/docker-compose.yml.dist, project-base/docker/php-fpm/Dockerfile, project-base/kubernetes/deployments/redis.yml, upgrade/UPGRADE-v9.0.0-dev.md
|Description, reason for the PR| There is newer version of redis client available. We want to keep our platform up to date.
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| Yes (upgrading dependency to new major version) 
=> [shopsys] Redis upgrade

packages/framework/assets/package.json, project-base/package.json
|Description, reason for the PR| We create new dev versio of npm package for fix project-base repo
=> [shopsys] upgraded npm

packages/framework/src/Component/Image/Config/ImageConfig.php
|Description, reason for the PR| cherry-picked commit from #1777 (thanks @pk16011990!), removed semicolon from annotation
=> [framework] fixed typo in annotation in ImageConfig

packages/framework/src/Component/Error/ErrorPagesFacade.php, project-base/templates/Front/Content/Error/error.html.twig, project-base/templates/Front/Layout/footer.html.twig, project-base/templates/Front/Layout/layout.html.twig, upgrade/UPGRADE-v9.0.0-dev.md
|Description, reason for the PR| better removed subscription form on error pages, this reshape PR #1799 
=> [shopsys] better removed subscription form on error pages

packages/backend-api/install/config/bundles.php.patch, packages/framework/assets/js/admin/components/Parameters.js, packages/framework/assets/js/common/utils/number.js, packages/framework/assets/js/common/validation/ShopsysConstraintUniqueCollection.js, packages/framework/src/Form/Admin/Product/ProductFormType.php, packages/framework/src/Resources/views/Admin/Form/productParameterValue.html.twig, project-base/config/bundles.php, upgrade/UPGRADE-v9.0.0-dev.md
|Description, reason for the PR| Parameter constraints on product detail page did not work properly. This PR fixes it.
=> [shopsys] fixed parameters validation

packages/framework/src/Component/Filesystem/Flysystem/VolumeDriver.php, packages/framework/src/Component/Translation/PhpFileExtractor.php, packages/frontend-api/src/Model/User/FrontendApiUserProvider.php
|Description, reason for the PR| New version of PHPStan comes with newly found problems that must be fixed.
=> [shopsys] fixed PHPStan violations

packages/framework/assets/styles/admin/components/list/files.less, packages/framework/assets/styles/admin/todo.less, project-base/assets/styles/frontend/common/svg-custom.less
|Description, reason for the PR| Move content of todo.less to right places, added svg antialiasing attributes.
=> [shopsys] Clear todo.less, add anti-aliasing

upgrade/UPGRADE-v9.0.0-dev.md
|Description, reason for the PR| just a typo
=> [shopsys] UPGRADE-v9.0.0-dev.md: fix typo

packages/frontend-api/apiary.apib
|Description, reason for the PR| This PR fix apiary doc format
=> [frontend-api] added get parameters into apib syntax

packages/framework/src/Resources/translations/messages.cs.po, packages/framework/src/Resources/translations/messages.en.po
|Description, reason for the PR| Some translation missing ...
=> [framework] added missing translation

packages/framework/assets/package.json, project-base/package.json
|Description, reason for the PR| Set new version of npm package
=> [shopsys] upgrade npm framework package

composer.json, packages/framework/composer.json, project-base/composer.json, upgrade/UPGRADE-v7.3.4-dev.md
|Description, reason for the PR| There were bugs in previous versions that caused problems. More info can be found in #1775 
|Fixes issues| closes #1775 
=> [shopsys] updated snc/redis-bundle version

packages/framework/src/Form/Admin/Customer/UserFormType.php
|Description, reason for the PR| Email uniqueness is wrongly checked against selected domain in administration instead of selected domain in form. This was fixed by this PR.
|Fixes issues| closes #1715 
=> [framework] fixed unique email validation in administration

packages/backend-api/composer.json, packages/form-types-bundle/composer.json, packages/framework/composer.json, packages/framework/src/ShopsysFrameworkBundle.php, packages/frontend-api/composer.json, packages/google-cloud-bundle/composer.json, packages/http-smoke-testing/composer.json, packages/migrations/composer.json, packages/plugin-interface/composer.json, packages/product-feed-google/composer.json, packages/product-feed-heureka-delivery/composer.json, packages/product-feed-heureka/composer.json, packages/product-feed-zbozi/composer.json, packages/read-model/composer.json, project-base/composer.json
|Description, reason for the PR|We removed branch alias for release new version and we forgot added back it after release
=> [shopsys] added back branch alias

packages/coding-standards/composer.json
|Description, reason for the PR| We want version 9.1.x dev in all master branches.
=> [coding-standards] added missing branch alias

docs/installation/installation-using-docker-windows-10-pro-higher.md
|Description, reason for the PR| Fixed installation SSFW on Windows 10 via docker
Description every commit:
1. [Debian in Windows Store](https://www.microsoft.com/en-us/p/debian/9msvkqc78pk6?activetab=pivot:overviewtab) doesn't have `wget` command installed by default, so I install it (I don't know whether is installed in native Debian 🤷‍♂)
2. Sometimes it happened to me [close linux console](https://github.com/shopsys/shopsys/blame/master/docs/installation/installation-using-docker-windows-10-pro-h …
=> [docs] Fixed installation docs for Windows 10 via Docker

composer.json, packages/framework/build.xml, packages/framework/composer.json, packages/framework/src/Command/ElFinderPostInstallCommand.php, packages/framework/src/Component/Filesystem/Flysystem/VolumeDriver.php, project-base/composer.json, project-base/config/bootstrap.php, project-base/config/bundles.php, project-base/config/routes/fm_elfinder.yaml, symfony.lock, upgrade/UPGRADE-v9.1.0-dev.md
|Description, reason for the PR| Fix wysiwyg elfinger file manager and update to last version 10.
|Fixes issues| closes #1893  
=> [shopsys] fixed not working upload of files in wysiwyg editor

project-base/docker/conf/docker-compose.prod.yml.dist, upgrade/UPGRADE-v9.0.1-dev.md
|Description, reason for the PR| I had problem with building docker for production, and this solved my troubles with connectiong to elasticsearch.
=> [project-base] Added extra_host for missing elasticsearch in production docker-compose.yml file

packages/framework/src/Form/Admin/Product/VariantFormType.php, packages/framework/src/Resources/views/Admin/Content/Product/createVariant.html.twig
=> [framework] Unification of product variant form

docs/model/elasticsearch.md
|Description, reason for the PR| The link probably led to an older version
=> [docs] fixed link for checking exported product in elasticsearch

packages/framework/src/Controller/Admin/ArticleController.php, packages/framework/src/Controller/Admin/CategoryController.php, packages/framework/src/Controller/Admin/CustomerController.php, packages/framework/src/Controller/Admin/ProductController.php, packages/framework/src/Controller/Admin/PromoCodeController.php, packages/framework/src/Controller/Admin/ScriptController.php, packages/framework/src/Controller/Admin/SliderController.php, packages/framework/src/Controller/Admin/TransportController.php
|Description, reason for the PR| shorter, unified. Developers very offen copy from ProductController and edit action contains unnecessary things.
=> [framework] unification of using form data if it is object

packages/framework/src/Model/Order/OrderFacade.php
=> [framework] edit transport and payment names in order items after order is changed

project-base/docker/php-fpm/Dockerfile
|Description, reason for the PR| the comment does not make sense after https://github.com/shopsys/project-base/commit/32755202185ed04fcf0e50b1d96d2af0fae8d778
=> [project-base] Dockerfile: remove useless comment

project-base/src/Controller/Front/OrderController.php, upgrade/UPGRADE-v9.0.1-dev.md
=> [project-base] Order can now be completed when successful flash message exists

utils/releaser/src/ReleaseWorker/ReleaseCandidate/ReleaseNewNodeModulePackageVersion.php
|Description, reason for the PR| added new release worker with release new node module package
=> [shopsys] added new release worker with release new node module package

packages/framework/src/Model/Order/Order.php
=> [framework] fixed throwing OrderItemNotFoundException

project-base/templates/Front/Content/Product/detail.html.twig, upgrade/UPGRADE-v9.0.1-dev.md
|Description, reason for the PR| Variant availability is not shown on product detail
=> [shopsys] add variant availabilities to product detail

project-base/src/DataFixtures/Demo/ProductDataFixture.php, upgrade/UPGRADE-v9.0.1-dev.md
|Description, reason for the PR| speed-up product demo data loading approximately to one quarter of the original time , little optimize caching product entities for building product variants - now cache only necessary products instead of all.
=> [project-base] optimization of ProductDataFixture.php

project-base/templates/bundles/FMElfinderBundle/Elfinder/ckeditor.html.twig, upgrade/UPGRADE-v9.0.1-dev.md
|Description, reason for the PR| Currently uploaded files in wysiwyg editor were passing URL, that is secured by administrator login. This has been fixed by this PR.
|Fixes issues| closes #1921 
=> [project-base] fixed wrong url of freshly uploaded files in wysiwyg

packages/framework/src/Component/Grid/Grid.php, packages/framework/src/Model/Product/ProductDataFactory.php
|Description, reason for the PR| Atfer monorepo split there was a standards error in shopsys/framework package
=> [framework] fixed framework standards

project-base/config/routes/shopsys_front.yaml, upgrade/UPGRADE-v9.0.2-dev.md
|Description, reason for the PR| This route should have been removed in #1522, but was forgotten.
=> [project-base] removed unused route /contactForm/

project-base/src/Controller/Front/CustomerController.php, project-base/src/Controller/Front/NewsletterController.php, project-base/src/DataFixtures/Performance/OrderDataFixture.php, upgrade/UPGRADE-v9.0.2-dev.md
|Description, reason for the PR| it is more readable, easier to maitain
=> [project-base] removed unnecessary else conditions

project-base/src/DataFixtures/Demo/ProductDataFixture.php, upgrade/UPGRADE-v9.0.2-dev.md
=> [project-base] call static method as static

build.xml, composer.json, packages/framework/build.xml, phpstan.neon, project-base/composer.json, project-base/phpstan.neon, project-base/tests/FrontendApiBundle/Functional/Product/ProductTest.php, project-base/tests/FrontendApiBundle/Functional/Product/ProductVariantTest.php, symfony.lock, upgrade/UPGRADE-v9.1.0-dev.md
|Description, reason for the PR| #1059 
|Fixes issues| closes #1059 
=> [symfony] added phpstan-symfony extension

docs/introduction/cron.md
|Description, reason for the PR| Documented behavior of long-running cron modules.
|Fixes issues| closes #1873 
=> [shopsys] added cron limitation documentation

packages/framework/src/Controller/Admin/ProductPickerController.php, packages/framework/src/Form/ProductType.php, packages/framework/src/Form/ProductsType.php
|Description, reason for the PR| Fixes linked issue
|Fixes issues| closes #1187 
=> [framework] fixed clearing form options in product picker

project-base/assets/js/frontend/utils/Window.js, project-base/assets/js/frontend/utils/showFormErrorsWindow.js, upgrade/UPGRADE-v9.0.2-dev.md
|Description, reason for the PR| see #1341 
|Fixes issues| closes #1341  
=> [project-base] fixed displaying errors in popup window

docs/introduction/cron.md
|Description, reason for the PR| This is reworked #1973 to be valid for version 7.3
=> [shopsys] fixed cron limitation documentation for version 7.3

packages/framework/src/Component/Doctrine/Exception/DuplicatedAliasException.php, packages/framework/src/Component/Doctrine/QueryBuilderExtender.php, packages/framework/tests/Unit/Component/Doctrine/QueryBuilderExtenderTest.php
|Description, reason for the PR| see #1417
|Fixes issues| closes #1417 
=> [framework] fixed joining the same table with different alias

packages/framework/assets/styles/admin/components/in/domain.less
|Description, reason for the PR| Fixes administration with more domains. Now there are correctly displayed on more lines if needed.
|Fixes issues| closes #1882  
=> [framework] design - admin - domain switcher for more domains

docs/introduction/how-to-set-up-domains-and-locales.md, mkdocs.yml
|Description, reason for the PR| see #983 
|Fixes issues| closes #983  
=> [docs] updated doc for configuring new domain

packages/framework/src/Migrations/Version20200819165818.php, packages/framework/src/Model/Article/Article.php, packages/framework/src/Model/Article/ArticleData.php, packages/framework/src/Model/Article/ArticleFacade.php, packages/framework/src/Model/Article/ArticleRepository.php, packages/frontend-api/apiary.apib, packages/frontend-api/src/Model/Resolver/Article/ArticleResolver.php, packages/frontend-api/src/Model/Resolver/Article/ArticlesResolver.php, packages/frontend-api/src/Resources/config/graphql-types/ArticleDecorator.types.yaml, packages/frontend-api/src/Resources/config/graphql-types/Pagination/ArticleDecoratorConnection.types.yaml, packages/frontend-api/src/Resources/config/graphql-types/QueryDecorator.types.yaml, project-base/config/graphql/types/Article.types.yaml, project-base/config/graphql/types/Pagination/ArticleConnection.types.yaml, project-base/src/DataFixtures/Demo/ArticleDataFixture.php, project-base/tests/FrontendApiBundle/Functional/Article/GetArticleTest.php, project-base/tests/FrontendApiBundle/Functional/Article/GetArticlesTest.php, project-base/translations/dataFixtures.cs.po, project-base/translations/dataFixtures.en.po
|Description, reason for the PR| Adds resolver for getting paginated list of articles with posibility to filter them by pllacement. Also this PR adds resolver for getting single article by uuid.
=> [frontend-api] added articles resolver

packages/framework/src/Form/AbstractFileUploadType.php
|Description, reason for the PR| When there are multiple instances of `AbstractFileUploadType` in a given form (both `FileUploadType` and `ImageUploadType`), it might happen that the constraints from the first one are used for the second type in `AbstractFileUploadType::validateUploadedFiles` method. I am not sure why this even happens, however, the problem is solved by removing the class property and using a local variable instead.
=> [framework] AbstractFileUploadType: remove fileConstraints class property

project-base/tests/FrontendApiBundle/Functional/Article/GetArticlesTest.php
|Description, reason for the PR| There is a bug in asertion.
=> [frontend-api] fixed checking for key existence in articles test

packages/framework/src/Component/Error/ErrorPagesFacade.php
=> [framework] remove space in error page filename

packages/frontend-api/apiary.apib, packages/frontend-api/src/Model/Resolver/Article/ArticleResolver.php, packages/frontend-api/src/Resources/config/graphql-types/QueryDecorator.types.yaml, project-base/tests/FrontendApiBundle/Functional/Article/GetArticleTest.php
|Description, reason for the PR| In SSFW there are some special articles displayed in different places than common articles (e.g. cookies). This PR adds new methods for retrieving these articles.
=> [frontend-api] Added special article resolvers

packages/framework/src/Model/Cart/Item/CartItem.php, project-base/tests/App/Acceptance/acceptance/OrderCest.php, upgrade/UPGRADE-v9.0.2-dev.md
|Description, reason for the PR| There is an error after merging #2010
After registering a new customer the error was thrown when tried to send order:
```
[2020-08-31 08:17:19] request.CRITICAL: Uncaught PHP Exception Doctrine\ORM\ORMInvalidArgumentException: "A new entity was found through the relationship 'Shopsys\FrameworkBundle\Model\Cart\Item\CartItem#cart' that was not configured to cascade persist operations for entity: Shopsys\FrameworkBundle\Model\Cart\Cart@000000003dbe347a000000001429a666. …
```
=> [shopsys] fixed sending order as logged customer

UPGRADE.md
|Description, reason for the PR| the link was broken :slightly_smiling_face: 
Btw, should not this be covered automatically by Releaser? :thinking:
=> UPGRADE.md: fix link to UPGRADE-v9.0.2.md

CODE_OF_CONDUCT.md
|Description, reason for the PR| Adding code of conduct to our repository
=> [shopsys] added CODE_OF_CONDUCT.md

packages/framework/src/Migrations/Version20200923075659.php, packages/framework/src/Model/Product/Brand/Brand.php, packages/framework/src/Model/Product/Brand/BrandData.php, packages/framework/src/Model/Product/Brand/BrandFacade.php, packages/framework/src/Model/Product/Brand/BrandRepository.php, packages/frontend-api/apiary.apib, packages/frontend-api/src/Model/Product/ProductFacade.php, packages/frontend-api/src/Model/Resolver/Brand/BrandResolver.php, packages/frontend-api/src/Model/Resolver/Brand/BrandResolverMap.php, packages/frontend-api/src/Model/Resolver/Brand/BrandsResolver.php, packages/frontend-api/src/Model/Resolver/Image/ImagesResolver.php, packages/frontend-api/src/Model/Resolver/Products/ProductResolverMap.php, packages/frontend-api/src/Model/Resolver/Products/ProductsResolver.php, packages/frontend-api/src/Resources/config/graphql-types/BrandDecorator.types.yaml, packages/frontend-api/src/Resources/config/graphql-types/ProductDecorator.types.yaml, packages/frontend-api/src/Resources/config/graphql-types/QueryDecorator.types.yaml, project-base/config/graphql/types/Brand.types.yaml, project-base/easy-coding-standard.yml, project-base/src/DataFixtures/Demo/BrandDataFixture.php, project-base/tests/FrontendApiBundle/Functional/Brand/BrandTest.php, project-base/tests/FrontendApiBundle/Functional/Brand/BrandsTest.php, project-base/tests/FrontendApiBundle/Functional/Product/ProductTest.php, project-base/tests/FrontendApiBundle/Functional/Product/ProductsTest.php, upgrade/UPGRADE-v9.1.0-dev.md
|Description, reason for the PR| We want to add everything to frontend API that could be displayed on frontend. This PR adds brands.
=> [shopsys] add brands to frontend API

UPGRADE.md
|Description, reason for the PR| Added missing link to 9.0.3 upgrade notes in general upgrade file
=> [shopsys] updated upgrade.md with v9.0.3 release

packages/framework/src/Migrations/Version20200930074334.php, packages/framework/src/Model/Product/Parameter/Parameter.php, packages/framework/src/Model/Product/Parameter/ParameterData.php, packages/framework/src/Model/Product/Parameter/ParameterDataFactory.php, packages/framework/src/Model/Product/Parameter/ParameterValue.php, packages/framework/src/Model/Product/Parameter/ParameterValueData.php, packages/framework/src/Model/Product/Parameter/ParameterValueDataFactory.php, packages/frontend-api/apiary.apib, packages/frontend-api/easy-coding-standard.yml, packages/frontend-api/src/Model/Parameter/ParameterWithValues.php, packages/frontend-api/src/Model/Parameter/ParameterWithValuesFactory.php, packages/frontend-api/src/Model/Product/ProductAccessoryFacade.php, packages/frontend-api/src/Model/Resolver/Products/ProductResolverMap.php, packages/frontend-api/src/Resources/config/graphql-types/ParameterDecorator.types.yaml, packages/frontend-api/src/Resources/config/graphql-types/ParameterValueDecorator.types.yaml, packages/frontend-api/src/Resources/config/graphql-types/ProductDecorator.types.yaml, project-base/config/graphql/types/Parameter.types.yaml, project-base/config/graphql/types/ParameterValue.types.yaml, project-base/easy-coding-standard.yml, project-base/tests/FrontendApiBundle/Functional/Product/ProductTest.php, project-base/tests/FrontendApiBundle/Functional/Product/ProductsTest.php, upgrade/UPGRADE-v9.1.0-dev.md
|Description, reason for the PR| Some data of Product has been missing in frontend API, these has been added by this PR.
=> [shopsys] added missing data to Product frontend API type

packages/framework/src/Model/Product/Elasticsearch/ProductExportRepository.php, packages/framework/src/Model/Product/Search/ProductElasticsearchConverter.php, packages/framework/tests/Unit/Model/Product/Search/ProductElasticsearchConverterTest.php, project-base/src/Resources/definition/product/1.json, project-base/src/Resources/definition/product/2.json, project-base/tests/App/Functional/Model/Product/Elasticsearch/ProductExportRepositoryTest.php, upgrade/UPGRADE-v9.1.0-dev.md, upgrade/upgrading-monorepo.md
|Description, reason for the PR| Adds Product SEO informations into elasticsearch
=> [shopsys] added product seo informations into elasticsearch

packages/frontend-api/apiary.apib, packages/frontend-api/src/Model/Resolver/Category/CategoryResolverMap.php, packages/frontend-api/src/Model/Resolver/Products/ProductResolverMap.php, packages/frontend-api/src/Resources/config/graphql-types/CategoryDecorator.types.yaml, packages/frontend-api/src/Resources/config/graphql-types/ProductDecorator.types.yaml, project-base/easy-coding-standard.yml, project-base/src/DataFixtures/Demo/CategoryDataFixture.php, project-base/src/DataFixtures/Demo/ProductDataFixture.php, project-base/tests/FrontendApiBundle/Functional/Category/CategoryTest.php, project-base/tests/FrontendApiBundle/Functional/Product/ProductTest.php, project-base/translations/dataFixtures.cs.po, project-base/translations/dataFixtures.en.po, upgrade/UPGRADE-v9.1.0-dev.md
|Description, reason for the PR| SEO informations for products and categories were adde to frontend API.
=> [shopsys] Added seo information to FEAPI

packages/framework/src/Resources/translations/messages.cs.po, packages/framework/src/Resources/translations/messages.en.po, packages/frontend-api/apiary.apib, packages/frontend-api/src/Model/Resolver/Products/PromotedProductsResolver.php, packages/frontend-api/src/Resources/config/graphql-types/QueryDecorator.types.yaml, project-base/easy-coding-standard.yml, project-base/tests/FrontendApiBundle/Functional/Product/PromotedProductsTest.php, upgrade/UPGRADE-v9.1.0-dev.md
|Description, reason for the PR| With frontend API is now possible to get promoted products
=> [frontend-api] added promoted products

docs/frontend-api/introduction-to-frontend-api.md
|Description, reason for the PR| Adding documentation about the possibility to request frontend API from another domain (handling CORS)
|Fixes issues| closes #2030  
=> [shopsys] added documentation about CORS

docs/administration/grid-rendering-customization.md, packages/framework/src/Model/Customer/User/CustomerUserRepository.php, packages/framework/src/Resources/views/Admin/Grid/Grid.html.twig
|Description, reason for the PR| This PR fixes rendering currency symbol in administration grid.
|Fixes issues| fixes #1539, fixes #2021  
=> [framework] fixed rendering currency symbol in admin grid

project-base/easy-coding-standard.yml, project-base/tests/App/Acceptance/acceptance/CartCest.php, project-base/tests/App/Acceptance/acceptance/CustomerLoginCest.php, project-base/tests/App/Acceptance/acceptance/CustomerRegistrationCest.php, project-base/tests/App/Acceptance/acceptance/LoginAsCustomerCest.php, project-base/tests/App/Acceptance/acceptance/OrderCest.php, project-base/tests/App/Acceptance/acceptance/PageObject/Front/CartPage.php, project-base/tests/App/Acceptance/acceptance/PageObject/Front/LayoutPage.php, project-base/tests/App/Acceptance/acceptance/PageObject/Front/LoginPage.php, project-base/tests/App/Acceptance/acceptance/PageObject/Front/OrderPage.php, project-base/tests/App/Acceptance/acceptance/PageObject/Front/ProductDetailPage.php, project-base/tests/App/Acceptance/acceptance/PageObject/Front/ProductFilterPage.php, project-base/tests/App/Acceptance/acceptance/PageObject/Front/ProductListPage.php, project-base/tests/App/Acceptance/acceptance/PageObject/Front/RegistrationPage.php, project-base/tests/App/Acceptance/acceptance/PaymentImageUploadCest.php, project-base/tests/App/Acceptance/acceptance/ProductImageUploadCest.php, project-base/tests/App/Acceptance/acceptance/TransportImageUploadCest.php, project-base/tests/App/Test/Codeception/Module/StrictWebDriver.php, upgrade/UPGRADE-v9.1.0-dev.md
|Description, reason for the PR| It was difficult to maintain acceptance tests functioning. Some small changes caused tests to fail. This PR introduces some enhancements that should help to maintain acceptance tests in the future.
=> [project-base] Improved acceptance tests

packages/monorepo-tools/README.md
|Description, reason for the PR| Monorepo-tools is awesome tool, but it is not our core business. There were some PRs and issues that we had no time to provide feedback and support, so we decided to let community know, that they are welcome to use it, but to not expect any support or new features.
=> [monorepo-tools] added message to monorepo-tools readme about not providing support for that package

upgrade/UPGRADE-v9.1.0-dev.md
|Description, reason for the PR| change upgrade notes to follow the order of implemented tasks
=> update upgrade notes to follow the order of implemented tasks

docs/frontend-api/pagination.md, packages/frontend-api/apiary.apib, packages/frontend-api/src/Component/Arguments/Exception/BuilderArgumentException.php, packages/frontend-api/src/Component/Arguments/Exception/MandatoryArgumentMissingException.php, packages/frontend-api/src/Component/Arguments/PaginatorArgumentsBuilder.php, packages/frontend-api/src/Model/Resolver/Products/ProductsResolver.php, packages/frontend-api/src/Resources/config/graphql-types/BrandDecorator.types.yaml, packages/frontend-api/src/Resources/config/graphql-types/CategoryDecorator.types.yaml, packages/frontend-api/src/Resources/config/graphql-types/EnumType/ProductOrderingModeEnumDecorator.types.yaml, packages/frontend-api/src/Resources/config/graphql-types/QueryDecorator.types.yaml, project-base/config/graphql/types/EnumType/ProductOrderingModeEnum.types.yaml, project-base/config/packages/shopsys_frontend_api.yaml, project-base/tests/FrontendApiBundle/Functional/Product/PaginatedProductsTest.php, upgrade/UPGRADE-v9.1.0-dev.md
|Description, reason for the PR| Added support for ordering paginated products
=> FE API ordering products

project-base/src/DataFixtures/Demo/CategoryDataFixture.php, upgrade/UPGRADE-v9.1.0-dev.md
=> [project-base] fixed SEO informations in categories demo data

packages/framework/src/Model/Newsletter/NewsletterFacade.php, packages/frontend-api/apiary.apib, packages/frontend-api/src/Model/Mutation/Newsletter/NewsletterMutation.php, packages/frontend-api/src/Resources/config/graphql-types/Mutation.types.yaml, packages/frontend-api/src/Resources/config/graphql-types/NewsletterSubscriptionDataInputDecorator.types.yaml, project-base/config/graphql/types/NewsletterSubscriptionDataInput.types.yaml, project-base/tests/FrontendApiBundle/Functional/Newsletter/NewsletterTest.php, upgrade/UPGRADE-v9.1.0-dev.md
|Description, reason for the PR| add support for subscribing for e-mail newsletter to FE API
=> add support for subscribing for e-mail newsletter to FE API

packages/framework/src/Model/Product/ProductElasticsearchProvider.php, packages/framework/src/Model/Product/Search/FilterQuery.php, packages/framework/src/Model/Product/Search/FilterQueryFactory.php, packages/read-model/src/Product/Detail/ProductDetailViewElasticsearchFactory.php, packages/read-model/src/Product/Listed/ListedProductViewElasticFacade.php
|Description, reason for the PR| In elasticsearch implementation there is accessories provided from PostgreSQL. This PR is changing it.
|Fixes issues| fixes #2102  
=> [shopsys] accessories is provided by elasticsearch for ListedProductView

docs/introduction/automated-testing.md, docs/introduction/console-commands-for-application-management-phing-targets.md, docs/introduction/running-acceptance-tests.md, packages/framework/build.xml, packages/framework/src/Component/Environment/EnvironmentFileSetting.php, packages/framework/src/Component/Environment/EnvironmentType.php, packages/framework/src/Model/Cookies/CookiesFacade.php, packages/framework/src/Resources/config/services_test.yaml, project-base/.env.acc, project-base/app/Environment.php, project-base/app/getEnvironment.php, project-base/build/codeception.yml, project-base/config/routes/acc/shopsys_test.yaml, project-base/config/services_acc.yaml, project-base/src/Controller/Front/ErrorController.php, project-base/tests/App/Functional/Controller/ProductRenameRedirectPreviousUrlTest.php, project-base/tests/App/Smoke/NewProductTest.php, project-base/tests/App/Test/Codeception/Helper/SymfonyHelper.php, project-base/tests/App/Test/Codeception/Module/StrictWebDriver.php, project-base/tests/FrontendApiBundle/Functional/Advert/GetAdvertsTest.php, project-base/tests/FrontendApiBundle/Test/GraphQlTestCase.php, project-base/tests/FrontendApiBundle/Test/GraphQlWithLoginTestCase.php, upgrade/UPGRADE-v9.1.0-dev.md
|Description, reason for the PR| Acceptance tests were running in test environment, which was not the best solution. Tests have mocked sessions and some other configuration changes that might lead to same false positive errors. Also they were testing different than production settings. This difference has now been mitigated as much as possible and acceptance tests are closest to production environment as possible.
=> [shopsys] new application environment for running acceptance tests

upgrade/UPGRADE-v9.1.0-dev.md
|Description, reason for the PR| replaced links in ugrade notes for next minor release
=> [shopsys] replaced links in 9.1.0 upgrade

docs/model/introduction-to-model-architecture.md
|Description, reason for the PR| In #1123 and #1543 were introduced changes and those changes were not propagated into introduction-to-model-architecture.md article
=> [shopsys] updated docs with changes from #1123 and #1543

packages/framework/src/Component/String/TransformString.php, packages/frontend-api/apiary/article/methods/article-detail.md, packages/frontend-api/apiary/brand/methods/brand-detail.md, packages/frontend-api/apiary/category/methods/category-detail.md, packages/frontend-api/apiary/product/methods/product-detail.md, packages/frontend-api/src/Model/Article/ArticleFacade.php, packages/frontend-api/src/Model/Article/ArticleRepository.php, packages/frontend-api/src/Model/FriendlyUrl/FriendlyUrlFacade.php, packages/frontend-api/src/Model/FriendlyUrl/FriendlyUrlRepository.php, packages/frontend-api/src/Model/Resolver/Article/ArticleResolver.php, packages/frontend-api/src/Model/Resolver/Brand/BrandResolver.php, packages/frontend-api/src/Model/Resolver/Category/CategoryResolver.php, packages/frontend-api/src/Model/Resolver/Products/ProductByUuidResolver.php, packages/frontend-api/src/Model/Resolver/Products/ProductDetailResolver.php, packages/frontend-api/src/Model/Resolver/Products/ProductResolver.php, packages/frontend-api/src/Resources/config/graphql-types/QueryDecorator.types.yaml, project-base/tests/FrontendApiBundle/Functional/FriendlyUrl/FriendlyUrlTest.php, upgrade/UPGRADE-v9.1.0-dev.md
|Description, reason for the PR| You can find entity by url slug as well as by uuid 
=> [shopsys] Added support to find entity by slug into FEAPI

packages/frontend-api/src/Model/Parameter/ParameterWithValues.php, packages/frontend-api/src/Model/Parameter/ParameterWithValuesFactory.php
|Description, reason for the PR| There were used wrong annotations, this is fixed now.
=> [frontend-api] fixed wrong annotations of ParameterWithValues

upgrade/UPGRADE-v9.1.0-dev.md
=> [shopsys] added upgrade notes for adding articles support in FEAPI

docs/administration/grid-rendering-customization.md
- added a tip on how to override a column title
|Description, reason for the PR| just a small tip that might be useful, I do not think many people know about this option :slightly_smiling_face: 
=> [docs] grid-rendering-customization.md tweak

packages/framework/src/Model/Product/ProductRepository.php, packages/frontend-api/src/Model/Product/ProductFacade.php, upgrade/UPGRADE-v9.1.0-dev.md
|Description, reason for the PR| We forgot to add upgrade notes and deprecation notices in #2156, this PR fixes that.
=> [project-base] added missing upgrade notes and deprecation notices for product filtering in frontend API

docs/frontend-api/pagination.md, packages/framework/src/Model/Category/CategoryRepository.php, packages/frontend-api/apiary/category/methods/categories-search.md, packages/frontend-api/apiary/product/methods/list-of-products.md, packages/frontend-api/src/Component/Arguments/PaginatorArgumentsBuilder.php, packages/frontend-api/src/Model/Category/CategoryFacade.php, packages/frontend-api/src/Model/Category/CategoryRepository.php, packages/frontend-api/src/Model/Product/ProductFacade.php, packages/frontend-api/src/Model/Resolver/Category/CategoriesSearchResolver.php, packages/frontend-api/src/Model/Resolver/Products/ProductsResolver.php, packages/frontend-api/src/Resources/config/graphql-types/Pagination/CategoryDecoratorConnection.types.yaml, packages/frontend-api/src/Resources/config/graphql-types/QueryDecorator.types.yaml, project-base/config/graphql/types/Pagination/CategoryConnection.types.yaml, project-base/tests/FrontendApiBundle/Functional/Category/CategoriesSearchTest.php, project-base/tests/FrontendApiBundle/Functional/Product/ProductsFilteringTest.php, project-base/tests/FrontendApiBundle/Functional/Product/ProductsGraphQlTestCase.php, project-base/tests/FrontendApiBundle/Functional/Product/ProductsSearch.php, project-base/tests/FrontendApiBundle/Functional/Product/ProductsTest.php, upgrade/UPGRADE-v9.1.0-dev.md
|Description, reason for the PR| Search is one of important functions on ecommerce platform. This functionality has been missing and this PR adds it.
=> [shopsys] added search for products and categories in frontend API

.travis.yml, project-base/.ci/docker_login.sh, project-base/.travis.yml
|Description, reason for the PR| Docker introduced limits for accessing images on Docker Hub - https://docs.docker.com/docker-hub/download-rate-limit/.
=> [shopsys] add login to our docker hub account for travis in order to prevent docker pull limit errors

CHANGELOG.md, UPGRADE.md, upgrade/UPGRADE-v9.0.3.md, upgrade/UPGRADE-v9.0.4-dev.md, upgrade/UPGRADE-v9.0.4.md
|Description, reason for the PR| Merge 9.0.4 branch into master
=> [shopsys] update master branch by changes in 9.0 branch

.github/stale.yml
|Description, reason for the PR| Issues with set milestone are decided to be solved in future, so it does not make any sense to mark those as stale.
=> stalebot now ignores issues with set milestone

packages/framework/src/Component/String/TransformString.php, project-base/src/Controller/Front/ProductController.php, project-base/src/Controller/Front/SearchController.php, upgrade/UPGRADE-v9.1.1-dev.md
|Description, reason for the PR| #2063 
|Fixes issues| fixes #2063 
_This PR needs to be rebased on 9.0 branch and have added upgrade notes after release of v9.1.0_
=> [project-base] validate search text is printable

packages/framework/src/Model/Cart/Cart.php
|Description, reason for the PR| see #1991
|Fixes issues| fixes #1991  
=> [framework] fixed cart when one of cart item is not sellable

project-base/src/Controller/Front/ProductController.php, project-base/src/Controller/Front/SearchController.php, project-base/templates/Front/Content/Search/searchBox.html.twig, upgrade/UPGRADE-v9.1.1-dev.md
|Description, reason for the PR| See #2073
|Fixes issues| fixes #2073  
=> [project-base] search text is now trimmed

packages/framework/src/Model/Customer/User/CustomerUserFacade.php
|Description, reason for the PR| Fixes linked issue, see it for more details.
|Fixes issues| fixes #1724 
=> [framework] CustomerUserFacade.php: assign customer to delivery address when changed only

.github/build-elasticsearch-image.sh, .github/build-php-fpm-image.sh, .github/check-image-exists.sh, .github/workflows/docker-build.yaml, .github/workflows/rebuild-docker-images.yaml, README.md, docker/conf/docker-compose.github-actions.yml.dist, project-base/config/services_acc.yaml, project-base/docker/php-fpm/Dockerfile, yaml-standards.yaml
|Description, reason for the PR| @s3tezsky started in #2188 using Github Actions and I got excited about it and implemented some other functionality in order to improve build times
|Fixes issues| closes #2188  
=> [monorepo] github actions with persisted docker images

packages/framework/src/Model/Pricing/Exception/NoProductPriceForPricingGroupException.php, packages/framework/src/Model/Product/Pricing/PriceFactory.php, packages/read-model/src/Product/Listed/ListedProductViewElasticFacade.php, packages/read-model/src/Product/Listed/ListedProductViewFactory.php
|Description, reason for the PR| See linked issue
|Fixes issues| fixes #2098  
=> [shopsys] prevent to pass null to not-nullable argument to ListedProductViewFactory::createFromArray()

.github/get-build-exit-code.sh, .github/workflows/docker-build.yaml, yaml-standards.yaml
|Description, reason for the PR| Previous version of Github actions could not be run from forked pull requests, this PR adds that
=> [monorepo] updated Github actions to build right fork pull requests

packages/framework/src/Model/MultidomainEntityClassProvider.php
|Description, reason for the PR| Adding new domains does not create country domain data
=> [framework] set CountryDomain as multi domain entity

packages/coding-standards/.travis.yml, packages/coding-standards/composer.json
|Description, reason for the PR| added support for symfony5 for coding standards package
=> [coding-standards] added support for symfony5

packages/product-feed-google/tests/Unit/GoogleFeedItemTest.php
|Description, reason for the PR| @var annotation does not make sense in method description
=> [product-feed-google] removed unnecessary annotation

packages/framework/assets/js/common/utils/number.js, project-base/assets/styles/frontend/common/components/box/breadcrumb.less, project-base/assets/styles/frontend/common/components/box/filter.less, project-base/assets/styles/frontend/common/components/box/gallery.less, project-base/assets/styles/frontend/common/components/box/promo-code.less, project-base/assets/styles/frontend/common/components/form/choice.less, project-base/assets/styles/frontend/common/components/form/error.less, project-base/assets/styles/frontend/common/components/in/icon.less, project-base/assets/styles/frontend/common/components/in/tab.less, project-base/assets/styles/frontend/common/components/list/addresses.less, project-base/assets/styles/frontend/common/components/list/menu.less, project-base/assets/styles/frontend/common/components/table/cart.less, project-base/assets/styles/frontend/common/components/window/popup.less, project-base/assets/styles/frontend/common/core/mixin/base.less, project-base/assets/styles/frontend/common/layout/footer.less, project-base/assets/styles/frontend/common/layout/header.less, project-base/assets/styles/frontend/common/layout/header/cart-detail.less, project-base/assets/styles/frontend/common/layout/header/cart.less, project-base/assets/styles/frontend/common/layout/header/contact-us.less, project-base/assets/styles/frontend/common/layout/header/menu-iconic.less, project-base/assets/styles/frontend/common/layout/header/search.less, project-base/assets/styles/frontend/common/svg-custom.less, project-base/templates/Front/Content/Product/filterFormMacro.html.twig, project-base/tests/App/Acceptance/acceptance/PageObject/Front/ProductFilterPage.php, upgrade/UPGRADE-v9.1.1-dev.md
|Description, reason for the PR| Currency code is after inputs, the color of the placeholder is gray and the filter has been a little bit refactored (animation of hiding/showing content is smoother, arrows have animated too and html structure of the filter is clearer)
|Fixes issues| closes #1571
=> [project-base] fix price-slider and small refactoring of filter

docs/frontend/icon-function.md, docs/frontend/index.md, docs/frontend/navigation.yml, packages/framework/src/Resources/views/Common/Inline/Icon/icon.html.twig, packages/framework/src/Twig/IconExtension.php, project-base/templates/Front/Content/Cart/index.html.twig, project-base/templates/Front/Content/Category/panel.html.twig, project-base/templates/Front/Content/ContactForm/index.html.twig, project-base/templates/Front/Content/Customer/edit.html.twig, project-base/templates/Front/Content/Customer/orders.html.twig, project-base/templates/Front/Content/Login/loginForm.html.twig, project-base/templates/Front/Content/Login/windowForm.html.twig, project-base/templates/Front/Content/Order/PromoCode/index.html.twig, project-base/templates/Front/Content/Order/step3.html.twig, project-base/templates/Front/Content/Product/detail.html.twig, project-base/templates/Front/Content/Product/filterFormMacro.html.twig, project-base/templates/Front/Content/Product/filterFormTheme.html.twig, project-base/templates/Front/Content/Product/list.html.twig, project-base/templates/Front/Content/Product/search.html.twig, project-base/templates/Front/Content/Registration/register.html.twig, project-base/templates/Front/Content/Search/autocomplete.html.twig, project-base/templates/Front/Content/Search/searchBox.html.twig, project-base/templates/Front/Form/theme.html.twig, project-base/templates/Front/Inline/Breadcrumb/breadcrumb.html.twig, project-base/templates/Front/Inline/Cart/cartBox.html.twig, project-base/templates/Front/Inline/Cart/cartBoxItemMacro.html.twig, project-base/templates/Front/Inline/Newsletter/subscription.html.twig, project-base/templates/Front/Layout/header.html.twig, project-base/templates/Styleguide/styleguide.html.twig, upgrade/UPGRADE-v9.2.0-dev.md
|Description, reason for the PR| Icon extension adds ability to change icon representation in one place. It brings possibility to add new icon types or even combine them.
=> [shopsys] replaced <i> tag with twig icon function

docs/frontend-api/introduction-to-frontend-api.md
|Description, reason for the PR| list is now rendered correctly
=> [docs] improved formatting in FE API introduction

UPGRADE.md
|Description, reason for the PR| Added missing link in upgrade.md
=> [shopsys] added 9.1.1 upgrade notes link

packages/framework/src/Controller/Admin/CustomerController.php
|Description, reason for the PR| Admin should not be able to log as user on different domains that is supposed to be.
|Fixes issues| closes #2198 
=> [shopsys] prevent admin to log as customer user on a different domain than user is registered on

.travis.yml, project-base/.ci/docker_login.sh
|Description, reason for the PR| We want to fix some problems in version 7.3 and we need Travis to build project successfully.
=> [shopsys] fix travis for version 7.3

docs/frontend-api/introduction-to-frontend-api.md
|Description, reason for the PR| just a few typos
=> [docs] introduction-to-frontend-api.md: fix typos

packages/frontend-api/apiary.apib
|Description, reason for the PR| blueprint was not updated in #2150
=> [docs] updated apiary.apib to be up to date

docs/project/how-to-write-an-upgradable-application.md, docs/project/index.md, docs/project/navigation.yml
|Description, reason for the PR| Few useful tips how to write application ready for the future upgrades
=> [docs] added hints for upgradable application

packages/framework/src/Component/Image/ImageFacade.php, packages/framework/src/Form/Constraints/FileAbstractFilesystemValidator.php, packages/framework/src/Form/Constraints/ImageAbstractFilesystemValidator.php, packages/framework/src/Model/Mail/Mailer.php
|Description, reason for the PR| Getting file from main filesystem is not validated. In case the file is not present the applications may fail. 
=> [framework] handled FileNotFoundException on main filesystem

packages/framework/src/Model/Pricing/Currency/CurrencyFacade.php, packages/framework/src/Model/Pricing/Currency/CurrencyRepository.php, packages/framework/src/Model/Pricing/PriceConverter.php, packages/framework/src/Model/Pricing/PricingSetting.php, project-base/src/DataFixtures/Demo/CurrencyDataFixture.php, project-base/src/DataFixtures/Demo/PaymentDataFixture.php, project-base/src/DataFixtures/Demo/ProductDataFixture.php, project-base/src/DataFixtures/Demo/TransportDataFixture.php, project-base/tests/App/Functional/Model/Product/ProductOnCurrentDomainFacadeCountDataTest.php, project-base/tests/App/Functional/Model/Product/ProductOnCurrentDomainFacadeTest.php, project-base/tests/App/Functional/Model/Product/Search/FilterQueryTest.php, project-base/tests/App/Test/Codeception/Helper/NumberFormatHelper.php, project-base/tests/FrontendApiBundle/Test/GraphQlTestCase.php, upgrade/UPGRADE-v9.1.2-dev.md
|Description, reason for the PR| see https://github.com/shopsys/shopsys/issues/2059
|Fixes issues| closes #2059  
=> [framework] exchange rate recalculation after changing default currency

docs/frontend-api/introduction-to-frontend-api.md
|Description, reason for the PR| the port was missing in the link
=> [docs] introduction-to-frontend-api.md: fix graphiql links

docs/introduction/database-migrations.md
|Description, reason for the PR| fixed typo
=> [docs] typo in database-migrations.md

build.xml, composer.json, easy-coding-standard.yml, packages/backend-api/composer.json, packages/coding-standards/composer.json, packages/form-types-bundle/composer.json, packages/framework/composer.json, packages/framework/easy-coding-standard.yml, packages/framework/phpstan.neon, packages/framework/tests/Test/Codeception/ActorInterface.php, packages/frontend-api/composer.json, packages/google-cloud-bundle/composer.json, packages/http-smoke-testing/composer.json, packages/migrations/composer.json, packages/plugin-interface/composer.json, packages/product-feed-google/composer.json, packages/product-feed-heureka-delivery/composer.json, packages/product-feed-heureka/composer.json, packages/product-feed-zbozi/composer.json, packages/read-model/composer.json, phpstan.neon, project-base/composer.json, project-base/phpstan.neon, project-base/src/DataFixtures/Demo/CustomerUserDataFixture.php, project-base/symfony.lock, project-base/tests/App/Test/Codeception/AcceptanceTester.php, project-base/tests/App/Test/Codeception/Module/StrictWebDriver.php, symfony.lock, upgrade/UPGRADE-v9.1.3-dev.md
|Description, reason for the PR| there are few security problems reported by our security check + "allow-plugins" setting is required since composer 2.2.0
|Fixes issues| #2284 
=> composer updates

LICENSE, packages/backend-api/LICENSE, packages/coding-standards/LICENSE, packages/form-types-bundle/LICENSE, packages/framework/LICENSE, packages/frontend-api/LICENSE, packages/google-cloud-bundle/LICENSE, packages/http-smoke-testing/LICENSE, packages/migrations/LICENSE, packages/monorepo-tools/LICENSE, packages/plugin-interface/LICENSE, packages/product-feed-google/LICENSE, packages/product-feed-heureka-delivery/LICENSE, packages/product-feed-heureka/LICENSE, packages/product-feed-zbozi/LICENSE, packages/read-model/LICENSE, project-base/LICENSE
|Description, reason for the PR| New year, new number
=> [shopsys] updated year in license files

packages/framework/src/Component/ClassExtension/DocBlockParser.php
|Description, reason for the PR| Fixes usage of docblock parser
|Fixes issues| Fixes usage of docblock parser 
=> [framework] Fix DocBlock Parser

composer.json, packages/backend-api/composer.json, packages/framework/composer.json, symfony.lock
|Description, reason for the PR| Update `ramsey/uuid` library to newest version
=> [shopsys] Upgrade ramsey/uuid to ^4.3

.gitignore, composer.json, packages/framework/composer.json, packages/framework/src/Model/Sitemap/SitemapDumper.php, packages/framework/src/Model/Sitemap/SitemapDumperFactory.php, packages/framework/src/Model/Sitemap/SitemapListener.php, project-base/composer.json, upgrade/UPGRADE-v10.0.0-dev.md
|Description, reason for the PR| we want up-to-date dependencies and get rid of the deprecation errors from previous version
=> [framework] upgrade presta/sitemap-bundle to ^3.3

composer.json, project-base/composer.json
|Description, reason for the PR| We don't want to use dev- dependencies. New version of phing was released.
=> [shopsys] upgraded phing to latest version

project-base/src/DataFixtures/Demo/SliderItemDataFixture.php
|Description, reason for the PR| Updated links in Slider item data fixtures
=> [project-base] updated links in banner demo data

packages/framework/composer.json
- fixes error handler
|Description, reason for the PR| Fixes error handler
=> [framework] add tracy dependency to FW

project-base/translations/messages.en.po
|Description, reason for the PR| add missing Search [noun] english translation
=> [project-base] add Search [noun] english translation

docs/requirements.txt
|Description, reason for the PR| New version does not allow building the application.  See https://github.com/mkdocs/mkdocs/issues/2892
=> [docs] pin markdown version for docs generation

upgrade/UPGRADE-v11.0.0-dev.md
|Description, reason for the PR| #2483 deserves upgrade notes
=> [shopsys] added upgrade notes for #2483

.github/workflows/docker-build.yaml, .github/workflows/rebuild-docker-images.yaml
|Description, reason for the PR| the 10.0 branch was sad for being left behind (it was not build on github actions)
=> [shopsys] github actions tweaks for 10.0 branch

composer.json, packages/framework/composer.json, packages/framework/src/Model/Heureka/HeurekaFacade.php, project-base/composer.json, upgrade/UPGRADE-v10.0.5-dev.md
|Description, reason for the PR| update to latest version heureka/overeno-zakazniky package
=> [framework] update heureka/overeno-zakazniky to latest version 4.0.1

composer.json, packages/framework/composer.json
|Description, reason for the PR| upgrade elfinder cache system to prevent cache errors
=> [framework] upgrade elfinder cache system to prevent cache errors

docs/automated-testing/introduction-to-automated-testing.md, packages/framework/build.xml, packages/framework/src/Model/Customer/User/CurrentCustomerUser.php, packages/framework/tests/Unit/Model/Customer/CurrentCustomerUserTest.php, packages/framework/tests/Unit/Model/Customer/Mock/TokenMock.php
|Description, reason for the PR| We dont want to requesting current customer user multiple times from database
=> [framework] Cache current customer user

packages/framework/src/Form/Admin/Article/ArticleFormType.php, packages/framework/src/Model/Article/Article.php, packages/framework/src/Model/Article/ArticleData.php, packages/framework/src/Model/Article/ArticleDataFactory.php, project-base/src/Form/Admin/ArticleFormTypeExtension.php, project-base/src/Model/Article/Article.php, project-base/src/Model/Article/ArticleData.php, project-base/src/Model/Article/ArticleDataFactory.php, symfony.lock, upgrade/UPGRADE-v11.0.0-dev.md
|Description, reason for the PR| created at of article is editable
=> Fix editing created at of article

docker/conf/docker-compose-mac.yml.dist, docker/conf/docker-compose.yml.dist, docs/installation/installation-using-docker-application-setup.md, project-base/docker/conf/docker-compose-mac.yml.dist, project-base/docker/conf/docker-compose.yml.dist, project-base/kubernetes/deployments/redis-admin.yml, upgrade/UPGRADE-v11.0.0-dev.md
|Description, reason for the PR| old phpRedisAdmin has been replaced with new Redis Commander
|Fixes issues| closes #2532 
=> [framework] New Redis Commander

docs/introduction/console-commands-for-application-management-phing-targets.md, packages/framework/build.xml, upgrade/UPGRADE-v11.0.0-dev.md
|Description, reason for the PR| introduced new phing target `demo-data` that wipes and completely installs demo data including export to Elasticsearch
=> [framework] introduced new phing target demo-data that wipes and completely installs demo data including export to Elasticsearch

packages/framework/src/Model/ImageSitemap/ImageSitemapFacade.php
|Description, reason for the PR|  fix wrong annotation copied from commerce cloud
=> [framework] fix wrong annotation

packages/framework/src/Model/Product/Elasticsearch/ProductExportRepository.php, packages/framework/src/Model/Product/ProductRepository.php, packages/framework/src/Model/Product/Search/FilterQuery.php, project-base/src/Resources/definition/product/1.json, project-base/src/Resources/definition/product/2.json, project-base/tests/App/Functional/Model/Product/Elasticsearch/ProductExportRepositoryTest.php, project-base/tests/App/Functional/Model/Product/Search/FilterQueryTest.php, project-base/tests/FrontendApiBundle/Functional/Product/PaginatedProductsTest.php, project-base/tests/FrontendApiBundle/Functional/Product/ProductsFilteringTest.php, project-base/tests/FrontendApiBundle/Functional/Product/ProductsTest.php, upgrade/UPGRADE-v11.0.0-dev.md
|Description, reason for the PR| product ordering in all product lists has been changed, now are products ordered primary by availability dispatch time. In stock as first and out of stock as last.
=> [shopsys] Product sorting by availability

project-base/docker/elasticsearch/Dockerfile, upgrade/UPGRADE-v11.0.0-dev.md
|Description, reason for the PR| Update to newest Elasticsearch image
=> [shopsys] updated Elasticsearch image to newest version in order to support arm processors

packages/framework/src/Component/UploadedFile/UploadedFile.php
=> [framework] added missing getters to UploadedFile

docs/introduction/cron.md, packages/framework/assets/js/admin/components/Statistics.js, packages/framework/assets/js/admin/utils/constant.js, packages/framework/src/Command/CronCommand.php, packages/framework/src/Component/Cron/Config/CronConfig.php, packages/framework/src/Component/Cron/Config/CronModuleConfig.php, packages/framework/src/Component/Cron/CronFacade.php, packages/framework/src/Component/Cron/CronModuleExecutor.php, packages/framework/src/Component/Cron/CronModuleFacade.php, packages/framework/src/Component/Cron/CronModuleRepository.php, packages/framework/src/Controller/Admin/DefaultController.php, packages/framework/src/DependencyInjection/Compiler/RegisterCronModulesCompilerPass.php, packages/framework/src/Resources/views/Admin/Content/Default/cronDetail.html.twig, packages/framework/src/Resources/views/Admin/Content/Default/cronListGrid.html.twig, packages/framework/src/Resources/views/Admin/Content/Default/cronModuleRunsListGrid.html.twig, packages/framework/src/Twig/DateTimeFormatterExtension.php, packages/framework/tests/Unit/Component/Cron/CronFacadeTest.php, packages/framework/tests/Unit/Component/Cron/CronModuleExecutorTest.php, project-base/config/services/cron.yaml, upgrade/UPGRADE-v11.0.1-dev.md
|Description, reason for the PR| Developers are now able to change length and periodicity of cron instances.
=> [shopsys] added ability to change periodicity and length of cron runs

packages/framework/src/Model/Transport/Transport.php
|Description, reason for the PR| fix typo
=> [framework] Transport::getPrice() - fix error message

packages/framework/build.xml, packages/framework/src/Model/Transport/Transport.php, packages/framework/src/Resources/views/Debug/Elasticsearch/template.html.twig, project-base/translations/dataFixtures.cs.po, project-base/translations/dataFixtures.en.po, upgrade/UPGRADE-v11.0.1-dev.md
|Description, reason for the PR| improve readability of elasticsearch debug panel when using dark theme
=> [framework] improved elasticsearch debug panel readability in Symfony Profiler

packages/framework/src/Resources/config/services.yaml, upgrade/UPGRADE-v11.0.1-dev.md
|Description, reason for the PR| There were errors in upgrade notes and omitted required parameter
=> [framework] fixed upgrade notes and resolved possible BC-break

docker/conf/docker-compose-mac.yml.dist, docker/conf/docker-compose.github-actions.yml.dist, docker/conf/docker-compose.yml.dist, docs/automated-testing/running-acceptance-tests.md, open-source-license-acknowledgements-and-third-party-copyrights.md, packages/framework/build.xml, packages/framework/tests/Test/Codeception/AbstractCheckbox.php, packages/framework/tests/Test/Codeception/ActorInterface.php, phpstan.neon, project-base/docker/conf/docker-compose-mac.yml.dist, project-base/docker/conf/docker-compose.yml.dist, project-base/kubernetes/deployments/selenium-server.yml, project-base/tests/App/Acceptance/acceptance.suite.yml, project-base/tests/App/Acceptance/acceptance/PageObject/Admin/ProductAdvancedSearchPage.php, project-base/tests/App/Acceptance/acceptance/PageObject/Front/CartPage.php, project-base/tests/App/Acceptance/acceptance/PageObject/Front/OrderPage.php, project-base/tests/App/Acceptance/acceptance/PageObject/Front/RegistrationPage.php, project-base/tests/App/Test/Codeception/Module/StrictWebDriver.php, upgrade/UPGRADE-v11.0.1-dev.md
|Description, reason for the PR| Acceptance tests were not working on local machines.
=> [shopsys] updated acceptance tests because they were no longer working locally

composer.json, packages/framework/tests/Test/Codeception/ActorInterface.php, project-base/build/codeception.yml, project-base/phpstan.neon, project-base/tests/App/Acceptance/acceptance.suite.yml, project-base/tests/App/Test/Codeception/Module/Db.php, project-base/tests/App/Test/Codeception/Module/StrictWebDriver.php, symfony.lock
|Description, reason for the PR| We want to keep our dependencies as up to date as possible
=> [shopsys] updated codeception to version 5

packages/framework/src/Component/Image/ImageFacade.php, upgrade/UPGRADE-v12.0.0-dev.md
|Description, reason for the PR| Because I want... Yes it is not complex solution for all repository, but I do something in this class and I did it... Small step to better future...
=> [framework] add typehints and return types in ImageFacade

.github/cancel-review.sh, .github/workflows/cancel-review-after-branch-merge.yaml
|Description, reason for the PR| Tuning of canceling review after merge
=> fix canceling review after branch merge

.github/workflows/docker-build.yaml, .github/workflows/rebuild-docker-images.yaml
|Description, reason for the PR| Tuning GitHub Actions after moderate changes, that could not be tested before merging to master.
=> fixed actions for rebuilding images and building 

.github/workflows/rebuild-docker-images.yaml
=> rebuild-docker-images.yaml now use personal token to push images

.github/build-elasticsearch-image.sh, .github/build-php-fpm-image.sh, .github/build-storefront-ci-image.sh, .github/build-storefront-image.sh, .github/set-urls-for-review.sh, .github/workflows/docker-build.yaml, .github/workflows/rebuild-docker-images.yaml, Makefile, composer.json, docker/conf/docker-compose.github-actions.cypress.yml.dist, docker/conf/docker-compose.github-actions.review.yml.dist, docker/conf/docker-compose.github-actions.yml.dist, packages/coding-standards/src/Sniffs/ForceLateStaticBindingForProtectedConstantsSniff.php, packages/coding-standards/tests/Unit/Sniffs/ForceLateStaticBindingForProtectedConstantsSniff/fixed/SingleValue.php, packages/coding-standards/tests/Unit/Sniffs/ForceLateStaticBindingForProtectedConstantsSniff/wrong/SingleValue.php, project-base/app/src/Model/Blog/Article/BlogArticle.php, project-base/storefront/cypress/docker/Dockerfile, project-base/storefront/cypress/fixtures/demodata.js, project-base/storefront/cypress/integration/Functions/login.js, project-base/storefront/cypress/integration/Functions/orderThirdStep.js, project-base/storefront/cypress/integration/Tests/order/createOrderAsUnloggedUserWithRegisteredEmailAndTransportToHome.cy.js, project-base/storefront/cypress/integration/Tests/order/createOrderAsUnloggedUserWithTransportPersonallCollection.cy.js, project-base/storefront/cypress/integration/Tests/order/createOrderAsUnloggedUserWithTransportToHome.cy.js, project-base/storefront/docker/ci.Dockerfile
|Description, reason for the PR| We have currently added a new JS storefront and this PR update GitHub actions to correctly work with new changes
=> updated GitHub actions for new storefront

.github/build-elasticsearch-image.sh, .github/build-php-fpm-image.sh, .github/check-image-exists.sh, .github/workflows/docker-build.yaml, utils/releaser/src/Guzzle/ApiCaller.php
|Description, reason for the PR| We have recently updated the way we build images and we need to update all of our current supported versions builds in order to make everything work correctly.
=> fixed rebuilding of images on branch 11.0

docker/conf/docker-compose-mac.yml.dist, docker/conf/docker-compose.yml.dist, project-base/storefront/cypress/docker/Dockerfile, project-base/storefront/cypress/integration/Functions/orderThirdStep.js
|Description, reason for the PR| Cypress tests had few problems in local development, part of them could be easily fixed by newer Cypress and others by fixes in docker-compose files.
=> fix running Cypress tests locally + updated Cypress image to latest version

.github/workflows/docker-build.yaml, .github/workflows/rebuild-docker-images.yaml
|Description, reason for the PR| We do not need to rebuild Docker images for no longer supported versions.
=> images are now rebuilt only for currently supported versions

.github/cancel-old-reviews.sh, .github/workflows/cancel-old-reviews.yaml, .github/workflows/cancel-review-after-branch-merge.yaml, .github/workflows/docker-build.yaml, .github/workflows/manually-cancel-review.yaml
|Description, reason for the PR| We will be changing main branch name and we need GitHub actions to be able to be prepared for that. Protected branches instead of main branch name are used in docker-build.yaml because env variables cannot be used in job conditions.
=> introduced environment variable for the main branch name

.github/get-build-exit-code.sh, .github/workflows/docker-build.yaml
=> build will no longer be successful if the storefront standards or review will fail

project-base/storefront/components/Basic/Gallery/Gallery.tsx
=> images are not downloadable from the product gallery

project-base/storefront/components/Blocks/Product/ButtonsAction/ProductCompareButton.tsx, project-base/storefront/components/Blocks/Product/ButtonsAction/ProductWishlistButton.tsx, project-base/storefront/components/Blocks/Product/ProductsList/ProductItem.tsx, project-base/storefront/components/Blocks/Product/SliderProductItem.tsx, project-base/storefront/components/Pages/ProductDetail/ProductDetailContent.tsx
|Description, reason for the PR| This PR adds the possibility to add product variants to wishlist and comparison from product cards.
=> wishlist and comparison for product variant cards

project-base/storefront/components/Layout/Footer/NewsletterForm.tsx
|Description, reason for the PR| Margin of the newsletter form submit button was incorrect.
|Fixes issues|
=> fixed incorrect button margin in newsletter form
